### ISSUE TITLE
react-native link fails with buildsettings.LIBRARY_SEARCH_PATHS.push 

### ISSUE THREAD

**Issue by emmajam** [airbnb/react-native-maps#1000]
```
➜  repo git:(master) react-native link
rnpm-install info Android module react-native-camera is already linked
rnpm-install info iOS module react-native-camera is already linked
rnpm-install info Android module react-native-maps is already linked
rnpm-install info Linking react-native-maps ios dependency
rnpm-install ERR! It seems something went wrong while linking. Error: buildSettings.LIBRARY_SEARCH_PATHS.push is not a function
```

`react-native link react-native-maps` fails

```
react-native-cli: 1.2.0
react-native: 0.36.0
```

**Comment by dfranssen** [comment]
Perhaps not related, but I had a similar issue with `react-native-config` and by adding following in XCODE project it linked successfully:
Build Settings > Library Search Paths > `$(SRCROOT)/../node_modules/react-native-config` (recursive)

**Comment by skovhus** [comment]
`react-native-link` seems to assume that `LIBRARY_SEARCH_PATHS` is a list.

So inside the `project.pbxproj` file change
`LIBRARY_SEARCH_PATHS = "$(BUILD...";`

to 
`LIBRARY_SEARCH_PATHS = ("$(BUILD...");`
