### ISSUE TITLE
fitToCoordinates at initialization of the map

### ISSUE THREAD

**Issue by MathieuMailhos** [airbnb/react-native-maps#1003]
The example provided in the examples shows a button to execute a function to set the appropriate zoom considering to a list of markers:

```
  fitAllMarkers() {
    this.map.fitToCoordinates(MARKERS, {
      edgePadding: DEFAULT_PADDING,
      animated: true,
    });
}

```

Would it be possible to initialize the map with the appropriate fit given an array of markers already initialized ?

When trying to set the right fit on the componentDidMount, I am receiving:
`
Error using new LatLntBounds(LatLngBounds, int): Map size can't be 0. Most likely, layout has not yet occured for the map view.`

It is definitively too early to call my` fitAllMarkers() `function. Is there a `onLoad` function that can be triggered right after the map was initialized ?

**Comment by spikebrehm** [comment]
Interesting, so `componentDidMount()` is too early then.

Try adding an `onLayout` callback to your `<MapView>` instance and calling `fitAllMarkers()` in `onLayout`.

**Comment by spikebrehm** [comment]
> Would it be possible to initialize the map with the appropriate fit given an array of markers already initialized ?

It is possible to pass in an `initialRegion` prop.  You could use that.

**Comment by kanekotic** [comment]
uhmmm this works for me. I will leave the code i am using for future people that arrive here. I am not using markers as fitToCoordinates is for `latlong` object.

```js
class Map extends Component {

    constructor() {
        super()
        this.mapRef = null;
    }

    componentDidMount() {
        this.mapRef.fitToCoordinates(this.props.myLatLong, { edgePadding: { top: 10, right: 10, bottom: 10, left: 10 }, animated: false })
    }

    render() {
      return    <MapView style={{flex: 1}}
                    ref={(ref) => { this.mapRef = ref }}>
                    <Polyline coordinates={this.props.myLatLong} strokeWidth={4} strokeColor="#2962FF" /> 
                </MapView>
    }
}

```

**Comment by kanekotic** [comment]
the previous code fails on android but not in IOS, so following the what @spikebrehm said, a better solution that work in both is
```js
class Map extends Component {

    constructor() {
        super()
        this.mapRef = null;
    }

    render() {
      return    <MapView style={{flex: 1}}
                    ref={(ref) => { this.mapRef = ref }}
                    onLayout = {() => this.mapRef.fitToCoordinates(this.props.myLatLongs, { edgePadding: { top: 10, right: 10, bottom: 10, left: 10 }, animated: false })}
                    >
                    <Polyline coordinates={this.props.myLatLongs} strokeWidth={4} strokeColor="#2962FF" /> 
                </MapView>
    }
}

```

**Comment by kanekotic** [comment]
@spikebrehm I have opened a PR on the documentation for this issue. Hope at list makes it easier for future users of this function.

**Comment by esutton** [comment]
Calling from onLayout works great when first showing map!

Any advice on how can to call fitToCoordinates when a new set of markers is loaded?  

I tried componentWillReceiveProps but was called when map was hidden when user is selecting a new set of markers.

**Comment by ryankask** [comment]
@esutton Several months ago I required similar functionality for an app. The list of coordinates could periodically be updated and I remember I could never get the functionality working on Android. 

I vaguely recall it had to do with the React lifecycle not matching up with the underlying map view's lifecycle. The parent React component that rendered the map (or the map itself) was updated (ie `componentDidUpdate()` was called) but the native child markers weren't yet added to the native map view so when you called `fitToCoordinates()` it didn't account for all of them.

I ended up just implementing `fitToCoordinates()` in JS and using the `region` prop to mimic the functionality.

**Comment by esutton** [comment]
@ryankask Thank you for your advice.  

I expect I must solve a number of issues when I re-start work on the neglected Android version of my app building again.   I am not looking forward to all the updating issues breaking both iOS and Android gradle stuff.

**Comment by razerduy** [comment]
hi guys, 
how to use fitToCoordinates with region when init Map ?

**Comment by kanekotic** [comment]
@razerduy what do you mean with when init map?

**Comment by razerduy** [comment]
@kanekotic
I init map with initialRegion then , i call fitToCoordinates in componentDidMount but it not working.
Now i found solution for my issue. :))
I call fitToCoordinates in componentDidUpdate and it's fine.
Tks.

**Comment by okarakose** [comment]
react-native : 0.43.4
react-native-maps : 0.13.0

@kanekotic onLayout **did not triggered** for us. the code is below :

    <MapView
        ref="map"
        legalLabelInsets={{ bottom: 150, right: 20 }}
        loadingEnabled={this.state.loading}
        onRegionChange={(region) => this.setRegion(region)}
        showsMyLocationButton={false}
        showsPointsOfInterest={false}
        showsCompass={false}
        showsScale={false}
        showsTraffic={false}
        toolbarEnabled={false}
        onLayout={()=> console.log("onLayoutt")}
        style={style.map}
    >

we don't want to use **componentDidUpdate** because it is not suitable for our situation.

There is not **onMapReady** or **onLayout** callback from **MapView.js** file.

we don't want to use dummy setTimeout.

this PR is looking important : ( Add onMapReady callback )
https://github.com/airbnb/react-native-maps/pull/1369

is there any official solution for fitToCoordinates problem on some android devices ?

**Comment by peterlau** [comment]
I understand that this is an open source project and people are volunteering their time. But to the extent that its possible, could we get an 'official' response on how one can trigger a `fitToXXX()` or `animateToXXX()` call at the earliest possible time without running into a race condition, and without gimmicks like `setTimeout()`.

In other words, which callback can we use that is always guaranteed to succeed? Some, such as `componentDidMount` is too early and the panning call gets ignored. Others, like `onMapReady` doesn't get called consistently, and so cannot be counted on.

This seems like a basic use case that the examples should cover.

**Comment by sarmad1995** [comment]
I solved it by this, maybe it could help
in mapview
`onLayout={this.onLayout}`

` onLayout = () => {
        setTimeout(
            () => {
                this.map.fitToCoordinates([{ latitude: 33.9260206, longitude: 75.0173499 }, { latitude: 33.949817, longitude: 74.985655 }], {
                    edgePadding: DEFAULT_PADDING,
                    animated: true,
                });
            }, 2000
        );   
    }`

**Comment by bhalvy** [comment]
Setting a timeout like @sarmad1995 worked for me, although this feels hacky. Has anyone found other ways to handle fitToCoordinates()?

**Comment by ryankask** [comment]
@bhalvy I adapted this [snippet](http://stackoverflow.com/a/10568267/171744) and created a utility function in JS that returns a region. It’s worked well for my client’s app.

**Comment by mdere-unbound** [comment]
Does this apply to fitMarkers ? If it is - it isn't working for me...

**Comment by mdere-unbound** [comment]
Nevermind - I totally missed @mappico-kritn 's comment - that solved my issues and works for both functions

**Comment by jacquesdev** [comment]
onMapLoaded seems like a better event in my use case, it seems to be the very last event that loads once the mapRef has been registered

**Comment by elabayoub** [comment]
What worked for me is the following:

> onMapReady={() => {
            if (platform.is.android) {
              onMapReady();
            }
          }}
          onLayout={() => {
            if (platform.is.ios) {
              onMapReady();
            }
          }}

then on "onMapReady()":

> const onMapReady = useCallback(() => {
    const paddings = {top: 80, right: 40, bottom: 40, left: 40};
    mapRef.current?.getMapRef()?.fitToCoordinates(
      // array of coords as below example
      [
         {latitude: 33.5617926, longitude: -7.5956317},
        {latitude: 33.588469, longitude: -7.673966},
        {latitude: 31.452207, longitude: -9.763101}
      ],
      {edgePadding: paddings, animated: true},
    );
  }, []);

**Comment by moneszarrugh** [comment]
> onMapLoaded seems like a better event in my use case, it seems to be the very last event that loads once the mapRef has been registered

This worked for me too. onLayout is not reliable.
