### ISSUE TITLE
Problem when used with react-native-device-info

### ISSUE THREAD

**Issue by bufke** [airbnb/react-native-maps#1005]
Strange problem. If both maps and device-info are linked I get this when starting the app.

http://pastebin.com/e4grAUXa

Unlinking device-info makes the app work again - but you'll notice the stack trace points to com.airbnb.android.react.maps.AirMapManager

**Comment by gdancel** [comment]
Hi, I made a temporary fix for this. The problem is due to the different versions of google play services that the two libraries are using.
https://github.com/gdancel/react-native-device-info

**Comment by lelandrichardson** [comment]
Duplicate of #1028
