### ISSUE TITLE
are showsBuildings/showsIndoors implemented?

### ISSUE THREAD

**Issue by wasa4587** [airbnb/react-native-maps#1006]
I enabled these options, but there are several places where the buildings doesn't appear
For example Marin County - Civic center, in google maps app, or web it shows a building and the office inside it.

```
              <MapView
                style={styles.map}
                showsBuildings={true}
                showsIndoors={true}
                loadingEnabled={true}
                region={this.regionFrom(orig.latitude, orig.longitude, 100)}
              />
```

**Comment by spikebrehm** [comment]
`showsBuildings` does seem to be implemented.  

`showsIndoors` only appears implemented on Android.  Which platform are you testing?

**Comment by wasa4587** [comment]
I'm testing on android,
I didn't see the indoor level picker, but I think it's because `view.map.getUiSettings().setIndoorLevelPickerEnabled(true);` is not implemented, I'll try to fix it by my own
thanks
