### ISSUE TITLE
Another blank map on Android

### ISSUE THREAD

**Issue by cokealmonacid** [airbnb/react-native-maps#1014]
Hey guys! trying to make work on android but get the blank map all the time, on iOS works perfectly. Use the android studio for set up the emulator and even try with the avd manager, but nothing's seems to work, but i was wondering why in the emulator i don't have the google play app's (didnt know how to install on the emulator, maybe its for that).
I follow the installation instructions and even make a review of all the (opens and closed) issues and nothing's work's for me, this is the code and all the things that i made: 

export default class reactMap extends Component {
  render() {
    return (
      <View style={styles.container}>
        <MapView style={styles.map} 
        region={{
          latitude: -39.313776136248116,
          longitude: -71.05638285000003,
          latitudeDelta: 0,
          longitudeDelta: 0
          }}
        ></MapView>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  map: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0
  }
});

(Try even change the style and using the ...StyleSheet.absoluteFillObject)

Im correctly using the Google Maps Android API (using the correct key), even i can see the request and the history of them: 
<img width="1008" alt="captura de pantalla 2017-02-02 a las 09 04 23" src="https://cloud.githubusercontent.com/assets/16389394/22548621/1d47aada-e926-11e6-91d8-bcc7365f404b.png">
*Try even changing this to the V2.KEY version or even using the javascript API.

Got this on the AVD:
![captura de pantalla 2017-02-02 a las 09 06 30](https://cloud.githubusercontent.com/assets/16389394/22548674/61884d76-e926-11e6-92e0-aa998ed88f3b.png)

This is my android packages installed: 
![captura de pantalla 2017-02-02 a las 09 07 19](https://cloud.githubusercontent.com/assets/16389394/22548699/7eefd898-e926-11e6-8b04-32f39fffe28b.png)

Like i say, trying to follow the instructions and there is no response, please help me!
![captura de pantalla 2017-02-02 a las 08 56 10](https://cloud.githubusercontent.com/assets/16389394/22548772/dc98f9fc-e926-11e6-9f0f-cd01eaeecd17.png)

**Comment by unboundfire** [comment]
Try upping the target on the AVD to API Level 25

**Comment by cokealmonacid** [comment]
Upping the target dont works ): @unboundfire

**Comment by Amurmurmur** [comment]
Same issue here, after upgrading to RN 0.41 :/
Using 
```
compileSdkVersion 23
buildToolsVersion "25.0.1"
```

**Comment by cokealmonacid** [comment]
Lost a lot of hours on this, the value of location and latitude delta was zero, so didnt see anything
