### ISSUE TITLE
Publish 0.13.0 to npm

### ISSUE THREAD

**Issue by the-simian** [airbnb/react-native-maps#1020]
- this resolves the duplicate module declaration problem with react-native .40 and .41

- https://github.com/airbnb/react-native-maps/issues/937

**Comment by Naoto-Ida** [comment]
Any progress on this guys?

**Comment by Naoto-Ida** [comment]
Hmm, seems to be up? I did `npm view react-native-maps versions` and saw 0.13.0 on there.

**Comment by the-simian** [comment]
![image](https://cloud.githubusercontent.com/assets/954596/22722171/dcb73252-ed7a-11e6-8a17-0b591f15d0b7.png)

i see 0.12.4 currently...

**Comment by Tim-W** [comment]
Why is it still 0.12.4? Please update asap :)

**Comment by lelandrichardson** [comment]
Closed. 0.13.x is now latest
