### ISSUE TITLE
What is a [Getter/Setter] object?

### ISSUE THREAD

**Issue by freshnewegg** [airbnb/react-native-maps#1022]
From the Views as Markers example, i set the state of the marker coordinate to some value (ie latitude: 40, longitude: -70). However, at some point the coordinate's fields gets set as [Getter/Setter]

<img width="498" alt="screen shot 2017-02-04 at 6 07 11 pm" src="https://cloud.githubusercontent.com/assets/5714313/22622315/3768ccba-eb05-11e6-8e64-e6e744e85cd6.png">

What does this mean? When I remove prop from use...

<img width="372" alt="screen shot 2017-02-04 at 6 12 39 pm" src="https://cloud.githubusercontent.com/assets/5714313/22622354/9bdf0d08-eb05-11e6-9056-349dfe20f418.png">

TO: 

<img width="176" alt="screen shot 2017-02-04 at 6 12 53 pm" src="https://cloud.githubusercontent.com/assets/5714313/22622355/9e349dd4-eb05-11e6-8701-fb18c32fb2b8.png">

The coordinate field is then magically set properly. 

coordinate: { latitude: 40.xxx, longitude: -70.xxx }

Why does using a prop alter my component's state? Could someone explain what's happening?

**Comment by akajack** [comment]
Same problem :(

**Comment by pedro** [comment]
Just ran into a similar issue, although not related to react-native-maps. React-native seems to be converting simple strings in my object values to this odd `[Getter/Setter]`.

Are you folks on Android by chance? I think this could be related:
https://github.com/mobxjs/mobx/issues/734

**Comment by felipecsl** [comment]
This seems to be a react native question, not specific to this library. Closing.

**Comment by CodeKunal** [comment]
Yes its a react native issue. I am too getting this weird behaviour. When I move back to previous screen in navigation suddenly all local state object that contain strings become [Getter/Setter]. Has anyone found the solution?

**Comment by pedro** [comment]
Is it on Android? If so check the issue above, make sure you're on a good version of mobx.
