### ISSUE TITLE
Map catches touches intended for parent ScrollView

### ISSUE THREAD

**Issue by Naoto-Ida** [airbnb/react-native-maps#1032]
The map won't let me scroll my ScrollView if the touch start originates from within the app, despite `zoomEnabled`, `rotateEnabled` and `scrollEnabled` being set to `false`.

This was brought up in #730 for Android,
but seems to be happening on iOS at the moment.

My RN version is **0.41.0** and this library is at **0.13.0**.

Here is my code:

```js
<MapView
	provider={MapView.PROVIDER_GOOGLE}
	liteMode
	zoomEnabled={false}
	rotateEnabled={false}
	scrollEnabled={false}
	style={{
		margin: 10,
		width: Dimensions.get('window').width - 20,
		height: Dimensions.get('window').width - 20,
	}}
	initialRegion={{
		latitude: coordinates.latitude,
		longitude: coordinates.longitude,
		latitudeDelta: 0.0922,
		longitudeDelta: 0.0421,
	}} />
```

**Comment by Naoto-Ida** [comment]
Sorry, my code prior to setting all the props to false seemed to be cached. Now its working. Closing.

**Comment by draperunner** [comment]
I am experiencing this issue with react-native@0.47.1 react-native-maps@0.16.3.

It works fine on Android, but not on iPhone.

This is my MapView implementation:
```
<MapView
                    style={ StyleSheet.flatten(containerStyles.map) }
                    onPress={ this.props.onPress }
                    provider={ PROVIDER_GOOGLE }
                    customMapStyle={ mapUtils.getMapStyle() }
                    initialRegion={ region }
                    rotateEnabled={false}
                    scrollEnabled={false}
                    moveOnMarkerPress={false}
                    zoomEnabled={false}>
                    { currentPositionMarker }
                </MapView>
```

**Comment by hammadzz** [comment]
@draperunner it works for me with these:
```
        zoomEnabled={false}
        scrollEnabled={false}
        pitchEnabled={false}
        rotateEnabled={false}
```

**Comment by Return-1** [comment]
@draperunner hey, ever got around this issue? im still experiencing on iOS
@hammadzz unfortunately this solution doesnt seem to work

**Comment by patrick-gleeson** [comment]
I am also experiencing on iOS, using 0.26.1: if the MapView is inside a ScrollView, swipe gestures that original on the MapView component don't get passed to the ScrollView, even though scrollEnabled={false}. As a workaround we can add `pointerEvents="none"` to the MapView component, although this also makes zooming impossible

**Comment by Return-1** [comment]
@patrick-gleeson pointerEvents on map doesnt work for me. would you add directly it as a prop or as part of the style prop?

**Comment by patrick-gleeson** [comment]
@Return-1 as a prop:

```jsx
            <MapView
              pointerEvents="none"
              provider={MapView.PROVIDER_GOOGLE}
              style={...blah...}
              customMapStyle={...blah...}
              scrollEnabled={false}
            >
              ...blah...
            </MapView>
```

**Comment by DEEPAKSINGHRAGHAV** [comment]
> @Return-1 as a prop:
> 
> ```js-jsx
>             <MapView
>               pointerEvents="none"
>               provider={MapView.PROVIDER_GOOGLE}
>               style={...blah...}
>               customMapStyle={...blah...}
>               scrollEnabled={false}
>             >
>               ...blah...
>             </MapView>
> ```

It worked but...in this way:

<View style={innerstyles.container} pointerEvents="none">
      <MapView
        provider={PROVIDER_GOOGLE} 
        style={innerstyles.map}
        zoomControlEnabled={false}
        scrollEnabled={false}
        region={{
          latitude: 37.78825,
          longitude: -122.4324,
          latitudeDelta: 0.015,
          longitudeDelta: 0.0121,
        }}
      >
        <Marker coordinate={{ latitude:37.782525, longitude: -122.4324 }}>
        <Callout>
      <Text>{name}</Text>
        </Callout>
        </Marker>
        
      </MapView>
    </View>

**Comment by DEEPAKSINGHRAGHAV** [comment]
Was stuck from 1 week but finally it worked !!
`<View style={innerstyles.container} pointerEvents="none">
      <MapView
        provider={PROVIDER_GOOGLE} 
        style={innerstyles.map}
        zoomControlEnabled={false}
        scrollEnabled={false}
        region={{
          latitude: 37.78825,
          longitude: -122.4324,
          latitudeDelta: 0.015,
          longitudeDelta: 0.0121,
        }}
      >
        <Marker coordinate={{ latitude:37.782525, longitude: -122.4324 }}>
        <Callout>
      <Text>{name}</Text>
        </Callout>
        </Marker>
        
      </MapView>
    </View>`

**Comment by mhammerc** [comment]
> I am also experiencing on iOS, using 0.26.1: if the MapView is inside a ScrollView, swipe gestures that original on the MapView component don't get passed to the ScrollView, even though scrollEnabled={false}. As a workaround we can add `pointerEvents="none"` to the MapView component, although this also makes zooming impossible

I think it is worth adding it to the documentation ! Thank you very much 😋
