### ISSUE TITLE
[Android] Blank map on physical device

### ISSUE THREAD

**Issue by Falconerd** [airbnb/react-native-maps#1043]
Hey all, I've read all of the blank map threads I can find and tried many of the solutions. However, I cannot get this map to show. Here's a screenshot, some relevant code, and a list of things I've tried.

I have doubts as to this being a style issue as the map is loading with a pale background and Google logo.

![http://i.imgur.com/VFNcKOx.png](http://i.imgur.com/VFNcKOx.png)

> JSX
```javascript
import React from 'react';
import { StyleSheet, Dimensions, View } from 'react-native';
import { Actions } from 'react-native-router-flux';
import MapView from 'react-native-maps';

export default () => (
  <View style={styles.container}>
    <MapView
      style={styles.map}
      initialRegion={{
        latitude: 37.78825,
        longitude: -122.4324,
        latitudeDelta: 150,
        longitudeDelta: 150
      }}
    />
  </View>
);

const styles = StyleSheet.create({
  container: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'flex-end',
    alignItems: 'center'
  },
  map: {
    ...StyleSheet.absoluteFillObject
  }
});
```
> android/app/build.gradle
```gradle
...
dependencies {
    compile(project(':react-native-maps')){
        exclude group: 'com.google.android.gms', module: 'play-services-base'
        exclude group: 'com.google.android.gms', module: 'play-services.maps'
    }
    compile 'com.google.android.gms:play-services-base:10.0.1'
    compile 'com.google.android.gms:play-services-maps:10.0.1'
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:+"  // From node_modules
}
...
```
> android/settings.gradle
```gradle
...
include ':react-native-maps'
project(':react-native-maps').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-maps/android')
...
```

> android/app/src/java/<project>/MainApplication.java
```java
...
import com.airbnb.android.react.maps.MapsPackage;
...
    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
          new MapsPackage()
      );
    }
...
```

I've tried installing manually and with react-native link. I've tried changing my play services version to match my phone (12.2.38) which apparently doesn't exist - perhaps I missed something there.

Any help would be appreciated.

**Comment by eard7** [comment]
I was having the same issue than you, it was weird, so i took a look in the log on Android Studio and detected this:
![captura de pantalla 2017-02-16 a las 12 10 30 p m](https://cloud.githubusercontent.com/assets/5809225/23034579/e434aeba-f441-11e6-8c71-8f80fe3fb663.png)

I haven't enabled Google Maps Android API in my project, so you have to check that.
Go to your project's Control Panel and check that Google Maps Android API appears in the list. If it doesn't, enable the api by click the  button marked with red (It should say Enable API, my lang is Spanish as you can see).

![captura de pantalla 2017-02-16 a las 12 18 32 p m](https://cloud.githubusercontent.com/assets/5809225/23034750/6cacf2f2-f442-11e6-9ac8-22a8ae3e3f04.png)

Finally just make sure that you have this in your AndroidManifest

```
<meta-data android:name="com.google.android.geo.API_KEY" android:value="Your api key"/>
```

After that, the maps worked like a charm.

Hope it helps!

**Comment by edgaru** [comment]
Thank you @eard7, it works!

**Comment by Falconerd** [comment]
That was it! Thank you very much, @eard7!

**Comment by mahe9415** [comment]
Thank you @eard7 🤟🏻
