### ISSUE TITLE
Duplicate interface definition for class 'RCTView'

### ISSUE THREAD

**Issue by Filipvdb321** [airbnb/react-native-maps#1047]
After executing "react-native link" I get in xcode a lot of of these errors :

> Duplicate interface definition for class 'RCTView'

I am using the latest version of react-native: 0.41.2 . Could this be an incompatibility problem with this version?

**Comment by Filipvdb321** [comment]
I see that this issue is fixed in the master branch

**Comment by npomfret** [comment]
I've got the same issue upgrading to rn 0.42 and maps 0.12.4.  Any idea what the solution is?
