### ISSUE TITLE
"Unable to resolve module react-native-maps"... "Module does not exist in the module map or in these directories: /../node_modules

### ISSUE THREAD

**Issue by JCDJulian** [airbnb/react-native-maps#1048]
Currently receiving the following error when trying to integrate RNM into my project. Am able to install and use react-native link successfully, however once project starts I hit red screen with:

"Unable to resolve module react-native-maps"... "Module does not exist in the module map or in these directories: /../node_modules

In my node_modules folder, react-native-maps is indeed there.

For reference, my package.json, which is from this Redux starter kit package:
https://github.com/LeoLeBras/react-native-redux-starter-kit/tree/next
```

{
  "name": "react-native-redux-starter-kit",
  "version": "2.0.0",
  "description": "Get started with React Native and Redux.",
  "repository": {
    "type": "git",
    "url": "https://github.com/LeoLeBras/react-native-redux-starter-kit"
  },
  "author": "Léo LE BRAS <leo.lebrasf@gmail.com> (http://github.com/LeoLeBras)",
  "contributors": "Charles MANGWA <charles.mangwa@gmail.com> (http://github.com/CharlesMangwa)",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/LeoLeBras/react-native-redux-starter-kit/issues"
  },
  "scripts": {
    "start": "node_modules/react-native/packager/packager.sh",
    "build-ios": "node node_modules/react-native/local-cli/cli.js bundle --entry-file index.ios.js --bundle-output iOS/main.jsbundle --platform 'ios' --assets-dest ./  --dev false --reset-cache",
    "build-android": "node node_modules/react-native/local-cli/cli.js bundle --entry-file index.android.js --bundle-output iOS/main.jsbundle --platform 'android' --assets-dest ./  --dev false --reset-cache",
    "reactotron": "node_modules/.bin/reactotron"
  },
  "engines": {
    "node": ">=4",
    "npm": ">=2 <4"
  },
  "dependencies": {
    "apisauce": "^0.7.0",
    "babel-preset-es2015": "^6.18.0",
    "flow-bin": "^0.36.0",
    "immutable": "^3.8.1",
    "react": "^15.4.1",
    "react-native": "^0.39.0",
    "react-native-maps": "^0.12.4",
    "react-native-router-flux": "^3.26.0",
    "react-redux": "^4.4.6",
    "recompose": "^0.20.2",
    "redux": "^3.5.2",
    "redux-thunk": "^2.0.1"
  },
  "devDependencies": {
    "babel-eslint": "^7.1.1",
    "babel-preset-react-native-stage-0": "^1.0.1",
    "eslint": "^3.11.1",
    "eslint-config-airbnb": "^13.0.0",
    "eslint-plugin-babel": "^3.3.0",
    "eslint-plugin-import": "^2.1.0",
    "eslint-plugin-jsx-a11y": "^2.2.3",
    "eslint-plugin-react": "^6.7.1",
    "reactotron": "^0.9.0"
  }
}

```

**Comment by JCDJulian** [comment]
Update: Tried to upgrade to RN 0.41 to try and resolve issue. Ended up hitting this issue, which just recommends rolling back to .39...

https://github.com/airbnb/react-native-maps/issues/937

**Comment by JCDJulian** [comment]
Partial solution through the following:

1. Upgraded to RN 0.41
2. Installed react-native-maps v13.0. 

The standard "npm install react-native-maps --save" in the installation guide was installing an earlier release.

Now the application is built fine. Can import maps fine. But the Map is still blank. Have tried unlinking and relinking but no dice. Will update if I find anything

**Comment by JCDJulian** [comment]
Okay, as a final update, fixed the blank map issue by editing the stylesheets. Everything is good now!

**Comment by mangguoaidami** [comment]
How can note solve, good job react-native!
