### ISSUE TITLE
Draggable marker is not working

### ISSUE THREAD

**Issue by surendharreddy** [airbnb/react-native-maps#1058]
```
<View style={styles.container}>
     <MapView
       style={mapStyles.map}
       region={this.state.region}
      >
     <MapView.Marker 
       coordinate={this.state.coordinate}
       onSelect={() => console.log('onSelect', arguments)}
       onDrag={() => console.log('onDrag', arguments)}
       onDragStart={() => console.log('onDragStart', arguments)}
       draggable
     />
  </MapView>
</View>


const mapStyles = StyleSheet.create({
  container: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'flex-end',
    alignItems: 'center',
    flex: 1
  },
  map: {
    ...StyleSheet.absoluteFillObject,
  }
});
```

Trying to implement draggable markers with the above code, but unable to drag the marker in the android app. 

Using the below mentioned config. 

- react-native-maps : ^0.12.4
- react-native : 0.39.2

**Comment by SuhairZain** [comment]
@surendharreddy I'm having the same issue. The entire map is getting dragged instead of the marker. Were you able to solve this issue?

**Comment by saidhruv** [comment]
@SuhairZain you'l need to long press the marker to drag it.. I guess it is because they do not want you to get confused between onPress and drag on the map.

source: https://stackoverflow.com/a/43779188
read the last line of the accepted answer

**Comment by rtman** [comment]
@saidhruv Thanks!

**Comment by arcollector** [comment]
if scrollEnabled={false} onto <MapView> dragging a marker is not smooth
