### ISSUE TITLE
how do I get location information (including latitude and longitude and city name)?

### ISSUE THREAD

**Issue by xubuhang** [airbnb/react-native-maps#1068]
我如何获取定位信息（包括经纬度和城市名称）？

**Comment by kaueDM** [comment]
检查这个 https://facebook.github.io/react-native/docs/geolocation.html

**Comment by xubuhang** [comment]
@kaueDM 你好。
1.Geolocation获取的坐标可以直接设置到react-native-maps地图上吗？需要进行坐标系转换的操作吗？
2.怎么获取定位坐标的城市名称呢？
3.react-native-maps在中国境内可以使用吗？
麻烦解答一下。

**Comment by pstevens74** [comment]
Hi.  Try this on your top level component.  I have just written this for you, so it's not tested, but in theory this should work and put the latest GPS readings from your device into state variables for you to use throughout your app. You can fiddle with the settings as desired. Good Luck!

//Once your top level component has finished mounting, start off a GPS watch which will fire every time the device gets a new GPS reading

componentDidMount() {

  this.watchID = navigator.geolocation.watchPosition((position) => {

      //It’s got a GPS location, so save to to the state to feed through your components 
      this.setState({latitude: position.coords.latitude, longitude: position.coords.longitude})

    }, error => {

      //It got an error from GPS, so do whatever you need to do in this case
      this.setState({latitude: 0, longitude: 0})

    },{

      //GeoLocation settings go here
      timeout: 30000,     			        // 30 seconds until it fires a GPS error
      maximumAge: 15000,  			// 15 seconds 
      enableHighAccuracy: true,   	       //check frequently and accurately using all sensors
      distanceFilter: 10    			     // don't use or update GPS if the user stays still though
    })

  }

  //Stop ‘watching’ the GPS when the user finishes with the component

  componentWillUnmount() {
    navigator.geolocation.clearWatch(this.watchID);
  }

**Comment by xubuhang** [comment]
How I get the location of city's name?@kaueDM @pstevens74

**Comment by kaueDM** [comment]
You need a **geocoder** @xubuhang 
Right now i am using this one: [react-native-geocoder](https://github.com/devfd/react-native-geocoder)
This will convert your coordinates in something 'readable for humans'
