### ISSUE TITLE
Multidex exception because hardcoded com.google.android.gms:play-services-base version

### ISSUE THREAD

**Issue by Gumija** [airbnb/react-native-maps#1076]
Using react-native-maps with react-native-fcm together causes a Multidex exception:
```
Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/internal/zzaac$zza;
```

The reason for this is that react-native-maps uses 9.x and react-native-fcm uses 10.x version of google play services and they don't like each other.

The solution given on and fcm thread was not working for us
[https://github.com/evollu/react-native-fcm/issues/282#issuecomment-276011849](https://github.com/evollu/react-native-fcm/issues/282#issuecomment-276011849)

Only the one where we modify the build.gradle file of react-native-maps.
[https://github.com/evollu/react-native-fcm/issues/282#issuecomment-275930975](https://github.com/evollu/react-native-fcm/issues/282#issuecomment-275930975)
```
compile "com.google.android.gms:play-services-base:+"
compile "com.google.android.gms:play-services-maps:+"
```

But that would get overwritten with every update.

**Comment by ryankask** [comment]
Does something like this help?

```
dependencies {
    ...
    compile 'com.google.android.gms:play-services-base:10.2.+'
    compile 'com.google.android.gms:play-services-maps:10.2.+'
    compile(project(':react-native-maps')) {
        exclude group: 'com.google.android.gms', module: 'play-services-base'
        exclude group: 'com.google.android.gms', module: 'play-services-maps'
    }
    ... 
}
```

**Comment by sankalpsingha** [comment]
I am facing the same issue. Any update? @ryankask your solution is not working.

**Comment by didaKtik** [comment]
@sankalpsingha You should take a look at this it further explains how to use the technique proposed by @ryankask to make fcm and google-maps compatible. If you do it correctly it should work.

**Comment by lelandrichardson** [comment]
Closing this as not actionable. We are going to hard code our GMS dependencies as this is standard practice. For dex issues, you should be able to apply gradle configurations similar to how ryankask and didaKtik suggested.
