### ISSUE TITLE
Unable to pod install in RN 0.42.0

### ISSUE THREAD

**Issue by anhtuank7c** [airbnb/react-native-maps#1078]
Hi all,

I have problem with RN 0.42.0, unable to execute `pod install` because of Yoga in RN 0.42.0 is not a latest version 1.2.0 (release 8 days ago)

![screen shot 2017-03-03 at 11 48 23 am](https://cloud.githubusercontent.com/assets/3163410/23538963/38055a98-000a-11e7-9aef-9dd913161fa3.png)

Latest Yoga is`1.2.0`
![Yoga releases](https://cloud.githubusercontent.com/assets/3163410/23538952/2303abf4-000a-11e7-8fb3-12384c53864d.png)

But i see latest Yoga in RN 0.42.0 is about 17 days ago.
![screen shot 2017-03-03 at 12 05 45 pm](https://cloud.githubusercontent.com/assets/3163410/23538978/6131724e-000a-11e7-8447-489ab9792ca3.png)

Do you have any solution to install `react-native-maps` to RN 42 version?

**Comment by thanhkma1594** [comment]
me too !!!

**Comment by Moussa112** [comment]
I was following the solution provided by @heron2014 on issue #118 and have the same problem here :(

**Comment by anhtuank7c** [comment]
@Moussa112 `RN version 0.39.0` is fully compatible with` react-native-maps` latest stable version `0.12.4`
We have to use `RN 39` instead of `RN version >= 40`

**Comment by tedjames** [comment]
I'm also experiencing this issue...

**Comment by tedjames** [comment]
Hey everyone! I just found the solution for this here:

I got it working by making my podfile look like this:
```
# You Podfile should look similar to this file. React Native currently does not support use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'



target 'finzen' do
  # Fixes required for pod specs to work with rn 0.42
  react_native_path = "../node_modules/react-native"
  pod "Yoga", :path => "#{react_native_path}/ReactCommon/yoga"
  pod "React", :path => react_native_path, :subspecs => [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
  ]

  pod 'GoogleMaps'  # <~~ remove this line if you do not want to support GoogleMaps on iOS

# when not using frameworks  we can do this instead of including the source files in our project (1/4):
#  pod 'react-native-maps', path: '../../'
#  pod 'react-native-google-maps', path: '../../'  # <~~ if you need GoogleMaps support on iOS
end

```

**Comment by davibe** [comment]
but in rn 0.42 i don't even have a podfile .. ?

**Comment by davibe** [comment]
I tried and this is what i get
```
dade@choo:~/work/AwesomeProject/ios$ pod install
Analyzing dependencies
Fetching podspec for `React` from `../node_modules/react-native`
[!] Unable to find a specification for `Yoga (= 0.42.0.React)` depended upon by `React/Core`
dade@choo:~/work/AwesomeProject/ios$
```

**Comment by naartjie** [comment]
@davibe the `Podfile` should be in the root of your project.

**Comment by RazvanCosmeanu** [comment]
@naartjie shouldn't it be in the ios folder?

**Comment by naartjie** [comment]
@RazvanCosmeanu you're correct, I meant a `Podfile` found in the project (root, ios, or other), vs a podfile in any of the libraries.

cc @davidbe

**Comment by davibe** [comment]
There is no Podfile. Looks like 0.42 does not use it.

**Comment by tedjames** [comment]
@davibe Correct. You need to include it yourself. The only reason I created a podfile was to integrate google maps.

**Comment by davidhenley** [comment]
@davibe no RN has a podfile. You create it like in the install instructions.

**Comment by grundmanise** [comment]
@davidhenley there is no `Podfile` initially. I've created one with `pod init`

**Comment by R3dC0d3** [comment]
@tedjames great job man, it worked, thank you.

**Comment by gayancliyanage** [comment]
try these steps [link](https://gayancliyanage.wordpress.com/2017/03/14/react-native-maps-with-google/)

**Comment by anhtuank7c** [comment]
@gayancliyanage Thank you so much
❤️
