### ISSUE TITLE
CustomMapStyle not working?

### ISSUE THREAD

**Issue by amaurymartiny** [airbnb/react-native-maps#1081]
Hey, can someone take 5 minutes to test if customMapStyle is still working?

I took the retro style from https://mapstyle.withgoogle.com/, and pasted it into the customMapStyle of a new

        <MapView
          region={this.props.region}
          showsUserLocation
          customMapStyle={mapStyle}
          onRegionChange={...}
        >

And the map style is not changed. I don't know what I can change here.

**Comment by greyvugrin** [comment]
@amaurymartiny this thread should help https://github.com/airbnb/react-native-maps/issues/881
