### ISSUE TITLE
Example project broken?

### ISSUE THREAD

**Issue by pbassut** [airbnb/react-native-maps#1082]
Did `npm install`, `react-native link`, `pod install` and all. 
When doing `react-native run-ios` I get this:
```
/Users/patrickbassut/Downloads/react-native-maps-master/example/node_modules/react-native-maps/ios/AirMaps/AIRMapPolygonManager.h:6:9: fatal error: 'React/RCTViewManager.h' file not found
#import <React/RCTViewManager.h>
```

**Comment by khle** [comment]
I think if you do pod install, then skip react-native link.  It will still be broken later on, at run time, but compile-time will complete successfully.  What I mean by broken later on at run time is you won't see the map, just a red-bordered box.  Do let me know if you get it working completely.

**Comment by lelandrichardson** [comment]
The example project should work now. Please let me know if you have any trouble.
