### ISSUE TITLE
onPress not working in AnimatedViews examples with PanResponder presenting

### ISSUE THREAD

**Issue by JLLLinn** [airbnb/react-native-maps#1087]
Hello, I was trying to add onPress to to the red coverflow view in the AnimatedViews example code but was not able to do it. In fact the outer View does not listen to the onPress event either. 

I was suspecting that the panresponder from PanController was taking over all the clicks, but even if I set the onStartShouldSetPanResponder and onMoveShouldSetPanResponder to false it still doesn't solve the problem. Is anyone else experiencing this problem?

**Comment by ducva** [comment]
Hi, @JLLLinn did you resolve this problem? "onPress not working in AnimatedView"?

**Comment by JLLLinn** [comment]
@ducva Yes I did resolve. I was actually doing something wrong myself and the component WAS responding to onPress.

**Comment by douglaswissett** [comment]
Hey @JLLLinn,
I'm having troubles with AnimatedViews, the red Animated.View drags on first touch but when released half way up gets stuck and the map doesn't respond at all.

How did you manage to resolve this?

Thanks in advance!
