### ISSUE TITLE
Is it possible to change the language into Japanese on MapView?

### ISSUE THREAD

**Issue by HiroNonoyama** [airbnb/react-native-maps#1091]
I would like to know how to change the language.
Does anybody  have an idea?

**Comment by HiroNonoyama** [comment]
solved.
already localized.

**Comment by HerbertLim** [comment]
@HiroNonoyama  did you find a solution?

**Comment by HiroNonoyama** [comment]
@HerbertLim 
Yes, I did.
In my case, Just changing language setting on mobile device solved this.

**Comment by 7772** [comment]
@HiroNonoyama's solution do work too when using Xcode simulator.
