### ISSUE TITLE
Question: Possible to mimic Google embedded look

### ISSUE THREAD

**Issue by Dashue** [airbnb/react-native-maps#1097]
Hello people, thanks for your good work on this lib.

We were looking to do something similar to this but on the mobile, is this something which can easily be accomplished through the use of this library? Alternatively anyone know the most appropriate way to achieve something like this? Basically a pre-set place shown on a map, rather than just a marker.

Thanks!

![image](https://cloud.githubusercontent.com/assets/473789/23656023/cf673b54-032f-11e7-8905-9f8a28d40b61.png)

**Comment by lelandrichardson** [comment]
I'm not aware of any API to do something like this natively. If you do some research and find anything though, let me know and we might be able to bake it in.
