### ISSUE TITLE
Polyline drawing leaves stain

### ISSUE THREAD

**Issue by Lerik** [airbnb/react-native-maps#1100]
In my application, I'm currently displaying several trip routes on the map by using polylines and circles. I display them one by one, by using two buttons for going to next and to previous trip.

Before I display a trip route, I fit the map to the coordinates from the route:

```javascript
this.map.fitToCoordinates(coordinates, {
	edgePadding: { top: 100, right: 100, bottom: 100, left: 100 },
	animated: true,
});
```

The routes are being drawn well. But sometimes, when I display a route which makes the app to zoom in the map in order to fit the coordinates of the route, it leaves a weird stain:

![4zqedmfem4](https://cloud.githubusercontent.com/assets/727798/23707580/8c260c90-03d8-11e7-832d-88a2e6afadf8.gif)

Why is that happening and how can I solve it?

**Comment by nick3389** [comment]
The same happens to me in my own app. I guess it's a MapKit bug. Is there anyone else with the same issue?

**Comment by jus101** [comment]
Yep, same issue here (iOS).

**Comment by lelandrichardson** [comment]
I'm not sure if there is anything actionable here. This seems unrelated to this library so I'm going to close for now.

**Comment by jus101** [comment]
@lelandrichardson any ideas on where this problem is originating from?

**Comment by FabioCH23** [comment]
Justin, I should be able to asnwer that question tomorrow morning since I need to direct it to our Dev team.

**Comment by FabioCH23** [comment]
@lelandrichardson  please don't close it. We still need help with this issue.

**Comment by guilhermepontes** [comment]
Same here.
