### ISSUE TITLE
[Android] Duplicate LifecycleEventListeners

### ISSUE THREAD

**Issue by psam44** [airbnb/react-native-maps#1102]
### Context
react-native@0.41.2
react-native-maps@0.12.4
Platform: Android
### Description
In AirMapView.java, a LifecycleEventListener instance is registered in onMapReady().
The problem is that instances are never unregistered.
It may appear as a leak.
How to reproduce:
- launch the app  --> creation, 1 listener
- tap on Back button  --> destroy, and the process stay (normal)
- launch again  --> creation, 2 listeners now
- tap on Overview button  --> onHostPause two times !!
- tap on the app  --> onHostResume two times !!
### Solution
In first approach, the following proposal seemed a fix:
In AirMapView.java/onMapReady()/onHostDestroy() add:
`context.removeLifecycleEventListener(this);`
But the problem came again with the introduction of React Navigation and a second screen (a DrawerNavigator is used). Everytime you come back to the map screen, an additional listener is registered.
In AirMapView.java:
- add `private LifecycleEventListener mLifecycleListener;`
- in onMapReady(), substitute these lines:
`LifecycleEventListener lifecycleListener = new LifecycleEventListener() {`
`context.addLifecycleEventListener(lifecycleListener);`
by:
`mLifecycleListener = new LifecycleEventListener() {`
`context.addLifecycleEventListener(mLifecycleListener);`
- add:
```
@Override
protected void onDetachedFromWindow() {
	if (mLifecycleListener != null ) {
		context.removeLifecycleEventListener(mLifecycleListener);
	}
	super.onDetachedFromWindow();
}
```

### Additional information
The fix may be beneficial to #939.

**Comment by lelandrichardson** [comment]
Fixed in #1130
