### ISSUE TITLE
i can't show map on device. help me

### ISSUE THREAD

**Issue by nguyenhatruong** [airbnb/react-native-maps#1105]
![capture](https://cloud.githubusercontent.com/assets/20810794/23786263/910686a0-059e-11e7-9991-cc43ab37b514.PNG)
import React, {Component} from 'react';
import{
  View,Text,ListView,TouchableOpacity,StyleSheet,Alert,TouchableHighlight
}from 'react-native';
import MapView from 'react-native-maps';
export default class Map extends Component{

    render(){
      return(
          

          <MapView style={con.map}
                initialRegigon={{
                  latitude: 11.5505007,
                  longitude: 107.8399706,
                  latitudeDelta: 0.5,
                  longitudeDelta: 0.5
                }}
          />

      );
    }
}

**Comment by i8wu** [comment]
do you have google api key defined in AndroidManifest?

**Comment by lelandrichardson** [comment]
seems like an API key issue. feel free to reopen if not.
