### ISSUE TITLE
Styling and positioning of the location button

### ISSUE THREAD

**Issue by deejayxd07** [airbnb/react-native-maps#1106]
Hi, Is there a way to style the location button? I've been reading through the docs but I couldn't find it.

Thanks.

**Comment by lelandrichardson** [comment]
Some light googling got me: http://stackoverflow.com/questions/40326403/set-custom-view-for-my-location-button-in-google-map

I think we could add some props for it, though it might be easiest to just make the button with react and put it on top of the map in the first place... which I think is probably a more reliable method of doing real customization here.

**Comment by mhamzawey** [comment]
I don't think this solves the problem.  on Android, the button is on the top right of the screen however, in iOS it is placed bottom right. What if i want to place in in the center right? is there a way to do so!
