### ISSUE TITLE
Warning : Native Component for 'AirMap' does not Exist

### ISSUE THREAD

**Issue by abhishekpandey747** [airbnb/react-native-maps#1107]

**Comment by aleksdao** [comment]
Hi @abhishekpandeykr did you ever resolve this issue? I'm encountering the same error message preventing the Maps component from correctly displaying

**Comment by abhishekpandeykr** [comment]
@aleksdao Please refer this, this worked for me 
https://github.com/airbnb/react-native-maps/issues/1127
