### ISSUE TITLE
showsMyLocationButton not working on Android

### ISSUE THREAD

**Issue by ashutosh-akss** [airbnb/react-native-maps#1108]
showsMyLocationButton is not working in Android , nothing shows up on map, tried compiling form mac & ubuntu 

react native : 0.42.0
react-native-maps: 0.12.4

```
 <MapView
                    style={styles.map}
                    showsMyLocationButton={true}
                    loadingEnabled={true}
                    showsPointsOfInterest={true}
                    showsCompass={true}
                    showsTraffic={false}
                    showsBuildings={true}
                    rotateEnabled={false}
                    region={{
                        latitude: this.state.latitude,
                        longitude: this.state.longitude,
                        latitudeDelta: 0.0922,
                        longitudeDelta: 0.0421,
                    }}

                    onRegionChange={this.onRegionChange}

                >
```

**Comment by deejayxd07** [comment]
try adding `showsUserLocation={true}`

**Comment by lelandrichardson** [comment]
Good first PR opportunity: add a useful warning for when people have `showsMyLocationButton` set to true but `showsUserLocation` is not...

**Comment by GayanSandaruwan** [comment]
Having the same issue. and my showsUserLocation is not working either.

**Comment by nonameolsson** [comment]
Same for me. Both `showsMyLocation` and `showsuserLocation` are set to true, but nothing shows up.

**Comment by DanGDroid** [comment]
for me the `showsUserLocation ` is working.  but not the `showsMyLocationButton`

**Comment by ericyip** [comment]
yes `showsMyLocationButton `  is not working...

**Comment by joegoodall1** [comment]
Seeing the same problem although `showsMyLocationButton` appears as soon as the phone (and map) is rotated?

**Comment by alvelig** [comment]
Duplicate of #1315

**Comment by alvelig** [comment]
Duplicate of #1033
