### ISSUE TITLE
animateToCoordinate sends me to Africa

### ISSUE THREAD

**Issue by JUnderwood1991** [airbnb/react-native-maps#1110]
```
this._map.animateToCoordinate({
coordinate: {
                      latitude: 28.869236999,
                      longitude: -81.234822999
                    }},
                    2);
```

> <MapView ref={(map)=>this._map = map}

Even with explicitly defined coordinates...

**Comment by peterept** [comment]
You shouldn't be putting the extra "coordinate:" key in your call.

This works for me:

```javascript
this._map.animateToCoordinate({
  latitude: 28.869236999,
  longitude: -81.234822999
}, 2);
```

**Comment by jeffreymendez1993** [comment]
How do you use this if the mapView is under MapView.Animated

**Comment by lelandrichardson** [comment]
@jeffreymendez1993 
```
this._map._component.animateToCoordinate({
  latitude: 28.869236999,
  longitude: -81.234822999
}, 2);
```

**Comment by hugomosh** [comment]
The documentation is misleading. https://github.com/airbnb/react-native-maps/blob/master/docs/mapview.md 
Same problem

**Comment by markmssd** [comment]
what's wrong with Africa, racist 😒
