### ISSUE TITLE
FitToCoordinates not working on MapView.Animated

### ISSUE THREAD

**Issue by JLLLinn** [airbnb/react-native-maps#1118]
For an animated mapview, I was not able to call FitToCoordinates, the error says it is not a function. is that the expected behavior?

**Comment by LubinPark** [comment]
<MapView   ref="_MapView" />
 this.refs._MapView.fitToElements(true);

**Comment by JLLLinn** [comment]
It still does not work, or would you be more clear about where to call this or how to incorporate it with FitToCoordinates? 

My ref is set to this.map and when I do this.map.fitToElements(true); or this.map.fitToCoordinates(<some parameters>), neither works. 

The error says that this.map.fitToElements or this.map.FitToCoordinates is not a function.

**Comment by LubinPark** [comment]
it not this.map.fitToElements(true) 
this.refs.map.fitToElements(true)

**Comment by JLLLinn** [comment]
[https://github.com/airbnb/react-native-maps/issues/896](url) These are possibly related

**Comment by JLLLinn** [comment]
@LubinPark I'm not sure if thats how you access the ref sir.. As I said I assign the ref to this.map. Btw I tried it and still doesn't work.

**Comment by LubinPark** [comment]
<MapView ref="MapView">     
this.refs._MapView.fitToElements(true); 
it work, 
![pasted graphic 1](https://cloud.githubusercontent.com/assets/18719819/23933822/1ca6a74a-097c-11e7-94da-a6198bcb2e5f.png)
![pasted graphic 2](https://cloud.githubusercontent.com/assets/18719819/23933939/de1c3804-097c-11e7-8c62-d03bf22a9419.png)
![1](https://cloud.githubusercontent.com/assets/18719819/23933940/e2503a74-097c-11e7-80ba-49302f64e41b.gif)
 if no mistake, may be other problems

**Comment by LubinPark** [comment]
MapView ref="MapView" 
 this.refs._MapView.fitToElements(true); 
 it work, 
 if no mistake, may be other problems

**Comment by LubinPark** [comment]
I also have a question,it only show user location button, how to get their current geographical position

**Comment by JLLLinn** [comment]
@LubinPark Are you using <MapView> or <MapView.Animated>? Can you post your MapView code?

**Comment by LubinPark** [comment]
<MapView ref="_MapView"
                   mapType='standard'
                   style={styles.mapView}
                   rotateEnabled={true}
                   scrollEnabled={true}
                   zoomEnabled={true}
                   showsCompass={true}
                   showsBuildings={true}
                   showsUserLocation={true}
                   region={this.state.region}
                   loadingEnabled={false}
                   showsMyLocationButton={true}
                   followsUserLocation={this.state.followsUserLocation}

                   onPress={(value)=>this._showLocation(value)}
                   onRegionChangeComplete={(value)=>this.onRegionChangeComplete(value)}>

**Comment by JLLLinn** [comment]
I see. It's MapView, this issue is related to MapView.Animated. 

FitToCoordinates and fitToElements do work for the original one, this issue here concerns about the animated one. Thanks anyway! :)

**Comment by grundmanise** [comment]
Try with `getNode()` like this `this._mapRef.getNode().fitToElements(true);`

**Comment by lelandrichardson** [comment]
`this._mapRef._component.fitToElements(true);` will also work.
