### ISSUE TITLE
[iOS] Blank Map (only google logo showing)

### ISSUE THREAD

**Issue by mxmtsk** [airbnb/react-native-maps#1120]
I tried to setup `react-native-maps` on my `react 0.41.0` project and so far it does seem to work with Apple Maps but when I switch to google it does only show the google logo and nothing else.

I have no idea how to debug this or what the issue could be?

**Comment by ryankask** [comment]
Is your Google Maps API key set up? Does it have the correct restrictions? Have you enabled the iOS API  in the Google API console: https://console.cloud.google.com/apis/api/maps_ios_backend/overview?

Please try those things and let me know if you still have issues.
