### ISSUE TITLE
AirMaps semantic issue on react-native link

### ISSUE THREAD

**Issue by anonrig** [airbnb/react-native-maps#1121]
Hello,

When I run `react-native link react-native-maps` on an iOS project I keep getting 20 issues on semantic issue regarding "duplicate interface definition for class RCTView" etc.

Additionally, I keep getting Apple LLVM 8.0 Error. Too many errors emitted stopping now.

I've added project using ` yarn add react-native-maps` and run `react-native link react-native-maps`

**Comment by manukn** [comment]
Same error for me too. seems like libAirMap.a and many other files are missing.

**Comment by anonrig** [comment]
This bug is due to installing 0.12 version not 0.13. Check out this pr https://github.com/airbnb/react-native-maps/pull/1092
