### ISSUE TITLE
User Location Icon has Background

### ISSUE THREAD

**Issue by mxmtsk** [airbnb/react-native-maps#1124]
The "Current Location Icon" has a white background that I can't seem to get rid of.

react-native-maps 0.13.0
react-native 0.41.0

EDIT: This only happens in the simulator

I have no additional styles in place for the map:
```Javascript
<MapView
  ref="map"
  provider={MapView.PROVIDER_GOOGLE}
  style={StyleSheet.absoluteFill}
  initialRegion={this.state.region}
  region={this.state.region}
  loadingBackgroundColor="transparent"
  showsUserLocation
  onPanDrag={() => { console.log('called'); }}
  onRegionChangeComplete={(region) => {
    this.setState(() => {
      return { region };
    });
  }}
/>
```

<img width="361" alt="bildschirmfoto 2017-03-13 um 19 40 28" src="https://cloud.githubusercontent.com/assets/4848184/23870012/64414824-0825-11e7-9b0a-da4e8e080359.png">

**Comment by JLLLinn** [comment]
I saw this on my simulator too, but it was showing ok on my phone.

**Comment by geek2050** [comment]
Likewise ... I am running on iOS.
react-native-maps 0.13.0
react-native 0.38.1

On simulator - can see the white background
On device - it is ok

**Comment by JLLLinn** [comment]
I tested that on iPhone 6s with iOS 10.2 and the icon was fine, anyone tried with other hardwares?

**Comment by alexbelyeu** [comment]
This is because the perimeter around the location icon is for the orientation of the device, so instead of mocking an orientation by default (which could be a good idea, to avoid this confusion) it just shows that weird square around it. Nothing to worry about! 👍

**Comment by cbartondock** [comment]
Rather different explanation given here: https://issuetracker.google.com/issues/35822632

Annoying if one wants to automate taking in app screenshots
