### ISSUE TITLE
How to get the user's geographical location(iOS)

### ISSUE THREAD

**Issue by LubinPark** [airbnb/react-native-maps#1126]
it only show user Location on map,How to get the user's geographical location

**Comment by JLLLinn** [comment]
If you meant the coordinates, you might need to turn to this https://facebook.github.io/react-native/docs/geolocation.html

**Comment by LubinPark** [comment]
I use this method, but a map with the error of half a kilometer, when the user's location changes cannot be detected

**Comment by JLLLinn** [comment]
Hmm Interesting, have not noticed issue with it yet, and I put a watch on it too, it detects the user's movement. 

Deep down they should use the same native api (Google map also uses Apple's location api, assuming your on iPhone). If the location given by react native matches the blue dot on your map, I don't think there's much you can do about it.
