### ISSUE TITLE
Map Key Not Found

### ISSUE THREAD

**Issue by abhishekpandeykr** [airbnb/react-native-maps#1127]
I have added Map Key in Manifest file, I think I have did everything what airbnb maps required to implement map in React Native.
1. this is the output what I am getting
![capture](https://cloud.githubusercontent.com/assets/19070938/23886597/3c3fe1be-08a2-11e7-9fe4-66b9a975f978.JPG)
2. Manifest.xml file is 
![manifest](https://cloud.githubusercontent.com/assets/19070938/23886615/5b592dd0-08a2-11e7-9e5b-de654e9d3c05.JPG)

3. Main Application.java file is 
![mainapplicationjava](https://cloud.githubusercontent.com/assets/19070938/23886627/757d7edc-08a2-11e7-9512-6305625fb814.JPG)
 4. and the main file where I am calling map is 
![spotlocation](https://cloud.githubusercontent.com/assets/19070938/23886646/902eaf94-08a2-11e7-938f-1722152f128d.JPG)

Please let me know, where I am doing wrong, I have spend too much time here.

**Comment by abhishekpandeykr** [comment]
I have solved this issue.

**Comment by irvan2208** [comment]
Please let us know how you solve this issue, maybe other people have the same problem

**Comment by dscx** [comment]
@abhishekpandeykr what was your fix? I am running into this issue as well.

**Comment by abhishekpandeykr** [comment]
@dscx what i did was 
1. gradlew clean ,
2. react-native run-android
it has fixed my issues, what i thought that time, it was stored in the cache, so it is not updating my Google API Key, hope that same issue with you as well if everything is fine, what you have did.

**Comment by cesargdm** [comment]
Having this issue, despite my configuration

<img width="731" alt="screen shot 2017-12-16 at 4 50 52 pm" src="https://user-images.githubusercontent.com/10179494/34075136-cdc0a7a8-e282-11e7-9616-47f836469a62.png">
