### ISSUE TITLE
Where to config API Key for IOS?

### ISSUE THREAD

**Issue by ithieund** [airbnb/react-native-maps#1128]
Hi,
I followed the instruction, there was a place in AndroidManifest to config API Key for Android, but I can't find the instruction to config that API Key for IOS?

Is IOS does not need the API Key, or the instruction missing this step?
Thanks.

**Comment by eard7** [comment]
You need to add this inside your AppDelegate.m

In the imports section
```
@import GoogleMaps;
```
And then add this
```
[GMSServices provideAPIKey:@"YourMapsApiKey"];
```
inside
```
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
```
The [Google Maps SDK for iOS docs](https://developers.google.com/maps/documentation/ios-sdk/start?hl=en-419) had the answer

Hope it helps!

**Comment by ithieund** [comment]
@eard7 ,
Thank you very much.

**Comment by ithieund** [comment]
@eard7 ,
Did you make it work?
Thanks.

**Comment by eard7** [comment]
@ithieund 
Sure, it works really well.
You just need to add your Pod file in the root of the ios folder. This is my Pod file
```
# You Podfile should look similar to this file. React Native currently does not support use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

# Change 'yourProject' to match the target in your Xcode project.
target 'yourProject' do
  pod 'React', path: '../node_modules/react-native', :subspecs => [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
  ]

  pod 'GoogleMaps'  # <~~ remove this line if you do not want to support GoogleMaps on iOS

# when not using frameworks  we can do this instead of including the source files in our project (1/4):
#  pod 'react-native-maps', path: '../../'
#  pod 'react-native-google-maps', path: '../../'  # <~~ if you need GoogleMaps support on iOS
end
```
Then follow all the installation instructions on the wiki. Then mod your AppDelegate with the instructions i put above. Remember that after the pod install, you need to open your project using the xcworkspace file, not the xcodeproj.
Hope that helps!

**Comment by ithieund** [comment]
@eard7 ,
Thank you very much.
I know the reason now: I'm not the cocoapods user so I missed the step of manual install Google Maps SDK.

I'm doing that step now. Hope all will be OK :)

**Comment by eard7** [comment]
@ithieund ,
let's hope everything works as expected ;)
let us know how all goes

**Comment by ithieund** [comment]
@eard7 ,
It worked now. I had to follow this instruction to make it work.
https://gist.github.com/heron2014/e60fa003e9b117ce80d56bb1d5bfe9e0

Thanks.

**Comment by lelandrichardson** [comment]
Closing. Seems like this could be a good docs PR for someone!
