### ISSUE TITLE
Use of undeclared identifier 'GMSMapStyle' ---Google Map on iOS

### ISSUE THREAD

**Issue by guoliang1206** [airbnb/react-native-maps#1129]
Is anyone faced this warning on iOS? I can't find the GMSMapStyle, my GoogleMaps SDK version is 1.3.2,I used cocoapods install the sdk.

**Comment by guoliang1206** [comment]
![2017-03-15 3 25 26](https://cloud.githubusercontent.com/assets/12846676/23937674/a76b9342-0993-11e7-92ca-d453276eb7f5.png)

some guys said update to 2.0.1 or 2.1.1 but there only have 1.3.2 for the new.

**Comment by ABleas** [comment]
I'm having the same issue.. did you resolve it @guoliang1206 ?

**Comment by guoliang1206** [comment]
@ABleas  I was deleate the alert code....,and run the project. At now,there is normally
