### ISSUE TITLE
Images doesn't show on release apk android using custom view

### ISSUE THREAD

**Issue by wasa4587** [airbnb/react-native-maps#1135]
It works good when i use the debug apk, i tested on ios emulator and it's working good as well,
but when i create the release apk, the images are not showing, 
i tried incrementing the zindex, building the bundle before the assembleRelease, 
but i can't  get it works.
react-native-cli: 2.0.1
react-native: 0.41.2
package.json
`    "react-native-maps": "0.13.0",
`
```
            <MapView.Marker
              key={key}
              coordinate={marker.latlng}
              provider={PROVIDER_GOOGLE}
              onPress={(position)=> {
                this.setState({selectedMarker: marker.doc, mode: DETAIL_MODE});
                this._map.animateToCoordinate(marker.latlng, 10);
              }}
            >
              <Image
                  style={{ width: 50, height: 50 , zIndex:9999}}
                  source={markerImage
                  }
               />
            </MapView.Marker>
```

**Comment by bramvbilsen** [comment]
I'm sorry, totally off topic. But how did you even get it installed on iOS? Did you just npm install, link it and changed your package.json?

**Comment by wasa4587** [comment]
i installed using yarn add react-native-maps@0.13.0, and it automatically linked everything

**Comment by ilyadoroshin** [comment]
same here... images within MapView.Marker are not shown on Android

**Comment by wasa4587** [comment]
Ok, this is not a fix at all, but i get my custom views working,
the issue is that the image is not being bundling correctly,
so i added an image
    ```
        <MapView.Marker
              coordinate={
                this.props.app.position.coords
              }
              >
              <Image
                source={require('../../assets/img/direction.png')}
              />
           </MapView.Marker>
```
in the top of my component i added
```
      //this makes the image bundles correctly, and now it appears on my marker :D
              <Image
                style={{width:0, height:0}}
                source={require('../../assets/img/direction.png')}
              />
```
