### ISSUE TITLE
Confusion on Readme documentation

### ISSUE THREAD

**Issue by oatcrunch** [airbnb/react-native-maps#1136]
The document is a bit misleading, especially for the part where it mentioned onPress/onLongPress events (for MapView or MapView.Marker for example) where the stated return would be "{ coordinate: LatLng, position: Point }".

Source: https://github.com/airbnb/react-native-maps/blob/master/docs/mapview.md

After scrutinizing the examples, I only realized that it should be something like "e.nativeEvent.coordinate" instead, where "e" is the direct return for onPress/onLongPress. For example:

//map view:
<MapView
     //truncated for clarity
                    showsUserLocation={true}
                    showsMyLocationButton={true}
                    onLongPress={this.onMapPress.bind(this)}
                ></MapView>

//event handler:
onMapPress(e) {
        alert(e.nativeEvent.coordinate);//returns object
        alert(e.nativeEvent.coordinate.latitude);//returns a number
//confusion happens when readers will assume "e" as parameter that has "coordinate" and "position" objects, which in turn returns null for both
    }

Appreciate some updates on the readme to cause future confusion for beginners like me.

Thanks and regards.

**Comment by lelandrichardson** [comment]
@oatcrunch this is a great suggestion! I will add this to my list of things to do, but if you would like to put up a PR to the docs that would be even better! It seems like you have a good grasp on it.

**Comment by mikenk2010** [comment]
Yup, worked for me as well for `onLongPress` 
```
e.nativeEvent.coordinate
```
