### ISSUE TITLE
Move map to marker on ScrollView scroll

### ISSUE THREAD

**Issue by grundmanise** [airbnb/react-native-maps#1139]
I am trying to get [the same behavior](https://camo.githubusercontent.com/9b5fcde0cb8146672f54d39fc3c34bd2e1f7891f/687474703a2f2f692e67697068792e636f6d2f336f365542644751644d31476d566f4964712e676966) but only with a `ScrollView` instead of a `PanController`.  I am using `Animated.ScrollView` and setting `onScroll` like this:

```
onScroll = {Animated.event({
   [ { nativeEvent: { contentOffset: { x: this._scrollX } } } ],
   { useNativeDriver: true }
})}
```

`this.state.region = new MapView.AnimatedRegion({ latitude:..., longitude:..., latitudeDelta:...., longitudeDelta:...,  });`

and I am trying to interpolate `this.state.region.latitude` like this:

`this.state.region.latitude = this._scrollX.interpolate({ inputRange: [0, SCROLLVIEW_LENGTH], outputRange: [25.0000, 26.0000] });`

but nothing happens. What am I doing wrong? How can I hook latitude & longitude to the `ScrollView` `x offset`?

**Comment by lelandrichardson** [comment]
@grundmanise I am going to close this issue as well. I hope you are not discouraged! It looks like you are on the right path. StackOverflow might be a better venue for questions like this FWIW.
