### ISSUE TITLE
Marker position like Uber

### ISSUE THREAD

**Issue by thiagoterleski** [airbnb/react-native-maps#1154]
Hi! How can I use "Uber" like mode to put my marker on correct position, I don't drag the marker, I want drag only map and my marker stay on center of map.

Can anyone help me? Thanks.

**Comment by markmssd** [comment]
My approach would be to always set the marker's position to the position of the map's center position.
So, when you listen on the `end_drag` (or is it `enddrag`?) event of the map, you get the map's center and set it as your position

**Comment by thiagoterleski** [comment]
Yes, I wondering if it could be a performance problem..

**Comment by ryankask** [comment]
You can position absolutely position a marker image in the center of the map view.

 You may need to offset it depending on its shape.

**Comment by DevillBuster** [comment]
how did you do that can you explain it??

**Comment by kytwb** [comment]
More info in https://github.com/airbnb/react-native-maps/issues/1542

**Comment by Ahmed-Imam** [comment]
I have positioned the fake marker in the map just didn't know how to get the Latitude and Longitude of the fake marker since its an Image?
     ```
<MapView
                        region={this.getMapRegion()}
                        style={styles.map}
                        provider={PROVIDER_GOOGLE}>

                        <Image style={{
                            left: '50%',
                            marginLeft: -24,
                            marginTop: -48,
                            height: 60, width: 60,
                            
                            position: 'absolute',
                            top: '50%'
                        }} source={require('../assets/fake-marker.png')} />

                    </MapView>
```

**Comment by Tokol** [comment]
> I have positioned the fake marker in the map just didn't know how to get the Latitude and Longitude of the fake marker since its an Image?
> 
> ```
> <MapView
>                region={this.getMapRegion()}
>                 style={styles.map}
>                  provider={PROVIDER_GOOGLE} >
> 
>                <Image style={{
>                         left: '50%',
>                             marginLeft: -24,
>                             marginTop: -48,
>                             height: 60, width: 60,
>                             
>                             position: 'absolute',
>                             top: '50%'
>                         }} source={require('../assets/fake-marker.png')} />
> 
>  </MapView>
> ```

how would you get lattitude and longitude of middle of the map??

**Comment by snowmen10** [comment]
> 
> how would you get lattitude and longitude of middle of the map??

onRegionChange or onRegionChangeComplete
