### ISSUE TITLE
Overlapping markers flicker over eachother

### ISSUE THREAD

**Issue by duhaime** [airbnb/react-native-maps#1159]
I've been working on some maps with custom marker icons from [react-native-vector-icons](https://github.com/oblador/react-native-vector-icons) and have just discovered that when two custom marker icons are positioned at the same location, they flicker over eachother:

![flicker](https://cloud.githubusercontent.com/assets/4801116/24244672/4731298e-0f96-11e7-9781-4c4bc1c651f9.gif)

Here's how I'm creating the markers:

```
render() {
    const location = this.props.location && this.props.location.latitude ?
      <MapView.Marker
        coordinate={{
          latitude: this.props.location.latitude,
          longitude: this.props.location.longitude
        }}>
        <Icon name={'ghost'} size={35} color="#444" />
      </MapView.Marker>

    : null;

    return (
      <MapView
        style={styles.map}
        region={this.props.location}
        provider={PROVIDER_GOOGLE}
        customMapStyle={require('../../assets/json/MapStyle.json')} >

        {location}

        {this.state.markers.map((marker, i) => (
          <MapView.Marker
            key={i}
            coordinate={marker.coordinate}
            title={marker.address}>
            <Icon name={'factory'} size={35} color="#F44336" />
          </MapView.Marker>
        ))}
      </MapView>
    );
```

I'm on react-native-maps `"version": "0.13.0",` react-native `"version": "0.41.2"`.

If anyone has any thoughts on why the flicker might be happening, I'd be grateful for any insights they can offer. Either way, thank you for this phenomenal library!

**Comment by duhaime** [comment]
I should have mentioned this was observed on the ios simulator for iPhone 6.

**Comment by duhaime** [comment]
This can be resolved by simply giving each marker its own zIndex:
```
  render() {
    const location = this.props.location && this.props.location.latitude ?
      <MapView.Marker
        coordinate={{
          latitude: this.props.location.latitude,
          longitude: this.props.location.longitude
        }}>
        <Icon name={'ghost'} size={35} color="#444" />
      </MapView.Marker>

    : null;

    return (
      <MapView
        style={styles.map}
        region={this.props.location}
        provider={PROVIDER_GOOGLE}
        customMapStyle={require('../../assets/json/MapStyle.json')} >

        {location}

        {this.state.markers.map((marker, i) => (
          <MapView.Marker
            key={i}
            coordinate={marker.coordinate}
            title={marker.address}
            zIndex={i}>
            <Icon name={'factory'} size={35} color="#F44336" />
          </MapView.Marker>
        ))}
      </MapView>
    );
  }
```

**Comment by sytolk** [comment]
@duhaime I have this exception when I have on the Google Map vector Marker using react-native-vector-icons in Android.
This appears only in production environment. It not appears in dev environment -Google Emulator. 
Do you test to build .apk and install you application in real device?
```
React: Exception in native call
                 java.lang.IllegalArgumentException: Failed to decode image. The provided image must be a Bitmap.
                     at com.google.maps.api.android.lib6.impl.n.a(:com.google.android.gms.DynamiteModulesB:40)
                     at com.google.maps.api.android.lib6.impl.o.a(:com.google.android.gms.DynamiteModulesB:47)
                     at com.google.maps.api.android.lib6.impl.db.<init>(:com.google.android.gms.DynamiteModulesB:1212)
                     at com.google.maps.api.android.lib6.impl.az.a(:com.google.android.gms.DynamiteModulesB:39141)
                     at com.google.android.gms.maps.internal.l.onTransact(:com.google.android.gms.DynamiteModulesB:167)
                     at android.os.Binder.transact(Binder.java:499)
                     at com.google.android.gms.maps.internal.IGoogleMapDelegate$zza$zza.addMarker(Unknown Source)
                     at com.google.android.gms.maps.GoogleMap.addMarker(Unknown Source)
                     at com.airbnb.android.react.maps.AirMapMarker.addToMap(AirMapMarker.java:258)
                     at com.airbnb.android.react.maps.AirMapView.addFeature(AirMapView.java:398)
                     at com.airbnb.android.react.maps.AirMapManager.addView(AirMapManager.java:277)
                     at com.airbnb.android.react.maps.AirMapManager.addView(AirMapManager.java:29)
                     at com.facebook.react.uimanager.NativeViewHierarchyManager.manageChildren(NativeViewHierarchyManager.java:394)
```

**Comment by sytolk** [comment]
My bad. font.ttf is not exported in android/app/src/main/assets folder.

**Comment by duhaime** [comment]
@sytolk sounds good. I saw the behavior above on the ios simulator, not an android device build, but I'm glad it all worked out!

**Comment by kdong007** [comment]
@duhaime  is z index still working?

**Comment by duhaime** [comment]
@kdong007 I haven't been on this project for some time, so can't say--sorry about that!

**Comment by hugoh1995** [comment]
Still getting the flickering when moving map around and when updating markers

**Comment by herlan-evocorp** [comment]
Hello guys, in my react native project I'm using react-native-maps and the react-native-super-cluster. At some points I have several nearby markers that even with the maximum zoom I can not interact with them.

I want to do something similar to this:
http://fritz-c.github.io/OverlappingMarkerSpiderfier/examples/

**Comment by herlan-evocorp** [comment]
Hi @steventilator, I noticed that this problem only appears when I click on the cluster and it zooms in on the map. To work around this problem I have passed a function to the onClusterPress props and I check the zoom level, for this function I can capture all the points of that cluster and decide how to work with them, in case I displayed a modal listing my points.
