### ISSUE TITLE
no +[rctconvert airmapcoordinatearray:] function found.

### ISSUE THREAD

**Issue by datvudang** [airbnb/react-native-maps#1168]
Hi,
When I run code on iOS, it show error "no +[rctconvert airmapcoordinatearray:] function found." if the map use <MapView.Polyline /> Component API.

Code work well on Android. On iOS, the app work when only show map and some marker.

**Comment by lelandrichardson** [comment]
cc @janicduplessis  related to #1138 ?

**Comment by janicduplessis** [comment]
@lelandrichardson Hmm probably, I guess it picks the RCTConvert+Mapkit extension from RN instead of the one from AirMaps. we could probably rename the extension to something else to make sure it doesn't conflicts with the one in RN.

**Comment by lelandrichardson** [comment]
@janicduplessis would you be up for submitting a PR doing that renaming? perhaps we can use `RCTConvert+AirbnbReactNativeMaps` or something

**Comment by janicduplessis** [comment]
Sure
