### ISSUE TITLE
iOS animateToRegion navigates to lat: 0 long: 0

### ISSUE THREAD

**Issue by 6farer** [airbnb/react-native-maps#1171]
I created a button to center on the user's location and it brings me to 0, 0.
Has anyone encountered this?

EDIT: The user's location is irrelevant. I hard code the coordinates and same results.

**Comment by nitindhar7** [comment]
having the same issue with the GoogleMaps provider

**Comment by marufino** [comment]
ran into this same issue I was using 
```
this.map.animateToRegion({
        region: {
            latitude: 35.7796,
            longitude: -78.6382,
            latitudeDelta: 10,
            longitudeDelta: 10
        }
      },1);
```

removing the region: fixed it 
```
this.map.animateToRegion({
        latitude: 35.7796,
        longitude: -78.6382,
        latitudeDelta: 10,
        longitudeDelta: 10
      },1);
```
