### ISSUE TITLE
takesnapshot on iOS using Google Maps

### ISSUE THREAD

**Issue by pvsleeper** [airbnb/react-native-maps#1173]
Hi,

I'm trying to use Google maps on iOS and I'm having an issue when calling takesnapshot().  The exception I get is:
``[tid:com.facebook.react.ShadowQueue][RCTModuleMethod.m:488] AIRGoogleMapManager. was called with 8 arguments but expects 5 arguments. If you haven't changed this method yourself, this usually means that your versions of the native code and JavaScript code are out of sync. Updating both should make this error go away.``

AIRGoogleMapManager's takeSnapshot takes 5 arguments and AIRMapManager's takeSnapshot takes 8, however, it seems that MapView.js will aways call it with 8 arguments.

**Comment by christopherdro** [comment]
https://github.com/airbnb/react-native-maps/pull/1774
