### ISSUE TITLE
react-native-maps conflict something with react-native-push-notification, app is closed unexpected ?

### ISSUE THREAD

**Issue by phanngoc** [airbnb/react-native-maps#1191]
When i installed more react-native-push-notification(https://github.com/zo0r/react-native-push-notification) library, page which have mapview will be closed suddenly without any error show, even screen mobile and js remotely. I don't know why, hope some people can find out it's reason .

**Comment by Jose4gg** [comment]
I'm having the same problem

**Comment by dorthwein** [comment]
Same here +1

**Comment by phanngoc** [comment]
I have already resolved this problem, it's reason is conflict between many library google gms, we need update library to lastest for 2 library, i must modify in npm library for fix this, it is so weird. @_@

**Comment by trinhak** [comment]
i updated version lastest but my app still crash ... maps v0.22.1, push-notification v3.1.2
