### ISSUE TITLE
[v0.14.0] Apple Mach-O Linker Error: library not found for -lAirMaps

### ISSUE THREAD

**Issue by joncursi** [airbnb/react-native-maps#1201]
After upgrading from `0.13.x` -> `0.14.0` and clearing out xcode's derived data, my builds started to fail. I'm getting an Apple Mach-O Linker Errror:

```
ld: library not found for -lAirMaps
```

![screen shot 2017-04-06 at 6 20 53 am](https://cloud.githubusercontent.com/assets/4974609/24749521/5ff6f448-1a91-11e7-94cd-c601f8ebb233.png)

There were no release notes for 0.14.0 so I was unaware there were potential breaking changes.

**Comment by joncursi** [comment]
I'm re-walking through all of the installation steps and i noticed that `libAirMaps.a` does not seem to exist under AirMaps.xcodeproj > AirMaps > Products as it used to. See: https://github.com/airbnb/react-native-maps/blob/master/docs/installation.md#option-3-manually -> step 2

![screen shot 2017-04-06 at 6 34 55 am](https://cloud.githubusercontent.com/assets/4974609/24750023/56acca8c-1a93-11e7-94ea-77ffc77b059b.png)

**Comment by joncursi** [comment]
Alright, I was able to drill down and find the source of the problem. Seems to be a react-native link issue which several others have faced: https://github.com/airbnb/react-native-maps/issues/1193

**Comment by phaptq** [comment]
I has success build in ios with tips:

1. init project with version 0.42.3 (to fix '_npm WARN react-native-maps@0.14.0 requires a peer of react@>=15.4.0 but none was installed'_).

2. skip step _react-native link react-native-maps_ to use **Option 3: Manually** in the docs.

3. in Xcode open libraries -> right click AirMaps.xcodeproj -> add file to AirMaps -> go to find react-native-maps into node_module -> lib -> ios -> AirMaps -> select RCTConvert+MapKit.h/m -> add (to fix 'File RCTConvert+MapKit.m not found').

4.  **npm install --save-dev babel-plugin-module-resolver** (to fix .babelrc cause error).

5. watchman watch-del-all. And rebuild project.
