### ISSUE TITLE
showsMyLocationButton appears on map, even if its hidden.

### ISSUE THREAD

**Issue by avdept** [airbnb/react-native-maps#1203]
I'm having problem with `showsMyLocationButton`. If was set to `false`, however when i click on any marker(have callout inside), it shows set of buttons. Is there any way to hide them?
<img width="403" alt="screen shot 2017-04-06 at 9 05 53 pm" src="https://cloud.githubusercontent.com/assets/1757017/24768842/d81143ae-1b0c-11e7-9975-81532598dcdf.png">

**Comment by gerrod** [comment]
If you mean the little "Navigate" icon (in blue) - try setting `toolbarEnabled={false}`.

**Comment by avdept** [comment]
Yes, that helped me. THanks
