### ISSUE TITLE
.babelrc in git repo

### ISSUE THREAD

**Issue by davidhellsing** [airbnb/react-native-maps#1206]
https://github.com/airbnb/react-native-maps/blob/master/.babelrc

This file should be removed, or you will get `Unknown plugin: "module-resolver"` when compiling.

**Comment by ZeroCho** [comment]
+1

**Comment by tugorez** [comment]
+1 Same issue here

**Comment by rigdern** [comment]
There's some discussion about this starting here: https://github.com/airbnb/react-native-maps/issues/795#issuecomment-289828439

**Comment by khalid32** [comment]
I had to remove .babelrc file. Now works fine.

**Comment by anydasa** [comment]
+1 Same issue here

**Comment by anandbhardwaj** [comment]
+1 same issue. I am not able to use the map. getting error - Unknown plugin "Module-Resolver" specified in the .../.babelrc.

**Comment by ZeroCho** [comment]
Temporay solution for this is to npm-install **module-resolver**

**Comment by tugorez** [comment]
@ZeroCho or install the latest-working version.

**Comment by sangagung** [comment]
@tugorez it seems that the developers pulled the earlier version from npm registry. 
Running `npm install react-native--maps@0.13.1` presented me with error 404 messages.

I've tried removing .babelrc and followed the suggestion from #1219, I still got the `Unknown plugin: "module-resolver"` error

**Comment by tugorez** [comment]
@sangagung try with this version 0.12.4

**Comment by anydasa** [comment]
I have installed 0.13.0 version.

**Comment by quickskape** [comment]
@sangagung 

> Running npm install react-native-maps@0.13.1 presented me with error 404 messages.

You have two dashes in your package name it should be `npm install react-native-maps@0.13.1`

That should at least get rid of those 404 messages on install and targeting that version has also fixed my compile issue too.

**Comment by EmielM** [comment]
Afaict this really does nothing, just adds another bunch of useless (dev)dependencies to my project. Aliassing the module is not necessary as it already exists in `node_modules/` 99% of the time. An idea to just remove the file for the next release?

**Comment by agentilela** [comment]
Wrote a simple shell script to fix react-native-maps build errors that gets run whenever i rebuild my project. Maybe it'll be helpful to someone:

`sed -ie 's/RCTConvert\+MapKit\.m/RCTConvert\+AirMap\.m/g' node_modules/react-native-maps/lib/ios/AirMaps.xcodeproj/project.pbxproj
sed -ie 's/RCTConvert\+MapKit\.h/RCTConvert\+AirMap\.h/g' node_modules/react-native-maps/lib/ios/AirMaps.xcodeproj/project.pbxproj
rm -f node_modules/react-native-maps/.babelrc`

**Comment by fxfactorial** [comment]
Had quick a few difficulties with this as well, I find the solution is versioning correctly. 

```
"dependencies": {
    "mobx": "^3.1.9",
    "mobx-react": "^4.1.8",
    "native-base": "^2.1.2",
    "react": "16.0.0-alpha.6",
    "react-native": "0.43.4",
    "react-native-calendar": "^0.11.0",
    "react-native-communications": "^2.2.1",
    "react-native-maps": "^0.14.0",
    "react-native-swiper": "^1.5.4",
    "react-navigation": "git+https://github.com/react-community/react-navigation.git#7edd9a7",
    "styled-components": "^1.4.5"
  },
  "devDependencies": {
    "babel-jest": "19.0.0",
    "babel-plugin-module-resolver": "^2.7.0",
    "babel-preset-react-native": "1.9.1",
    "jest": "19.0.2",
    "react-test-renderer": "16.0.0-alpha.6"
  },
```

Getting the proper combination of dependencies versioning is key.

**Comment by MacKentoch** [comment]
Thank you @fxfactorial,

`yarn add --dev babel-plugin-module-resolver` solved the issue for me.

**Comment by rigdern** [comment]
@christopherdro why was this issue closed?

**Comment by christopherdro** [comment]
Fixed via https://github.com/airbnb/react-native-maps/commit/36a36917e4897c934b5bfe9cbaf1a63f87637e8e

**Comment by rigdern** [comment]
@christopherdro Cool, thanks for the quick response. Does that help in the scenario that somebody is working on a change to `react-native-maps` so they have the `react-native-maps` git repo cloned into their app's `node_modules` folder?

**Comment by bosung90** [comment]
Still breaks when using `yarn install`.
Had to resolve to `yarn add --dev babel-plugin-module-resolver` but would like to get this fixed without this hack.
