### ISSUE TITLE
Android marker images takes quite long to load the image

### ISSUE THREAD

**Issue by macdonjo** [airbnb/react-native-maps#1208]
So my app has both an iOS and an Android version.

My Android users are complaining that the images take a very long time to load, and they do. The iOS version loads almost immediately but Android images take 10-30 seconds to load.

Nothing is different between the 2 code bases. I copied index.ios.js to index.android.js.

There are a number of decent-sized images, so there should be some delay, but I don't get the difference.

Does iOS load all images in the marker before the marker is tapped? I think so. Does Android? Maybe it doesn't. I'm just thinking out loud.

**Comment by MathieuMailhos** [comment]
Is it for Android only ? Does the image actually appears at a point ?

There are several issues with Image Markers on Android, see:
[#100](https://github.com/airbnb/react-native-maps/issues/100) and [#924](https://github.com/airbnb/react-native-maps/issues/924)

**Comment by macdonjo** [comment]
It usually do. I'll test further but I'm 95% sure it's one of these issues. I'll reopen if it's not. Thank-you.
