### ISSUE TITLE
Do not install v0.14.0 on Android

### ISSUE THREAD

**Issue by hemedani** [airbnb/react-native-maps#1219]
In install instruction you say should add this line in `android/settings.gradle` :
```
include ':react-native-maps'
project(':react-native-maps').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-maps/android')
```

But in the `../node_modules/react-native-maps` we don't have `android` folder I think it's move to `lib` folder, so I change the path to :
```
include ':react-native-maps'
project(':react-native-maps').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-maps/lib/android')
```

The path error for dependency is fixed but we have `Unknown plugin "module-resolver"` problem :
```
TransformError: /home/syd/Work/ignite/TaxiBS/node_modules/react-native-maps/index.js: Unknown plugin "module-resolver" specified in "/home/syd/Work/ignite/TaxiBS/node_modules/react-native-maps/.babelrc" at 0, attempted to resolve relative to "/home/syd/Work/ignite/TaxiBS/node_modules/react-native-maps"
```

**Comment by hemedani** [comment]
The version 0.13.0 working fine

**Comment by henrikra** [comment]
I have exactly same problem after updating from 0.13.1 to 0.14 :/

**Comment by chris-at-translate** [comment]
Yup I encountered the same problem too, upgrading the same as @henrikra above. I was also looking around and found that it's related to babelrc. For one reason or another. Let me find the issue again.

**Comment by chris-at-translate** [comment]
Sorry if this is messy I'm on my phone. This issue here #1206 references this issue here https://github.com/airbnb/react-native-maps/issues/795#issuecomment-289828439 which makes my project work again but breaks other libraries I'm using.

**Comment by zengyanzi** [comment]
is there any solution towards this problem please?

**Comment by iztokf** [comment]
i can confirm that version 0.14 is buggy on android:

1. `react-native link react-native-maps` not working
2. if i manually set up dependencies (settings.gradle, build.gradle, MainApplication.java) i get this during build:
```
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > Configuration with name 'default' not found.
```
3. after downgrading to version 0.13, works as expected

**Comment by zengyanzi** [comment]
![image](https://cloud.githubusercontent.com/assets/21092607/24954792/ebdb5e20-1fd4-11e7-9396-33440b3b9f0d.png)
here is my error

**Comment by karpoff** [comment]
as a workaround you can manually remove .babelrc file in node_modules/react-native-maps
hope it will be fixed soon

**Comment by PARAGJYOTI** [comment]
@hemedani  @henrikra  @chris-at-translate @zengyanzi   npm install --save-dev babel-plugin-module-resolver

**Comment by prajapati-parth** [comment]
@PARAGJYOTI After downgrading to 0.13.1 `react-native run-android` seems to work fine but now bundle creation throws the following error

> watch /home/parth/Documents/Projects/trash/testmap/node_modules/react-native-maps/android/build/intermediates/res/merged/debug/values-sv ENOSPC
{"code":"ENOSPC","errno":"ENOSPC","syscall":"watch /home/parth/Documents/Projects/trash/testmap/node_modules/react-native-maps/android/build/intermediates/res/merged/debug/values-sv","filename":"/home/parth/Documents/Projects/trash/testmap/node_modules/react-native-maps/android/build/intermediates/res/merged/debug/values-sv"}
Error: watch /home/parth/Documents/Projects/trash/testmap/node_modules/react-native-maps/android/build/intermediates/res/merged/debug/values-sv ENOSPC
    at exports._errnoException (util.js:1029:11)
    at FSWatcher.start (fs.js:1399:19)
    at Object.fs.watch (fs.js:1425:11)
    at NodeWatcher.watchdir (/home/parth/Documents/Projects/trash/testmap/node_modules/jest-haste-map/node_modules/sane/src/node_watcher.js:148:20)
    at Walker.<anonymous> (/home/parth/Documents/Projects/trash/testmap/node_modules/jest-haste-map/node_modules/sane/src/node_watcher.js:361:12)
    at emitTwo (events.js:106:13)
    at Walker.emit (events.js:194:7)
    at /home/parth/Documents/Projects/trash/testmap/node_modules/walker/lib/walker.js:69:16
    at go$readdir$cb (/home/parth/Documents/Projects/trash/testmap/node_modules/graceful-fs/graceful-fs.js:149:14)
    at FSReqWrap.oncomplete (fs.js:114:15)

If you've experienced this before can you please help...
