### ISSUE TITLE
Configuration with name 'default' not found

### ISSUE THREAD

**Issue by MilosR** [airbnb/react-native-maps#1220]
I was getting following error while try to build project for Android, i see that i am not only one who got this

`> Configuration with name 'default' not found.`

There are a lot of issues regarting to this. Why is this error so often? 
It still persists in v0.14.0 ( i am using RN v0.42.3 )

I have tried every solution provided in other issues, but none of them didn't work. I installed everything according to docs. I tried to run `react-native link react-native-maps` but it only links for iOS, not for Android, so i have to link manually for android. I followed docs, and double checked everything, even remove react-native-maps and tried again to link it.

### /app/build.gradle (this is according to docs)

```
dependencies {
    ...
    compile project(':react-native-maps')
    ...
}
```

### /app/settings.gradle **(not according to docs, notice /lib)** 
On other issuses people managed to build by appending /lib at the end of the path, which i dont know how they managed to build...

For example (but it is probably for the older version of react-native-maps):
#504 
#372 
#288 
...

```
include ':react-native-maps'
project(':react-native-maps').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-maps/lib/android')
```
### MainApplication.java (this is according to docs)

import package
`import com.airbnb.android.react.maps.MapsPackage;`

and in getPackages method append  line `new MapsPackage()`
```
@Override
protected List<ReactPackage> getPackages() {
  return Arrays.<ReactPackage>asList(
      ...
      new MapsPackage()     // append this line
  );

}
```

Also you must have installed **Google Play Services**.

**Comment by MilosR** [comment]
Now there is error about **module-resolver** dependecy which is in .bablerc file of react-native-maps project, i think there is no other fix than manually delete that file for now...

**Comment by hemedani** [comment]
I'm using version 0.13.1 and just work fine.

**Comment by MyTotoro** [comment]
there isn't an android folder in node_modules/react-native-maps/, I don't get why that is

**Comment by henrikra** [comment]
I have the same problem `Configuration with name 'default' not found` after I update RN to 0.42.3 and react-native-maps to 0.14 :/

**Comment by mpayetta** [comment]
I'm having the same issue as @MilosR mentioned:

> Now there is error about module-resolver dependecy which is in .bablerc file of react-native-maps project

Any ideas about this?

**Comment by jeffmath** [comment]
@MilosR, thank goodness for your post, which got me unstuck with this issue.
You might want to change your "/app/build.gradle (not according to docs, notice /lib)" heading to "/app/settings.gradle (not according to docs, notice /lib)", to better match with the documentation. 
About your module-resolver issue, I had found that installing babel-plugin-module-resolver using npm got me past something similar.

**Comment by MilosR** [comment]
Changed, my mistake, i didn't noticed that, thanks. Yes that is good solution, better than deleting file in node_modules...

**Comment by phaptq** [comment]
I think that is bug in version 0.14.0
I change this like:
dependencies {
    ....
    compile 'com.airbnb.android:react-native-maps:0.13.1'
}
it's work

**Comment by kesha-antonov** [comment]
This is the reason

https://github.com/airbnb/react-native-maps/pull/1249/files

**Comment by Kalyani518** [comment]
I was getting following error
A problem occurred configuring project ':app'.
> Failed to notify project evaluation listener.
   > A problem occurred configuring project ':react-native-maps'.
      > Failed to notify project evaluation listener.
         > failed to find Build Tools revision 25.0.0
         > failed to find Build Tools revision 25.0.0
   > Could not find property 'processDebugGoogleServices' on project ':app'.

**Comment by yskoverride** [comment]
I had the same problem **Configuration with name 'default' not found**. It was resolved by manually pulling the Babel Plugin 

yarn add babel-plugin-module-resolver

**Comment by henrikra** [comment]
@felipecsl This is fixed so can be closed

**Comment by felipecsl** [comment]
thanks for the triaging @henrikra

**Comment by BuffMcBigHuge** [comment]
A quick fix is to ensure your `settings.gradle` has:

```
include ':react-native-maps'
project(':react-native-maps').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-maps/**lib**/android')
```

**Comment by bethwelt** [comment]
hemedani solution worked well i removed lib from the path and updated the react-native-maps for my project it worked well...

**Comment by vsys-dhanashree** [comment]
.

**Comment by vsys-dhanashree** [comment]
.
