### ISSUE TITLE
Map from other tab on top of each other [Android]

### ISSUE THREAD

**Issue by Deevent** [airbnb/react-native-maps#1225]
I have two maps on different tabs in my app and when I go from a tab to another the previous map is still rendered on top of the new one. I've never had an issue like that. I tried to play with zIndex but no luck.

![ezgif-2-214d5f1d98](https://cloud.githubusercontent.com/assets/16573898/24863950/08d6f652-1e03-11e7-84ce-d7c1b673b2f4.gif)

react-native-maps : 0.13.0
react-native : 0.41.2

**Comment by KarlosQ** [comment]
I have the same issue but only with react-native-maps 0.13.1 and 0.14.0. Some one know's way occurs?

**Comment by Deevent** [comment]
Actually I'm using the last version `compile 'com.google.android.gms:play-services-maps:+'` but I've tried with other ones and also with 9.8.0 and my app crashed at startup. Same story if I exclude play-services from react-native-maps and compile them in my main build.gradle

**Comment by KarlosQ** [comment]
Maybe the app crash because you have a conflict with other component (maybe react-native-google-places, or react-native-device-info) that use play-services and this component have different version. Put 9.8.0 in all component that use play-services. 

If you do like see why crash use bugsnag-react-native
The docs are here https://docs.bugsnag.com/platforms/react-native/

This service show you the crash error and is useful for production too because save the error in a server.

**Comment by thylo** [comment]
I'm experiencing the same issue with the following stack :
- react-native 0.43.3
- react-native-maps 0.14
Every screen with a <MapView /> overlaps the other maps as if the zIndex was not right
@Deevent Did you manage to find a solution ?

**Comment by Deevent** [comment]
@thylo Nope, I didn't find any solution. I ended up using images on my first screen because I had a short deadline.

**Comment by aserrano1971** [comment]
I've used liteMode={true} and now I've a beatiful static map in Android but It has solved the problem for me.

**Comment by ijharulislam** [comment]
I am facing the same problem and didn't find any solution.

**Comment by Deevent** [comment]
@ijharulislam updating to 0.13.1 fixed the issue by my side.

**Comment by cubbuk** [comment]
Having the same issue:
react-native 0.43.4
react-native-maps 0.14.0

Using `liteMode` on previous screen solves it, but I need the both map to be interactive, any solution to that?

**Comment by samthui** [comment]
I have same problem.
Let say I have 2 scenes: A & B, both contain Map. Pushing B from A will display A's map on B's.
I solved it by hiding A's map before pushing B, and re-showing it after popping back to A.
That makes map blink, but at least solves the issue.
