### ISSUE TITLE
TransformError and  installation ERROR

### ISSUE THREAD

**Issue by guoliang1206** [airbnb/react-native-maps#1238]
Xcode Version : 8.21
React-Native Version:0.43 

when I cd my project, I ran that: 
`npm install react-native-maps -- save`
then consloe log that "npm WARN react-native-maps@0.14.0 requires a peer of react@>=15.4.0 but none was installed."
I search on React-Native issues, they said that warning is harmless.
then I ran `react-native link react-native-maps` 

![2017-04-13 2 46 18](https://cloud.githubusercontent.com/assets/12846676/24993303/58c1299c-2058-11e7-96fc-2aec2f948c14.png)

**Comment by guoliang1206** [comment]
I have opened the project.pbxproj file, and search HEADER_SEARCH... delete this line .now I can open my project on Xcode, but how to install the 0.14.0  maps ？

**Comment by guoliang1206** [comment]
does it not supported the React-Native v0.43.3 ?

**Comment by guoliang1206** [comment]
I init a new project, and ran` npm install react-native-maps --save` and `react-native link react-native-maps`, 
it just say link successful on iOS ,and when my run the project ,

 TransformError: /Users/Guodada/LocationDemo/node_modules/react-native-maps/components/MapMarker.js: ENOENT: no such file or directory, open '/Users/Guodada/LocationDemo/node_modules/react-native-maps/.babelrc'

**Comment by guoliang1206** [comment]
ok ,I ind a way fix this problem 
1.manual config the react-native-maps  my version is 0.13.1
2.if you meet the problem: TransformError ...  execute this code on your project 
`./node_modules/react-native/packager/packager.sh start --reset-cache`
now you can use the map

**Comment by motasimfoad** [comment]
@guoliang1206 bro i am new to rn. Can you please tell me hou did u manually config the version. Iw will be really helpful if you can explain in details. Its a bit urgent.

**Comment by guoliang1206** [comment]
@motasimfoad  hi,   1) the version I have choose is 0.13.1    2) accept use the command `react-native link react-native-maps ` first ，if the terminal display that you only link success on iOS platform, try run the `./node_modules/react-native/packager/packager.sh start --reset-cache`. 
3) redo the step 2,  if it still not work ,manually config it . The manually step is follow the Option 3 in installation.md file.

**Comment by agustinaliagac** [comment]
@guoliang1206 thanks man ! your solution worked for me
