### ISSUE TITLE
Hide Google logo

### ISSUE THREAD

**Issue by Mjuk-Biltvatt** [airbnb/react-native-maps#1239]
Hello,

I've finally got the map working after having the blank map and a red border on both iOS and Android. Now my issue is the Google logo. The map is displaying correctly, but since I want my MapView to be really tiny, the Google logo is just too large for me not to be bothered by it.

Here's what I'm talking about:
![image](https://cloud.githubusercontent.com/assets/24603919/24994646/12dda92c-202c-11e7-98a1-f8ee7f084c87.png)

The entire idea is that the MapView will be a button, press it and you will be brought to the Maps app on your OS. Anyone have any idea about how to hide this Google logo entirely?

**Comment by Mjuk-Biltvatt** [comment]
I've found a half-assed solution. Having the map absolutely positioned inside a View wrapper, I simply have the positions set as this now: top: 0, left: 0, right: 0, bottom: -25. This is enough to hide the logo if anyone else might want to do something similar.

**Comment by juanmanuelarze** [comment]
in my case I have a map that occupies the entire screen, then i set height: 125% and bingo

**Comment by emiliano1** [comment]
It is not a good idea to hide it but it is a great idea to remove the link back to google maps.

**Comment by valeriik** [comment]
In my case it is absolutely not usable case - I need to have bottom map padding more than half a screen... so it is very bad to not have an option to disable the logo!!!

**Comment by Jarrettgohh** [comment]
> It is not a good idea to hide it but it is a great idea to remove the link back to google maps.

Are there any possible ways to do this?

**Comment by valeriik** [comment]
I achieved this by using **mapPadding** prop

**Comment by Jarrettgohh** [comment]
> I achieved this by using **mapPadding** prop

Alright thank you!

**Comment by valeriik** [comment]
you need to put the **MapView** into container OR overlap the MapView some other components and provide bottom offset - it depends on your design.
```
mapPadding={{
 top: 0,
 right: 0,
 bottom: {some your value},
 left: 0
}}
```

but please note - after that if you will use any API for centering content (some area, markers...) this will work considering this offset which is sometimes not convenient or appropriate. But there is no other way to hide it.
You also need to know - Google may not approve your app when you release it on market without whit label! Therefore, you must decide whether you really need to remove this label.

**Comment by Jarrettgohh** [comment]
> you need to put the **MapView** into container OR overlap the MapView some other components and provide bottom offset - it depends on your design.
> 
> ```
> mapPadding={{
>  top: 0,
>  right: 0,
>  bottom: {some your value},
>  left: 0
> }}
> ```
> 
> but please note - after that if you will use any API for centering content (some area, markers...) this will work considering this offset which is sometimes not convenient or appropriate. But there is no other way to hide it.
> You also need to know - Google may not approve your app when you release it on market without whit label! Therefore, you must decide whether you really need to remove this label.

Oh alright sure, thank you so much!

**Comment by 99Jannis99** [comment]
Not a nice solution couse that also hide the two buttons in the bottom right. Like Here:
![Scrren1](https://user-images.githubusercontent.com/106659297/176140045-ae536f99-2e94-4253-a596-7c10384a5b4a.jpg)

And when i use the marginLeft like -100 the focus from the Callout isnt correkt annymore. Like you can see here:
![scrren2](https://user-images.githubusercontent.com/106659297/176140301-fb35d38e-9f0c-40f5-b1a6-6e4928b8f7ad.jpg)

Any other good Idea?

**Comment by oosunkeye** [comment]
Just set your height: "110%"

**Comment by MariuzM** [comment]
This what worked well for me 
```
        mapPadding={{ top: 500, right: 0, bottom: 500, left: 0 }}
```

**Comment by falk-stefan** [comment]
Quoting the terms of service here as stated [in the docs](https://developers.google.com/maps/documentation/android-sdk/configure-map):

> Note: As per the [Google Maps Platform Terms of Service](https://cloud.google.com/maps-platform/terms), your application must not remove or obscure the Google logo or copyright notices. Map padding lets you reposition these elements if necessary. If you display a custom UI at the bottom of the map, add padding to the bottom of the map so that the logo and legal notices will always be visible.
