### ISSUE TITLE
Installation guide for Android is out of date

### ISSUE THREAD

**Issue by pflenker** [airbnb/react-native-maps#1253]
I tried to get react-native-maps running on Android, following the installation guide. 
I found multiple issues which prevented me from using it right away:
- I had to remove the .babelrc from node_modules/react-native-maps/ (Found in #1220)
- `react-native link` does not seem to work. I had to follow the instructions step by step.
- When following the instructions, I found that the instructions to change the `android/settings.gradle`  are missing a `/lib/`
- The steps to create API credentials differ from what is described in the guidelines
- I found that I needed to change parts of the `MainApplication.java `, which is not part of the step by step instructions, but only appears in the Troubleshooting section.

**Comment by xilaraux** [comment]
I had the same problems, and now I'm trying to resolve problem with blank screen.

**Comment by pooya1361** [comment]
I also stuck with the blank screen. Please post it here if you found the solution.

**Comment by pflenker** [comment]
@pooya1361 , I was able to get this up and running following all the steps mentioned above. Since you are seeing no error, but a blank map, I suggest you try to follow the step by step instructions from the documentation for Android, even those steps mentioned as optional after using ´react-native link´.

Do you see a blank screen, a blank screen with a red border or a blank screen with a Google logo on the bottom left?

**Comment by AlexandrePalo** [comment]
Check if the lib is well compiled when you run `react-native run-android` with the logs. If you, you probably have an issue with style. Then try the simple example of a full screen map (cf. docs).

**Comment by beerteam** [comment]
Itэs true for me: react-native: 0.43.3
react-native link doesn't work
I followed the author's instructions

**Comment by AlexandrePalo** [comment]
For me react-native link never worked haha 
Whereas rnpm did :(
I always use the diy tutorial ...

**Comment by Nkzn** [comment]
This PR maybe fixes half of this issue #1226

**Comment by calitbk** [comment]
The same problem, 'link' does not work, even when manually set up (error: * What went wrong:
A problem occurred evaluating project ':app'.
> Project with path ':react-native-maps' could not be found in project ':app'.)

**Comment by pflenker** [comment]
@calitbk Try adding this to your `android/settings.gradle`:
```
include ':react-native-maps'
project(':react-native-maps').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-maps/lib/android')
```

(mind the additional /lib here!)

**Comment by Nkzn** [comment]
#1200 seems to solve the `link` issue.

**Comment by Nkzn** [comment]
how about this workaround?

### 1. npm install normally

```bash
$ npm install react-native-maps --save
// or yarn add react-native-maps
```

### 2. edit module setting

once finished installing, we can edit the inside `node_modules`. so i was edit `$YOUR_APP/node_modules/react-native-maps/package.json`. like below.

```diff
   "rnpm": {
      "android": {
 -      "sourceDir": "./android"
 +      "sourceDir": "./lib/android"
      }
    }
```

ref: https://github.com/airbnb/react-native-maps/pull/1200/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R56

### 3. link

```
$ react-native link
```

After run abobe command at my env, `link` succeeded.

**Comment by calitbk** [comment]
Thanks a lot, it worked well now, but i have to remove file .babelrc also, I don't know what this file mean.

**Comment by dmitrika** [comment]
Spent few hours trying to setup maps. Thanks @pflenker and others for helpful information.

**Comment by Nkzn** [comment]
@calitbk 
oh... I worry about to remove `.babelrc`. it has Babel settings.

Babel is a JS to JS transpiler which works to add new syntaxes for our code (like the [Retrolambda](https://github.com/orfjackal/retrolambda) provides Java8 syntaxes for Android Java). The RN default `.babelrc` provides [these](http://facebook.github.io/react-native/docs/javascript-environment.html#javascript-syntax-transformers) syntaxes, it includes JSX.

I wonder why your code works. Since JavaScriptCore (JS Runtime in RN) has a lot of modern EcmaScript 201x(ES6, ES7) syntaxes, we has few trouble without babel, but the JSX syntax probably doesn't work. hmm...

**Comment by Nkzn** [comment]
@calitbk I found reasonable workaround. Maybe you should leave the `.babelrc` and install below plugin.

```
$ npm install --save-dev babel-plugin-module-resolver
```

ref: https://github.com/airbnb/react-native-maps/issues/1258#issuecomment-295609767

**Comment by calitbk** [comment]
Yeah, because this file declared a 'module-resolver', but the module can not be installed automatically. Thank you so much for helping.

**Comment by pooya1361** [comment]
@Nkzn BEST SOLUTION EVER!!!
Thanks a lot!

**Comment by christopherdro** [comment]
Recently merged a few PR's that should have the docs up to date.

**Comment by Nkzn** [comment]
@christopherdro great work!

**Comment by npomfret** [comment]
I'm still getting `Error:Configuration with name 'default' not found.`  My package.json is pointing at master:

`"react-native-maps": "git+https://github.com/airbnb/react-native-maps.git",`

My `settings.gradle` looks like this:

```
include ':react-native-maps'
project(':react-native-maps').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-maps/lib/android')
```

And my `app/build.gradle` is this:

```
    compile(project(':react-native-maps')){
        exclude group: 'com.google.android.gms', module: 'play-services-base'
        exclude group: 'com.google.android.gms', module: 'play-services-maps'
    }
```

What have I missed?

**Comment by Frosty21** [comment]
@npomfret the best solution that worked for me is @Nishchit14 on issue #951 at link
[https://medium.com/@suchydan/how-to-solve-google-play-services-version-collision-in-gradle-dependencies-ef086ae5c75f](url)

The gcm is missing which resolves the issue on the android side for linux and mac OS. the updated install instructions docs only works for mac.

`dependencies {
    // compile project(':react-native-maps')
    compile(project(':react-native-maps')){
        exclude group: 'com.google.android.gms'
    }
      compile ("com.google.android.gms:play-services-base:10.0.1") {
        force = true;
    }
    compile ("com.google.android.gms:play-services-maps:10.0.1") {
        force = true;
    }
    compile ("com.google.android.gms:play-services-gcm:10.0.1") {
        force = true;
    }
    compile project(':react-native-device-info')
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:+"  // From node_modules
    compile project(":react-native-android-keyboard-adjust") // Android keyboard layout with view https://github.com/zubricky/react-native-android-keyboard-adjust
}`
