### ISSUE TITLE
Cannot dynamically change customMapStyle

### ISSUE THREAD

**Issue by AlexandrePalo** [airbnb/react-native-maps#1254]
Hey there,

I cannot dynamically set the props `customMapStyle` with the component MapView. I don't know if it's a bug or the normal behaviour, the doc doesn't mentions this case.

The `customMapStyle` props is only set when the component render the first time, and even if I change this later and send it to my component, the display stay unchanged.

For instance, in my case I want to apply the following mapStyle to my component if and only if the tile is OpenStreetMap (in order to not have labels over the tile) and the standard mapStyle if not :

``` js
blankMapStyle = [
  {
    "stylers": [
      {
        "visibility": "off"
      }
    ]
  }
]
standardMapStyle = []
```

To do this, I have the state `mapType` which change with a picker, values are "standard", "satellite", "hybrid" or "openstreetmap".
My component is rendered like this :

``` js

state = {
  mapType: 'standard' // only way to change is to set 'openstreetmap' here !
}

render() {
   <MapView
     mapType={(this.state.mapType !== 'openstreetmap') ? this.state.mapType : 'standard'}
     customMapStyle={(this.state.mapType === 'openstreetmap') ? blankMapStyle : standardMapStyle}
   >
     {(this.state.mapType === 'openstreetmap') && <MapView.UrlTile urlTemplate='http://c.tile.openstreetmap.org/{z}/{x}/{y}.png' />
   </MapView>
}
```

When I change the state 'mapType' to something (for instance "hybrid") the mapType changed, the tile is also well added when the picker select 'openstreetmap'. However the customMapStyle doesn't change. The only way to change it is to change to default value in the state ...

Do you have an idea ?

Thanks you.
Alexandre P.

**Comment by chris-at-translate** [comment]
Intended behaviour imo, as hot reloading the map style does not seem viable. But could be made to do so.

**Comment by AlexandrePalo** [comment]
I was searching for forking the repo and make the map Style dynamic and I found that map types allowed are :
```js
const MAP_TYPES = {
  STANDARD: 'standard',
  SATELLITE: 'satellite',
  HYBRID: 'hybrid',
  TERRAIN: 'terrain',
  NONE: 'none',
};
```

Then, `none` display nothing as I wanted. I think this option should be mentionned in the docs too !

**Comment by VinceBT** [comment]
I need this option for dynamically switching to night mode in an app but I'm too bad with native to do a PR

**Comment by chris-at-translate** [comment]
To change the map style dynamically, you need a global stat for the style such as redux and store the styling json there, then to make the map have the new styling you will need to unmount the component that the map sits in, then remount easy as.

**Comment by nageshwar521** [comment]
> > then remount easy as.
> 
> It works :)
> And in case someone else wonders how to do it, just change `key` prop on the MapView component and react will remount it

`Key` prop is key to update the MapView.

Thank you, you saved me...
