### ISSUE TITLE
Question: Architecture of react-native-maps

### ISSUE THREAD

**Issue by Catharsis68** [airbnb/react-native-maps#1262]
Hey guys,

I'm interested in how react-native-maps works. I write my thesis in computer science about a comparison of technologies like react native and cordova/ionic.

Is there any information available about how this map library is realized?
Or is it the the standard React way like JavaScript => JavaScriptCore / V8 engine => Native Bridge C++/Java? vice versa.

Any further information would be helpful, thanks

Best regards, Markus

**Comment by fxfactorial** [comment]
@Catharsis68 the code is open source, you can look through it.
