### ISSUE TITLE
Blank Map

### ISSUE THREAD

**Issue by privateOmega** [airbnb/react-native-maps#1265]
I am getting a blank map while rendering using React-native-maps. I am able to view the map on first scene after which I am going to another scene where I am encountering this error. I am using geolocator for finding current location.
**React-native-router-flux 3.38.0**
**React-native-maps 0.13.0**
**React-native 0.42.0**

**Comment by razzaghi** [comment]
I have same problem with version of 0.12 and
React-native-router-flux 3.38.0
React-native-maps 0.13.0
React-native 0.43.0

**Comment by jonstep** [comment]
Hi,
I added a style to the Map component:
```
<MapView
  style={styles.map}...
/>
```
```
map: {
  position: 'absolute',
  left: 0,
  right: 0,
  top: 0,
  bottom: 0
}
```

Which displayed the map for me on:
"react": "15.4.2",
"react-native": "0.42.3",
"react-native-maps": "^0.14.0",

**Comment by AlexandrePalo** [comment]
Can you show us code, especially with `Actions.map()` or something :)

**Comment by croustibat** [comment]
Hello,

same problem here with **React-native-maps 0.13.0** and **React-native 0.42.0**
We're using Ignite 2 and add map with : **ignite add map** which configure the react-native-maps package in the background.

We trying to solve this issue (by updating package, modifying android configs, etc...) we let you know if we find something.

Here is our MapComponent.js file :

`
import React from 'react'
import MapView from 'react-native-maps'
import MapCallout from './MapCallout'
import Styles from './Styles/MapStyles'
import { calculateRegion } from '../Lib/MapHelpers'

export default class MapComponent extends React.Component {

  constructor (props) {
  		super(props)
		const locations = [
			{ title: 'Location A', latitude: 37.78825, longitude: -122.4324 },
			{ title: 'Location B', latitude: 37.75825, longitude: -122.4624 }
		]
		// const region = calculateRegion(locations, { latPadding: 0.05, longPadding: 0.05 })
		const region = { latitude: 123, longitude: 123, latitudeDelta: 0.1, longitudeDelta: 0.1}
		this.state = {
			region,
			locations,
			showUserLocation: true
		}
		this.renderMapMarkers = this.renderMapMarkers.bind(this)
		this.onRegionChange = this.onRegionChange.bind(this)
	}

	componentWillReceiveProps (newProps) {
		this.setState({
		  region: calculateRegion(newProps.locations, { latPadding: 0.1, longPadding: 0.1 })
		})
	}

	onRegionChange (newRegion) {
		// const searchRegion = {
		//   ne_lat: newRegion.latitude + newRegion.latitudeDelta,
		//   ne_long: newRegion.longitude + newRegion.longitudeDelta,
		//   sw_lat: newRegion.latitude - newRegion.latitudeDelta,
		//   sw_long: newRegion.longitude - newRegion.longitudeDelta
		// }
		// Fetch new data...
	}

	calloutPress (location) {
		console.tron.log(location) // Reactotron
	}

	renderMapMarkers (location) {
		return (
			<MapView.Marker key={location.title} coordinate={{latitude: location.latitude, longitude: location.longitude}}>
				<MapCallout location={location} onPress={this.calloutPress} />
			</MapView.Marker>
		)
	}

	render () {
		return (
			<MapView
				style={Styles.map}
				initialRegion={this.state.region}
				onRegionChangeComplete={this.onRegionChange}
				showsUserLocation={this.state.showUserLocation}
			>
				{this.state.locations.map((location) => this.renderMapMarkers(location))}
			</MapView>
		)
	}
}
`

**Comment by croustibat** [comment]
Ok, we finally managed to make it work !
Here's few changes we made :

- update RN-maps from 0.13.0 to 0.14.0 
- in settings.gradle update android path to : `react-native-maps/**lib**/android` 
- in your component style make sure you have this : 
`container: {
    ...StyleSheet.absoluteFillObject,
    height: 400,
    width: 400,
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  map: {
    ...StyleSheet.absoluteFillObject,
  },`
- and the most important : make sure your **GOOGLE API KEY**  is **NOT** restricted to android application. You have to set **NO RESTRICTION** ! 

Hope this will help.

**Comment by privateOmega** [comment]
@AlexandrePalo Sorry for late reply. I was away. I resolved it by passing `type:'reset'` in flux action. Thanks.

**Comment by alainib** [comment]
i have a blank maps too 

my styles :  

`  mapContainer: {
    ...StyleSheet.absoluteFillObject,
    height: 400,
    width: 400,
    justifyContent: "flex-end",
    alignItems: "center"
  },
  map: {
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    position: "absolute",
    ...StyleSheet.absoluteFillObject
  }`

my package.json :

`	{...   
	  "dependencies": {
		"react": "16.0.0-alpha.12",
		"react-native": "0.45.1",
		"react-native-camera": "git+https://github.com/lwansbrough/react-native-camera.git",
		"react-native-camera-roll-picker": "^1.1.9",
		"react-navigation": "git+https://github.com/react-community/react-navigation.git",
		"react-native-maps":"0.15.3"
	  },
	  "devDependencies": {
		"babel-jest": "20.0.3",
		"babel-preset-react-native": "2.0.0",
		"jest": "20.0.4",
		"react-test-renderer": "16.0.0-alpha.12"
	  }   
	}
`


and my js :  

    import MapView, { MAP_TYPES } from 'react-native-maps';
	export default class Test extends Component {
	  constructor() {
		super();

		this.state = {
		  region: {
			latitude: 37.78825,
			longitude: -122.4324,
			latitudeDelta: 0.0922,
			longitudeDelta: 0.0421
		  }
		};
	  }

	  onRegionChange(region) {
		this.setState({ region });
	  }

	  render() {
		return (
		   <View style={styles.mapContainer}>
			<MapView
			  style={styles.map}
			  region={this.state.region}
			  onRegionChange={this.onRegionChange}
			/>
			<Text style={styles.title}>{this.state.region.latitude}  / {this.state.region.longitude}  </Text>

		  </View>
		);
	  }
	}

any idea please ?

**Comment by AdmirHuric** [comment]
In case that you went through all of the above steps and still get the blank android map with google logo, and are running the app on emulator, do not run emulator on the latest `preview` API (API 27 as of now).

This was an issue for me, I changed the API to  `API 26`, and everything works as expected.
Full emulator config that works for me:
 - Type: Phone
 - Name: Nexus 5x API 26
 - Resolution: 1080x1920: 420dpi
 - API: 26
 - Target: Android 8.0 (Google Play)
 - Cpu/ABI: x86
 - Size on Disk: 2GB

**Comment by snehaChaudhari** [comment]
I have same problem.Map is blank event not showing google logo.
I'm using react-native-map.
