### ISSUE TITLE
iOS build failed RCTConver+Mapkit.o RCTConvert+Mapkit.m

### ISSUE THREAD

**Issue by kinber95** [airbnb/react-native-maps#1266]
I am getting this build fail after installing react-native-maps : 
`	CompileC /Users/bjorn/atom/ishareit/ios/build/Build/Intermediates/AirMaps.build/Debug-iphonesimulator/AirMaps.build/Objects-normal/x86_64/RCTConvert+MapKit.o AirMaps/RCTConvert+MapKit.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)`

**react-native: 0.43.4
react-native-maps: 0.14.0**

**Comment by phaptq** [comment]
I has success build in ios with tips:

init project with version 0.42.3 (to fix 'npm WARN react-native-maps@0.14.0 requires a peer of react@>=15.4.0 but none was installed').

skip step react-native link react-native-maps to use Option 3: Manually in the docs.

in Xcode open libraries -> right click AirMaps.xcodeproj -> add file to AirMaps -> go to find react-native-maps into node_module -> lib -> ios -> AirMaps -> select RCTConvert+MapKit.h/m -> add (to fix 'File RCTConvert+MapKit.m not found').

npm install --save-dev babel-plugin-module-resolver (to fix .babelrc cause error).

watchman watch-del-all. And rebuild project.

**Comment by kinber95** [comment]
I follow your steeps and the build succeded, but yet I get a box with a red border when I impl. the MapView.
