### ISSUE TITLE
React 16 support?

### ISSUE THREAD

**Issue by kesha-antonov** [airbnb/react-native-maps#1267]
Hello!

RN 0.43 require to use react-16.

It'll be great to update this lib to use React 16.
Can we do that?

**Comment by julienR2** [comment]
Any news about this ? Someone managed to get it work with react 16 ?

**Comment by henrikra** [comment]
At least when using latest version from master this library works perfectly with React 16 :D

**Comment by julienR2** [comment]
Sweet ! thanks for the feedback ! I'll get to work and try it on my current config :)

**Comment by christopherdro** [comment]
Latest version is compatible with latest stable version of RN which uses React 16.
