### ISSUE TITLE
How to render markers on map fetched from API ?

### ISSUE THREAD

**Issue by zakkymfajar** [airbnb/react-native-maps#1268]
Can anyone help me solve this problem? I want to make a lot of map markers by getting data from API, I've tried but I always fail.
This is my code : 
`import React, { Component } from 'react';
import { View, StyleSheet, Text } from 'react-native';
import MapView from 'react-native-maps';

export default class MyLocation extends Component {

  constructor(props) {
    super(props);
    this.state = {
      region: {
        latitude: -6.914744,
        longitude: 107.609810,
        latitudeDelta: 0.015,
        longitudeDelta: 0.0121,
      },
      markers: [
        {
          latlng: { latitude: marker.lat, longitude: marker.lng}
        }
      ]
    }
    this.onRegionChange = this.onRegionChange.bind(this);
  }
  

  componentDidMount() {
    this.mapMarkers();
    navigator.geolocation.getCurrentPosition (
      (position) => {
        console.log("getCurrentPosition Succes");
        this.setState({
          region: {
            ...this.state.region,
            latitude: position.coords.latitude,
            longitude: position.coords.longitude,
          }
        });
        this.watchPosition();
      },
      (error) => {
        this.props.displayError("Error detecting your Location");
        alert(JSON.stringify(error))
      },
      {enableHightAccuracy: true, timeout: 20000, maximumAge: 1000}
    );
  }

  watchPosition() {
    this.watchID = navigator.geolocation.watchPosition(
      (position) => {
        console.log("Watch Position Succes");
        if(this.props.followUser) {
          this.map.animateToRegion(this.newRegion(position.coords.latitude, position.coords.longitude));
        }
      },
      (error) => {
        this.props.displayError("Error detecting your location");
      },
      {enableHightAccuracy: true, timeout: 20000, maximumAge: 1000}
    );
  }

  componentWillUnmount() {
    navigator.geolocation.clearWatch(this.watchID);
  }

  onRegionChange(region) {
    this.setState({ region });
  }

  mapMarkers() {
    return fetch('http://128.199.82.65/api/data/')
      .then((response) => response.json())
      .then((responseJson) => {
        this.setState({
          marker: responseJson.data
        });
        console.log(responseJson);
        return responseJson.data;
      })
      .catch((error) => {
        console.error(error);
      });
  }

  render() {
    return (
     <MapView
       style={styles.map}
       showsMyLocationButton={true}
       showsUserLocation={true}
       region={this.state.region}
       onRegionChange={this.onRegionChange} >
       {this.state.markers.map((marker,i) => (
         <MapView.Marker
           key={i}
           coordinate={marker.latlng}
           title={marker.name}
           description={marker.address}
           />
          ))}
      </MapView>
    )
  }
}

const styles = StyleSheet.create({
  map: {
      ...StyleSheet.absoluteFillObject,
    }
})
`
my data : 

Object {status: "success", data: Array(5)}
data
:
Array(5)
0
:
Object
address
:
"Jl. KH. Ahmad Dahlan No 53, Turangga, Lengkong, Turangga, Kota Bandung, Jawa Barat 40264"
created_at
:
"2017-04-04 03:21:04"
file
:
"uploads/3sDKHK_RS-Muhammadiah-bandung-300x174.jpg"
id
:
7
lat
:
"-6.9336379"
lng
:
"107.5531344"
name
:
"Rumah Sakit Muhammadiyah Bandung"
phone
:
"(022)7301062"
updated_at
:
"2017-04-04 03:21:04"
__proto__
:
Object
1
:
Object
2
:
Object
3
:
Object
4
:
Object
length
:
5
__proto__
:
Array(0)
status
:
"success"
__proto__
:
Object

**Comment by babenzele** [comment]
Formatting, please.

https://guides.github.com/features/mastering-markdown/
