### ISSUE TITLE
GoogleMaps not found IOS

### ISSUE THREAD

**Issue by sasuke10** [airbnb/react-native-maps#1278]
I run pop install following the instructions there are here Option 1: CocoaPods [https://github.com/airbnb/react-native-maps/blob/master/docs/installation.md](url)
but I have an error in Xcode `GoogleMaps.h file not found`
![captura de pantalla 2017-04-27 a la s 15 58 50](https://cloud.githubusercontent.com/assets/26877548/25504431/97a27434-2b63-11e7-9a1f-1937d2a2ff1a.png)
The map result in IOS is like this. The map works good in Android. 
![captura de pantalla 2017-04-27 a la s 16 00 04](https://cloud.githubusercontent.com/assets/26877548/25504512/c7a2457e-2b63-11e7-8511-750d14b86af0.png)
and my Podfile result is this
![captura de pantalla 2017-04-27 a la s 15 51 23](https://cloud.githubusercontent.com/assets/26877548/25504559/ecb0271e-2b63-11e7-8f0d-228ea213fd30.png)

**Comment by sasuke10** [comment]
The problem was fixed adding correct api key for IOS application.
[](https://developers.google.com/maps/documentation/ios-sdk/start?hl=es-419)
but I don't know why Xcode still shows the error `@import GoogleMaps; module googleMaps not found` I will continue to testing.

**Comment by aserrano1971** [comment]
Try using this guide.
It helped to me to fix my problems installing AirMaps

https://gist.github.com/heron2014/e60fa003e9b117ce80d56bb1d5bfe9e0

**Comment by anhtuank7c** [comment]
Try to follow this repo too: https://github.com/anhtuank7c/maps-example
It's work on latest ReactNative 0.44.2 and RNM 0.15.2

**Comment by jdonald** [comment]
This problem returned in 2018 and there's an explanation + proposed fix here in #2159

**Comment by RohitRajpal** [comment]
Upgrading to latest react-native-maps(0.23.0) resolved my problem

npm i react-native-maps@0.23.0
react-native link
