### ISSUE TITLE
AirGoogleMapManager was called with 8 arguments but expects 5 arguments

### ISSUE THREAD

**Issue by gerardus1995** [airbnb/react-native-maps#1281]
I get this error when trying to get snapshot of google maps (only in IOS). I get this working perfect on android. 

                  const snapshot = this.refs['mapview'].takeSnapshot({
                    format: 'jpg',   // image formats: 'png', 'jpg' (default: 'png')
                    quality: 0.8,    // image quality: 0..1 (only relevant for jpg, default: 1)
                    result: 'base64'   // result types: 'file', 'base64' (default: 'file')
                  });
                  snapshot.then((uri) => {
                     console.log(uri);
                  });

**Comment by felangga** [comment]
Same error :(
On iOS, not tested  yet on Android

**Comment by namdq1969** [comment]
+1

**Comment by Snowsoul** [comment]
+1 Anyone has been able to find a solution to this? (iOS only)

**Comment by fabiancarlos** [comment]
+1

**Comment by GunnarHolwerda** [comment]
+1

**Comment by brunsy** [comment]
Looks like the same issue that was raised here #1173,
As a temporary workaround, I added the missing parameters into AIRGoogleMapManager's takeSnapshot.

**Comment by GunnarHolwerda** [comment]
@brunsy is that PR worthy? Or could you share your temporary fix? I am interested.
