### ISSUE TITLE
Can't import MapView. 

### ISSUE THREAD

**Issue by zuber303** [airbnb/react-native-maps#1285]
Hi. First I had this problem: [http://stackoverflow.com/questions/38095524/cannot-evaluate-module-react-native-maps-configuration-with-name-default-n](url)
and tried fix it by follow steps in that topic. 
Finally I fixed that problem, build was successful but new problem appeared.
I try import MapView but system doesn't recognize this component. 
![screenshot_1493567933](https://cloud.githubusercontent.com/assets/16595138/25565801/61d4d53a-2dc6-11e7-9c30-563c857e1e78.png)

Can you tell me what is wrong?
Thank you

My code:

Geo.js
`
import React, { Component } from 'react';
import {
    AppRegistry,
    StyleSheet,
    Text,
    Button,
    View
} from 'react-native';
import MapView from 'react-native-maps'
export default class Geo extends Component {
    constructor() {
        super();
        this.state = {
            position:'none'
        }
    }
   

    render() {
        return (
            <View>
                <MapView/>
                <Text>{this.state.position}</Text>
            </View>
        )
    }

}
AppRegistry.registerComponent('Geo', () => Geo);`

Build.gradle
`def enableProguardInReleaseBuilds = false

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.1"

    defaultConfig {
        applicationId "com.kurs"
        minSdkVersion 16
        targetSdkVersion 22
        versionCode 1
        versionName "1.0"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86"
        }
    }
    buildTypes {
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
            def versionCodes = ["armeabi-v7a":1, "x86":2]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }
}

dependencies {
    compile project(':react-native-vector-icons')
    compile project(':react-native-push-notification')
    compile 'com.airbnb.android:react-native-maps:0.6.0'
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:+"  // From node_modules
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}
`
settings.gradle
`rootProject.name = 'kurs'
include ':react-native-vector-icons'
project(':react-native-vector-icons').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-vector-icons/android')

include ':react-native-push-notification'
project(':react-native-push-notification').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-push-notification/android')

include ':react-native-maps'
project(':react-native-maps').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-maps/android')

include ':app'
`

MainActivity.java
`package com.kurs;

import com.facebook.react.ReactActivity;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;
import java.util.Arrays;
import java.util.List;
import com.airbnb.android.react.maps.MapsPackage; //<- this line is important
public class MainActivity extends ReactActivity {

    /**
     * Returns the name of the main component registered from JavaScript.
     * This is used to schedule rendering of the component.
     */
    @Override
    protected String getMainComponentName() {
        return "kurs";
    }

      protected boolean getUseDeveloperSupport() {
        return BuildConfig.DEBUG;
      }

      protected List<ReactPackage> getPackages() {
        return Arrays.<ReactPackage>asList(
        new MainReactPackage(),
        new MapsPackage(this) //here you must be write the param this
        );
      }
}
`
MainAPlication.java

`package com.kurs;

import android.app.Application;

import com.facebook.react.ReactApplication;
import com.oblador.vectoricons.VectorIconsPackage;
import com.dieam.reactnativepushnotification.ReactNativePushNotificationPackage;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;
import com.facebook.soloader.SoLoader;

import java.util.Arrays;
import java.util.List;

public class MainApplication extends Application implements ReactApplication {

  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
    @Override
    public boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }

    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
            new VectorIconsPackage(),
            new ReactNativePushNotificationPackage()
      );
    }
  };

  @Override
  public ReactNativeHost getReactNativeHost() {
    return mReactNativeHost;
  }

  @Override
  public void onCreate() {
    super.onCreate();
    SoLoader.init(this, /* native exopackage */ false);
  }
}
`

**Comment by benyliantriana** [comment]
have you open your project in android studio so the gradle load the module?

**Comment by zuber303** [comment]
I don't use android studio so don't know what you ask.

**Comment by benyliantriana** [comment]
in some cases (like mine) some library wont load to android when use 'react-native run-android'. And the lib  will be loaded by gradle when you open your project in android studio. Your case is the library / module not loaded in your project. So the solution is, delete the library and re-install it using npm or try open your project in android studio.

**Comment by zuber303** [comment]
Finally was working when I install maps on fresh clean RN project. But in my proper project maps still not working. 
I have got enough. I should write a code not fighting with issues. Why react native not support own maps any more?
  
And is there anyone who has no problems with this extension?

**Comment by benyliantriana** [comment]
try re-install the lib

> remove the library
> npm install
@zuber303

**Comment by henrikra** [comment]
@felipecsl I think this should be closed since now `.babelrc` is added to `.npmignore`
