### ISSUE TITLE
can't compile after installation, react-native link doesn't seam to work for android

### ISSUE THREAD

**Issue by alexandredumat** [airbnb/react-native-maps#1294]
I can't install react native react-native-maps, i get this error when i try to build with react-native run-android :

    A problem occurred configuring project ':app'. Could not resolve all dependencies for configuration ':app:_debugApk'. Configuration with name 'default' not found.

I followed the instructions here :

https://github.com/airbnb/react-native-maps/blob/master/docs/installation.md

when i run :

    react-native link

I get :

    rnpm-install info iOS module react-native-maps is already linked
    rnpm-install info Android module react-native-geocoder is already linked
    rnpm-install info iOS module react-native-geocoder is already linked

It seams that it worked on iOS but not on android although for geocoder it worked (and the service is working fine).

So i follwed manual instructions and edited (but i still get the error above):
> android/app/build.gradle
> android/settings.gradle
> MainApplication.java
> android\app\src\main\AndroidManifest.xml (was already edited for geocoder.)

I did play a bit with the version numbers in build.gradle :

    // instructed in the installation guide -> build fail see above
    compile project(':react-native-maps')
    // Version 0.12.1 and earlier -> Build success but ERROR 500 in the app
    compile 'com.airbnb.android:react-native-maps:0.12.1'
    // Version 0.12.2 and later -> error see below

    A problem occurred configuring project ':app'. Could not resolve all dependencies for configuration ':app:_debugApkCopy'. Could not find com.airbnb.android:react-native-maps:0.12.2.

I've tryed different things but nothing worked. I tryed stuff from this link (but it seams deprecated) :

cannot evaluate module 'react-native-maps' : Configuration with name 'default' not found

Link to question on StackOverflow : http://stackoverflow.com/questions/43742424/react-native-install-react-native-maps

**Comment by prajapati-parth** [comment]
Looking at #1253 seems like, you'll need to follow the steps there until the installation documentation is updated. 

Note: those steps are specific to android and react-native-maps-0.13.1. Also from #1219, the latest version doesn't seem to be stable.

**Comment by alexandredumat** [comment]
Thank you @prajapati-parth i got it working thanks to you !

For those who have the same problem, the solution for me was that the instructions to change the android/settings.gradle are missing a /lib/

This gives :

    include ':react-native-maps'
    project(':react-native-maps').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-maps/lib/android')

If it's still not working you might try to remove the .babelrc from node_modules/react-native-maps/

I could close the issue since there is a work around but i feel like the documentation should be updated first.

**Comment by prajapati-parth** [comment]
@alexandredumat Great to hear that it's working again. Since there are PRs #1293 and #1246 already in the open state regarding the same problem, it'd be fine to close this issue.
Thanks.
