### ISSUE TITLE
Map and Device Info

### ISSUE THREAD

**Issue by Ethan0007** [airbnb/react-native-maps#1300]
If you are having issues with both libraries and encountered app crashes i suggest my fixed below:

#:  I change version in react-native-device-info to compile 'com.google.android.gms:play-services-gcm:9.8.0'  node_modules -> react-native-device-info -> android -> build.gradle ->

dependencies {
    compile 'com.facebook.react:react-native:+'
    compile 'com.google.android.gms:play-services-gcm:9.8.0'
}

hope will help..

**Comment by felipecsl** [comment]
Thanks!
