### ISSUE TITLE
AnimatedViews example: bad positionning of rightmost tile item after swiping

### ISSUE THREAD

**Issue by badasve** [airbnb/react-native-maps#131]
Hello,

as said in the title, when you swipe all the items from right to left in order to get to the last item to the right, you can still swipe a little more and the last item settles at the wrong place, meaning not in the middle of the screen but left of it (you can actually see only a part of it) as if there was room for yet another "ghost" item to the right of it. 

So far I have tried messing with the different params available at the top of the component and the styles but to no avail...

Any simple way to fix this ?

**Comment by badasve** [comment]
Ok, I managed to do it with a hacky trick : I set the xBounds prop of the PanController component to xBounds={[-screen.width * (markers.length-1.6), 0]} instead of xBounds={[-screen.width * (markers.length-1), 0]} . I'm not very happy with this though as I'm not sur it will work on any viewport, so if someone has something more elegant I'd be happy to try it !

**Comment by badasve** [comment]
Ok, not working if I change the size of items (or screen I guess), I'm trying to work out a formulae from those constants, ITEM_SPACING, ITEM_PREVIEW, ITEM_WIDTH and screen.width

I'm close but it's not perfect

**Comment by badasve** [comment]
I think I have it !

`let offsetSize = ITEM_SPACING / 2 + ITEM_PREVIEW;` (this is the space before the first item and after the last one)
`let xStartBound = -(offsetSize * 2 + ITEM_WIDTH * markers.length + ITEM_SPACING * markers.length - screen.width);`

then set the xBounds prop of PanController with this :
`xBounds={[xStartBound, 0]}`

**Comment by javiercr** [comment]
@badasve thanks! that worked for me too :)

**Comment by badasve** [comment]
No pb, I will close the issue since it seems resolved

**Comment by douglaswissett** [comment]
setting the xBounds prop on the PanController in AnimatedView.js worked for me.

`xBounds={[ -((ITEM_SPACING / 2) + ITEM_PREVIEW * 2 + ITEM_WIDTH * markers.length + ITEM_SPACING * markers.length - screen.width), 0]}`

Thanks @badasve!
