### ISSUE TITLE
Getting build failed after running react-native link react-native-maps

### ISSUE THREAD

**Issue by Marswang92** [airbnb/react-native-maps#1348]
Package installed through yarn, version `0.15.1`. React native version `0.44.0`. After linking, keep fail building. Giving following error:
```
clang: error: no such file or directory: '/Users/Mars/.../node_modules/react-native-maps/lib/ios/AirMaps/AIRGMSPolyline.m'
clang: error: no input files
```
Any clue?

**Comment by Marswang92** [comment]
@guilhermepontes might be related to this PR?
https://github.com/airbnb/react-native-maps/pull/1194

**Comment by ujwal-setlur** [comment]
I have this issue as well. I did not even know 0.15.1 was out. I just did a ```npm install``` and I got 0.15.1, and my compile failed.

I have now pinned the version to 0.15.0

**Comment by mehdijjz** [comment]
any updates on this ?!

**Comment by Marswang92** [comment]
@mehdijjz already solved in this pr https://github.com/airbnb/react-native-maps/pull/1351
