### ISSUE TITLE
MapView.Marker icon angle is always set relative to the canvas and not map (fails when map is rotated)

### ISSUE THREAD

**Issue by amitv87** [airbnb/react-native-maps#1349]
Setting **rotation** prop of **MapView.Marker** does rotate the marker icon but always relative to the canvas of the map.
So when the map is rotated using gestures the the marker icon orientation is not consistent with what was set

**Comment by amitv87** [comment]
Setting **flat** prop avoids this.

**Comment by emilefleming** [comment]
Have you tried this on Google Maps on iOS by chance? flat={ true } is not working for me there.
