### ISSUE TITLE
HOW CAN WE SHOW ROUTE MAP FROM DESTINATION TO SOURCE

### ISSUE THREAD

**Issue by lavarajallu** [airbnb/react-native-maps#1354]
https://stackoverflow.com/questions/44094183/how-can-i-show-route-map-from-currentlocation-to-some-destinationsome-addressl

**Comment by henrikra** [comment]
![image](https://cloud.githubusercontent.com/assets/12229968/26305707/1ac6cbb4-3ef9-11e7-8f52-523040666c2a.png)

**Comment by JackThomson2** [comment]
+1 would like to know how to achieve this

**Comment by vinagrito** [comment]
This has nothing to do with the functionality of this component.
1. Open a project on Google, 
2. Get an API key 
3. Make request to the directions API 
4. Parse the response

Parsing the response will result in an array of coordinates that you can put in `Polyline` component.

@christopherdro I think you can close this one
