### ISSUE TITLE
Error invoking com.google.maps.api.android.lib6.impl.aq.e()

### ISSUE THREAD

**Issue by tineo** [airbnb/react-native-maps#1358]
I updated Play Services and Mapview throws this.

With another version of PS, MapView works.

![capture _2017-05-22-16-21-42](https://cloud.githubusercontent.com/assets/1090336/26329489/1ff8df64-3f0d-11e7-99bb-e9c3420b9b5b.png)

**Comment by ekologic** [comment]
I am also getting this exception on Lenovo Yoga tablet, however on android phones it works fine
`java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources com.google.maps.api.android.lib6.impl.aq.e()' on a null object reference
05-24 16:16:29.470  6212  6212 E unknown:React:         at com.google.maps.api.android.lib6.gmm6.vector.ah.getResources(:com.google.android.gms.DynamiteModulesB:340)
05-24 16:16:29.470  6212  6212 E unknown:React:         at android.util.ResolutionOverride.<init>(ResolutionOverride.java:56)
05-24 16:16:29.470  6212  6212 E unknown:React:         at android.view.SurfaceView.init(SurfaceView.java:207)
05-24 16:16:29.470  6212  6212 E unknown:React:         at android.view.SurfaceView.<init>(SurfaceView.java:187)
05-24 16:16:29.470  6212  6212 E unknown:React:         at com.google.maps.api.android.lib6.gmm6.vector.am.<init>(:com.google.android.gms.DynamiteModulesB:1)
05-24 16:16:29.470  6212  6212 E unknown:React:         at com.google.maps.api.android.lib6.gmm6.vector.ah.<init>(:com.google.android.gms.DynamiteModulesB:3)
05-24 16:16:29.470  6212  6212 E unknown:React:         at com.google.maps.api.android.lib6.gmm6.api.am.<init>(:com.google.android.gms.DynamiteModulesB:53)
05-24 16:16:29.470  6212  6212 E unknown:React:         at com.google.maps.api.android.lib6.gmm6.api.am.a(:com.google.android.gms.DynamiteModulesB:49)
05-24 16:16:29.470  6212  6212 E unknown:React:         at com.google.android.gms.maps.internal.bv.a(:com.google.android.gms.DynamiteModulesB:38)
05-24 16:16:29.470  6212  6212 E unknown:React:         at com.google.maps.api.android.lib6.impl.az.a(:com.google.android.gms.DynamiteModulesB:80)
05-24 16:16:29.470  6212  6212 E unknown:React:         at com.google.maps.api.android.lib6.impl.az.a(:com.google.android.gms.DynamiteModulesB:1)
05-24 16:16:29.470  6212  6212 E unknown:React:         at com.google.maps.api.android.lib6.impl.cw.a(:com.google.android.gms.DynamiteModulesB:18)
05-24 16:16:29.470  6212  6212 E unknown:React:         at com.google.android.gms.maps.internal.t.onTransact(:com.google.android.gms.DynamiteModulesB:17)
05-24 16:16:29.470  6212  6212 E unknown:React:         at android.os.Binder.transact(Binder.java:387)
05-24 16:16:29.470  6212  6212 E unknown:React:         at com.google.android.gms.maps.internal.IMapViewDelegate$zza$zza.onCreate(Unknown Source)
05-24 16:16:29.470  6212  6212 E unknown:React:         at com.google.android.gms.maps.MapView$zza.onCreate(Unknown Source)
05-24 16:16:29.470  6212  6212 E unknown:React:         at com.google.android.gms.dynamic.zza$3.zzb(Unknown Source)
05-24 16:16:29.470  6212  6212 E unknown:React:         at com.google.android.gms.dynamic.zza$1.zza(Unknown Source)
05-24 16:16:29.470  6212  6212 E unknown:React:         at com.google.android.gms.maps.MapView$zzb.zzIL(Unknown Source)
05-24 16:16:29.470  6212  6212 E unknown:React:         at com.google.android.gms.maps.MapView$zzb.zza(Unknown Source)
05-24 16:16:29.470  6212  6212 E unknown:React:         at com.google.android.gms.dynamic.zza.zza(Unknown Source)
05-24 16:16:29.470  6212  6212 E unknown:React:         at com.google.android.gms.dynamic.zza.onCreate(Unknown Source)
05-24 16:16:29.470  6212  6212 E unknown:React:         at com.google.android.gms.maps.MapView.onCreate(Unknown Source)

05-24 16:16:29.470  6212  6212 E unknown:React:         at com.airbnb.android.react.maps.AirMapView.<init>(AirMapView.java:93)
05-24 16:16:29.470  6212  6212 E unknown:React:         at com.airbnb.android.react.maps.AirMapManager.createViewInstance(AirMapManager.java:62)
05-24 16:16:29.470  6212  6212 E unknown:React:         at com.airbnb.android.react.maps.AirMapManager.createViewInstance(AirMapManager.java:29)

05-24 16:16:29.470  6212  6212 E unknown:React:         at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:46)
05-24 16:16:29.470  6212  6212 E unknown:React:         at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:218)
05-24 16:16:29.470  6212  6212 E unknown:React:         at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:148)
05-24 16:16:29.470  6212  6212 E unknown:React:         at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:890)
05-24 16:16:29.470  6212  6212 E unknown:React:         at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:863)
....`

**Comment by tineo** [comment]
Yes, only some devices throws this error :( after update de google play services

**Comment by tineo** [comment]
I have to upgrade the API version to 25
```

android {
    compileSdkVersion 25
    buildToolsVersion "25.0.2"

    defaultConfig {
        applicationId "com.application"
        minSdkVersion 16
        targetSdkVersion 23
        versionCode 1
        versionName "1.0.8"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    } ...
```

And it solved the error :)

**Comment by felipheggaliza** [comment]
I had this problem, and after many days I found a solution by adding android:hardwareAccelerated="true" to my MapsActivity on AndroidManifest.xml

Example:


```
<activity
            android:name=".MapsActivity"
            android:configChanges="orientation"
            android:hardwareAccelerated="true"
            android:screenOrientation="portrait" />
```

**Comment by henrikra** [comment]
@felipheggaliza Why is this working?

**Comment by ericacooksey** [comment]
A couple of my users are also getting this error (I can see it in the crashlytics logs). It doesn't happen to all of my users but it makes the app pretty much unusable for those affected. Is there a workaround that I can suggest?

**Comment by tineo** [comment]
Well you need change config not the code. How this would be reported?

**Comment by henrikra** [comment]
@felipheggaliza We tried this and the app still crashed instantly :/

**Comment by IgorVanian** [comment]
This is pretty much critical, is there any workaround possible? :(

**Comment by IgorVanian** [comment]
```
E/AndroidRuntime(14327): java.lang.NullPointerException
E/AndroidRuntime(14327): 	at android.os.Parcel.readException(Parcel.java:1478)
E/AndroidRuntime(14327): 	at android.os.Parcel.readException(Parcel.java:1426)
E/AndroidRuntime(14327): 	at xw.a(:com.google.android.gms.DynamiteModulesB:1259)
E/AndroidRuntime(14327): 	at xi.a(:com.google.android.gms.DynamiteModulesB:3105)
E/AndroidRuntime(14327): 	at ns.b(:com.google.android.gms.DynamiteModulesB:142)
E/AndroidRuntime(14327): 	at oq.a(:com.google.android.gms.DynamiteModulesB:1163)
E/AndroidRuntime(14327): 	at pk.a(:com.google.android.gms.DynamiteModulesB:258)
E/AndroidRuntime(14327): 	at pf.a(:com.google.android.gms.DynamiteModulesB:331)
E/AndroidRuntime(14327): 	at xh.a(:com.google.android.gms.DynamiteModulesB:85)
E/AndroidRuntime(14327): 	at com.google.maps.api.android.lib6.impl.cn.a(:com.google.android.gms.DynamiteModulesB:120)
E/AndroidRuntime(14327): 	at pf.a(:com.google.android.gms.DynamiteModulesB:9199)
E/AndroidRuntime(14327): 	at ot.g(:com.google.android.gms.DynamiteModulesB:491)
E/AndroidRuntime(14327): 	at ot.a(:com.google.android.gms.DynamiteModulesB:426)
E/AndroidRuntime(14327): 	at pk.a(:com.google.android.gms.DynamiteModulesB:440)
E/AndroidRuntime(14327): 	at od.a(:com.google.android.gms.DynamiteModulesB:34)
E/AndroidRuntime(14327): 	at se.a(:com.google.android.gms.DynamiteModulesB:231)
E/AndroidRuntime(14327): 	at rt.a(:com.google.android.gms.DynamiteModulesB:788)
E/AndroidRuntime(14327): 	at rk.a(:com.google.android.gms.DynamiteModulesB:1837)
E/AndroidRuntime(14327): 	at rn.handleMessage(:com.google.android.gms.DynamiteModulesB:4345)
E/AndroidRuntime(14327): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(14327): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime(14327): 	at android.app.ActivityThread.main(ActivityThread.java:5590)
E/AndroidRuntime(14327): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(14327): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(14327): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
E/AndroidRuntime(14327): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
E/AndroidRuntime(14327): 	at dalvik.system.NativeStart.main(Native Method)
```

**Comment by PogoMips** [comment]
Experiencing the same issue on a LG G5 running Android 6.0.1. The workarounds above did not solve the issue.

**Comment by ftheriault** [comment]
Same problem here, using LG G4, running Android 6.0.

**Comment by henrikra** [comment]
I think this should be priority number one since this package is useless if it won't work at all on some devices :/

**Comment by boxsmiley** [comment]
Another with same on LG G4 Android 6.0

**Comment by MaxToyberman** [comment]
I have found a solution that works for me. please follow the next steps : 

1) update react native maps version to 0.15.2

2) in your settings.gradle change : 

```
include ':react-native-maps'
project(':react-native-maps').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-maps/android')
```
to :
```
include ':react-native-maps'
project(':react-native-maps').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-maps/lib/android')
```

3) add this to build.gradle to use play-services 11.0.0 version 

```
configurations.all {
    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        if (details.getRequested().getGroup() == 'com.google.android.gms') {
            // If different projects require different versions of
            // Google Play Services it causes a crash on run.
            // Fix by overriding version for all projects.
            details.useVersion('11.0.0')
        }
    }
}
```
I hope this helps :)

**Comment by henrikra** [comment]
I am 100% sure that 1, 2 and 3 steps do not help. 1 and 2 are related to installing. 3rd step we have already done. And in fact that should be done in `app/build.gradle`. What the 4 step does?

**Comment by MaxToyberman** [comment]
@henrikra  I just wanted to help , it works for me ... , you don't have to take my advise if you don't believe me.

**Comment by chaitanya0bhagvan** [comment]
This is happening because of a bug in AirMapView. I have submitted a PR for this.

**Comment by henrikra** [comment]
@chaitanya0bhagvan is talking about this PR https://github.com/airbnb/react-native-maps/pull/1403

**Comment by Deevent** [comment]
@chaitanya0bhagvan The PR is not solving the issue by my side.

**Comment by henrikra** [comment]
@Deevent Are you sure you are using it right? Do you still get same error etc.

**Comment by chaitanya0bhagvan** [comment]
@Deevent As @henrikra mentioned double check that the fix is applied and the new apk is running on the device. If you still have the same error could you post the full stack trace?

**Comment by Nelrohd** [comment]
@felipecsl I believe there is the same issue [here](https://github.com/airbnb/react-native-maps/blob/master/lib/android/src/main/java/com/airbnb/android/react/maps/AirMapView.java#L307)

From 0.15.3
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'void com.google.maps.api.android.lib6.impl.bn.o()' on a null object reference
       at com.google.maps.api.android.lib6.impl.cw.b(:com.google.android.gms.DynamiteModulesB:26)
       at com.google.android.gms.maps.internal.t.onTransact(:com.google.android.gms.DynamiteModulesB:21)
       at android.os.Binder.transact(Binder.java:507)
       at com.google.android.gms.maps.internal.IMapViewDelegate$zza$zza.onResume(Unknown Source)
       at com.google.android.gms.maps.MapView$zza.onResume(Unknown Source)
       at com.google.android.gms.dynamic.zza$7.zzb(Unknown Source)
       at com.google.android.gms.dynamic.zza.zza(Unknown Source)
       at com.google.android.gms.dynamic.zza.onResume(Unknown Source)
       at com.google.android.gms.maps.MapView.onResume(Unknown Source)
       at com.airbnb.android.react.maps.AirMapView$12.onHostResume(AirMapView.java:307)
```

As a tmp solution, I changed myself the line for:
```
if(!destroyed) {
   AirMapView.this.onResume();
}
```
It fixed the problem, not sure if it was the correct fix however.

**Comment by loiclouvet** [comment]
I applied #1403 but still have the issue. Will post the full stack trace asap :smile:

**Comment by loiclouvet** [comment]
Here is stack trace using react-native-maps from [v0.15.3](https://github.com/airbnb/react-native-maps/commit/153e83def147395041e18709c40c7f19633de2c2) commit

```
# Platform: android
# OS Version: 6.0.1
# Device: ASUS_Z00AD

#0. Crashed: main: 0 0 0x0000000000000000
       at com.google.maps.api.android.lib6.impl.cw.b(:com.google.android.gms.DynamiteModulesB:26)
       at com.google.android.gms.maps.internal.t.onTransact(:com.google.android.gms.DynamiteModulesB:21)
       at android.os.Binder.transact(Binder.java:387)
       at com.google.android.gms.internal.zzed.zzb(Unknown Source)
       at com.google.android.gms.maps.internal.zzk.onResume(Unknown Source)
       at com.google.android.gms.maps.MapView$zza.onResume(Unknown Source)
       at com.google.android.gms.dynamic.zzh.zzb(Unknown Source)
       at com.google.android.gms.dynamic.zza.zza(Unknown Source)
       at com.google.android.gms.dynamic.zza.onResume(Unknown Source)
       at com.google.android.gms.maps.MapView.onResume(Unknown Source)
       at com.airbnb.android.react.maps.AirMapView$12.onHostResume(AirMapView.java:305)
```

**Comment by mikelambert** [comment]
@felipecsl Can you reopen this bug, since it appears not to have actually been completely fixed?

I do think (but without a local repro case, I cannot prove) that @Nelrohd 's tmp fix is the second half of the workaround here, necessary to keep things from crashing. Even if it's still not the Real Fix for the Underlying Problem.

**Comment by offwhite** [comment]
@mikelambert just tested your branch on an LG G3 - 6.0 and i'm still experiencing the same issue.

**Comment by mikelambert** [comment]
@offwhat, what is the crash you are seeing, specifically? In `onResume`?

**Comment by loiclouvet** [comment]
I did not reproduce the issue since i applied both patches on _onHostPause_ and _onHostResume_.

**Comment by offwhite** [comment]
@mikelambert Yeah, I'm getting the onResume error. I don't recall the iOS error - but it fails to build. I had to switch to another task - will try again later and let you know.

**Comment by bgnlordhelmut** [comment]
I've managed to fix this error from happening thanks to some of the fixes suggested in this thread, but running into a new issue as a result: https://github.com/airbnb/react-native-maps/issues/1471

Not sure if anyone else is experiencing this at all, but thought it might be relevant.

**Comment by junaediwidjojo** [comment]
Thought the problem is on the device? I have same error with LG G4 too.
Still waiting for solution about this

**Comment by franzmoro** [comment]
tried a lot of the above without success on an LG G4.
After having a look at `MapView.js` what worked for me was to pass the property **`liteMode={true}`** to the `MapView` component.

**Comment by linhtqse02192** [comment]
@felipheggaliza: Thanks, you save my life. :)
But I'm a newbie. Can you explain to me why it working.

**Comment by BraunreutherA** [comment]
Hi, is there any progress with this bug? I'm running on 0.15.0 and applied the destroyed check to resume and pause, but it still crashes on multiple devices (PS 11.0.1)

**Comment by loiclouvet** [comment]
@BraunreutherA They fixed it: #1403 and #1464.
Use latest release: v0.16.2

**Comment by ou2s** [comment]
I have a similar issue on 0.17.1

```
11-13 16:50:20.000 414-1261/? E/AndroidRuntime: FATAL EXCEPTION: androidmapsapi-vts_lu.myapp.myapp_default
                                                java.lang.OutOfMemoryError
                                                    at com.google.maps.api.android.lib6.gmm6.util.c.a(:com.google.android.gms.DynamiteModulesB:15)
                                                    at com.google.maps.api.android.lib6.gmm6.model.br.a(:com.google.android.gms.DynamiteModulesB:107)
                                                    at com.google.maps.api.android.lib6.gmm6.model.bk.a(:com.google.android.gms.DynamiteModulesB:5)
                                                    at com.google.maps.api.android.lib6.gmm6.store.cache.u.c(:com.google.android.gms.DynamiteModulesB:239)
                                                    at com.google.maps.api.android.lib6.gmm6.store.d.a(:com.google.android.gms.DynamiteModulesB:273)
                                                    at com.google.maps.api.android.lib6.gmm6.store.d.a(:com.google.android.gms.DynamiteModulesB:175)
                                                    at com.google.maps.api.android.lib6.gmm6.store.g.handleMessage(:com.google.android.gms.DynamiteModulesB:4)
                                                    at android.os.Handler.dispatchMessage(Handler.java:99)
                                                    at android.os.Looper.loop(Looper.java:176)
                                                    at com.google.maps.api.android.lib6.gmm6.store.d.run(:com.google.android.gms.DynamiteModulesB:131)
                                                    at com.google.maps.api.android.lib6.gmm6.store.z.run(:com.google.android.gms.DynamiteModulesB:19)
```

**Comment by reivaxcorp** [comment]
I solved it with


 ` if(Build.VERSION.SDK_INT > Build.VERSION_CODES.LOLLIPOP_MR1) {
            mMap.getUiSettings().setZoomControlsEnabled(true);
        }else{
            mMap.setMaxZoomPreference(16); 
//            mMap.getUiSettings().setZoomControlsEnabled(false);
        }`

apparently it is a mistake with previous versions of api 22

[https://stackoverflow.com/questions/3423754/retrieving-android-api-version-programmatically](url)

**Comment by tineo** [comment]
It wasn't fixed?
