### ISSUE TITLE
Help: Having trouble using react native maps

### ISSUE THREAD

**Issue by xshadowlegendx** [airbnb/react-native-maps#1366]
I am a web developer coming from Meteor + ReactJS. Now I want to learn how to develop mobile app using React Native, although it is new to me but since I am using ReactJS for long so i thought learning React Native should be easy since it has only some differences.
I am having trouble starting the map, i tried searching google and the issues from this package, then i found 1 possible solution, but it does not work.
**Error:**
```
A problem occurred configuring project ':app'.
    >Could not resolve all dependencies for configuration ':app:_debugApk'.
        >A problem occurred configuring project: ':react-native-maps'

// index.android.js

import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View
} from 'react-native';

import MapView from 'react-native-maps';

const styles = StyleSheet.create({
  container: {
    ...StyleSheet.absoluteFillObject,
    height: 400,
    width: 400,
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  map: {
    ...StyleSheet.absoluteFillObject,
  },
});

module.exports = class MyApp extends React.Component {
  render() {
    const { region } = this.props;
    console.log(region);

    return (
      <View style ={styles.container}>
        <MapView
          style={styles.map}
          region={{
            latitude: 37.78825,
            longitude: -122.4324,
            latitudeDelta: 0.015,
            longitudeDelta: 0.0121,
          }}
        >
        </MapView>
      </View>
    );
  }
}

AppRegistry.registerComponent('MyApp', () => MyApp);

```

**Steps i do for this project:**
```
react-native init Test
cd Test/

yarn //waits until it finish the installing....

yarn add react-native-maps

react-native link react-native-maps

// open android studio to start virtual device emulator

react-native run-android

```

**Implement solution found in context from the web ( NOT WORKING, SAME ERROR )**
```
//package.json

"dependencies": {
    ...
    "react-native-maps": "*" // change from x.x.x i forgot sorry
}

```
Sorry if this is too beginner question and thanks very much for helping.

**Comment by saeropark** [comment]
omg same! My app was working fine yesterday but then it suddenly hit me with this error.

**Comment by foyarash** [comment]
What is your version of the package? Do you have more details for the error you get?

**Comment by xshadowlegendx** [comment]
@foyarash Sorry for the late reply here is the package.json
```
{
	"name": "FastLane",
	"version": "0.0.1",
	"private": true,
	"scripts": {
		"start": "node node_modules/react-native/local-cli/cli.js start",
		"test": "jest"
	},
	"dependencies": {
		"react": "16.0.0-alpha.6",
		"react-native": "0.44.0",
		"react-native-maps": "*",
		"react-native-meteor": "^1.0.3",
		"redux": "^3.6.0"
	},
	"devDependencies": {
		"babel-jest": "20.0.3",
		"babel-preset-react-native": "1.9.2",
		"jest": "20.0.3",
		"react-test-renderer": "16.0.0-alpha.6"
	},
	"jest": {
		"preset": "react-native"
	}
}

```
Here is the full error log:
```
Preparing "Install Android SDK Build-Tools 25.0.2".
Warning: Failed to read or create install properties file.
Checking the license for package Android SDK Build-Tools 25.0.2 in /opt/android-sdk/licenses
License for package Android SDK Build-Tools 25.0.2 accepted.
Preparing "Install Android SDK Build-Tools 25.0.2".
Warning: Failed to read or create install properties file.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':react-native-maps'.
      > Failed to notify project evaluation listener.
         > Failed to install the following SDK components:
           [Android SDK Build-Tools 25.0.2]
           Please install the missing components using the SDK manager in Android Studio.
         > Failed to install the following SDK components:
           [Android SDK Build-Tools 25.0.2]
           Please install the missing components using the SDK manager in Android Studio.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output
.

BUILD FAILED

Total time: 54.924 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html

```
FYI: I left my android emulator running, tested with running clean react-native project ( see welcome react native screen... ), and i do not think that android sdk might be a problem because i have the latest 25.0.3 installed.
**Since I am first time using react native and react native map, so FYI what if I did the initialization of the project in wrong way possible? If there is no further solution could find for me so can you please tell me from scratch of what i should do?**
Here is the summary step of what I did to initialize the project:
```
react-native init Test

yarn

yarn add react-native-maps

yarn //First time using yarn also btw, run it again like npm install or npm update i think...

// Edit package.json
"dependencies": {
    ...
    "react-native-maps": "*" // change from x.x.x i forgot sorry
}

yarn //again to update

react-native link react-native-maps // successfully linked message appears...

//open android virtual devices

//copy example map from github to replace in index.android.js

react-native run-android

```

**Comment by foyarash** [comment]
This problem seems to be related to your android sdk installation, related to what RN needs.

Did you correctly follow the instructions mentionned here? https://facebook.github.io/react-native/docs/getting-started.html#2-install-the-avd-and-haxm

**Comment by xshadowlegendx** [comment]
@foyarash Yes bro, I am sure i correctly follow the instructions from its official site

**Comment by foyarash** [comment]
What I understand here is that the lib asks for the Android SDK Build-Tools 25.0.2 but you did not install it from android studio SDK manager.

Just go to your SDK manager, and check if this package is installed. If not, install it and retry to build to project

**Comment by xshadowlegendx** [comment]
@foyarash I tried to install it from android studio but it throw me an error:
```
To install:
- Android SDK Build-Tools 25.0.2 (build-tools;25.0.2)
Preparing "Install Android SDK Build-Tools 25.0.2 (revision: 25.0.2)".
Failed to read or create install properties file.
Failed packages:
- Android SDK Build-Tools 25.0.2 (build-tools;25.0.2)

```
Last night, I tried re do everything again and it throws me **this error:**
```
Starting JS server...
Building and installing the app on the device (cd android && ./gradlew installDebug)...
Checking the license for package Android SDK Build-Tools 23.0.1 in /home/shadowlegend/Android/Sdk/licenses
Warning: License for package Android SDK Build-Tools 23.0.1 not accepted.
Checking the license for package Android SDK Platform 23 in /home/shadowlegend/Android/Sdk/licenses
Warning: License for package Android SDK Platform 23 not accepted.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> You have not accepted the license agreements of the following SDK components:
  [Android SDK Platform 23, Android SDK Build-Tools 23.0.1].
  Before building your project, you need to accept the license agreements and complete the installation of th
e missing components using the Android Studio SDK Manager.
  Alternatively, to learn how to transfer the license agreements from one workstation to another, go to http:
//d.android.com/r/studio-ui/export-licenses.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output
.
BUILD FAILED

Total time: 53.263 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html

```

**Comment by foyarash** [comment]
Did you accept the license agreements during the installation of the Build-Tools ? If not just accept them and complete their installation as mentioned in the error message

**Comment by xshadowlegendx** [comment]
@foyarash Ok I will try it tonight, so sorry that i am outside right now, will report back to you after that.

**Comment by xshadowlegendx** [comment]
Hello @foyarash, i was having problem installing android sdk, as i dig deep, there are problem related to permission so right now i have not yet able to install the 23.0.1 sdk, since it is not related to the issue of this package, i will try to solve the android problem first then i will report back to this, thanks very much for your time.
FYI: I am using Arch Linux.

**Comment by foyarash** [comment]
If you still have the problem, then i advise you to open an issue on RN github, or just a topic on StackOverflow, since your problem seems to be not related to this library

**Comment by xshadowlegendx** [comment]
@foyarash I am now able to install and run the app on my emulator, and the map has shown normally, although the problem is related to android studio, thanks very much for your time and help bro, the problem now is solved.

@saeropark  hello bro, I dunno if it helps you but I was having problem with android studio since I am just using it and I do not know that permission issue could be the problem for me to install the android sdk properly, here is how i fixed it:

**1. Completely remove android studio and its dependencies also along with android-sdk (I removed all its dependencies using pacaur and manually remove android-sdk directory using root)**

**2. Download the zip file from its official site ( I install it from AUR before )**

**3. Extract it to my home directory and mostly importantly installing sdk in home directory to prevent permission issue again, install necessary stuff, then run it again**
