### ISSUE TITLE
Map not working properly when goes to background

### ISSUE THREAD

**Issue by rexlow** [airbnb/react-native-maps#1380]
I am trying to integrate background active tracking in my app. 

As you can see from the image below, the red marker is where I started working and blue pulse icon is where I stopped. I had only walked a distance somewhere between 0.1 - 0.2 km, it was a U-turn. The app works well when the app is in the foreground, polylines render correcly. But as soon as the app goes into the background, and to the foreground again, it would think that I've traveled far, ergo, the ridiculous polylines.

I have already followed the steps according to the [API](https://facebook.github.io/react-native/docs/geolocation.html) and enabled NSLocationAlwaysUsageDescription to enable always on GPS but it does not render correctly. 

![img_1454](https://cloud.githubusercontent.com/assets/7680796/26740889/e8ae38fa-4809-11e7-882f-739416ff3e9e.PNG)

**Comment by henrikra** [comment]
Are you using built in `navigator.geolocation` to get user's position?

**Comment by rexlow** [comment]
Yes, and I have not seen any examples that are able to optimize the GPS tracking module 😢

**Comment by henrikra** [comment]
Okay then you are screwed :D

**Comment by rexlow** [comment]
@henrikra why?

**Comment by henrikra** [comment]
Since built in geolocation module does not work right when app is on background. You would have to make something custom or use maybe something like this which is not free https://github.com/transistorsoft/react-native-background-geolocation

**Comment by rexlow** [comment]
@henrikra I'm suspecting the problem is with the phone itself. Though I have no way to be sure other than testing with another physical phone. Is there a way to calibrate/debug my iPhone's GPS?

**Comment by henrikra** [comment]
Trust me. I have been working with React Native and GPS stuff for over 6 months now. Ping me if you solve this xD

**Comment by rexlow** [comment]
@henrikra That's terrible to hear 😢 Then how do you resolve your problem? Custom build something or purchase the module?

**Comment by henrikra** [comment]
We bought the paid geolocation I linked you. It works pretty good on iOS but for Android we made totally custom.

**Comment by rexlow** [comment]
Ah, I see. Will try to do some deep research on this polyfills later. It must be something that we are missing.

**Comment by jcharlet** [comment]
see my answer (I'm using a objective C lib, using native geoloc api for iOS, for RN) https://stackoverflow.com/questions/43629524/react-native-ios-geoloc-has-poor-accuracy-by-default/43639144#43639144

check that too https://github.com/facebook/react-native/issues/12967#issuecomment-292176191 (is your issue duplicating that one?)

**Comment by rexlow** [comment]
@jcharlet Things look pretty good now with react-native-location! Thanks!
