### ISSUE TITLE
Open google maps app

### ISSUE THREAD

**Issue by valinsky** [airbnb/react-native-maps#1381]
This is not an issue per se, but something that's been on my mind since i "discovered" it and can't recreate it. 
My application uses the Google Maps Directions API to get a list polylines that i use to draw a route on the map with some pins here and there.
Today when i was playing around with the app, in the bottom right corner of the map, 2 button appeared (i wanted to recreate it and show you an screenshot but i don't know how) which when pressed opened the actual Google Maps app with the destination and route already set for that destination. One was an arrow and the other like a mini version of the Google Maps icon.
This is exactly what i want my app to do, be able to open Google Maps with the coordinates used in my app. I literally freaked out when it happened and now i don't know how to make those buttons show up again and stay there.
Any help would be greatly appreciated.

**Comment by foyarash** [comment]
Set the toolbarEnabled prop to true for the MapView component

**Comment by valinsky** [comment]
I found out what the issue was. The toolbar should show up when a marker is pressed, but if the View is not re-rendered, toolbar will not show up. I think somehow my View got re-rendered when i freaked out and i didn't know why or how :)
If anyone experiences the same issue i suggest reading this thread [https://github.com/airbnb/react-native-maps/issues/549](url)
