### ISSUE TITLE
[Android] Blank map because of api key restriction

### ISSUE THREAD

**Issue by smartdevth** [airbnb/react-native-maps#1382]
I have a problem with key restriction only when it released upon play store, the map goes blank.

I also got SHA1 finger print from released jks file.

Note: when I try to build via react-native run-android --variant=release on my device it is perfectly fine.

--------
RN 0.43
RNM 0.13

**Comment by smartdevth** [comment]
Fix by using SHA1 from https://play.google.com/apps/publish/ on  App signing menu

**Comment by mistryhiren94** [comment]
which SHA1 Key?
App Signing Certificate OR Uploas certificate
please help
thanks

**Comment by mistryhiren94** [comment]
@fokoz thanks,
its working

**Comment by e-molochko** [comment]
@fokoz Hey, did u find a solution,how to use key with restrictions for react-native-maps?
