### ISSUE TITLE
Maps not doing anything

### ISSUE THREAD

**Issue by gitlovenotwar** [airbnb/react-native-maps#1390]
package.json

react": "16.0.0-alpha.6",
"react-native": "0.44.3",
"react-native-maps": "^0.15.2",

code:
import MapsView from 'react-native-maps'

`

    class App extends Component {

    render() {

    return (

      <View style={{flex: 1}}>

         <MapsView

           initialRegion={{

            latitude: 37.78825,

            longitude: -122.4324,

            latitudeDelta: 0.0922,

            longitudeDelta: 0.0421,

         }}/>

      </View>

    );

    }
   }

`

Just follow the installations and successfully linked them all, but maps not rendering, or doing anything at all.

**Comment by georgetroughton** [comment]
Looking at your code above you are importing Map**s**View but using MapView.... but that should give errors rather than un-rendered map.

**Comment by gitlovenotwar** [comment]
Hi, a typo, I am using MapsView.

**Comment by gitlovenotwar** [comment]
Hi, I've solved the issue with this. The troubleshoot is in the bottom of the docs. Might as well make it to the top, before all the examples. 

const styles = StyleSheet.create({
  map: {
    ...StyleSheet.absoluteFillObject,
  },
});

The map have to be explicitly have a width and height...

**Comment by RWOverdijk** [comment]
@gitlovenotwar That works. Would you mind closing this issue?
