### ISSUE TITLE
Blank Maps

### ISSUE THREAD

**Issue by tsunhime** [airbnb/react-native-maps#1398]
First, I thought API key was wrong but it's not. I tried to change API key to API key from example folder in this repository. But it's can't fixed. What should I try for fix this issue?

ISSUE:
<img src="https://c1.staticflickr.com/5/4229/34355821504_bd81b5570a.jpg" width="380" height="451" alt="Capture">

This all dependency installed:
<img src="https://c1.staticflickr.com/5/4203/35035305992_725ae98690.jpg" width="427" height="434" alt="Capture2">

**Comment by tsunhime** [comment]
I upgrade android emulator from Marshmallow to O instead and it's work!
Or I'm not sure you need to wait a minute and google API will work instead.

**Comment by mistryhiren94** [comment]
I'm also facing same problem
blank map on release
please help
thanks

**Comment by mistryhiren94** [comment]
Hi
its issue of SHA1 key
for Release APK the SHA1 key is from Release SHA1 key(Google Play Store)
thanks
