### ISSUE TITLE
React-navigation breaks mapView

### ISSUE THREAD

**Issue by beerteam** [airbnb/react-native-maps#1400]
My project very simple. MapView is works fine. But when I use react-navigation - navigate and back again to map, then map is broken. No interaction, no zoom, noting. Maybe is bug with RN 0.45?

![out](https://user-images.githubusercontent.com/1646784/27007650-53eefe10-4e7c-11e7-9533-c7966e723f5c.gif)

React Native: 0.45.1
React Native Maps: 0.15.2
React Navigation: 1.0.0-beta.9

**Comment by grigored** [comment]
maybe another view remains on top of the map, and that view is capturing all events?

**Comment by beerteam** [comment]
@grigored I will check it and reply. Thanks

**Comment by beerteam** [comment]
@grigored When I using inspector and don't see views over mapView. Navigation back breaks maps inside processes.

I tried to disable props sent to map and found cacheEnabled={true}. When I turned off cacheEnabled everything ok. Issue closed.

**Comment by EroticCode** [comment]
I tried to disable props sent to map and found cacheEnabled={true}. When I turned off cacheEnabled everything ok. Issue closed.

it's not working true or false
