### ISSUE TITLE
UrlTile example is showing a beige screen on Apple Maps

### ISSUE THREAD

**Issue by shenst1** [airbnb/react-native-maps#1404]
<img width="380" alt="screen shot 2017-06-13 at 4 03 24 pm" src="https://user-images.githubusercontent.com/3740533/27108711-93d08e62-5053-11e7-961c-3400f580b01f.png">
When trying to recreate the example of CustomTiles in the example folder, I am getting the above screen instead of the watercolor overlay. 
I created a [separate react-native project with the component isolated](https://github.com/shenst1/MapPlayground).

**Comment by markmssd** [comment]
Could it be because of a missing/wrong Google Maps API key? I know there was an opened PR to make urlTiles not to depend on it, not sure if it's merged yet though...

**Comment by shenst1** [comment]
This example isn't using Google Maps, it is using apple maps. Unless urlTiles are only meant to work with Google Maps?

**Comment by markmssd** [comment]
I think you're right, it could be related to this PR https://github.com/airbnb/react-native-maps/pull/1357

**Comment by shenst1** [comment]
hmm, I don't think that is the same issue. According to the screenshot provided by @spikebrehm in PR [595](https://github.com/airbnb/react-native-maps/pull/595), the tileurls should be working in apple maps. I think an overlay is different than a tile, i could be wrong about that though.

**Comment by neo125874** [comment]
@shenst1 hi, did you got the tile working on the apple's map?

**Comment by shenst1** [comment]
@neo125874 nope, still stuck in a land of beige screens

**Comment by shenst1** [comment]
needed to allow the example url: 
For IOS: configure App Transport Security in your app
So, in your `Info.plist`
```
<key>c.tile.stamen.com</key>
<dict>
  <key>NSExceptionAllowsInsecureHTTPLoads</key>
  <true/>
</dict>
```
