### ISSUE TITLE
liteMode IOS

### ISSUE THREAD

**Issue by JoseIgnacio92** [airbnb/react-native-maps#1411]
Hello there,

Is there any similar function for ios? 

I need only a static image of a location.

Thanks

**Comment by guilhermepontes** [comment]
*There's no support for `liteMode` on Google Maps SDK for iOS.*
But, fortunately we can use the _Google Static Maps API_. ✨ 

Which you can find more about it here:
https://developers.google.com/maps/documentation/static-maps/intro

An example about how to solve it:

```js
const staticMapURL = 'https://maps.googleapis.com/maps/api/staticmap'

const mapImage = {
  uri: `${staticMapURL}?center=Amsterdam,Netherlands&size=750x400&key=YOUR_API_KEY`
}

<Image source={mapImage} style={{ width: '100%', height: 200 }} />
```

**Comment by JoseIgnacio92** [comment]
Thanks buddy!
