### ISSUE TITLE
Marker Fix appear on the Top of the maps

### ISSUE THREAD

**Issue by yelkamel** [airbnb/react-native-maps#1412]
Hello everyone,

When I move in the map somethimes I got marker stock on the top as you can see in the screenshoot below: 

![image uploaded from ios 1](https://user-images.githubusercontent.com/10924422/27234957-3c273b02-52bf-11e7-95f7-4c8e60a897be.jpg)

I can even know when it's happen (and then maybe re-render the markers).

Does anyone have an idea to correct this? 

thanks,
Youcef

**Comment by freshnewegg** [comment]
Hello friend,

I fixed it here, https://github.com/freshnewegg/react-native-maps/commit/89a5cdaee7827d13ebbcd88dc1dab32f221b22c3 

But the versions are not for the most recent rn-maps and rn. It works though. Hope this helps!!!!! If someone could instruct on how such a PR may occur, I'd be interested in learning.

Thanks

**Comment by beerteam** [comment]
Hello, did you found solution?

**Comment by yelkamel** [comment]
Use the code of @freshnewegg in his commit.
Manually change the file AIRMapMarker.m and AIRMapMarker.h.

Then you should not have this issue again.

**Comment by Stevenfly** [comment]
@freshnewegg Hey could you do a pull request, I am also having this issue and I don't really want to modify the package. Thanks!
