### ISSUE TITLE
Cannot install in react@16.0.0-alpha.12

### ISSUE THREAD

**Issue by mobilemaster5** [airbnb/react-native-maps#1423]
npm WARN react-native-maps@0.15.2 requires a peer of react@>=15.4.0 but none was installed.

How can I fix the issue and add the `maps` ?

Regards !

**Comment by candauvan** [comment]
me too !!!

**Comment by ruedigerfranke** [comment]
+1

**Comment by kmrachko** [comment]
This worked for me: [Fix guide](https://github.com/lwansbrough/react-native-camera/issues/662#issuecomment-303562060)

**Comment by christopherdro** [comment]
https://github.com/airbnb/react-native-maps/commit/d57edd2a095552999a961f210e610f0746f1470b
