### ISSUE TITLE
eact-native-maps: AirGoogleMaps dir must be added to your xCode project to support GoogleMaps on IOS.

### ISSUE THREAD

**Issue by pascantk** [airbnb/react-native-maps#1434]
I have installed react-native-maps on macOS with option3, it build ok but it have a error when running:
console.error: "react-native-maps: AirGoogleMaps dir must be added to your xCode project to support GoogleMaps on IOS."
https://github.com/airbnb/react-native-maps/blob/1e71a21f39e7b88554852951f773c731c94680c9/docs/installation.md#option-3-manually
Please help me!!! Any tips will be appreciated :) Thanks!
  "dependencies": {
    "react": "16.0.0-alpha.6",
    "react-dom": "16.0.0-alpha.6",
    "react-native": "0.44.0",
    "react-native-maps": "^0.15.2",
...
}

**Comment by luco** [comment]
@pascantk Follow this guide:
https://github.com/anhtuank7c/maps-example

**Comment by pascantk** [comment]
Thank you very much. You save my day :)

**Comment by tbrandle** [comment]
I am still having an issue with this error after following the installation instructions you linked to. I have been stuck on this problem for almost a week and I can't get rid of this error. Android seems to render the map just fine. Someone please help!

	"dependencies": {
		"react": "^16.0.0-alpha.6",
		"react-native": "^0.48.0",
		"react-native-maps": "^0.15.3",
}

**Comment by awojtczyk** [comment]
Not working for me aswell.
Getting "AirGoogleMaps dir must be added to your xCode project to support GoogleMaps on iOS."

    "react-native": "0.47.2",
    "react": "16.0.0-alpha.12",
    "react-native-maps":"^0.16.3"

**Comment by benjamin3991** [comment]
Not working.
"react-native-maps: AirGoogleMaps dir must be added to your Xcode project to support GoogleMaps on iOS."
		```
"react": "^16.0.0-alpha.12",
		"react-native": "^0.48.4",
		"react-native-maps": "^0.16.4"
```

**Comment by juergengunz** [comment]
same issue, any solutions?

**Comment by tbrandle** [comment]
@juergengunz Fixed it! It has to do with the pods you are importing in your Podfile. If you already have React in your Libraries, there would be no need to add react via pod. It would conflict with your library in the main app.

https://medium.com/@kswanie21/react-native-google-map-with-react-native-maps-572e3d3eee14

**Comment by juergengunz** [comment]
what fixed it for me was to do "react-native unlink react-native-maps"

**Comment by jordenchang55** [comment]
Is there anyone successful by manual installing?

**Comment by dobrysmak** [comment]
I'm also facing this issue.

pacakge.json
```
"react": "^16.0.0-beta.5",
"react-native": "^0.48.4",
"react-native-maps": "^0.16.3"
```

Pod file
```
target 'testApp' do
  pod 'Yoga', path: "./node_modules/react-native/ReactCommon/yoga/Yoga.podspec"
  pod 'GoogleMaps'
end
```

1. AirGoogleMaps and AirMaps added to root directory in xCode.
2. Added AirMaps.a lib to xCode
3. Adjusted the paths to react-native-maps in Header Search paths

Maps for iOS (MapKit) work, but if PROVIDER_GOOGLE is added - the error appears.

Any workaround for this?

**Comment by alexgvozden** [comment]
I also cannot fix this followed all tutorials, it's pretty confusing and someone should do new tutorial probably with more clear info

**Comment by dobrysmak** [comment]
can this issue be reopen?

**Comment by kiroskirin** [comment]
I can make it work here my pod file

```
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Example' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

    pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

    pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'RCTText',
    'RCTImage',
    'RCTAnimation',
    'RCTActionSheet',
    'RCTLinkingIOS',
    'RCTSettings',
    'RCTVibration',
    'RCTNetwork',
    'RCTWebSocket',
    'DevSupport',
    'BatchedBridge',
    'RCTGeolocation',
    ]

pod 'GoogleMaps'  # Remove this line if you don't want to support GoogleMaps on iOS
pod 'react-native-maps', path: '../node_modules/react-native-maps'
pod 'react-native-google-maps', path: '../node_modules/react-native-maps'  # If you need GoogleMaps support on iOS

  target 'Example' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == 'react-native-google-maps'
            target.build_configurations.each do |config|
                config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
            end
        end
        
        if target.name == "React"
            target.remove_from_project
        end
    end
end

end
```

and you don't need to drag `AirGoogleMaps` or anything to root folder, Just pod install.
... BUT when run build with Xcode it will failed duplicate library.
... BUT don't worry just fixed by delete `-l"react-native-maps"` from both of your `Pods-Example.debug | release.xcconfig` at `OTHER_LDFLAGS`

My dependencies
```
"dependencies": {
    "react": "16.0.0-alpha.12",
    "react-native": "^0.48.2",
    "react-native-maps": "^0.16.4",
  },
```
Here a proof

![simulator screen shot - iphone 6 - 2017-10-06 at 14 07 40](https://user-images.githubusercontent.com/311686/31266906-509482d2-aaa0-11e7-8f95-b9f54b026cb9.png)

**Comment by dobrysmak** [comment]
@kiroskirin awesome! after a week of struggle it's working :) 
Just needed to tweak the podfile lil bit

package.json
```
"dependencies": {
    "react": "16.0.0-alpha.12",
    "react-native": "^0.48.2",
    "react-native-maps": "^0.16.4",
  },
```

Podfile 
```
source 'https://github.com/CocoaPods/Specs.git'
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'AppName' do
    pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
    pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'RCTText',
    'RCTImage',
    'RCTAnimation',
    'RCTActionSheet',
    'RCTLinkingIOS',
    'RCTSettings',
    'RCTVibration',
    'RCTNetwork',
    'RCTWebSocket',
    'DevSupport',
    'BatchedBridge',
    'RCTGeolocation',
    ]

    pod 'GoogleMaps'  # Remove this line if you don't want to support GoogleMaps on iOS
    pod 'react-native-maps', path: '../node_modules/react-native-maps'
    pod 'react-native-google-maps', path: '../node_modules/react-native-maps'  # If you need GoogleMaps support on iOS

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == 'react-native-google-maps'
            target.build_configurations.each do |config|
                config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
            end
        end
        
        if target.name == "React"
            target.remove_from_project
        end
    end
end
```

**Comment by Tom29** [comment]
@dobrysmak got this error with your pod file:

> [!] Unable to satisfy the following requirements:
> 
> - `React/BatchedBridge (from `../node_modules/react-native`)` required by `Podfile`
> 
> None of your spec sources contain a spec satisfying the dependency: `React/BatchedBridge (from `../node_modules/react-native`)`.
> 
> You have either:
>  * out-of-date source repos which you can update with `pod repo update`.
>  * mistyped the name or version.
>  * not added the source repo that hosts the Podspec to your Podfile.
> 
> Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

i use `platform :ios, '8.0'`

**Comment by rom1k** [comment]
Not any of the podfiles posted here works for me, still getting error "AirGoogleMaps dir must be added to your xCode project to support GoogleMaps on IOS"

Using react-native 0.49.3 and tried react-native-maps versions 0.16.4 and 0.17.0

The react-native-maps documentation is obviously outdated so I don't even bother with it. Why are there 3 options?? One should work for everyone.
This one is a bit more proper but I still get the same error.
https://github.com/anhtuank7c/maps-example

**Comment by dapregala** [comment]
What fixed this for me is **manual linking**. I unlinked react-native-maps first: `react-native unlink react-native-maps` and then I followed the instructions on: https://facebook.github.io/react-native/docs/linking-libraries-ios.html#manual-linking. In there, it explicitly says that:

> If the library has native code, there must be a .xcodeproj file inside it's folder. Drag this file to your project on Xcode (usually under the Libraries group on Xcode);

Hence, I dragged the `AirMaps.xcodeproj` from `node_modules/react-native-maps/lib/ios` to the `Libraries` folder on XCode.

Just follow Option 3 on the installation instructions. But I think it is important to unlink first if you have tried automatic linking (`react-native link react-native-maps`) beforehand.

The error does not show anymore, hope this helps.

Versions used:
```
react-native-cli: 2.0.1
react-native: 0.44.0
npm: 4.1.2
node: 7.7.4
pod: 1.3.1
```

**Comment by rom1k** [comment]
@dapregala Tried that, still getting the same error.
I tried some solution that works after a couple of times (drag AirGoogleMaps to project navigator or something) but then I get the duplicate symbols error instead.

**Comment by davidroman0O** [comment]
Hey @lelandrichardson any advices to solve this issue?

It's really awful right now since the last react-native update. 

Mostly impossible to have a clean installation. Every time we (and i) got the same kind of error. 
This famous : `air google maps dir must be added to your xcode project to support google maps on ios`

Really frustrating to not be able to install this module, it's was waaaaay more easier before the last update of RN... :/ 

Hope you'll see this comment and help! :)

**Comment by mehdijjz** [comment]
I have the same issue

**Comment by kgozali** [comment]
@kiroskirin hi, can you please elaborate on the last part where i should delete files? where do i run the command?. So basically i just need to `pod init` then copy your podfile, then run `pod install`?

**Comment by runia1** [comment]
Same issue :(

**Comment by vinicius5581** [comment]
**OS:**
```
macOs High Sierra
v 10.13.3
```

**Node version**
```
v8.9.4
```

**Steps**
```
$ npm install -g react-cli
$ react-cli init myProject
$ cd myProject
$ npm install
$ npm install react-native-maps --save 
$ cd ios/
$ vim Podfile
```

```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'myProject' do
  rn_path = '../node_modules/react-native'
  rn_maps_path = '../node_modules/react-native-maps'

  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
    'BatchedBridge'
  ]

  pod 'react-native-maps', path: rn_maps_path

  pod 'GoogleMaps'  # Remove this line if you don't want to support Google Maps on iOS
  pod 'react-native-google-maps', path: rn_maps_path  # Remove this line if you don't want to support Google Maps on iOS
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'react-native-google-maps'
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
      end
    end
    if target.name == "React"
      target.remove_from_project
    end
  end
end
```
```
$ pod install
```

**ERROR:**

```
$ pod install
Analyzing dependencies
Fetching podspec for `React` from `../node_modules/react-native`
Fetching podspec for `react-native-google-maps` from `../node_modules/react-native-maps`
Fetching podspec for `react-native-maps` from `../node_modules/react-native-maps`
Fetching podspec for `yoga` from `../node_modules/react-native/ReactCommon/yoga/yoga.podspec`
[!] CocoaPods could not find compatible versions for pod "React/BatchedBridge":
  In Podfile:
    React/BatchedBridge (from `../node_modules/react-native`)

None of your spec sources contain a spec satisfying the dependency: `React/BatchedBridge (from `../node_modules/react-native`)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

[!] Automatically assigning platform `ios` with version `8.0` on target `maps` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

```

**Comment by rborn** [comment]
@tetogomez did you try to follow the steps in a brand new project?

**Comment by Juniper11** [comment]
@dobrysmak how were you able to acheive:
"2.   Added libAirMaps.a to "Link Binary with Libraries" to xCode"
I am missing this file, no idea how to get it.

**Comment by mindjaydeep** [comment]
@kiroskirin , thanks finally its worked .. 
just update minor things in pod file 
removed BatchedBridge from pod and make yoga to Yoga.. and its worked for me. 


----------------------------------------------- if any one needs pod file ---------------------------
```
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'yourAppName' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

    pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

    pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'RCTText',
    'RCTImage',
    'RCTAnimation',
    'RCTActionSheet',
    'RCTLinkingIOS',
    'RCTSettings',
    'RCTVibration',
    'RCTNetwork',
    'RCTWebSocket',
    'DevSupport',
    'RCTGeolocation',
    ]

pod 'GoogleMaps'  # Remove this line if you don't want to support GoogleMaps on iOS
pod 'react-native-maps', path: '../node_modules/react-native-maps'
pod 'react-native-google-maps', path: '../node_modules/react-native-maps'  # If you need GoogleMaps support on iOS

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == 'react-native-google-maps'
            target.build_configurations.each do |config|
                config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
            end
        end
        
        if target.name == "React"
            target.remove_from_project
        end
    end
end
```

**Comment by JadRizk** [comment]
Same Issue here !!

**Comment by bantingGamer** [comment]
**react-native@0.57** is the **issue here,** for me anyway. I just got this working by creating a **react-native@0.56** project, here are my exact steps: 

- react-native init newproject --version react-native@0.56
- yarn add react-native-maps.

my **package.json** files looks like this now
```
"dependencies": {
    "react": "16.4.1",
    "react-native": "0.56",
    "react-native-maps": "^0.22.1"
  },
```

- I then tested it by running "react-native run-ios" - this through me a error and i had to make all my files read and write, by right clicking the project folder and selecting "getinfo" and then click the cog to apply to enclosed items.
- I then ran "react-native run-ios" to test if i at least get the welcome screen. the test passed. moving onto next step.

Then i linked the react-native-maps manually in xcode here is how:
- open  .xcodeproj file
- right click  libraries folder and click add files to "projectName"
-  add node_modules/react-native-maps/lib/ios/AirMaps.xcodeproj
-  click on projectName and go Build Phases, click drop down for Link Binary With Libaries, click the plus icon and select libAirMaps.a

finally change your **App.js** like so:
```
import React, { Component } from "react";
import { StyleSheet, View } from "react-native";
import MapView from "react-native-maps";

export default class App extends Component {
  render() {
    return (
      <View>
        <MapView
          initialRegion={{
            latitude: 37.78825,
            longitude: -122.4324,
            latitudeDelta: 0.0922,
            longitudeDelta: 0.0421
          }}
          style={styles.map}
        />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1
  },
  map: {
    width: "100%",
    height: "100%"
  }
});
```
- then run "react-native run-ios"
- finally its working for me.

I really hope whomever reads this comes right.
rock on!

**Comment by mecoFarid** [comment]
So the issue is closed with no solution or update?

**Comment by DataGreed** [comment]
Just ran into this issue on RN 0.59.9.

**Comment by abrahamAlonzo** [comment]
Just ran into this issue on RN 60.4

**Comment by acro5piano** [comment]
Maybe this PR could help:

https://github.com/anhtuank7c/maps-example/pull/5

**Comment by ncuillery** [comment]
@datvp09 Are you sure you didn't miss this step in the README file:
>c) (React Native 0.60 and higher) Add the following to your Podfile above the `use_native_modules!` function and run `pod install` in the ios folder:
>  ```ruby
>    # React Native Maps dependencies
>    rn_maps_path = '../node_modules/react-native-maps'
>    pod 'react-native-google-maps', :path => rn_maps_path
>    pod 'GoogleMaps'
>    pod 'Google-Maps-iOS-Utils'
>  ```

The RN 0.60 auto-linking doesn't see the second podspec file `react-native-google-maps.podspec` so you need to reference it manually in your Podfile.

The instructions in the article you mentioned basically bring in your main project what this podspec file brings into the Pods project.

**Comment by lfoliveir4** [comment]
> @datvp09 Are you sure you didn't miss this step in the README file:
> 
> > c) (React Native 0.60 and higher) Add the following to your Podfile above the `use_native_modules!` function and run `pod install` in the ios folder:
> > ```ruby
> >   # React Native Maps dependencies
> >   rn_maps_path = '../node_modules/react-native-maps'
> >   pod 'react-native-google-maps', :path => rn_maps_path
> >   pod 'GoogleMaps'
> >   pod 'Google-Maps-iOS-Utils'
> > ```
> 
> The RN 0.60 auto-linking doesn't see the second podspec file `react-native-google-maps.podspec` so you need to reference it manually in your Podfile.
> 
> The instructions in the article you mentioned basically bring in your main project what this podspec file brings into the Pods project.

It worked for me. For versions above react-native 0.60

**Comment by SamiChab** [comment]
I just removed following prop in `MapView` component and it worked!
`provider={MapView.PROVIDER_GOOGLE}`

**Comment by nabeelasjid1** [comment]
> I just removed following prop in `MapView` component and it worked!
> `provider={MapView.PROVIDER_GOOGLE}`

So you are no more using google maps, after removing the props the app will no longer use google maps(p.c it will use apple maps now)

**Comment by SamiChab** [comment]
@nabeelasjid1 exactly, Apple Maps on iPhone and Google Maps on Android

**Comment by RajatBhati444** [comment]
> I just removed following prop in `MapView` component and it worked!
> `provider={MapView.PROVIDER_GOOGLE}`

thanks man 👍🏻

**Comment by princefishthrower** [comment]
Yeah, and for those of us who want to use google maps on both operating systems?

**Comment by LazyAfternoons** [comment]
Wondering the same. I follower the instructions in this repo but I still get AirGoogleMaps dir must be added to your xCode project to support GoogleMaps on IOS. Any clue? 
I tried follow some of the proposals in this discussions to no avail.

**Comment by adabaed** [comment]
I'm having this error too, any solution? 😥

**Comment by ChristopherGabba** [comment]
Anyone know how to accomplish this using Expo Managed Workflow?

**Comment by daavidwlf** [comment]
@ChristopherGabba I fixed the Error on a Project which is Expo Managed by:
1. Providing the API Keys for Android and IOS in the app.json as documented [here](https://docs.expo.dev/versions/latest/sdk/map-view/#ios)
2. Activating the Google Maps SDK for Android and Google Maps SDK for IOS on Google Cloud SDK Manager.
3. Make a new EAS Build
