### ISSUE TITLE
My map is not displayed, only 'Google' label

### ISSUE THREAD

**Issue by andrisole92** [airbnb/react-native-maps#1436]
That is all I have:
![screenshot_5](https://user-images.githubusercontent.com/17086705/27552844-b873d27c-5aa0-11e7-98a2-a38f0b31b49b.png)

**Comment by bsonntag** [comment]
This is also happening to me. Did you found any fix for this @andrisole92 ?

**Comment by andrisole92** [comment]
Yeah, I have had to enable Google Android Maps API in Google console. It is turned off by default.
