### ISSUE TITLE
Map shows up blue

### ISSUE THREAD

**Issue by nonameolsson** [airbnb/react-native-maps#1452]
Hi! I'm trying to get started with `react-native-maps`, but I'm encountering some difficulties. The map shows up blue with the Google logo. 
![screenshot_1499264547](https://user-images.githubusercontent.com/1493018/27868865-a8da2d1a-6163-11e7-9a68-a404a45b85f3.png)

This is my code: [https://gist.github.com/nonameolsson/4931e81b426539434ddf4e240f021316](https://gist.github.com/nonameolsson/4931e81b426539434ddf4e240f021316)

What could be the problem? I've wiped my emulator, installed the app again, even on my physical device.

**Comment by christopherdro** [comment]
Invalid coordinates for initial region.

https://gist.github.com/nonameolsson/4931e81b426539434ddf4e240f021316#file-visitsmap-js-L46-L47

**Comment by nonameolsson** [comment]
Thanks! 😲  That helped a lot!

**Comment by ghoshabhi** [comment]
@chrisopherdro Did you resolve this finally ? I am having the same issue on iOS. But, my `initialRegion` is correct. My map loads correctly the first time, but one when loaded second time it causes the blue screen issue. Issue: https://github.com/airbnb/react-native-maps/issues/1742

Can you please help me out here ? Thanks :)

**Comment by jordanmkoncz** [comment]
I'm having the same problem. I'm using `initialRegion`, and the first time the map is rendered it works perfectly, but the second time it's rendered the map is zoomed in at coordinates `0,0` (which is in the sea) so it looks like a blank blue map.

Here's my dependencies:

```
"react": "16.0.0",
"react-native": "0.50.3",
"react-native-maps": "^0.18.3",
```

I also had this issue when I was using `"react-native-maps": "^0.17.1"`.
