### ISSUE TITLE
React Native Maps removes somes packages upon installation, such as "babel-preset-react-native/configs/hmr"

### ISSUE THREAD

**Issue by Farzad7** [airbnb/react-native-maps#1454]
I installed a fresh copy of React Native and tested everything was working, JS Server was running fine too, but as soon as I installed react-native-maps, even before linking react-native with react-native-maps, everything broke and stopped working!

JS Server stopped working and the emulator showed the red error screen stating the development server cannot be found!

Installed another fresh copy and tested with other thirdparty react components and works fine, like the firebase etc.

React native version = 0.45, but also updated to 0.46 which it was just released but didn't made any difference
Node version = 8.1.3
NPM version = 5.0.3

So it is definitely react-native-maps that breaks things apart and everything stops working!
Hope someone could help
Thanks

**Comment by Farzad7** [comment]
After trying various things to install the missing packages such as the one mentioned above, the best work around this bug is to run >> npm install for 2 times and if nothing happened, shutdown your Android Studio and reopen it, then run >> npm start followed by >> npm install and this time it should be able to add 127 something files to your node_modules folder, mine worked, but I need to see if any map will be rendered on the screen or not!

**Comment by Farzad7** [comment]
Just wanted to keep you updated;

The problem occurred again despite all of that steps I undertook, so even if you follow the work around I mentioned above, it will still happen again

**Comment by Deevent** [comment]
The problem doesn't come from react-native-maps itself. It's actually NPM >= 5.0.0 that causes that. We opened various issues about that but never got an answer so I encourage you to switch to yarn or downgrade npm with `npm install -g npm@4.6.1`

**Comment by Farzad7** [comment]
Thank you for the reply, I downgraded my NPM to v4 but still happening... I go and reinstall everything and hopefully that will fix it, I'll update this issue in relate to this matter!
Thank you
