### ISSUE TITLE
Security concern about Google Map API

### ISSUE THREAD

**Issue by sandropoluan** [airbnb/react-native-maps#1461]
```
<application>
    <meta-data
      android:name="com.google.android.geo.API_KEY"
      android:value="Your Google maps API Key Here"/>
</application>
```
When we put our key to manifest file, is it possible someone can see and steal it?

**Comment by se1exin** [comment]
Only if you publish your manifest file to the public. You can overcome this by using manifest/gradle variables - see https://developer.android.com/studio/build/manifest-build-variables.html

**Comment by christopherdro** [comment]
Another option is to set it as a env variable that is injected during the build process of your CI.

In the end, there are ways to decompile your apk and retrieve the contents of the manifest so there is not real way to contain this information, just make it harder for people to get access.
