### ISSUE TITLE
App crash when add MapView.Marker

### ISSUE THREAD

**Issue by xmanemran** [airbnb/react-native-maps#1462]
Hi I am using `"react": "15.4.2"`, `"react-native": "0.42.3"`, and `"react-native-maps": "^0.15.2"`. When I try to add MapView.Marker, App crash. Here is my code.

    export default class Map extends Component {
        constructor(props) {
            super(props);
            this.state = {
                current: {},
                region: {
                    latitude: LATITUDE,
                    longitude: LONGITUDE,
                    latitudeDelta: LATITUDE_DELTA,
                    longitudeDelta: LONGITUDE_DELTA,
                },
                markers: [],
            };
        }
    
        onMapPress(e) {
            this.setState({
                markers: [
                    ...this.state.markers,
                    {
                        coordinate: e.nativeEvent.coordinate,
                        key: id++,
                        color: randomColor(),
                    },
                ],
            });
            window.alert(JSON.stringify({
                coordinate: e.nativeEvent.coordinate,
                key: id++,
                color: randomColor(),
            }));
        }
    
        componentWillMount(){
            navigator.geolocation.getCurrentPosition((success)=>{
                this.setState({
                    region: {
                        latitude: success.coords.latitude + 0.00050,
                        longitude: success.coords.longitude + 0.00050,
                        latitudeDelta: LATITUDE_DELTA ,
                        longitudeDelta: LONGITUDE_DELTA,
                    },
                    current: success.coords
                });
            },(error)=>{},  {enableHighAccuracy: true, timeout: 20000});
        }
    
        onRegionChange(region) {
            // this.setState({ region });
        }
    
        render() {
            return (
                <View style={styles.container}>
                    <TopBar title="SELECT LOCATION" navigator={this.props.route.data} navigation={[]}/>
                    <View style={styles.contentContainer}>
                        <MapView
                            onPress={this.onMapPress.bind(this)}
                            style={[styles.map]}
                            region={this.state.region}
                            onRegionChange={this.onRegionChange.bind(this)}
                        >
                            <MapView.Circle
                                center={this.state.region}
                                radius={50}
                                fillColor="rgba(255, 0, 0, 0.2)"
                                strokeColor="rgba(255,0,0,0.1)"
                                zIndex={2}
                                strokeWidth={2}
                            />
                            <MapView.Marker
                                key={1}
                                image={flag}
                                anchor={{ x: 0.5, y: 0.5 }}
                                coordinate={{ latitude: this.state.region.latitude, longitude: this.state.region.longitude }}
                                title={"This is title"}
                            />
    
                        </MapView>
                    </View>
                </View>
            );
        }
    }

**Comment by christopherdro** [comment]
What's the crash error?

**Comment by xmanemran** [comment]
No.I didn't. I was change the react-native version.

**Comment by tutak** [comment]
Make sure the Latitude and Longitude values passed to _coordinate_  props are Number and not String.

**Comment by Sidibedev** [comment]
thanks @tutak  that was my mistake ; i was passing strings.
