### ISSUE TITLE
OnMapReady callback render warning

### ISSUE THREAD

**Issue by petrovakd** [airbnb/react-native-maps#1466]
Hello! I'm trying to use this callback to show map preview if map is not ready.  I tried to call this function multiple ways, but non was successfull. 
...
hideMapPreview () {
    if (this.props.address.mapPreview) {
      this.props.hideMapPreview();
    }
  }
...
<MapView 
onMapReady={this.hideMapPreview} or onMapReady={() => this.hideMapPreview()}
>

do not trigger this function.

onMapReady={this.hideMapPreview()}  

shows warning "Cannot update during an existing state transition (such as within `render` or another component's constructor)"

But all of my callbacks here lead to rerender, like 

onPress={(e) => this.onMapPress(e)}
onRegionChange={(region) => this.props.setRegion(region)}

What is wrong?

**Comment by christopherdro** [comment]
The warning is not related to this library. 

It's possible that your setting state on a component as it unmounts, perhaps when you navigate to your map view.
