### ISSUE TITLE
when Map is first rendered Markers are being rendered in the middle of the screen

### ISSUE THREAD

**Issue by ElSadeq** [airbnb/react-native-maps#1468]
I have markers on different countries and places in the map. When the map first renders the Markers are being rendered in the middle of the screen until I zoom out. What is the solution for that? or how can I start the Map completely zoomed out?

**Comment by christopherdro** [comment]
@ElSadeq You'll have to set your `latitudeDelta` and `longitudeDelta` in your initial region or use available methods on MapView to auto fit to your markers.
https://github.com/airbnb/react-native-maps/blob/master/docs/mapview.md#methods

**Comment by ElSadeq** [comment]
@christopherdro Actually, I should've mentioned that I no matter what I changed with the latitudeDelta and longitudeDelta in the initial region the zooming didn't change.. although, markers where being rendered fine but this problem happened only when I mapped some markers..

**Comment by ElSadeq** [comment]
@christopherdro fitToSuppliedMarkers method did the job! thanks a lot.
