### ISSUE TITLE
MapView doesn't update coordinates

### ISSUE THREAD

**Issue by MichaelSzer** [airbnb/react-native-maps#1482]
I am trying to display the user initial location, so I am rendering <MapView>:

```
render() {

    console.log(this.state.initialPositionCoordinates.latitude);
    console.log(this.state.initialPositionCoordinates.longitude);
    return (

      <View style ={styles.container}>
        <MapView
          style={styles.map}
          initialRegion={this.state.initialPositionCoordinates}
          showsUserLocation={true}
          showsCompass={false}
          loadingEnabled={true} >
        </MapView>
      </View>
    );
  }
```
And then updating the State in componentDidMount():
`componentDidMount(){

    navigator.geolocation.getCurrentPosition( (position) => {

      var tempInitialPosition = JSON.parse(JSON.stringify(this.state.initialPositionCoordinates));

      tempInitialPosition.latitude = position.coords.latitude;
      tempInitialPosition.longitude = position.coords.longitude;

      this.setState({initialPositionCoordinates: tempInitialPosition});

    }, (error) => alert(error.message), {enableHighAccuracy: true} );

  }`

Each Console.log() runs twice and show the user location but the MapView doesn't update. It show's the position which was initialized the state.

**Comment by yonahforst** [comment]
@MichaelSzer - `getCurrentPosition` is asynchronous. It's possible that by the time the callback has fired, the `mapview` has already initialized with the original position from the state. Updating the initial position after the mapview has rendered will have no effect.

You can try putting this inside `getCurrentPosition` callback
```js
		       var mapRef = this.refs['mapView']

			mapRef && mapRef.animateToRegion({
				...position.coords,
				longitudeDelta: 0.005,
				latitudeDelta: 0.005,
			})
```

**Comment by MichaelSzer** [comment]
Thanks @yonahforst !
