### ISSUE TITLE
Click on map and get address

### ISSUE THREAD

**Issue by thomasbaldwin** [airbnb/react-native-maps#1487]
Is it possible to click on the map, and have a marker come up that shows the address of the area of the map that was just pressed? If not, is it possible to at least get the latitude / longitude and use google to do a look up?

Thanks for the help!

**Comment by zolrath** [comment]
Uning [onPress](https://github.com/airbnb/react-native-maps/blob/master/docs/mapview.md#events) on the map should give you the location you tapped.  
In the function you have it call you can create a marker and use [Google's Reverse Geocoding API
](https://developers.google.com/maps/documentation/javascript/examples/geocoding-reverse) to get the address at the tapped location.

**Comment by EhsanSarshar** [comment]
you can use '[react-native-geocoder](https://www.npmjs.com/package/react-native-geocoder)'

**Comment by Timon0305** [comment]
not working

**Comment by MohamedLamineAllal** [comment]
Here how you can access the cordinate on click

```tsx
const onLocationSelect = (event: MapEvent) => {
  console.log(event.nativeEvent.coordinate);
}

// ...

<MapView
  region={{
    ...location,
  }}
  onPress={onLocationSelect}
>
```

When you click onPress fire! And you get the event above!
