### ISSUE TITLE
i have an issue to link twitter signin in react native 

### ISSUE THREAD

**Issue by sandip7484** [airbnb/react-native-maps#1493]
![simulator screen shot 19-jul-2017 5 56 34 pm](https://user-images.githubusercontent.com/18194974/28366760-baa34466-6cab-11e7-98e6-30058086a1e3.png)

**Comment by sandip7484** [comment]
os: macOS
npm version: 3.10.10
node version: 6.11.0

**Comment by grigored** [comment]
what does this have to do with react-native-maps ?

**Comment by sandip7484** [comment]
i am connect to twitter signIn in react native so, i link react-native-twitter-signin package but simulater given above error

**Comment by sandip7484** [comment]
i just create twitter signIn in react native.

**Comment by vinagrito** [comment]
I don't see how this is related to this repo

@christopherdro I think this one can go

**Comment by christopherdro** [comment]
@vinagrito You're right.

@sandip7484 You can open up a ticket  on the libraries repo https://github.com/GoldenOwlAsia/react-native-twitter-signin
