### ISSUE TITLE
Error using newLatLngBounds(LatLngBounds, int, int, int): Map size can't be 0.

### ISSUE THREAD

**Issue by chapeljuice** [airbnb/react-native-maps#1501]
Anyone know what to look for here?

Getting this error:
<img width="558" alt="screen shot 2017-07-21 at 2 39 26 pm" src="https://user-images.githubusercontent.com/862642/28483498-6e3c1396-6e22-11e7-84bc-8c954c2bbf72.png">

Here's my component code:
```
import MapView from 'react-native-maps'
import styles from './Styles/SearchMapStyle'

class SearchMap extends React.Component {
  constructor (props) {
    super(props)
    this.state = {
      region: {
        latitude: 47.6062,
        longitude: 122.3321,
        latitudeDelta: 0.02,
        longitudeDelta: 0.02
      }
    }
  }

  render () {
    return (
      <View style={styles.container}>
        <MapView
          onPress={e => console.log(e.nativeEvent)}
          style={styles.map}
          provider='google'
          mapType='standard'
          showsScale
          showsCompass
          showsPointsOfInterest
          showsBuildings
          region={this.state.region}>
          <MapView.Marker
            title={this.props.title}
            coordinate={{
              latitude: this.state.region.latitude,
              longitude: this.state.region.longitude
            }} />
        </MapView>
      </View>
    )
  }

}

```

...and my styles:
```
import { Dimensions, StyleSheet } from 'react-native'
import { Colors, Metrics } from '../../Themes/'

const width = Dimensions.get('window').width
const height = Dimensions.get('window').height

export default StyleSheet.create({
  container: {
    flex: 1
  },
  map: {
    flex: 1,
    height: height,
    width: width
  }
})
```

...and finally, some environment info:
```
    "react": "^16.0.0-alpha.6",
    "react-native": "^0.44.0",
    "react-native-maps": "^0.15.2",
```

**Comment by igor90007** [comment]
same problem.

**Comment by luugiathuy** [comment]
@chapeljuice @igor90007 I also encountered this issue on Android. I think the problem is that you cannot render the markers when the map not finish its layout yet. I use the approach below to fix (reuse @chapeljuice code):

```
class SearchMap extends React.Component {
  constructor (props) {
    super(props)
    this.state = {
      isMapReady: false,
      region: {
        latitude: 47.6062,
        longitude: 122.3321,
        latitudeDelta: 0.02,
        longitudeDelta: 0.02
      }
    }
  }

  onMapLayout = () => {
    this.setState({ isMapReady: true });
  }

  render () {
    return (
      <View style={styles.container}>
        <MapView
          onPress={e => console.log(e.nativeEvent)}
          style={styles.map}
          provider='google'
          mapType='standard'
          showsScale
          showsCompass
          showsPointsOfInterest
          showsBuildings
          region={this.state.region}
          onLayout={this.onMapLayout}
        >
          { this.state.isMapReady &&
            <MapView.Marker
              title={this.props.title}
              coordinate={{
                latitude: this.state.region.latitude,
                longitude: this.state.region.longitude
              }} />
          }
        </MapView>
      </View>
    )
  }

}
```
I added a state called `isMapReady`, set it to `true` when the map finished its layout, and only render the markers when `isMapReady` is `true`. Hope it helps!

**Comment by igor90007** [comment]
@luugiathuy , thank you very much! Solved for me

**Comment by chapeljuice** [comment]
I'm not having this issue anymore so closing. Thanks for the reply!

**Comment by yairopro** [comment]
In order to use this solution automatically, I wrapped the map (RNMap here) with another component:
````
/**
 * This component wrap the map in order to automatically place its markers after onLayout callback.
 * @see https://github.com/react-community/react-native-maps/issues/1501
 */
export default class Map extends Component {
	constructor(){
		super();
		this.state = {ready: false};
	}

	render(){
		const props = this.props;

		// replace onLayout function
		const {onLayout} = props;
		props.onLayout = (...params) => {
			this.setState({ready : true});

			// pass params
			if (onLayout)
				onLayout(...params);
		};

		// set children only if map ready
		const {ready} = this.state;
		props.children = ready ? props.children : null;

		// callback to use instead of ref
		let {instance} = props;
		return <RNMap {...props} ref={map => {
			if (instance)
				instance(map);
		}}/>;
	}
}
````

Now that we know what's the problem exactly, this check should be implemented & handled by the library itself.
We shouldn't have to place an `onLayout` function, just to update a `boolean` in the state, and this for each time we use the Map component in our app.

**Comment by pennyloafers** [comment]
Instead of having a Boolean, you could begin rendering markers on componentDidMount. Solved my instance.

**Comment by SKempin** [comment]
Setting the map dimensions and rendering the markers only when the mapview was ready solved this for me:
https://github.com/react-community/react-native-maps/issues/842#issuecomment-419029045

**Comment by dodevski** [comment]
I have no markers on my map, but have `showsUserLocation={true}` and try to solve this issue with `boolean` in the state turned on `true` on `onLayout` event, but the issue is still here. Not always but every 3-4 time run the app. Any other solution?

**Comment by brien-crean** [comment]
This is also still happening for me on the latest release, not sure why this issue was closed. For me to fix it I had to put the MapView on the top level and give it a specific width and height (not percentages of a parent). It was previously nested within other components.

See this [comment](https://github.com/react-native-community/react-native-maps/issues/842#issuecomment-384335310) from  sarmad1995 which helped me

**Comment by zelenko** [comment]
The solution proposed by @luugiathuy is working, but I had to use `onMapReady` instead of `onLayout`

**Comment by brccabral** [comment]
```
    @Override
    public void onMapReady(GoogleMap googleMap) {
        mMap = googleMap;
        //***
        //***
        mMap.setOnMapLoadedCallback(new GoogleMap.OnMapLoadedCallback() {
            @Override
            public void onMapLoaded() {
                mMap.moveCamera(CameraUpdateFactory.newLatLngBounds(builder.build(), padding));
            }
        });
    }
```

**Comment by JorgeValdes** [comment]
la solucion propuesta por  @luugiathuy es funcionando muchas gracias
