### ISSUE TITLE
Need help to change markers based on horizontal scrolling on list.

### ISSUE THREAD

**Issue by AkshayKomarla** [airbnb/react-native-maps#1505]
![selection_049](https://user-images.githubusercontent.com/15768487/28511328-5a984630-706a-11e7-8fec-34127ec7bc95.jpg)

i need to highlight the marker based on the corresponding restaurant selected in the horizontal list.

any tips or example code to achieve this would be a great help.

Thanks.

**Comment by chris-at-translate** [comment]
GitHub issues are for issues relating to the repo/library itself, post this on StackOverflow to get tailored help.
