### ISSUE TITLE
Geojson and fill color

### ISSUE THREAD

**Issue by alexaung** [airbnb/react-native-maps#1509]
I am using react-native-maps with geojson. My json have 14 state (region). It is show on map but I would like to show different color for each state. My geojson already had a fill color and stroke color but it is not show on map. May I know how can I add the color for each region.

Thanks.

**Comment by alexaung** [comment]
Ok, I can managed to solved it. added the fill color in <MapView.Polygon />

**Comment by nc3816** [comment]
Hi @alexaung, I have the same issue. May you provide your code sample so that I could know how to put it in my code. Thank you!

**Comment by doguinho** [comment]
I have the same problem and tried to use Polygon but they are showing in the middle of the ocean. When I was using <Geojson> everything was ok.
