### ISSUE TITLE
can't build on android

### ISSUE THREAD

**Issue by andrzli** [airbnb/react-native-maps#1516]
Hey guys, I'm having an issue building this for Android (iOS seems to work fine). my package.json looks like:
```
    "react": "16.0.0-alpha.12",
...
    "react-native": "^0.46.4",
...
    "react-native-maps": "^0.15.3",
```

when I run `react-native run-android` however, I get the following error:

```* Where:
Script 'PROJECT_DIR/node_modules/react-native-maps/lib/android/gradle-maven-push.gradle' line: 43

* What went wrong:
A problem occurred configuring project ':app'.
> A problem occurred configuring project ':react-native-maps'.
   > Failed to notify project evaluation listener.
      > gradle_maven_push_ajdkud73yn42oc9wixuxzv1mx$_run_closure1$_closure2```

**Comment by christopherdro** [comment]
What installation steps did you follow? Did you do manual setup or use `link`?

What's on `gradle-maven-push.gradle' line: 43`?

**Comment by andrzli** [comment]
I used link. Weird thing is I've just tried it again and it works without any changes. Only thing different was that I closed down Android studio..
