### ISSUE TITLE
[iOS] Not compatible with latest RN-0.47

### ISSUE THREAD

**Issue by vongohren** [airbnb/react-native-maps#1520]
Im running RN 0.47, and now im getting

```The following build commands failed:
CompileC /Users/snorreedwin/Code/entur/entur-clients/native/ios/build/Build/Intermediates/Pods.build/Debug-iphonesimulator/react-native-maps.build/Objects-normal/x86_64/AIRMapCircleManager.o 
/Users/snorreedwin/Code/entur/entur-clients/native/node_modules/react-native-maps/lib/ios/AirMaps/AIRMapCircleManager.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler```

I had the same problem with "react native vector icons" but I upgraded to newest release because it
seems like react native vector icons have done a fix to support 0.47, but cant pin point what the fix was.

**Comment by ericlewis** [comment]
This also occurs on Android, it seems the problem is removal of unused createJSModules at least for android. FWIW, I am running 0.47 + react-native-maps perfectly fine on the iOS 11 sim.

**Comment by vongohren** [comment]
Thanks for the feedback, but I believe the root cause here is that we are running swift as app language, which means that we get extra problems. Writing over now.

**Comment by andrelramos** [comment]
+1

**Comment by peter-pogocarshare** [comment]
I'm also getting this error with Android with several react native modules.

`.../react-native-maps/lib/android/src/main/java/com/airbnb/android/react/maps/MapsPackage.java:27: error: method does not override or implement a method from a supertype
  @Override
  ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
:react-native-maps:compileReleaseJavaWithJavac FAILED`

**Comment by connected-space** [comment]
@peter-pogocarshare I had the same problem but fixed it by commenting out the `@Override` on line 27 in MapsPackage.java. Only a temp fix because this will be removed when node modules are reinstalled.

**Comment by connected-space** [comment]
@peter-pogocarshare react-native-maps 0.16.0 was pushed a few hours ago which fixes the issue.

**Comment by vongohren** [comment]
We moved away from cocoapods and swift, to just cocoapods and Objective-C. It fixed it, so closing this.
