### ISSUE TITLE
[Android] Issue with React Native 0.47

### ISSUE THREAD

**Issue by oatcrunch** [airbnb/react-native-maps#1523]
![android error - rn0 47 with react native map](https://user-images.githubusercontent.com/16144992/28859704-80b90412-778b-11e7-9860-4a8e2a26428c.jpg)
It seems like something is breaking in latest release of react native maps. It does not work on RN0.47 with "react-native run-android" on Windows 7 platform. Refer attached for details.

**Comment by richardcase** [comment]
I'm also seeing this error

**Comment by jeveloper** [comment]
There is a commit that allegedly fixes this , but you'll need to pull from the master, no idea when they'll cut a release

**Comment by emilbaekdahl** [comment]
Using the `master` branch works for me though an error related to `react-native-maps`  `.babelrc` comes up which can be fixed buy adding `babel-plugin-module-resolver` as a development dependency.

**Comment by kelset** [comment]
It has been [fixed on master](https://github.com/airbnb/react-native-maps/commit/1db4fffcea370781bf625ab5632e8bb7a49203e4) but a new release is needed.

**Comment by itsmepetrov** [comment]
@christopherdro please release the new version on npm with this fix

**Comment by christopherdro** [comment]
https://github.com/airbnb/react-native-maps/releases/tag/v0.16.0

**Comment by itsmepetrov** [comment]
@christopherdro thanks a lot

**Comment by 3210jr** [comment]
Im getting a similar issue, in my case whenever the <MapView /> component is placed on the view, the app just simply crashes without any errors. Any ideas?
