### ISSUE TITLE
Clicking on a Marker doesn't make the Callout visible on all sides

### ISSUE THREAD

**Issue by zakster12** [airbnb/react-native-maps#1534]
I have a marker/pin and when the user clicks on it the callout should be positioned visible on every side otherwise it can't be read if the user doesn't scroll to make it visible. It works on Android out of the box but doesn't work on iOS  although I am using Google Maps. Any ideas?

**UPDATE**: With AirMap it works as expected but with Google Maps the callout is not moved to be visible.

On Android this centering is happening automatically but on iOS I should manually scroll the map to center the marker and callout.

**Comment by foyarash** [comment]
To handle this on iOS, you could handle the onPress on a marker and use animateRegion to the coordinates of this marker

**Comment by zakster12** [comment]
@foyarash Yes I did it exactly in this way. Using:
`this.map.animateToCoordinate(coordinates, 1500);`
