### ISSUE TITLE
Change Map Marker Based on Zoom Level

### ISSUE THREAD

**Issue by benjdlambert** [airbnb/react-native-maps#1537]
hey!

This is more of a question than a problem - just wondered if it's currently possible.

Is there current functionality to get the zoom level so we can change the map marker style when you zoom on the map?

Our use case is that we want to change the scale of the `.Marker` when you zoom out, instead of clustering.

Any help welcome!

/blam

**Comment by isener** [comment]
It called 'Image Overlay' or 'Ground Overlay' on Google Maps which react-native-maps currently doesn't have. But one guy did it for iOS and I used with AirGoogleMaps on iOS, it works successfully. Now I'm researching to do same on Android, if you find, call us here please.

I'm putting it here for iOS (Don't forget to use on AirGoogleMaps, Mapkit doesn't work correctly);
#1359

**Comment by pellepersson** [comment]
Hello!

In our application, we have solved a similar problem by render different markers depending on the latitudeDelta of the map region. 

```
function renderCustomMarker(point, region) {
  if (region.latitudeDelta > MIN_DELTA_FOR_CIRCLE_MARKER) {
    renderCircle(point);
  } else {
    renderPinMarker(point);
  }
}

```

This should be quite easy to modify to set the height and width on a marker depending on the delta...

**Comment by benjdlambert** [comment]
Aha! I forgot about the delta! That will do! Thanks @pellepersson

**Comment by Sathiyamm** [comment]
Hi @benjdlambert  , How to you fix the zoom level in different region the map marker? 
How to set the zoom level in multiple map markers and different regions ? Help @benjdlambert and @pellepersson

**Comment by pellepersson** [comment]
@Sathiyamm - I am afraid that I do not understand the question? The solution I posted above shows how to call different render methods for different latitude deltas on the map. The latitude delta (distance between to different latitude values) is one way of expressing zoom level". Is this what you are asking for or do you want something else?

**Comment by Sathiyamm** [comment]
@pellepersson -I do not understand the your function. I have multiple location marker in different region. So how to i set the zoom level?

**Comment by pellepersson** [comment]
@Sathiyamm  - still don't understand what you are after. Do you want to change the looks of your markers depending on the zoom level of your map or is it something else you want to do?

**Comment by Sathiyamm** [comment]
@pellepersson -yes i want to change the looks of my markers depending on the zoom level of my map.

**Comment by Sathiyamm** [comment]
@pellepersson -Are you help me ?

I'm set the region value

this.setState({
                    region:{
                        latitude: responseData[0].originLatitude,
                        longitude: responseData[0].originLongitude,
                        latitudeDelta: 0.0922,
                        longitudeDelta: 0.0421
                    }
                });

and map view 

 <MapView  ref="map"  style={styles.map}   region={this.state.region} >
<MapView.Marker key={taskDetail.id} 
                  coordinate={
                                    {
                                        latitude: taskDetail.originLatitude,
                                        longitude: taskDetail.originLongitude
                                    }
                                     
                                }
                                
                            > </MapView.Marker></MapView>

**Comment by pellepersson** [comment]
@Sathiyamm - alright. I think that what you need to do is to pass your own marker as a child to <MapView.Marker>:

```
<MapView.Marker coordinate={marker.latlng}>
  <CustomMarker {...marker} />
</MapView.Marker>
```
and then based on a condition on your region.latitudeDelta in your CustomMarker render the different layouts for the marker... A smaller latitudeDelta means that your map is more zoomed in... Hope this helps...

**Comment by ronakjain-2** [comment]
Hi @benjdlambert 

I have faced the same requirement as you. I found a solution like:

<MapView ref={ref => { this.storeMap = ref; }}
intialRegion={this.state.region}
zoomControlEnabled={true}
onRegionChangeComplete={(region)=>this.onRegionChangeComplete(region)}>

onRegionChangeComplete=(region)=>{
     const northBoundary = region.latitude + region.latitudeDelta/2
     const eastBoundary = region.longitude + region.longitudeDelta/2
     const southBoundary = region.latitude - region.latitudeDelta/2
     const westBoundary = region.longitude - region.longitudeDelta/2
     const filteredStore = filter(this.state.storeLatLong, (store) => {
            return inRange(store.latitude, southBoundary, northBoundary) && inRange(store.longitude, eastBoundary, westBoundary)
})
console.log(filteredStore)
}

 - filter and inRange are functions of lodash library.
 - this.state.storeLatLong is my location array
