### ISSUE TITLE
Map resets to initialRegion when moving with fast gestures on the map

### ISSUE THREAD

**Issue by pellepersson** [airbnb/react-native-maps#1540]
I have got a weird issue since my last updates.

When trying to zoom or change position fast by dragging the map around or pinching, the map resets to the initialRegion. If I do the same thing but very slow, it works as expected.

Trying to run this in the iOS simulator.

My map code is very simple so I do not understand what could go wrong:

```
<MapView
            key={'initial-map'}
            style={styles.map}
            initialRegion={this.props.startRegion}
/>
```

Versions:
"react-native":  "0.47.1",
"react-native-maps": "0.16.0",

**Comment by foyarash** [comment]
I posted a workaround here https://github.com/airbnb/react-native-maps/issues/1507

But if you have a native solution you should post a PR !

**Comment by pellepersson** [comment]
@foyarash - haha you've got me a bit confused regarding your workaround. :)

Anyways... It seems like what you have done is changed the name on the parameters in the method RCT_CUSTOM_VIEW_PROPERTY. I have not had time to look into if that is the method that need changes, but it seems like we need to change what is sent to the method rather than its internal parameter names, right?

**Comment by foyarash** [comment]
Well i'll try to explain.

For what I understood after some searches, it seemed like the setInitialRegion method was never called. This was a simple property, which you can find the definition in AIRMapManager.m. But I noticed that instead of setInitialRegion being called, the setRegion was called, and it was called by all the instructions we can find in the definition of the region property (still in AIRMapManager.m), as I do not have any region property in my MapView definition. So what I've tried to do in the first place was to just copy/paste the definition of region property, and just replace the variable name, and the call to setRegion by setInitialRegion, which is what I describe in my workaround trial. But it never worked because, apparently, the value of the property is "nil". So as a temporary working workaround, my solution was just to replace setRegion by setInitialRegion in the region property definition.

Hope it is more clear for you

**Comment by pellepersson** [comment]
@foyarash - by looking at the history of **AirMapManager.m** I can not see that any changes has been done lately regarding **setRegion** or **setInitialRegion**. I have been using react-native-maps for over a year and since I found this bug after my latest updates, I believe that there must be something changed recently that is the reason for this behaviour.

I also found that if I comment out the code on row 453 in **"lib/components/MapView"**:
`//this.map.setNativeProps({ region: initialRegion });`
, the map will not reset to initialRegion anymore. That makes me think that "setInitialRegion" on the iOS native side actually gets called as it should, but for some reason it gets called a bit too often.

**Comment by foyarash** [comment]
Oh well ok maybe the problem just comes from this line, because here, from what I understand, it will actually set the region but not the initialRegion property on the native side.

But what is weird is that initialRegion perfectly works for Android

**Comment by pellepersson** [comment]
@foyarash - maybe it has something to do with changes regarding how React Native for iOS updates and renders things in newer versions? Which version on react-native and react-native-maps are you using? And what navigation solution are you using? I am a bit surprised that not more people have reported the same issue, which makes me think that it could be something with the combination of libraries and versions in my setup.

I changed the code a bit in **"lib/components/MapView.js"** and now it seem to work. It is not at all a pretty solution and I hope that someone could come up with something better:

`   componentDidMount() {
    const { isReady } = this.state;
    if (isReady) {
      this._updateStyle();
    }

    if (Platform.OS === 'ios' && this.props.initialRegion) {
      this.map.setNativeProps({ region: this.props.initialRegion });
    }
  }`

`
  _onMapReady() {
    const { region, initialRegion, onMapReady } = this.props;
    if (region) {
      this.map.setNativeProps({ region });
    } else if (Platform.os === 'android' && initialRegion) {
      this.map.setNativeProps({ region: initialRegion });
    }
    this._updateStyle();
    this.setState({ isReady: true }, () => {
      if (onMapReady) onMapReady();
    });
  }
`

**Comment by foyarash** [comment]
Using RN 0.46 and RN Maps 0.16, no navigation solution.

**Comment by valeryq** [comment]
I have the same behaviour. 

Platform: IOS only (emulator)
React Native: 0.47.1
React Native Maps: 0.16.0

**Comment by Metroninja** [comment]
I think there are enough +1's but I'm facing this issue as well 
Platform: IOS only (emulator)
React Native: 0.47.1
React Native Maps: 0.16.0

**Comment by foyarash** [comment]
@Metroninja are you talking about @pellepersson 's fix or my PR?

**Comment by mtt87** [comment]
+1 hour wasted here 😢 

RN 0.47.1
react-native-maps 0.16.0

What is exactly the temporary workaround?

Thanks everybody

**Comment by Metroninja** [comment]
@foyarash  - pellepersson fix.  I'll attempt yours now.

**Comment by mtt87** [comment]
@pellepersson tried your fix but doesn't seem to work for me, I still get the issue when moving "fast" the map 😞

**Comment by foyarash** [comment]
@mtt87 can you try my fix and tell me if it works ?

**Comment by mtt87** [comment]
@foyarash sure but I don't fully understand which fix are you talking about?

here you say it doesn't work so I didn't try.
https://github.com/airbnb/react-native-maps/issues/1507#issuecomment-320705885

Please tell exactly what I should try and I'll do it now with pleasure 😄

**Comment by foyarash** [comment]
@mtt87 this https://github.com/airbnb/react-native-maps/pull/1546 :)

**Comment by Metroninja** [comment]
@foyarash - I tried your fix, it actually doesn't work for me only @pellepersson fix works.  With just yours the map switches to SanFran and WOULD zoom all the way out except I'm blocking that with an
```
  onRegionChange(region){
    if(region.latitudeDelta < 30) {
      this.setState( region );
    }
  }
```

**Comment by foyarash** [comment]
That's weird, it perfectly works for me. Are you sure you are using initialRegion property?

**Comment by Metroninja** [comment]
Yes, if I don't use it the new fix doesn't work

**Comment by mtt87** [comment]
I think there is a bit of confusion here and 2 separate issues:

1) the map zooming totally out 
2) when moving fast the map it goes back to the previous region

@Metroninja seems like you are talking more about the first issue while we are talking about the second one?

**Comment by mtt87** [comment]
@foyarash at this point I think you are talking about the first issue as well
the map zooming totally out and setting a `initialRegion` different than the one that's supposed to be.

The issue here should be **Map resets to initialRegion when moving with fast gestures on the map**

It's the fast gestures moving/zooming the main problem.

For your issue there is a workaround, start with a state with `regionSet: false` and prevent region change if that's false. Then as soon as the map has completely loaded you can `this.setState({ regionSet: true })`
```js
region={this.state.region}
onRegionChangeComplete={(region) => {
  if (this.state.regionSet) {
    this.setState({ region });
  }
}}
onMapReady={() => {
  this.setState({ regionSet: true });
}}
```

**Comment by foyarash** [comment]
@mtt87 my PR is actually supposed to fix the map resetting to initialRegion :)

What i can propose to fix the zoom issue is to simply limit the zoom using the minZoomLevel and maxZoomLevel properties

**Comment by Metroninja** [comment]
@mtt87 should we cut a new issue for map resetting to default region and zooming all the way out?

**Comment by mtt87** [comment]
I'm in bed now from the phone :) there is already an issue for that problem I can link it to you tomorrow morning.

I'm a bit sad that out of all the packages that I used in 1.5yr of React native this one has always been the most problematic and full of bugs (still unresolved) despite being "maintained" by Airbnb which supposedly has some engineer time to dedicate to it...

**Comment by pellepersson** [comment]
Yes there seem to be some confusion here. I do not recognize the zoom thing described and do not know if it has anything to do with the main issue of this thread. 

The PR that @foyarash is referring to seem to be the same as the ugly fix I have posted above, except that by not adding the platform specific conditions - at least my - android application will crash.

I am not satisfied with the ”fix” I have posted since it changes rows of code in this library that has been there for many months, which feels like trying to heal something without knowing getting to the bottom of the problem.

**Side note (not about this issue):**
@mtt87 - I have also had my share of hours spent on making this library work, but I believe that the complexity of the needs that this library solves still makes me very greatful for its existence. I could not use react native for my application without it. It is open source so everyone is free to contribute to make it better if they have the time and skills to do so.

**Comment by mtt87** [comment]
@pellepersson I see your point, and I don't wanna sound arrogant or ungrateful for an open source project but I personally think there is a big difference between an open source project with a single/few maintainer that are doing this in their spare time and an open source project backed by a big company (Airbnb in this case) which is "supposedly" allocating engineer time.

I personally don't accept and I think it's what actually kills open source, the fact that this project is almost abandoned and there are 37 open PR of people that spent time to contribute and most of them are not even reviewed.

Maps was a package that was initially maintained by the React Native team of Facebook then they saw Airbnb released this package with many features and decided to stop maintaining their basic implementation and remove it from the RN core.

The result is that we have this buggy packge that in the past 9 months just accumulated issues and unreviewed PR.

I'm sorry but this to me looks like "hey look how cool we are at Airbnb we support React Native and we wanna help the community maintaining react-native-maps, come work with us 😄 "

This is the next generation brand marketing for their engineering teams.

**Comment by pellepersson** [comment]
@christopherdro - have you read the comments above before closing this issue? The fix that you have marked as the solver will probably break the app for android users. So have you really tested this? I do not consider #1546 a solution for this.

**Comment by christopherdro** [comment]
This issue was auto closed from the comment left in the PR that was merged.

**Comment by christopherdro** [comment]
The fix, or change in the PR that was merged may not apply to this pull request but I believe it is the correct implementation. 

What will cause this to break for Android users?

**Comment by pellepersson** [comment]
@christopherdro - I am sorry. My bad! It actually seem to work fine now with #1546. My app must have been in some "in-between-state" where initialRegion was not set on my android and got the app to crash when I tested it out before. It makes @foyarash solution better than my "ugly fix" above. 

I am still curious about how this seem to just be a problem with alter versions of RN and react-native-maps, since the code we change here has not been changed for quite a while before this...

**Comment by lalosh** [comment]
As for Android I had the same issue until as @mtt87 mentioned I used
                    onRegionChangeComplete={this.onRegionChange}
instead of
                    onRegionChange={this.onRegionChange}
And everything works excellent now.. Thank You!

**Comment by nc3816** [comment]
Hi, I meet the same issues, but only happens on Android 8.
For Android 7 and below, it works well.
Any suggestion about how to fix android 8?
Thank you very much!

**Comment by nc3816** [comment]
@mtt87 Hi, I tried your solution, it works for Android7 and below, but on Android 8, it doesn't work. Do you have some suggestions? Thank you!

**Comment by mtt87** [comment]
Unfortunately after many issues with this package I moved to mapbox

**Comment by RobinTack** [comment]
> 
> 
> As for Android I had the same issue until as @mtt87 mentioned I used
> onRegionChangeComplete={this.onRegionChange}
> instead of
> onRegionChange={this.onRegionChange}
> And everything works excellent now.. Thank You!

This seems to work for me, thanks a lot!

**Comment by NitinBag0riya** [comment]
Well, it needs to change `initialRegion` on `onRegionChangeComplete` so that map view can stick with the update region.

**Comment by abhaysoftskill** [comment]
A simplest way we can use **useDebouncedCallback**
