### ISSUE TITLE
Blank map in iOS

### ISSUE THREAD

**Issue by sambit-112081** [airbnb/react-native-maps#1543]
Thanks for the tutorial. This tutorial is awesome. But i have one issue.
I am trying to integrate map in iOS. 
I followed all the installation instruction for iOS. 
But every time i am trying to render the map view, only thing, I am able to see a blank map with red border around it. I have also checked the react-native-link and there is no issue with it.   
Please let me know, if is there any solution for this. 

More Information : 
React-native-maps 0.13.0
React-native 0.44.0

Thanks

**Comment by jeveloper** [comment]
Hi

Test this: add height and width to the view where the map is. 
I assume you're using apple map on ios , not google.

use the latest first version first of all, 0.16.0

**Comment by SambitPrakash** [comment]
Hello @jeveloper , thanks for your reply. I upgrade react-native-map version to 0.16.0 
but no luck for me. 
Also I tried to use google map. and followed all the steps as given in instruction. finally i got some error message. Please check the below screen shot. 

![simulator screen shot 11-aug-2017 12 53 39 pm](https://user-images.githubusercontent.com/22074730/29204369-33e74dbe-7e94-11e7-8941-23ee4c482d10.png)

I went through the path specified in the error. but react-native.js is present in that directory. 
Please let me know, if i am going wrong something.

**Comment by jeveloper** [comment]
strange error, i would assume that the issues is caching of modules , id suggest start in a new directory and also use RN 47 , btw linking libraries doesnt always work, your xcode workspace can confirm if the the libraries are truly linked.

**Comment by christopherdro** [comment]
@sambit-112081 Blank map with red border = bad api key

**Comment by SambitPrakash** [comment]
@jeveloper, I changed react native version to 0.47.0 and map version to 0.16.0. 
Now its working fine for me.

**Comment by jeveloper** [comment]
Fantastic ! , i suspect break changes prevented it from loading , RN had changed a bunch of things between 44 and 47
