### ISSUE TITLE
Cannot run example project by following instructions

### ISSUE THREAD

**Issue by ansonyao** [airbnb/react-native-maps#1548]
According to https://github.com/airbnb/react-native-maps/blob/master/docs/examples-setup.md.,
I cd to the folder and then run:
react-native run-android

It says: Command `run-android` unrecognized. Make sure that you have run `npm install` and that you are inside a react-native project.

I tried 'npm install', it works. Then I typed react-native run-android. Still the above message. Any ideas on what is missing?

**Comment by victorbadila** [comment]
+1 also getting this

**Comment by dk0r** [comment]
See #1659

**Comment by techwes** [comment]
I am getting the same thing and am also unable to run on iOS. Followed the directions exactly for each. On iOS I get:
```
ld: warning: directory not found for option '-L/Users/wesley/Library/Developer/Xcode/DerivedData/AirMapsExplorer-baiztxkzjiwcksawuesugggohalq/Build/Products/Debug-iphonesimulator/React'
ld: warning: directory not found for option '-F/Users/wesley/react-native-maps/example/ios/build/Debug-iphoneos'
ld: library not found for -lReact
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
when trying to run in XCode
