### ISSUE TITLE
[ANDROID] react-native 0.47 keeps crashing. no errors.

### ISSUE THREAD

**Issue by 3210jr** [airbnb/react-native-maps#1553]
I'm getting a weird error... whenever the <MapView /> component is placed on the view, the app just simply crashes without any errors. It just says "App has stopped"... Any ideas?

Here are my packages:

react = "16.0.0-alpha.12",
react-native = "0.47.1",
react-native-firebase = "^2.1.2",
react-native-maps = "^0.16.0"

Thanks.

**Comment by christopherdro** [comment]
Are you building your project through Android Studio? You should be able to see the crash report through the monitor. If not, then run `adb logcat` and see if you can track down the native crash and report back here.

**Comment by 3210jr** [comment]
Thanks @christopherdro , I have just fired up the app again and with the `<MapView />` it works just fine, the moment I uncomment the code and hit reload, it breaks with the following log:
`
08-15 19:58:11.145  2361  2886 I ReactNativeJS: Running application "app" with appParams: {"rootTag":1}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
08-15 19:58:11.453  2361  2887 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactVirtualTextShadowNode
08-15 19:58:13.877  2361  2887 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.airbnb.android.react.maps.SizeReportingShadowNode
08-15 19:58:13.899  2361  2361 E UncaughtException: 
08-15 19:58:13.899  2361  2361 E UncaughtException: java.lang.AbstractMethodError: abstract method "void com.google.android.gms.dynamic.zza.zza(com.google.android.gms.dynamic.zzo)"
08-15 19:58:13.899  2361  2361 E UncaughtException: 	at com.google.android.gms.dynamic.zza.zza(Unknown Source)
08-15 19:58:13.899  2361  2361 E UncaughtException: 	at com.google.android.gms.dynamic.zza.onCreate(Unknown Source)
08-15 19:58:13.899  2361  2361 E UncaughtException: 	at com.google.android.gms.maps.MapView.onCreate(Unknown Source)
08-15 19:58:13.899  2361  2361 E UncaughtException: 	at com.airbnb.android.react.maps.AirMapView.<init>(AirMapView.java:129)
08-15 19:58:13.899  2361  2361 E UncaughtException: 	at com.airbnb.android.react.maps.AirMapManager.createViewInstance(AirMapManager.java:60)
08-15 19:58:13.899  2361  2361 E UncaughtException: 	at com.airbnb.android.react.maps.AirMapManager.createViewInstance(AirMapManager.java:27)
08-15 19:58:13.899  2361  2361 E UncaughtException: 	at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:46)
08-15 19:58:13.899  2361  2361 E UncaughtException: 	at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:218)
08-15 19:58:13.899  2361  2361 E UncaughtException: 	at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:150)
08-15 19:58:13.899  2361  2361 E UncaughtException: 	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:923)
08-15 19:58:13.899  2361  2361 E UncaughtException: 	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:895)
08-15 19:58:13.899  2361  2361 E UncaughtException: 	at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:31)
08-15 19:58:13.899  2361  2361 E UncaughtException: 	at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:136)
08-15 19:58:13.899  2361  2361 E UncaughtException: 	at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:107)
08-15 19:58:13.899  2361  2361 E UncaughtException: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:885)
08-15 19:58:13.899  2361  2361 E UncaughtException: 	at android.view.Choreographer.doCallbacks(Choreographer.java:689)
08-15 19:58:13.899  2361  2361 E UncaughtException: 	at android.view.Choreographer.doFrame(Choreographer.java:616)
08-15 19:58:13.899  2361  2361 E UncaughtException: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:873)
08-15 19:58:13.899  2361  2361 E UncaughtException: 	at android.os.Handler.handleCallback(Handler.java:751)
08-15 19:58:13.899  2361  2361 E UncaughtException: 	at android.os.Handler.dispatchMessage(Handler.java:95)
08-15 19:58:13.899  2361  2361 E UncaughtException: 	at android.os.Looper.loop(Looper.java:173)
08-15 19:58:13.899  2361  2361 E UncaughtException: 	at android.app.ActivityThread.main(ActivityThread.java:6523)
08-15 19:58:13.899  2361  2361 E UncaughtException: 	at java.lang.reflect.Method.invoke(Native Method)
08-15 19:58:13.899  2361  2361 E UncaughtException: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:938)
08-15 19:58:13.899  2361  2361 E UncaughtException: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:828)
08-15 19:58:14.227  2361  2361 E AndroidRuntime: FATAL EXCEPTION: main
08-15 19:58:14.227  2361  2361 E AndroidRuntime: Process: com.app, PID: 2361
08-15 19:58:14.227  2361  2361 E AndroidRuntime: java.lang.AbstractMethodError: abstract method "void com.google.android.gms.dynamic.zza.zza(com.google.android.gms.dynamic.zzo)"
08-15 19:58:14.227  2361  2361 E AndroidRuntime: 	at com.google.android.gms.dynamic.zza.zza(Unknown Source)
08-15 19:58:14.227  2361  2361 E AndroidRuntime: 	at com.google.android.gms.dynamic.zza.onCreate(Unknown Source)
08-15 19:58:14.227  2361  2361 E AndroidRuntime: 	at com.google.android.gms.maps.MapView.onCreate(Unknown Source)
08-15 19:58:14.227  2361  2361 E AndroidRuntime: 	at com.airbnb.android.react.maps.AirMapView.<init>(AirMapView.java:129)
08-15 19:58:14.227  2361  2361 E AndroidRuntime: 	at com.airbnb.android.react.maps.AirMapManager.createViewInstance(AirMapManager.java:60)
08-15 19:58:14.227  2361  2361 E AndroidRuntime: 	at com.airbnb.android.react.maps.AirMapManager.createViewInstance(AirMapManager.java:27)
08-15 19:58:14.227  2361  2361 E AndroidRuntime: 	at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:46)
08-15 19:58:14.227  2361  2361 E AndroidRuntime: 	at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:218)
08-15 19:58:14.227  2361  2361 E AndroidRuntime: 	at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:150)
08-15 19:58:14.227  2361  2361 E AndroidRuntime: 	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:923)
08-15 19:58:14.227  2361  2361 E AndroidRuntime: 	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:895)
08-15 19:58:14.227  2361  2361 E AndroidRuntime: 	at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:31)
08-15 19:58:14.227  2361  2361 E AndroidRuntime: 	at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:136)
08-15 19:58:14.227  2361  2361 E AndroidRuntime: 	at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:107)
08-15 19:58:14.227  2361  2361 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:885)
08-15 19:58:14.227  2361  2361 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:689)
08-15 19:58:14.227  2361  2361 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:616)
08-15 19:58:14.227  2361  2361 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:873)
08-15 19:58:14.227  2361  2361 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
08-15 19:58:14.227  2361  2361 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
08-15 19:58:14.227  2361  2361 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:173)
08-15 19:58:14.227  2361  2361 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6523)
08-15 19:58:14.227  2361  2361 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-15 19:58:14.227  2361  2361 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:938)
08-15 19:58:14.227  2361  2361 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:828)
08-15 19:58:14.264  2361  2899 I FirebaseCrash: Sending crashes
08-15 19:58:14.798  2361  2899 I FirebaseCrash: Response code: 200
08-15 19:58:14.799  2361  2899 I FirebaseCrash: Report sent with crash report id: ae8a8472b0000000
08-15 19:58:15.047  3758  3784 E [B+]HtcProcessObserver:  ERROR: Failed to find any Process info!!! - onProcessStateChanged(): pid=2361, uid=10186, state=PROCESS_STATE_CACHED_EMPTY: {16 (0x10)}, importance=IMPORTANCE_BACKGROUND: {400 (0x190)}.
`

I am running the project from the terminal, running it on my android 7.0 device.

Thanks again!

**Comment by 3210jr** [comment]
I found a similar issue at [https://github.com/airbnb/react-native-maps/issues/1408](https://github.com/airbnb/react-native-maps/issues/1408) and was able to find the solution there as well! Thanks!
