### ISSUE TITLE
initialRegion is not updated properly when getting the addresses from json

### ISSUE THREAD

**Issue by krishbhattacharyya** [airbnb/react-native-maps#1565]
**Environment**
react-native: 0.47.1
node 7.9.0
react-native-maps ^0.16.0

**Target Platform:** Android

**Development Operating System:** Linux ( Ubuntu )

**Steps to Reproduce**
After updating the markers in the map, initialRegion does not take the updated defined position. 

**Expected Behavior**
initialRegion should be updated with the updating value.

**Actual Behavior**
initialRegion keeps the initial value.

**Extra info:**
Getting the lat long from addresses with this api using fetch ( markers are rendering properly )-
`'https://maps.googleapis.com/maps/api/geocode/json?address=' + val`

For the region I am using - 
getRegionForCoordinates function from the given url
https://github.com/airbnb/react-native-maps/issues/505

**Comment by foyarash** [comment]
I guess this is related to https://github.com/airbnb/react-native-maps/issues/1559

Should be fix in https://github.com/airbnb/react-native-maps/pull/1563

**Comment by krishbhattacharyya** [comment]
@foyarash . I think this is not the same issue. In the android it is working fine( real device but not working on the emulator). But need a method that refresh the mapview basically  **initialRegion**.

**Comment by foyarash** [comment]
So what you actually want to do is being able to change the initialRegion value am I correct?

If so, this is not possible, you should use region property

**Comment by krishbhattacharyya** [comment]
My Apologies ! @foyarash I think I missed one point in the document **Zoom to Specified Coordinates**. This can help me. If that I will close this issue please give me some time.

**Comment by krishbhattacharyya** [comment]
@foyarash, now I am in some steps ahead. I got some solution for now but I think very soon I can close this issue. please have a look this issue. I have mentioned here some temporary solution.

The issue is like this- https://github.com/airbnb/react-native-maps/issues/1149.

**Comment by krishbhattacharyya** [comment]
Now this is working as per my requirement but two issues is there-

1) Animation has taken time to reach the destination of region.

2) '1600 Amphitheatre Parkway, Mountain View, CA 94043, USA',
'Winnetka, IL, USA', 
'Oslo, Norway', 
'kolkata' - In this case region covers much more area. So I can not see all the markers at a time.

Thanks,
It would be better if anyone can help in this scenario. 

The last updated image - 

![screenshot_20170818-142257](https://user-images.githubusercontent.com/10433734/29453626-f21ee934-8427-11e7-9752-51a34fdcac83.png)
