### ISSUE TITLE
No virtual method getOpenSourceSoftwareLicenseInfo

### ISSUE THREAD

**Issue by christocracy** [airbnb/react-native-maps#1571]
Plugin Version: `0.16.1`
React Native Version: `0.47.1`

When using this module with latest `play-services 11.2.0`, there's no longer a method `GoogleApiAvailability#getOpenSourceSoftwareLicenseInfo`:
```
  compile "com.google.android.gms:play-services-base:11.2.0"
  compile "com.google.android.gms:play-services-maps:11.2.0"
```

[GoogleApiAvailability](https://developers.google.com/android/reference/com/google/android/gms/common/GoogleApiAvailability)

```
08-18 11:40:12.159 18012 18074 E AndroidRuntime: java.lang.NoSuchMethodError: No virtual method getOpenSourceSoftwareLicenseInfo(Landroid/content/Context;)Ljava/lang/String; in class Lcom/google/android/gms/common/GoogleApiAvailability; or its super classes (declaration of 'com.google.android.gms.common.GoogleApiAvailability' appears in /data/app/com.transistorsoft.backgroundgeolocation.react-1/base.apk)
08-18 11:40:12.159 18012 18074 E AndroidRuntime: 	at com.airbnb.android.react.maps.AirMapModule.getConstants(AirMapModule.java:50)
08-18 11:40:12.159 18012 18074 E AndroidRuntime: 	at com.facebook.react.bridge.JavaModuleWrapper.getConstants(JavaModuleWrapper.java:140)
08-18 11:40:12.159 18012 18074 E AndroidRuntime: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
08-18 11:40:12.159 18012 18074 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
08-18 11:40:12.159 18012 18074 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
08-18 11:40:12.159 18012 18074 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
08-18 11:40:12.159 18012 18074 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
08-18 11:40:12.159 18012 18074 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
08-18 11:40:12.159 18012 18074 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:761)
```

[`AirMapsModule#getConstants`](https://github.com/airbnb/react-native-maps/blob/master/lib/android/src/main/java/com/airbnb/android/react/maps/AirMapModule.java#L50
)

**Comment by levibotelho** [comment]
Apparently this method should no longer be used. [See here](https://developers.google.com/android/reference/com/google/android/gms/common/GooglePlayServicesUtil.html#getOpenSourceSoftwareLicenseInfo(android.content.Context)).

**Comment by kelset** [comment]
Same issue, there are currently 3 PRs open - out of the 3, I think #1612 has the better implementation since it provides a more meaningful message.

**Comment by levibotelho** [comment]
Yeah I agree. I don't know who to poke to get one of these merged... This is a pretty big issue and a very small fix...

**Comment by kelset** [comment]
I've already pinged the maintainer in the PR, he apparently (usually) does a new release every 2 weeks so it will hopefully be fixed before next week :)

And yeah, I agree, it's an important & easy fix to set in place :)

**Comment by levibotelho** [comment]
Fantastic thanks mate!

**Comment by lyw0149** [comment]
Same issue, Same solution

**Comment by Rewieer** [comment]
Any news on this ?

**Comment by kelset** [comment]
None on my side - no commits in the last 20 days :/
@gpeal @christopherdro sorry to ping you guys but it's kind of a necessary bug to fix

**Comment by zoontek** [comment]
This seems merged. Any chance to get a release?

**Comment by kelset** [comment]
I'm sure @christopherdro & @gpeal will take care of it soon :)

In the meantime you can use master: `    "react-native-maps": "airbnb/react-native-maps#9b11f7c",
`

**Comment by christopherdro** [comment]
Just published a new version. https://github.com/airbnb/react-native-maps/releases/tag/v0.17.0
