### ISSUE TITLE
App crashed, using of "react-native-device-info" & "react-native-maps" together

### ISSUE THREAD

**Issue by krishbhattacharyya** [airbnb/react-native-maps#1576]
**Environment**
react-native: 0.47.1
node 7.9.0
react-native-maps ^0.16.0

**Target Platform:** 
Android

**Development Operating System:** 
Ubuntu

**Steps to Reproduce:**
1) react-native run-android
2) Alert- Unfortunately, 'Project Name' has stopped.

Expected Behavior
Project should not crashed & Map should display properly.

Extra info:
Project is working properly & map looks great if I am not using **react-native-device-info**. Is there any conflict between two packages. How can I resolve this.

**Comment by jeveloper** [comment]
i have used them together, the problem was different versions of google play services, i suggest you check and you can modify them directly from node_modules

**Comment by cinder92** [comment]
@jeveloper can you help me with this issue? #1572

**Comment by krishbhattacharyya** [comment]
Thank you @jeveloper , I am trying to do this.

**Comment by bintoll** [comment]
@jeveloper Could you tell me please how to do it? Thanks!

**Comment by krishbhattacharyya** [comment]
@jeveloper, now this is worked for me. But how I don't know. When I have build from my system this is not working but when I have build from Mac it is working. Only I have changed the API key.

**Comment by bintoll** [comment]
@krishbhattacharyya You are lucky, i spend a lot of time and it doesn't work=(

**Comment by KarlosQ** [comment]
Do this steps:

1. Go to your project -> node_modules -> react-native-device-info -> android 
2. Open build.gradle file
3. change this line
`compile 'com.google.android.gms:play-services-gcm:+'`
to
`compile 'com.google.android.gms:play-services-gcm:10.2.4'`

In the future if you add more package with com.google.android lines in its build.gradle files change the version to whatever version is used by react-native-maps in your project. You can see the version in the build.gradle file of node_modules/react-native-maps/lib/android

**Comment by krishbhattacharyya** [comment]
@KarlosQ , @jeveloper , @jeveloper thanks. @KarlosQ I have not tried your solution.

But I got the solution in different way, instead of using the current documentation using older documentation. I have followed few steps from - "react-native-maps": "^0.15.3". 

In your android/app/build.gradle add ( Current document):
```
dependencies {
  ...
  compile project(':react-native-maps')
}
```
If you have a different play services than the one included in this library, use the following instead (switch 10.0.1 for the desired version):

```
dependencies {
    ...
    compile(project(':react-native-maps')){
        exclude group: 'com.google.android.gms', module: 'play-services-base'
        exclude group: 'com.google.android.gms', module: 'play-services-maps'
    }
    compile 'com.google.android.gms:play-services-base:10.0.1'
    compile 'com.google.android.gms:play-services-maps:10.0.1'
}
```

I got the result to do this- 
In your android/app/build.gradle add:

```
compile(project(':react-native-maps')){
      exclude group: 'com.google.android.gms'
 }
```

If you have a different play services than the one included in this library, use the following instead (switch 10.0.1 for the desired version):


```
    compile ("com.google.android.gms:play-services-base:10.0.1") {
      force = true;
    }
    compile ("com.google.android.gms:play-services-maps:10.0.1") {
      force = true;
    }
    compile ("com.google.android.gms:play-services-gcm:10.0.1") {
      force = true;
    }

```

This is my package.json- 

`{
  "name": "Promap",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "babel-preset-react-native": "^3.0.0",
    "link": "^0.1.5",
    "react": "16.0.0-alpha.6",
    "react-native": "^0.44.0",
    "react-native-device-info": "^0.11.0",
    "react-native-maps": "^0.16.2",
    "react-navigation": "^1.0.0-beta.11"
  },
  "devDependencies": {
    "babel-jest": "20.0.3",
    "babel-preset-react-native": "^2.0.0",
    "jest": "20.0.4",
    "react-test-renderer": "16.0.0-alpha.6"
  },
  "jest": {
    "preset": "react-native"
  }
}`

**Comment by ramavadhmaurya** [comment]
> **Environment**
> react-native: 0.47.1
> node 7.9.0
> react-native-maps ^0.16.0
> 
> **Target Platform:**
> Android
> 
> **Development Operating System:**
> Ubuntu
> 
> **Steps to Reproduce:**
> 
> 1. react-native run-android
> 2. Alert- Unfortunately, 'Project Name' has stopped.
> 
> Expected Behavior
> Project should not crashed & Map should display properly.
> 
> Extra info:
> Project is working properly & map looks great if I am not using **react-native-device-info**. Is there any conflict between two packages. How can I resolve this.

Change your app/build.gradle dependencies to look like this:

dependencies {
  ...
  compile(project(':react-native-device-info')) {
        exclude group: 'com.google.android.gms'
    }
}


and then go to cd android
clean your gradlew file
and come back to your root directory and then run your application.
It is working for me :)

BR,
Ram Avadh Maurya
