### ISSUE TITLE
[Android] TypeError: expected dynamic type `int64', but had type `double` when using fitToCoordiantes

### ISSUE THREAD

**Issue by shukerullah** [airbnb/react-native-maps#1602]
```
this.map.fitToCoordinates(markers, {
  edgePadding,
  animated
});
```
Above code working fine on iOS but showing red screen with following error as show in screenshot.

![screenshot_1504011836](https://user-images.githubusercontent.com/963765/29822460-65b920ca-8c80-11e7-9911-42df7ec254c5.png)

**Comment by shukerullah** [comment]
Its because of `edgePadding`, padding should be of type int Android.

Thanks for this useful component.

**Comment by christopherdro** [comment]
There is a open PR that might be related.

https://github.com/airbnb/react-native-maps/pull/1467

Care to give it a shot and report back if it worked for you?
