### ISSUE TITLE
Unable to scroll map on IOS

### ISSUE THREAD

**Issue by jomaint** [airbnb/react-native-maps#1605]
I have been trying to solve this issue where regardless of what i do, after refreshing the app. I am able to first pan when the screen is first loaded, after the map stops scrolling. I am unable to get it scrolling again. I am desperate for this to work and I have been trying for days without any solution to my problem. Hope someone can help me with this.

Upon further interaction, _specific behaviour is that after you double tap to zoom, you are able to scroll till you release. Then till you double tap to zoom again, you can't scroll._

If it helps, my project is currently using these versions:
    "react": "16.0.0-alpha.12",
    "react-native": "0.46.3",
    "react-native-maps": "0.16.0",

**Update 01/09/17 **
Out of desperation to try anything, I upgraded to 
    "react": "16.0.0-alpha.12",
    "react-native": "0.47.2",
    "react-native-maps": "0.16.2",

Also changed region props to initialRegion, then the issue seems to go away.

**Comment by christopherdro** [comment]
@jomaint There have been a few fixes merged related to issues with setting region/initialRegion.

Could you try the latest version and report back?

**Comment by olejka91** [comment]
@christopherdro
Everything works fine on Android as for iOS it still works as described above by @jomaint 

My versions are following:
    "react": "16.0.0-alpha.12",
    "react-native": "^0.49.1",
    "react-native-maps": "^0.17.1",
