### ISSUE TITLE
Can not run on Xcode when provider={PROVIDER_GOOGLE}

### ISSUE THREAD

**Issue by thuyiya** [airbnb/react-native-maps#1608]
node v6.11.1
Xcode : 8.3.3
React Native : 0.47
react-native-maps : 0.16.2

Build to 6s Version 11.0 (public beta 8) 
![screen shot 2017-09-01 at 11 03 50 am](https://user-images.githubusercontent.com/12233304/29956520-4ad45bda-8f05-11e7-8cd0-949e76128ef3.png)

**Comment by nicholasc** [comment]
Did you resolve this @thuyiya? I am having the same issue.
