### ISSUE TITLE
In Android device , Map is empty 

### ISSUE THREAD

**Issue by shrinandhini2801** [airbnb/react-native-maps#1634]
<img width="413" alt="screen shot 2017-09-11 at 7 07 26 pm" src="https://user-images.githubusercontent.com/20126145/30277147-8eae58f2-9724-11e7-9531-92c4b1ab8cfc.png">
In Android its showing empty page even though i have followed all the installation instructions thata were mentioned. I am using Pixel device to test .

please help . its quite urgent

**Comment by gabrielaHerreraPoggio** [comment]
Could you post how are you showing the map?
did you set an explicit height and width?

**Comment by gabrielaHerreraPoggio** [comment]
<MapView
                        style={{width: 310, height:150}}
                        region={
                latitude: 14.457282,
                longitude: -90.628757,
                latitudeDelta: 0.000922,
                longitudeDelta: 0.000421
                 }
                        mapType={"standard"}
                        showsUserLocation={false}
                        zoomEnabled={true}
                    >
</MapView>

Does your code look something like this??

**Comment by adeelakram696** [comment]
i installed using npm, then react-native link after that simple import mapview and provider and render below code
<MapView
        style={styles.map}
        provider={PROVIDER_GOOGLE}
        initialRegion={{
          latitude: 37.78825,
          longitude: -122.4324,
          latitudeDelta: 0.0922,
          longitudeDelta: 0.0421,
        }}
      />

**Comment by adeelakram696** [comment]
i installed using npm, then react-native link after that simple import mapview and provider and render below code
`<MapView
        style={styles.map}
        provider={PROVIDER_GOOGLE}
        initialRegion={{
          latitude: 37.78825,
          longitude: -122.4324,
          latitudeDelta: 0.0922,
          longitudeDelta: 0.0421,
        }}
      />`

**Comment by adeelakram696** [comment]
Working now. Just installed google services from SDK.
