### ISSUE TITLE
Performance issues with iOS 11

### ISSUE THREAD

**Issue by kytwb** [airbnb/react-native-maps#1665]
So I upgraded my simulator to iOS 11 and noticed maps were near to unusable. Very slow to mount and near-impossible to interact with (drag, press, or else).  
Anybody else experienced something similar?

**Comment by kytwb** [comment]
I deployed to a physical device that uses iOS 11 and everything is ok.  
This issue seems to affect only the simulators with iOS 11.

**Comment by aleks** [comment]
Same issue for me, runs fine on device (iOS 10.3.3) but virtually impossible to use with the iOS 11 Simulator.

I'm using **react-native 0.48.4** and **react-native-maps 0.16.4**.

**Comment by gokulkulkarni1987** [comment]
Even I am facing the same issue. Please let me know any work around, it is horribly slow.

**Comment by kytwb** [comment]
@gokulkulkarni1987 temporarily downgrade the iOS version used in your simulator.

**Comment by aleks** [comment]
@gokulkulkarni1987 you can use Xcode to download other simulators (Preferences > Components) and then create a new simulator (Window > Devices and Simulators) with a name to your liking (i.e. "iPhone iOS 10").

After that you can call `react-native run-ios --simulator "iPhone iOS 10"` and it should build and run your App inside that Simulator.

**Comment by gokulkulkarni1987** [comment]
thanks @kytwb and @aleks this workaround helped for me.

when can we expect a real solution for this

**Comment by buraky84** [comment]
Is anyone having any performance issues on Iphone 5S having IOS 11?

**Comment by tpisto** [comment]
I can confirm that this temporary fix works:
https://twitter.com/stroughtonsmith/status/910203896332783616

**Comment by kawashimaken** [comment]
Any updates or thoughts on this?

**Comment by aleks** [comment]
This seems to have nothing to do with react-native-maps, other developers have the same issue, see this thread for possible workarounds: https://forums.developer.apple.com/thread/83570

**Comment by Amnesthesia** [comment]
@tpisto Thank you so much for this. This solved my issue with Google Maps too - even with hundreds of markers its now running fine!

**Comment by kytwb** [comment]
Download and install Xcode 9.1 beta 2.  
The beta 2 fixes it.
