### ISSUE TITLE
Initial region not working properly

### ISSUE THREAD

**Issue by jpmazza** [airbnb/react-native-maps#1677]
I have been trying to set the initial region of the map without success.

I tried with the`initialRegion` prop but the map starts with latitude 0  and longitude 0 very very zoomed in. Also, I tried with the method `animateToRegion` in the `componentDidMount` but it doesn't work. Also, I tried with the `fitToCoordinates` in the `onLayout` event of the MapView.

I printed the regions into the `onRegionChange` event when the map is being loaded using the `fitToCoordinates` method on map view layout event (`onLayout`).

<img width="1279" alt="captura de pantalla 2017-09-29 a la s 18 33 13" src="https://user-images.githubusercontent.com/11351953/31036947-d69f8342-a544-11e7-8dde-937380b0bbc1.png">

Code snippet:
```
<MapView
    ref={(ref) => { this.mapRef = ref }}
    provider={PROVIDER_GOOGLE}
    style={map}
    mapType='hybrid'
    moveOnMarkerPress={false}
    rotateEnabled={false}
    initialRegion={initialView}
    onRegionChange={(region) =>  console.log(region)}
    onLayout = {() => this.mapRef.fitToCoordinates([
                                    {latitude: -30.25, longitude: -57.58333},
                                    {latitude: -34.9032800, longitude: -56.1881600}
                                    ], { edgePadding: { top: 10, right: 10, bottom: 10, left: 10 },
                                    animated: false })}
>
                        {this.renderPolylines()}
</MapView>
```

As you can see the last region has latitude = 0  and longitude = 0. This is the first region for the user perspective.

**Comment by mtt87** [comment]
Have a look here https://github.com/airbnb/react-native-maps/issues/1338

**Comment by jpmazza** [comment]
Thanks @mtt87 I've set the region of the map in the `onMapReady` event and it is working.

**Comment by aaronbuchanan** [comment]
@8-uh ^

**Comment by sbkl** [comment]
@jpmazza Do you have a code example? I can show the initial region the first time. But if I close the map screen and show it again (without reloading the app), I go back to the location {0,0} and the initial region is not taken into account.

**Comment by zelgan90** [comment]
@jpmazza Could you please elaborate how you fixed this issue? I've tried setting the region of the map on the `onMapReady` event, and it does work, thing is everytime I try to move the map around it goes back to this same spot over and over again which which is not ok for my app

**Comment by jpmazza** [comment]
@zelgan90 You should ask if it is the first load before update the region.

onMapReady => is first time? => UPDATE REGION

**Comment by RonaldPS1993** [comment]
onMapReady is not working for me, i am using expo-location to fetch the current lat,lon
