### ISSUE TITLE
[iOS, Google Maps] Issues with  panning with controlled region

### ISSUE THREAD

**Issue by ryankask** [airbnb/react-native-maps#1680]
When trying to work around the issues with `initialRegion` outlined in #1613, I tried using the `MapView` `region` prop.

I've noticed that panning doesn't work. Sometimes the map ends up of moving but it's unpredictable and choppy. Is anyone else seeing these issue?

Removing either `provider={PROVIDER_GOOGLE}` or `region={this.state.region`} fixes the panning issue.

**Comment by aaronbuchanan** [comment]
I'm seeing the map reset it's position after I zoom/pan/tilt, not sure if that's the same thing you're reporting here?

**Comment by ryankask** [comment]
I can't pan, zoom, or interact with any regularity. Occasionally I am able to pan but it's only after randomly clicking and dragging all over the map. When using MapKit, there are different issues. It appears like the region is reset when the map is ready. I haven't tried Android yet.

There appear to be several major regressions in the latest version (I've upgraded from 0.13.0).

**Comment by jmhuret** [comment]
I've seen this issue for quite some time. It's very annoying. The best thing I've seen to help what you are describing is to patch the MapView.js file in the `_onMapReady` function. Add this to the beginning of that function:

`if ( this.state.isReady ) return;`

**Comment by ryankask** [comment]
Thanks for the tip. I've actually patched onMapReady to fix the original issue I had with `initialRegion`. 

Unfortunatley I don't have the time now to try to fix these issues but I wonder if there's a way for the community to fund the work to resolve these critical issues. My projects have had issues with `MapView`'s props and callbacks and their behaviour across each platform and maps provider.

**Comment by aaronbuchanan** [comment]
Can confirm this fix worked on my fork
