### ISSUE TITLE
Marker image is not initially rendered on Android (image is missing or it doesn't have size)

### ISSUE THREAD

**Issue by vvusts** [airbnb/react-native-maps#1684]
I am using v 0.16.4 RN 44.3

I am rendering dynamic markers first time when I load map I don't get custom image for marker.
I have a marker and text inside it.
I already tried all hacks that I found here in issues.
On IOS it works perfect but on Android I see only text from marker but marker image is not present.
```
return (
        <MapView.Marker
        key={markerIndex}
          coordinate={{
            latitude: lat,
            longitude: lng
          }}
        >
        <View>
        <Image 
        source={
         require(markerImage)
        }
      >
        <Text>
           {'test'}
        </Text>
      </Image>
        </View>
        </MapView.Marker>
      )
```

Can somebody help me what to do?

**Comment by Venomstrike** [comment]
Why was this Issue closed without a comment? 
I've got the same problem!

**Comment by vvusts** [comment]
I gone through all issues and tried something in the end and it worked but I was not sure is it me or map but here what I did:
I declared in my render() method images that I use as a marker at the beginning.
```
render() {
  return (
     <Image source={.../myImage} style={{width: 0, height: 0}}
```
Width and height zero was the key.
When I did this markers worked.

**Comment by Venomstrike** [comment]
Thank you!

**Comment by khuongdv** [comment]
I got this issue as well. Don't know what is the official way to do that. I had to remove the image to use origin icon as a workaround
