### ISSUE TITLE
Show users current position

### ISSUE THREAD

**Issue by simplenotezy** [airbnb/react-native-maps#1698]
It would be nice to be able to show the users current position, like this:

![image](https://user-images.githubusercontent.com/3786627/31519912-566c9aba-afa4-11e7-802c-4b3f0d5e5beb.png)

**Comment by simplenotezy** [comment]
showsUserLocation={true}
					showsMyLocationButton={true}

**Comment by sahir** [comment]
@simplenotezy showsUserLocation not working in Android
