### ISSUE TITLE
iOS MapView.Marker onPress is not fired for 'google' map provider

### ISSUE THREAD

**Issue by aksonov** [airbnb/react-native-maps#1721]
as well  onMarkerPress and custom Touchable onPress .
Everything works well for native iOS maps.

**Comment by androidseb** [comment]
I have noticed the same issue, also only happening when using the 'google' provider.

The MapView's  onMarkerPress function was being called but without parameters, making it impossible to determine what marker was clicked.

The MapView.Marker onPress function was never being called.

I tested on version 17.0 of react-native-maps.

I tried debugging objective-C but I wasn't able to find out why the event is not bubbling back to the map marker.

**Comment by androidseb** [comment]
My problem was the the onMarkerPress function was being called but with no object/parameters so I could not know what marker ID that came from...
I found a way to fix the objective-C code to return the ID of the marker being pressed and I have submitted a merge request:
https://github.com/airbnb/react-native-maps/pull/1741

With this fix, if your MapView.Marker has a "identifier" prop, it should be present in the MapView.onMarkerPressed function parameters.
