### ISSUE TITLE
Google Maps Not Working on iOS

### ISSUE THREAD

**Issue by ashour** [airbnb/react-native-maps#1733]
Hello, 

I'm having a problem getting Google Maps to build and run on iOS with `react-native-maps`.

## Versions
- react-native 0.49.3
- react-native-maps 0.17.1
- XCode 9.0.1

## Steps Taken

- `react-native init google_maps_ios`
- `cd google_maps_ios && react-native run-ios` -- All is running well in simulator 
- `yarn add react-native-maps`
- `react-native link react-native-maps`
- Opened `.xcodeproj` file in XCode
- Dragged the `node_modules/react-native-maps/lib/ios/AirGoogleMaps` folder to the top-most level of the XCode project. 
	- In the dialog that opens up in XCode, selected "Create Groups" and left "Copy items if needed" unselected. 
- Closed XCode and ran `pod init` in the `ios/` directory
- Opened the generated `Podfile` and changed it to look like:

```
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'google_maps_ios' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for google_maps_ios

  pod 'GoogleMaps'

end
```

- Saved the Podfile and ran `pod install`
- Opened `google_maps_ios.xcworkspace` in XCode
- Attempted to run the project

At this point, the build fails because "'GoogleMaps\GoogleMaps.h' file not found" in `AirGoogleMaps > AIRGMSMarker.h`.

---

Now I've been working on this issue for hours, trying the official installation instructions in this repo's README / wiki. I also looked at a ton of issues here and StackOverflow but to no avail. 

Any help regarding this issue would be much appreciated.

Thanks for this project. It saves us a ton of time.

**Comment by rborn** [comment]
Try this in a new project - https://codeburst.io/react-native-google-map-with-react-native-maps-572e3d3eee14

**Comment by ashour** [comment]
Thanks @rborn. Unfortunately the URL you posted redirects to medium.com, which is blocked where I currently am. Could you do me a solid and just paste the contents of that article here? You don't need to format it or anything. Thanks.

**Comment by rborn** [comment]
https://www.dropbox.com/s/qyb9xmsc0345co8/ReactNativeGoogleMapwithreact-native-maps.pdf?dl=0  can you download this?

**Comment by ashour** [comment]
Indeed I can :) Thank you @rborn. I'll give the instructions a whirl and update here.

**Comment by ashour** [comment]
Hey @rborn, thanks for that article. The thing I was doing wrong, I believe, was not copying the files over when dropping the `AirGoogleMaps` files over to the XCode project.

I was leaving the radio button unchecked, which was just creating a reference to the files in that folder. That would explain why the import statement was failing the `AirGoogleMaps/AIRGMSMarker.h` file.

When I created a clean project and followed all the steps, and _copied the files over_, it worked :)

Thanks again @rborn. The screenshot of the XCode dialog in Kristen's article--the one you linked to--really helped. 

We should add a PR to be explicit about file copying the documentation. Happy to do it if you guys are taking contributions.

**Comment by rborn** [comment]
@ashour I think you can do the PR (I'm not involved with the module sadly) even if it's not getting merged. Other people will find it and use it 😄
