### ISSUE TITLE
Blue screen when loading the MapView second time using GoogleMaps as the provider

### ISSUE THREAD

**Issue by ghoshabhi** [airbnb/react-native-maps#1742]
Hello,

Thank you for this awesome library. I have been struggling for almost a week trying to integrate this package with our project. The setup took time - but is now working with at least iOS devices.

The problem right now is the map loads correctly and well the first time, but doesn't load correctly the second time. It loads a **BLUE SCREEN** instead. The behavior remains the same on both simulator and real device.

Here is a demo:

![map_view](https://user-images.githubusercontent.com/19292575/32150310-541e85c8-bcdf-11e7-8c6f-039b8e5b588e.gif)

I am not sure what is causing this. Also, the map loads perfectly when I use the native iOS maps. 

Can anyone please help me debug this behavior ?

```
"react": "16.0.0-beta.5",
"react-native": "0.49.3",
"react-native-maps": "^0.17.1",
```
iOS version: 11.0

**Comment by ghoshabhi** [comment]
Saw this issue: https://github.com/airbnb/react-native-maps/issues/1452 which mentions that the coordinates are invalid for `initialRegion`. But why would it load the first time then ? Here is how my component looks like: 

```
import React, { Component } from 'react';
import { View, Dimensions, ScrollView, StyleSheet } from 'react-native';
import MapView, { PROVIDER_GOOGLE } from 'react-native-maps';
import Button from '../../components/core/Button';

const { width, height } = Dimensions.get('window');
const ASPECT_RATIO = width / height;
const SCREEN_WIDTH = width;
const LATITUDE = 32.9873960;
const LONGITUDE = -96.7780670;
const LATITUDE_DELTA = 0.0922;
const LONGITUDE_DELTA = 0.0345;


const styles = StyleSheet.create({
  container: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  scrollview: {
    alignItems: 'center',
  },
  map: {
    width: SCREEN_WIDTH,
    height: 400,
  },
});

export default class MapExample extends Component {
  constructor(props) {
    super(props);

    this.state = {
      region: {
        latitude: LATITUDE,
        longitude: LONGITUDE,
        latitudeDelta: LATITUDE_DELTA,
        longitudeDelta: LONGITUDE_DELTA,
      },
    };
  }

  handlePress = () => {
    alert('Will redirect now...');
  }

  render() {
    return (
      <View style={styles.container}>
        <ScrollView
          style={StyleSheet.absoluteFill}
          contentContainerStyle={styles.scrollview}
        >
          <MapView
            style={styles.map}
            provider={PROVIDER_GOOGLE}
            zoomLevel={18}
            loadingEnabled
            scrollEnabled
            zoomEnabled
            pitchEnabled
            rotateEnabled
            initialRegion={this.state.region}
          >
            <MapView.Marker
              title="This is a title"
              description="This is a description"
              coordinate={this.state.region}
            />
          </MapView>
          <View style={{ margin: 20 }}>
            <Button
              style={{ padding: 20 }}
              title={'Get Directions'}
              onPress={this.handlePress}
            />
          </View>
        </ScrollView>
      </View>
    );
  }
}
```

**Comment by rborn** [comment]
This ain't blue screen, but the map going to `lat:0,  lng: 0` which happens to be in the ocean :smile:
Somehow it loses the state or the initial region I guess when you close the window.
A workaround that seems to work is to use `region` instead of `initialRegion` (works for me, and  I can replicate your issue with `initialRegion`)

**Comment by ghoshabhi** [comment]
Thanks @rborn ! Using `region` worked 😄 !

**Comment by rborn** [comment]
@ghoshabhi would this work for you (need to patch the map module) ? https://github.com/airbnb/react-native-maps/pull/1715

**Comment by ghoshabhi** [comment]
Yeah, I still need to figure out why is the prop for `initialRegion` being override.  Until then `region` works for me now. I still am facing some issues on Android too, need to work on that. I don't understand why setting up this library is so much of a hassle :/

**Comment by rborn** [comment]
The pace of which RN is evolving is pretty fast, so I guess the AirBnb guys and girls don't have enough time to keep up with it, so they fix what and when they need it. My 2c 😄

**Comment by ghoshabhi** [comment]
Haha! Yeah I don't blame the team at all. They are doing an awesome job 👍 🎉 It is just my frustration with my own inability ;)

**Comment by rborn** [comment]
neh... you managed to run it, so you're not that bad 😋

**Comment by larryranches** [comment]
@ghoshabhi @rborn I'm also facing this issue. Are goes seeing this too? The problem with using region is that the zoom and pinch to zoom in and out becomes laggy and slow.

Using initialRegion moves smoothly but when navigated to a second time the blue screen shows above :(

**Comment by rborn** [comment]
I don't have this. But if you use onRegionChange without throttling or debouncing you will re-render the map too often (assuming you do this, like painting new markers, etc)
I chose onRegionChangeComplete because the re-rendering only happens when the user finished the action.

Not sure it applies to you though :)

**Comment by jordanmkoncz** [comment]
I'm having the same problem. I'm using `initialRegion`, and the first time the map is rendered it works perfectly, but the second time it's rendered the map is zoomed in at coordinates `0,0` (which is in the sea) so it looks like a blank blue map.

Here's my dependencies:

```
"react": "16.0.0",
"react-native": "0.50.3",
"react-native-maps": "^0.18.3",
```

I also had this issue when I was using `"react-native-maps": "^0.17.1"`.

**Comment by esthercuan** [comment]
Im experiencing this problem too.. but unlike you guys, `region` is not working either.

**Comment by HarshitMadhav** [comment]
@esthercuan  can you post your <mapview> component here?

**Comment by anyatibrian** [comment]
@esthercuan please include the provider property for the case of android I also had the same issue that's how I managed to fix it.

**Comment by getusha** [comment]
Thank you @rborn :smile:
