### ISSUE TITLE
Cant drag map when cacheEnabled={true}

### ISSUE THREAD

**Issue by Adamnator92** [airbnb/react-native-maps#1744]
### Environment
"react-native-maps": "^0.16.3",
 "react": "16.0.0-alpha.12",
 "react-native": "^0.48.3",

Target Platform: iOS (10.3)

thing happen when i set `cacheEnabled={true}`
- unable to drag the map (ios - debug mode), but pitch on screen is possible
- unable to press on markers  (ios - debug mode)
- unable to `animateToCoordinate` after fetch request  (ios & android - debug mode)

**Comment by KarlosQ** [comment]
It is not a bug because when cacheEnabled={true} you can't do any actions.

**Comment by Adamnator92** [comment]
@KarlosQ  my thank for pointing it out, i just realize that
