### ISSUE TITLE
0.17.1 / onRegionChange is not fired

### ISSUE THREAD

**Issue by davidroman0O** [airbnb/react-native-maps#1752]
Hi,

I've just update my react-native to 0.49.3 and react-native-maps to 0.17.1 with a the same code, the maps don't work anymore.

The onRegionChange is not even fired and the initialRegion don't works properly.

I've tried to change my code multiple time to see what's happening.

When the maps freeze because onRegionChange isn't fired, i get those logs on xCode : 

```
CoreData: annotation:  Failed to load optimized model at path '/var/containers/Bundle/Application/79901795-8A36-4F0A-9E5A-117D59E483ED/mobile_application.app/GoogleMaps.bundle/GMSCacheStorage.momd/StorageWithTileVersionID.omo'
CoreData: annotation:  Failed to load optimized model at path '/var/containers/Bundle/Application/79901795-8A36-4F0A-9E5A-117D59E483ED/mobile_application.app/GoogleMaps.bundle/GMSCacheStorage.momd/StorageWithTileVersionID.omo'
CoreData: annotation:  Failed to load optimized model at path '/var/containers/Bundle/Application/79901795-8A36-4F0A-9E5A-117D59E483ED/mobile_application.app/GoogleMaps.bundle/GMSCacheStorage.momd/StorageWithTileVersionID.omo'
CoreData: annotation:  Failed to load optimized model at path '/var/containers/Bundle/Application/79901795-8A36-4F0A-9E5A-117D59E483ED/mobile_application.app/GoogleMaps.bundle/GMSCacheStorage.momd/StorageWithTileVersionID.omo'
2017-11-01 15:50:44.274371+0100 mobile_application[12512:4729023] [BoringSSL] Function boringssl_context_get_peer_sct_list: line 1754 received sct extension length is less than sct data length
```

My Google API key is correct, everything is be setup correctly. I don't know what to do. 
What kind of informations can i provide to resolve this issue ?

**Comment by rborn** [comment]
See this for a workaround. https://github.com/airbnb/react-native-maps/issues/1742

**Comment by davidroman0O** [comment]
Already seen that issue.
Changing to region fixed the blue screen issue. That's ok.
Buuuuut the onChangeRegion issue is still there... I'm gonna try to downgrade the version of react-native-maps. Wait&See

**Comment by rborn** [comment]
I had issues with `onRegionChangeComplete` but it might be in debugging mode only (meontioned in another issue too, don't remember which one). I've put the app on device and all works as expected

**Comment by davidroman0O** [comment]
OK ! 
Well, it's fully working under those versions : 

```
"react": "16.0.0-alpha.12",
 "react-native": "0.46.4",
 "react-native-maps": "^0.15.3"
```
If someone is in trouble with the last version of RN and Maps, you must downgrade to restore the features you've implemented.

I've test a lot of versions, those works perfectly.
