### ISSUE TITLE
Gray map with logo

### ISSUE THREAD

**Issue by sadboyzvone** [airbnb/react-native-maps#1761]
1. Made a new project with: react-native init
2. Ran: npm install react-native-maps --save
3. Ran: react-native link react-native-maps
4. Put the API key in the AndroidManifest.xml
5. Opened my Virtual Device
6. Ran: react-native run-android

The result is a gray map with a Google logo in the bottom left corner
I've read some solutions on the internet but none seem to work
The MapView component in the render function is copied from the README.md

**Comment by thegamenicorus** [comment]
+ 1 Same

**Comment by AleksandrAleksandrov** [comment]
The same on real device

**Comment by esutton** [comment]
@sadboyzvone I had same symptoms on Android,  gray map with a Google logo in the bottom left corner.

I assumed my problem was using an x86 emulator with no Google Services installed.  

However, I upgraded my x86 avd Android emulator to one that one that had Google Play Services installed. Genymotion emulator makes this easy with their **GApps** button on the emulators tool bar.  This did not fix it.  I still saw a gray background.

What fixed it was reading the install instructions again.  

Everything looked correct to me.  As a last resort, I went to Google, found my API key, copied it, then replaced the one I had in **google_maps_api.xml**

File: android/app/src/main/res/values/google_maps_api.xml
```
<string name="google_maps_key" templateMergeStrategy="preserve" translatable="false">SyCkY6nG5gBzo6aQ-coqU</string>
</resources>
```
My problem was the API key.  Now my map no longer displays gray in my Android x86 emulator and all is good.

**Comment by sadboyzvone** [comment]
@esutton i dont have google_maps_api.xml in the values folder

**Comment by rborn** [comment]
In your `android/app/src/main/AndroidManifest.xml` file add the next entry after the opening `<application...`> tag:

~~~
<meta-data android:name="com.google.android.geo.API_KEY" android:value="YOUR_API_KEY"/>

~~~

**Comment by sadboyzvone** [comment]
Fixed it!
I think the problem was that I was mixing yarn and npm.

**Comment by sadboyzvone** [comment]
Because I install react native via yarn

**Comment by AleksandrAleksandrov** [comment]
I have forgot to reply that I resolve the issue. Mine was that I didn't link to google console project with adding SHA-1

**Comment by kayson** [comment]
I have checked all possible solutions above and reinstalled from scratch at separate projects. Using AVD emulators and Genymotion emulator and even real devices. I have also tested using different keys and as @AleksandrAleksandrov wrote but still same problem.

@esutton I have no **google_maps_api.xml**, tried adding it manually with my own APIKEY but without any luck.

I am really stuck with this problem.

**Comment by alvelig** [comment]
that's a API_KEY issue clearly

**Comment by citizen-dror** [comment]
one more option to API_key problem is if you forget / misunderstood

 [ section 3.1 in the installtion!](https://github.com/react-native-community/react-native-maps/blob/master/docs/installation.md)

replace :

 supportLibVersion   = "xxx"
 playServicesVersion = "17.0.0" // or find latest version
 androidMapsUtilsVersion = "xxx"
with somthing like:

supportLibVersion = "28.0.0"
playServicesVersion = "17.0.0"  
androidMapsUtilsVersion = "2.0.3"

i did'nt uderstand what to replace supportLibVersion , androidMapsUtilsVersion version, 
skipped it and got gray screen for hours !! without a clear bug!

[see this qusetion ](https://stackoverflow.com/questions/58806151/get-supportlibversion-playservicesversion-and-androidmapsutilsversion-va)to find latest version

**Comment by ramisalem** [comment]
Guys, I have done all the solution mentioned above without any lack

**Comment by Timon0305** [comment]
This is not api key problem , My api key is working well but I can't solve this issue

**Comment by usmankhan495** [comment]
Same issue here.any one find the solution?

**Comment by AshishMadhu** [comment]
> 1. Made a new project with: react-native init
> 2. Ran: npm install react-native-maps --save
> 3. Ran: react-native link react-native-maps
> 4. Put the API key in the AndroidManifest.xml
> 5. Opened my Virtual Device
> 6. Ran: react-native run-android
> 
> The result is a gray map with a Google logo in the bottom left corner
> I've read some solutions on the internet but none seem to work
> The MapView component in the render function is copied from the README.md




> 1. Made a new project with: react-native init
> 2. Ran: npm install react-native-maps --save
> 3. Ran: react-native link react-native-maps
> 4. Put the API key in the AndroidManifest.xml
> 5. Opened my Virtual Device
> 6. Ran: react-native run-android
> 
> The result is a gray map with a Google logo in the bottom left corner
> I've read some solutions on the internet but none seem to work
> The MapView component in the render function is copied from the README.md

Faced this problem, tried many solutions nothing went correct. 
The problem was I was using a real device instead of an emulator, but the device was set on the incorrect date and time. Then, I turn on the Automatic date & time and yeah now it works for me fine. I don't know the exact reason but it works have a try.

**Comment by Timon0305** [comment]
I solved that.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by usmankhan495** [comment]
@Timon0305 Can you please share how did you solve this issue.

**Comment by Timon0305** [comment]
Okay


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Xplosive06** [comment]
Don't forget to activate your Maps SDK for Android and IOS in your Google console.

That was my problem!

**Comment by blwinters** [comment]
In my case, I had changed the tooling for building and signing our app, so I needed to [get the new SHA1 hash](https://stackoverflow.com/questions/61119983/how-do-i-get-sha-1-certificate-in-expo) and add it to the existing API key in the [Google Cloud console](https://console.cloud.google.com/google/maps-apis/credentials).
