### ISSUE TITLE
MapView onPress not always triggered

### ISSUE THREAD

**Issue by WernerRaath** [airbnb/react-native-maps#1787]
Hey guys

I would like to use the coordinates of where the user presses to create a marker at that location.

When I single click on the map with my finger, I don't always get a response, but when I do I get some rubbish (**Output Block**).

**MapView JSX** (within Component)
```
<MapView
    style={styles.map}
    region={this.state.mapRegion}
    showsUserLocation={true}
    followUserLocation={true}
    onPress= {this.setMarkerLocation.bind(this)}>
</MapView>
```
**onPress handler**
```
setMarkerLocation(location){
    console.log(location);
}
```
**Output Block**
```
{ dispatchConfig: { registrationName: 'onPress' },
   _targetInst:
      { _currentElement:
         { '$$typeof': 60103,
            type:
               { [Function: Constructor]
                  displayName: 'AIRMap', 
...
```

Any advice?

**Comment by efkan** [comment]
Just a possibility:
If there is another marker is at the behind of the marker you pressed it might be the reason.

**Comment by swcisel** [comment]
Also worth noting that the first argument to the onPress handler is going to be the event. It may be more meaningful to run: 

```
 setMarkerLocation(e){ 
    console.log(e.nativeEvent); 
 } 

```

**Comment by WernerRaath** [comment]
Okay so by using `e.nativeEvent`, I managed to get the location information.

Performance is still a problem, as you have to sometimes click up to 5 times before getting an event fired. Thus I am not closing this issue as the title of the issue relates to precisely this problem.

**Comment by hirokimoto** [comment]
This works for me.

<MapView
...
onPress={(e) => this.handlePress(e.nativeEvent)}
>
