### ISSUE TITLE
zIndex and overlapping marker issues

### ISSUE THREAD

**Issue by jnrepo** [airbnb/react-native-maps#1788]
Issue:
- when pressing overlapping markers, sometimes the marker at the top isn't pressed but the ones below, even when utilizing z-indexing
- when there are more than three markers overlapping, clicking on the overlapping area will cycle through three of the markers
- marker with the highest z-index also doesn't render all the way at the top, it can sometimes be covered by the other markers around it

react-native: 0.50.3
react-native-maps: 0.17.1
iOS: 11

**Comment by jnrepo** [comment]
similar to whats going on https://github.com/airbnb/react-native-maps/issues/1671

closing this one out.

**Comment by filipef101** [comment]
@jnrepo How did you solve this? having the same insane issue with the on presses
