### ISSUE TITLE
re-registered bubbling event 'topMarkerPress' as a direct event after updating to 0.18.1

### ISSUE THREAD

**Issue by wbattel4607** [airbnb/react-native-maps#1829]
Everything was working fine on 0.17.1. I just updated to 0.18.1 and now I'm getting this error:

`Component 'AIRMap' re-registered bubbling event 'topMarkerPress' as a direct event`

I read that the iOS Google Maps marker press was something that was changed/fixed in version 0.18.0, so maybe this is related. I am using Google Maps on iOS.

The other issues of this nature on this repo suggest it is a conflict with another lib, but none of the other libs have changed from the previously working version. I think it has to do with what changed in 0.18.0.

I've tried all of the typical things like project cleaning, re-linking, etc...

Any ideas? Thanks.

**Comment by wbattel4607** [comment]
I think this commit broke it: be1b6ded3913d09fe8462cdec741171ce9d939b4

with the file in question being: `lib/ios/AirGoogleMaps/AIRGoogleMapManager.m`

But that is just my theory.

**Comment by yakisama12** [comment]
Same here :/

**Comment by juergengunz** [comment]
same :(

**Comment by kelset** [comment]
Same issue here, has perhaps anyone tried deleting the `AIRMaps.xcodeproj`, meaning basically repeating [the manual steps](https://github.com/airbnb/react-native-maps/blob/master/docs/installation.md#option-3-manually)?

**Comment by christopherdro** [comment]
Hmm, I don't even see `topMarkerPress` be registered anywhere.

**Comment by wbattel4607** [comment]
It might just be an alias for markerPress. Not sure.

**Comment by christopherdro** [comment]
Related https://github.com/airbnb/react-native-maps/issues/289
https://github.com/airbnb/react-native-maps/issues/1615

**Comment by wbattel4607** [comment]
Those two issues are a result of conflicts with other packages- so unless 0.18.0/0.18.1 added a conflict, that shouldn't be the cause. None of my other packages were touched between the working and non-working builds.

**Comment by chrismcleod** [comment]
did react-native unlink, deleted AIRMaps xcodeproj, relinked, copied AIRGoogleMaps directory, still get error

**Comment by christopherdro** [comment]
Does this result in a hard crash or a yellow box warning?

/cc @androidseb Any ideas what might be causing this?

**Comment by chrismcleod** [comment]
results in a red box error that can be dismissed and everything seems to work

**Comment by SrLazar0** [comment]
yep, the same probleme with red screen, but when i go to android everything works fine

**Comment by androidseb** [comment]
@christopherdro 
Sorry about this!
@wbattel4607 is right, it is the modification to `lib/ios/AirGoogleMaps/AIRGoogleMapManager.m` causing the problem!

I have made a commit here to fix this:
[https://github.com/androidseb/react-native-maps/commit/8271c76f5da85e6e05b2c449de94057731676237](https://github.com/androidseb/react-native-maps/commit/8271c76f5da85e6e05b2c449de94057731676237)

I'm testing it to verify that it's actually fixing the issue and I'll issue a merge request as soon as it's confirmed.

**Comment by androidseb** [comment]
The problem is that the original modification that I made to fix the marker press not working was tested on an older version of react native. Upon upgrading my react native version I could see the issue as well.

**Comment by androidseb** [comment]
I can confirm the fix.
Here is the link to the merge request:
[https://github.com/airbnb/react-native-maps/pull/1839](https://github.com/airbnb/react-native-maps/pull/1839)

**Comment by wbattel4607** [comment]
Yay, I helped! :D

Thank you!
