### ISSUE TITLE
fitToCoordinates not fully working

### ISSUE THREAD

**Issue by stylianospanagakos** [airbnb/react-native-maps#1834]
I am creating an app that includes a map which should render two markers on it (one for a pickup location and one for destination location). Whenever the user selects a location suggestion, I fetch the coordinates and put it on a markers array. During the user's first attempt to input pickup and destination locations I can actually see fitToCoordinates animating the MapView and showing me both of the markers. The problem occurs as soon as the user decides to update one of the locations. When that happens, the new marker is rendered but the map bounds are not updated which means that the user can see both of the markers only if they zoom out. Any ideas what could be the reason for that problem?

```
<MapView
    ref={ref => this.mapRef = ref}
    initialRegion={{
        latitude: UK_LAT,
        longitude: UK_LNG,
        latitudeDelta: UK_LAT_DELTA,
        longitudeDelta: UK_LNG_DELTA
    }}
    style={container}
    onLayout={() => {
        if (this.props.map_markers.length) {
            this.mapRef.fitToCoordinates(
                this.props.map_markers,
                {
                     edgePadding: { top: 50, right: 50, bottom: 50, left: 50 },
                     animated: true 
                }
            )
        }
    }}
>
    {this.props.map_markers.map((marker) => (
        <MapView.Marker
            key={(marker.latitude + marker.longitude).toString()}
            coordinate={{
                latitude: marker.latitude,
                longitude: marker.longitude
            }}
        />
    ))}
</MapView>
```

**Comment by kytwb** [comment]
Looks like this is more a usage issue than an issue with the module itself. To keep it short, I think you need to call `fitToCoordinates` when `this.props.map_markers` changes using your component lifecycle methods (e.g. `componentWillReceiveProps` or `componentDidUpdate`). Feel free to post your question on StackOverflow and to add the `react-native-maps` tag to it if you need more help.

@christopherdro is that the kind of issue that qualify for StackOverflow-redirect and closing you think? I'll keep going after work hours if that looks good to you.
