### ISSUE TITLE
Using PROVIDER_GOOGLE slows down performance on Simulator

### ISSUE THREAD

**Issue by luco** [airbnb/react-native-maps#1837]
Do you guys experience this? 
When using `PROVIDER_GOOGLE` on my Map, every other view has it's performance affected. When using Apple's maps, it doesn't happens. This only happens on Simulator. On device, everything is fine.

**Comment by ismaserrano** [comment]
Is a normal situation in simulator. Test it on real device better; if continues slowly, then is time to worries.

**Comment by luco** [comment]
@ismaserrano Yes, on device, it works smoothly.
