### ISSUE TITLE
iOS google provider can't move the map

### ISSUE THREAD

**Issue by Germanaz0** [airbnb/react-native-maps#1838]
I am using this view

```tsx
<MapView.Animated
   style={styles.map}
   provider={"google"}
   showsUserLocation={true}
   showsMyLocationButton={true}
   showsTraffic={true}
   region={this.state.region}
   onRegionChange={(region) => this.onRegionChange(region)}
   onMapReady={(data) => this.onMapReady(data)}
/>
```
onRegionChange just update the `this.state.region` coords, this code works properly on android but wont work on ios, I tried with basic configurations like removing the events `onRegionChange` and `onMapReady` and still does not work.

The problem is that the map frozes, it cannot be moved if region is marked, it only works using initialRegion but is not what I need to use.

Versions:
 - react-native-cli: 2.0.1
 - react-native: 0.50.3
 - npm-version: 5.5.1
 - ios: 11.1.2
 - react-native-maps: 0.17.1

**Comment by JConcepts** [comment]
having the same problem... if you remove region and use only initialRegion it will move but you wont be able to have the button to 'move to your location'

Didnt solve it yet

**Comment by danielgindi** [comment]
You should update to latest version, or at least the one released 2 days ago with my PR

**Comment by Germanaz0** [comment]
@JConcepts I discovered that when you rotate the device, the button appears.
@danielgindi I tried to upgrade yesterday, but the newest version was kinda broken, going to try now.

**Comment by Germanaz0** [comment]
Going to close this issue because on last upgrade it did work

**Comment by swaroopa94** [comment]
@Germanaz0 
HI
I installed the latest version ^0.19.0 but it did not work it is not at all zooming in or out
Can you tell me how to solve this
