### ISSUE TITLE
ReactSubviews: Markers and Callouts behind 

### ISSUE THREAD

**Issue by alvelig** [airbnb/react-native-maps#1844]
I noticed that the callout, when it appears below some markers, is in MKNewAnnotationContainer, but the markers above it are direct children of AirMaps, added in AirMaps.m:

```
- (void)insertReactSubview:(id<RCTComponent>)subview atIndex:(NSInteger)atIndex {
    ... 
    [_reactSubviews insertObject:(UIView *)subview atIndex:(NSUInteger) atIndex];
}
```
Commenting that line all annotations appear in MKNewAnnotationContainer and the callout is before all the markers.

The problem that I have, is that I don't fully understand the logic behind _reactSubviews and I see that annotations are not removed when markers are changed in react.

Maybe someone of main contributors might help me showing the way to go to make this behavior in a proper way?

**Comment by alvelig** [comment]
Holy cow!

Just override addSubview in AirMap:
```
- (void)addSubview:(UIView *)view {
    if([view isKindOfClass:[AIRMapMarker class]]) {
        [self addAnnotation:(id <MKAnnotation>)view];
    } else {
        [super addSubview:view];
    }
}
```

Improvements and suggestions are welcome, while I'm creating a pull request.

**Comment by alvelig** [comment]
@kytwb, @esutton please comment if you tested and if there are any bugs detected, as collaborators ask me to have positive replies on my pull request to merge it to master.

**Comment by alvelig** [comment]
PR #1845 fixes this issue. Closing

**Comment by alvelig** [comment]
Duplicate of #418

**Comment by GarimaMathur07** [comment]
@alvelig I have about 600 markers. So, i am using https://github.com/novalabio/react-native-maps-super-cluster uses MapBox's SuperCluster as clustering engine. I am facing **Callout behind markers** issue. I am using `renderMarker` as follows:

```
<ClusteredMapView
			style={styles.map}
			data={this.state.pins}
			ref={o => (this.mapRef = o)}
		        renderMarker={this.renderMarker}
			renderCluster={this.renderCluster}
			fitToElements={ClusteredMapView.ANIMATED_FIT}
			edgePadding={styles.edgePaddingStyle}
			clusteringEnabled={true}
			initialRegion={{
						latitude: this.initialRegionLat,
						longitude: this.initialRegionLong,
						latitudeDelta: this.LATITUDE_DELTA,
						longitudeDelta: this.LONGITUDE_DELTA
					        }}/>

```
```
renderMarker (pin) {
	const styles = this.styleSheet();
	return (
		<Marker
			key={pin.id || Math.random()}
			coordinate={pin.location}
			ref={o => (this.marker = o)}
			calloutOffset={{ x: -8, y: 28 }}
			calloutAnchor={{ x: 0.5, y: 0.4 }}
			onCalloutPress={() => this.onPressCallout(pin)}
			image={map_pin.source}
		>
			<Callout tooltip style={styles.customCalloutView}>
				<LocationMarkerCallout title={pin.storeloc.name} description={pin.storeloc.address} />
			</Callout>
		</Marker>
	);
};
```
Can you please suggest how can i resolve this issue.

**Comment by rborn** [comment]
@GarimaMathur07 please don't post the same question in multiple posts, once should be enough.
Also you pinged @alvelig multiple times, imagine how many emails he receives - he, like everybody else here is trying to help in our free time, so please respect this 🤗

**Comment by GarimaMathur07** [comment]
@rborn Apologies for the inconvenience!! 

Can you please help me out with this issue.

**Comment by rborn** [comment]
I sadly don't know 😔

**Comment by alvelig** [comment]
@GarimaMathur07 in your issue you say that you use version 0.17.0. Update your version (to master branch) and let us know.

**Comment by GarimaMathur07** [comment]
Thanks for the reply 👍 I'll try with master branch then let you know about the scenarios.
