### ISSUE TITLE
Map size can't be 0. Most likely layout has not yet been occurred.

### ISSUE THREAD

**Issue by jaysson** [airbnb/react-native-maps#245]
Occassionally I get this error:
![screenshot_2016-05-22-23-58-08](https://cloud.githubusercontent.com/assets/1563862/15456694/774c068e-2095-11e6-81a7-d5fc482e950e.png)

But this does not happen always.

**Comment by christopherdro** [comment]
@jaysson Could you provide an example? My guess is it's some sort of race condition.
Is it possible it possible that your trying to set the original region of the app with fetched data.

A simple fix would be to make sure you have those coordinates before rendering the map.

**Comment by jaysson** [comment]
Yes, I am fetching the user location and animating the map to that region.

```
<MapView
                    style={ styles.map }
                    initialRegion={{
                        latitude: 12.97162345,
                        longitude: 77.59462345,
                        latitudeDelta: 0.0461,
                        longitudeDelta: 0.02105
                    }}
                    ref={(gMap) => this.googleMap = gMap}
                ><MapView.Marker draggable coordinate={this.state.coordinates} onDragEnd={this.markerDragged}/>
```
In constructor:
```
navigator.geolocation.getCurrentPosition(
            (position) => {
                Geocoder.geocodePosition({lat: position.coords.latitude, lng: position.coords.longitude}).then((results)=> {
                    let result = results[0];
                    Address.saveFromMap(result);
                    this.setState({
                        addressText: result.formattedAddress,
                        address: result
                    })
                });
                this.setState({
                    coordinates: {
                        latitude: position.coords.latitude, longitude: position.coords.longitude
                    }
                });
                this.googleMap.animateToRegion({
                    latitude: position.coords.latitude,
                    longitude: position.coords.longitude,
                    latitudeDelta: 0.02305,
                    longitudeDelta: 0.01075
                })
            },
            (error) => alert(error),
            {timeout: 60000, maximumAge: 10000}
        );
```

**Comment by adam-jakiela** [comment]
+1

**Comment by iiitmahesh** [comment]
@jaysson have you solved this. I have same issue..!

**Comment by manikantag** [comment]
For now I m setting the width & height. 

```
< MapView style={{width: Dimensions.get('window').width, height: Dimensions.get('window').height}}>
```

This only requires if I've `MapView` in the route navigation directly. If I render it on any event, it is not required. So, I think we need either the render the map delayed or keep the dimensions as above. `flex:1` is not working, though.

**Comment by nonameolsson** [comment]
I have this issue in #842

**Comment by mattshen** [comment]
Just submitted a PR at Java Code level to fix this type of crashes from happening. 
https://github.com/airbnb/react-native-maps/pull/1521

In my use case, it's not practical to set width and height in the very beginning. So I have to make the fix in Java Code level. 

Any feedbacks are welcome. Hope this would make this ancient issue be closed soon. :)

**Comment by vvscode** [comment]
I still have that error

[bugsnag_error_stacktrace_com.google.maps.api.android.lib6.common.apiexception.c_event_5e3ace9f0055f097f4f80000.txt](https://github.com/react-native-community/react-native-maps/files/4160165/bugsnag_error_stacktrace_com.google.maps.api.android.lib6.common.apiexception.c_event_5e3ace9f0055f097f4f80000.txt)

Any way to fix it from RN side?

**Comment by hudsondaf** [comment]
@mattshen Try using "onMapReady" method from here. @vvscode this could help you too.
https://github.com/react-native-community/react-native-maps/blob/master/docs/mapview.md

I'm using it and it's working for me.

**Comment by antoinepari** [comment]
Try with position : 'absolute' in your style. It solved my problem

**Comment by jafar-jabr** [comment]
I have the same issue today, this fix was:
`style={{ width: '100%', height: '100%' }}`

**Comment by frankitox** [comment]
So, this is still a problem. I'm getting an exception here

https://github.com/react-native-maps/react-native-maps/blob/ae09e685228f3bf5ac0a48c220ab64806f470d15/lib/android/src/main/java/com/airbnb/android/react/maps/AirMapView.java#L752-L753

In my case the problem arises if I disable animations in react-navigation, so I ended up adding a little timer before navigating. Anyone came up with a non shitty solution? At least a way of wrapping the main component. I tried using `getDerivedStateFromError` but it seems is a native crash.

The best solution to me would be to just skip calling `moveCamera` if width or height are zero. But I don't know enough about this code base or the libraries to be sure if that's a good idea.

**Comment by patrik-u** [comment]
Setting map width and height to screen width and height AND doing map initialization (fetching data for markers, etc.) in onLayout() worked for me.
`
            <MapView style={styles.map}
                onLayout={onMapReady}
            ...>
`

```
const onMapReady = async () => {
        if (mapInitialized) {
            return;
        }

        // initialize map data here
        
        setMapInitialized(true);
    };
```

```
const styles = StyleSheet.create({    
    map: {
        position: "absolute",
        width: Dimensions.get("window").width,
        height: Dimensions.get("window").height,
        flex: 1,
    },
});
```
