### ISSUE TITLE
On Map Ready

### ISSUE THREAD

**Issue by codyhazelwood** [airbnb/react-native-maps#246]
It would be really helpful to be able to specify an onMapReady callback, or listen for an event.

Use case:
I need to be able to `showCallout` on the Marker as soon as the map appears.

Workaround:
I'm currently using `setInterval` to check `this.refs.marker` until it's available, then calling `showCallout` and clearing the interval.  This is pretty nasty.

**Comment by christopherdro** [comment]
We can try adding a  `onReady`  prop to MapView and add the following line `this.props.onReady && this.props.onReady()` here https://github.com/lelandrichardson/react-native-maps/blob/798c2b800211c4563069fd373a2ae54937f92cb8/components/MapView.js#L311

Care you give that a shot and see if it works and possibly submit a PR?

Thanks!

**Comment by codyhazelwood** [comment]
Unfortunately this didn't work.  The onReady callback is definitely called, but at that point the `this.refs.marker` property is still undefined.

Example:
```
onMapReady() {
    console.log(this.refs.marker); // Undefined
    setTimeout(()=>console.log(this.refs.marker), 1000); // Displays info about the marker
}
```

I'll try to look into it some more soon.

**Comment by i8wu** [comment]
Did you ever get anything working? @codyhazelwood

**Comment by codyhazelwood** [comment]
@i8wu No, I didn't.  My project stalled, so I haven't put in more work into it.
