### ISSUE TITLE
Need a way to change marker zIndex

### ISSUE THREAD

**Issue by gilbox** [airbnb/react-native-maps#282]
I tried re-ordering the markers but that didn't change the zIndex.

This gif demonstrates the problem, it doesn't actually use any code that tries to change zIndex.

![rn-maps](https://cloud.githubusercontent.com/assets/2136203/15920551/799a5840-2dcf-11e6-98aa-654ee1614129.gif)

**Comment by jvaclavik** [comment]
Has anybody some update for this feature?

**Comment by gilbox** [comment]
it's in the latest release

**Comment by blackPeanut** [comment]
I'm having an issue, when chosen marker rendered over other elements on the map ingnoring their zIndex (for example zIndexed marker renders over your bottom vertical scrollable cards);

**Comment by martsie** [comment]
https://github.com/airbnb/react-native-maps/blob/master/example/examples/ZIndexMarkers.js (for those who see this issue but don't know where to go after "it's in the latest release"

**Comment by simonbengtsson** [comment]
The example posted above uses `zIndex: 1`. This did not work for me but `zIndex: 1000` did.

**Comment by janupruthvi** [comment]
Installing an index for the markers and controlling the zIndex according to that worked for me,
`style={index === selectedMarkerIndex ? {zIndex: 100000, elevation: 100000}: {zIndex: index, elevation: index}}`
In the above code snippet 'index' variable is derived from the loop
