### ISSUE TITLE
Support for Google Maps liteMode

### ISSUE THREAD

**Issue by jonesdar** [airbnb/react-native-maps#300]
Can we have support for liteMode? - this will allow maps to be used in lists etc. on Android.

@jrichardlai has some changes for this https://github.com/lelandrichardson/react-native-maps/compare/master...jrichardlai:android-with-litemode?expand=1
which I'm now using in my fork (https://github.com/jonesdar/react-native-maps/commit/2d98d3f12290a17a46b7d7096419aa8fcc639967) but it would be good to make them generally available.

**Comment by christopherdro** [comment]
This looks good. Can either one of you put it together as a PR?

**Comment by jrichardlai** [comment]
@jonesdar glad this worked well with you, did you encounter any issues? I didn't used it that much, I switched to the caching strategy coming from this branch https://github.com/lelandrichardson/react-native-maps/pull/295. I will make a PR for liteMode if it worked fine for you.

**Comment by jrichardlai** [comment]
@jonesdar ?

**Comment by jonesdar** [comment]
Works fine for me thanks!
Note that the changes in https://github.com/jonesdar/react-native-maps/commit/2d98d3f12290a17a46b7d7096419aa8fcc639967 are more up-to-date than your original changes but a colleague tried to update to the latest version of react-native-maps recently and found some issues so there might be more adjustments needed.

**Comment by spikebrehm** [comment]
Closing with https://github.com/airbnb/react-native-maps/pull/546.
