### ISSUE TITLE
Callout does not stretch based on content with React Native v0.28.0.

### ISSUE THREAD

**Issue by tpisto** [airbnb/react-native-maps#314]
At React Native v0.26.3. the content is visible and callout size varies based on the content size:

```
<MapView.Marker coordinate={marker.latlng}>
  <MapView.Callout>
    <Text> ABCDEFG </TEXT>
  </MapView.Callout>
</MapView.Marker>
```

But in v0.28.0 the callout size does not change:

<img width="191" alt="screen shot 2016-06-22 at 20 48 17" src="https://cloud.githubusercontent.com/assets/226244/16277264/e69e19ae-38ba-11e6-96d8-31e0aceeb887.png">

Tested versions:
react-native-maps v0.5.0
iOS 9.3
Android 6.0.1

**Comment by yonahforst** [comment]
same issue here.

**Comment by jeveloper** [comment]
Sorry to hijack, first of all try 0.6.0 version.
Gotta ask, within your callout, can you add touchable tag and invoke onpress ? ios works, android doesn't
I don't think i have enough understanding if its by design on android.

thanks

**Comment by jeveloper** [comment]
Shouldn't you wrap everything in a <View> ?

**Comment by yonahforst** [comment]
Tried `0.6.0`, still not stretching.
Here's a screenshot: 
![screen shot 2016-06-28 at 13 03 30](https://cloud.githubusercontent.com/assets/1440796/16413168/a3d02084-3d30-11e6-97d7-ea6c51cd70e9.png)

**Comment by jeveloper** [comment]
I noticed that my comment wasn't formatted propertly

It'll work just fine if you use 

``
<View>
... other componentns
</View>
```

Add styling with width, height perhaps

**Comment by yonahforst** [comment]
@jeveloper - they _are_ wrapped in a view. Setting a fixed height and width defeats the purpose. The callout should stretch to fit it's children

**Comment by peterknudsen** [comment]
Have the same problem suddenly appear on 0.6.0 and RN 0.28. And actually I can't even force it to scale the callout. I've tried wrapping everything in Views, removing flex'es and using explicit sizing for everything, but something overrides it and uses wrong scaling for the callout...

**Comment by sweetcharity** [comment]
same issue and onCalloutPress doesn't work too

0.6.0 and RN 0.28

**Comment by harrygreen** [comment]
Same for me:
![image](https://cloud.githubusercontent.com/assets/1975098/16579884/c495d6d8-4299-11e6-8710-81771a25a1d0.png)

```

**Comment by ssmlee04** [comment]
same issue here..

**Comment by gblejman** [comment]
Same with RNM 0.6.0 and RN v0.29.0, setting `<MapView.Callout style={{ flex: 1, position: 'relative' }}> `fixed it for me

**Comment by jsheets** [comment]
@gblejman: The flex and relative position didn't fix it for me. The callouts appeared in weird positions and flickered when panning the map. I had been setting a constant width on the child view inside the `MapView.Callout` but I think that's what broke with the new version.

I was able to fix it by setting a width directly on the callout: `<MapView.Callout style={{ width: 250 }}>`.

**Comment by tiero** [comment]
same issue in RN 0.31 and maps 0.71, moreover touchable is not working

**Comment by esutton** [comment]
Using RN 0.32 and latest 0.8.0 maps

@gblejman Thank you! position: '**relative**' fixes the restricted width.

position: '**relative**' fixes the restricted width:

`<MapView.Callout style={{ flex: 1, position: 'relative' }}>`

<img width="314" alt="screen shot 2016-08-31 at 11 23 38 am" src="https://cloud.githubusercontent.com/assets/6115047/18137435/ec4b49e6-6f6d-11e6-8dcb-07f6b74d1e89.png">

position: '**absolute**' restricts maximum width:

`<MapView.Callout style={{ flex: 1, position: 'absolute`

<img width="310" alt="screen shot 2016-08-31 at 11 29 04 am" src="https://cloud.githubusercontent.com/assets/6115047/18137597/92769730-6f6e-11e6-94c2-7878eb52db20.png">
' }}>

I just need to figure out if can get the pointer back to center of marker. Or maybe just turn off the pointer for now.

Is there a work-around that can fix the offset callout pointer when using position: '**relative**'  work-around for restricted width?

**Comment by jeveloper** [comment]
By the way, there is an offset property that i used to correct position. Checkout documentation , keep in mind android and ios use different properties

**Comment by esutton** [comment]
@jeveloper I tried a couple of props with offset in the name.

I think they were not working because I was using layout **position: relative** because realtive seem to fix the width constraint issue ( but break location position ).

Anyway, with your suggestion on issue https://github.com/lelandrichardson/react-native-maps/issues/427, setting flex -1, and width fixes my issue with the custom callout width.

```
            <MapView.Callout
            style={{ flex: -1, position: 'absolute', width:300}}

```

It was exhausting but I am finally using the latest version of both RN 32 and react-native-maps 0.8.0.  All is good again!

**Comment by jeveloper** [comment]
Awesome :)
In this case i would drop flex all together and set height and width explicitly (dynamic works) using Dimensions 

ios: calloutOffset 
android is anchor 

two totally different

here is what i got:

 calloutOffset={{ x: 0, y: 198 }}
 calloutAnchor={{ x: 0.5, y: 1.5 }}

for the same large image :)

Hope this helps

**Comment by kkgelu** [comment]
Did anyone try to have a custom marker such as an image? It makes the callout not shown at all. RN 0.34 here.

**Comment by esutton** [comment]
No issues on iOS at **0.12.1**

**Comment by AndrewHenderson** [comment]
@kkgelu Make sure you set a height and width on the image.

**Comment by ajbtechservices** [comment]
This is still a problem....

**Comment by jagthedrummer** [comment]
Not sure why this was closed it's still broken.

**Comment by bearkillerPT** [comment]
Hey! I've been trying to work around this all morning and I ended up creating a Callout that imitates the default one but also allows for a custom view, using the same styles.
The component that goes inside the <Marker>:
``` tsx
<Callout tooltip style={markerStyles.callout_container}>
    {customView ? customView :
        <View style={{ ...markerStyles.callout_view }}>
            <Text style={markerStyles.callout_title} numberOfLines={1}>{title}</Text>
            {description &&
                <Text style={markerStyles.callout_description} numberOfLines={1}>{description}</Text>
            }
            <View style={markerStyles.calloutOuterTriangle} />
            <View style={markerStyles.calloutInnerTriangle} />
        </View>
    }
</Callout>
```
The styles:
``` stylesheet

const triangleStyle = StyleSheet.create({
    triangle: {
        position: 'absolute',
        bottom: -10,
        alignSelf: 'center',
        width: 10,
        height: 10,
        backgroundColor: 'transparent',
        borderStyle: 'solid',
        borderTopWidth: 0,
        borderTopColor: 'transparent',
        borderRightColor: 'transparent',
        borderLeftColor: 'transparent',
        transform: [{ rotate: '180deg' }],
    }
});

export const markerStyles = StyleSheet.create({
    marker_container: {
        alignItems: 'center',
        justifyContent: 'center',
    },
    callout_container: {
        alignItems: 'center',
        justifyContent: 'center',
        flexDirection: 'row',
        width: Dimensions.get('window').width * 0.75,
    },
    callout_title: {
        fontWeight: 'bold',
        fontSize: 16,
        alignSelf: 'center',
        marginBottom: 5,
    },
    callout_description: {
        alignSelf: 'center',
        fontSize: 14,
    },
    callout_view: {
        alignSelf: 'center',
        backgroundColor: 'white',
        padding: 5,
        borderRadius: 5,
        borderWidth: 0.5,
        marginBottom: 10,
        position: 'relative',
    },
    calloutOuterTriangle: {
        ...triangleStyle.triangle,
        borderRightWidth: 10,
        borderBottomWidth: 10,
        borderLeftWidth: 10,
        borderBottomColor: 'black',
    },
    calloutInnerTriangle: {
        ...triangleStyle.triangle,
        borderRightWidth: 9.5,
        borderBottomWidth: 9.5,
        borderLeftWidth: 9.5,
        borderBottomColor: 'white',
    },
});
```
Example of the normal view:
![CD32DEB7-D265-4BEF-ABF2-99E4BBDEB4D0](https://user-images.githubusercontent.com/59414986/223762378-eee53e4d-b825-476d-9d44-06096a223f21.png)

Example with a custom view:
![E3495AC6-5049-4AD1-8C74-79BFD89CD964](https://user-images.githubusercontent.com/59414986/223762324-52f7dcba-da2b-40e2-9f88-366c440f4dd9.png)


Hope this helps you!

**Comment by minifisk** [comment]
Add tooltip={true} and you can change size as you please
`
                <Callout
                     tooltip={true}
                     style={{ width: 350, margin: 20, backgroundColor: "white" }}
                >
               ... 
               </Callout>`

**Comment by SumitNalavade** [comment]
> Hey! I've been trying to work around this all morning and I ended up creating a Callout that imitates the default one but also allows for a custom view, responsive up to a width of callout_container.width... The component that goes inside the <Marker>:
> 
> ```tsx
> <Callout tooltip style={markerStyles.callout_container}>
>     {customView ? customView :
>         <View style={markerStyles.callout_view}>
>             <Text style={markerStyles.callout_title} numberOfLines={1}>{title}</Text>
>             {description &&
>                 <Text style={markerStyles.callout_description} numberOfLines={1}>{description}</Text>
>             }
>             <View style={markerStyles.calloutOuterTriangle} />
>             <View style={markerStyles.calloutInnerTriangle} />
>         </View>
>     }
> </Callout>
> ```
> 
> The styles:
> 
> ```tsx
> const triangleStyle = StyleSheet.create({
>     triangle: {
>         position: 'absolute',
>         bottom: -10,
>         alignSelf: 'center',
>         width: 10,
>         height: 10,
>         backgroundColor: 'transparent',
>         borderStyle: 'solid',
>         borderTopWidth: 0,
>         borderTopColor: 'transparent',
>         borderRightColor: 'transparent',
>         borderLeftColor: 'transparent',
>         transform: [{ rotate: '180deg' }],
>     }
> });
> 
> export const markerStyles = StyleSheet.create({
>     marker_container: {
>         alignItems: 'center',
>         justifyContent: 'center',
>     },
>     callout_container: {
>         alignItems: 'center',
>         justifyContent: 'center',
>         flexDirection: 'row',
>         width: Dimensions.get('window').width * 0.75,
>     },
>     callout_title: {
>         fontWeight: 'bold',
>         fontSize: 16,
>         alignSelf: 'center'
>     },
>     callout_description: {
>         alignSelf: 'center',
>         fontSize: 14,
>         marginTop: 5,
>     },
>     callout_view: {
>         alignSelf: 'center',
>         backgroundColor: 'white',
>         padding: 5,
>         borderRadius: 5,
>         borderWidth: 0.5,
>         marginBottom: 10,
>         position: 'relative',
>     },
>     calloutOuterTriangle: {
>         ...triangleStyle.triangle,
>         borderRightWidth: 10,
>         borderBottomWidth: 10,
>         borderLeftWidth: 10,
>         borderBottomColor: 'black',
>     },
>     calloutInnerTriangle: {
>         ...triangleStyle.triangle,
>         borderRightWidth: 9.5,
>         borderBottomWidth: 9.5,
>         borderLeftWidth: 9.5,
>         borderBottomColor: 'white',
>     },
> });
> ```
> 
> Example of the normal view and one without a description:
> 
> <img alt="" height="400" src="https://user-images.githubusercontent.com/59414986/223762378-eee53e4d-b825-476d-9d44-06096a223f21.png"> <img alt="" height="400" src="https://user-images.githubusercontent.com/59414986/223773870-fa617a06-7d0e-4ad7-b5eb-74aced0c9903.jpg">
> 
> Example with a custom view: <img alt="" height="400" src="https://user-images.githubusercontent.com/59414986/223762324-52f7dcba-da2b-40e2-9f88-366c440f4dd9.png">
> 
> Please note that the callout_container.width (75% of the device width), as discussed by other users, is the limit to the width of the inner view and although it's background is transparent (you can only see the callout_view), the element still has that width and clicking on it counts as clicking the callout and not the map! Hope this helps you!

Works for me!

**Comment by Michota** [comment]
nearly a decade later this is still an issue
