### ISSUE TITLE
Google Maps support for iOS

### ISSUE THREAD

**Issue by EricPKerr** [airbnb/react-native-maps#35]
Any plans to implement the Google Maps SDK for iOS so we don't have to use the default Apple Maps?

**Comment by lelandrichardson** [comment]
@EricPKerr no plans at this point. Is there a reason why Google maps should be preferred over MapKit?

**Comment by EricPKerr** [comment]
@lelandrichardson Matter of preference. There aren't  any iOS ports of Google Maps for React Native yet, but the API for this library (markers/callouts as children, etc.) seems like the right approach.

**Comment by thatsmydoing** [comment]
This would also be useful when using Google Maps Places Search or similar. The terms of service say that you can only show the search results on a Google Map.

**Comment by lelandrichardson** [comment]
This is an interesting topic and I'm not sure where to go with it. 

On the one hand using the same maps platform across iOS and Android would certainly be nice and able to provide a more consistent cross-platform experience...

On the other hand, mapkit handles the types of things I want this library to do (ie, arbitrary views inside of  callouts and markers). Google Maps is significantly underpowered relative to mapkit in this regard, the other maps on the android platform just don't provide anything better.

The limitation regarding places search is one I hadn't considered though.

**Comment by XiSmartElf** [comment]
Google map for consistency on IOS nd Android, especially we use a lot of google map API

**Comment by arhmnsh** [comment]
Apple Maps don't have information about places in my region. Would definitely love using Google Maps on iOS.

**Comment by billdozr** [comment]
Wandering what the effort would be to implement support for Google Maps SDK for iOS as an alternative to Apple Maps. Perhaps as a config flag for react-native-maps to decide on which one to build/link with.

Would be keen to hear others thoughts on this and potentially explore this further.

**Comment by bang88** [comment]
+1 
use Google Map or AMap or other Map provider .

**Comment by warmwater** [comment]
+1 Google Maps on iOS

since google maps has richer information in my region....

**Comment by albenik** [comment]
+1 for Google Maps os iOS

**Comment by codyhazelwood** [comment]
+1 Being able to use the Google Places API on both and consistency in the user experience would be a big plus.

**Comment by markfranco** [comment]
+1 for Google Maps os iOS

**Comment by alexsbobylev** [comment]
+1 for Google Maps

**Comment by otech47** [comment]
+1 for Google Maps for iOS

**Comment by lapcchan** [comment]
+1 for Google Maps for iOS

**Comment by bsthomsen** [comment]
+1 google maps for ios

**Comment by EricPKerr** [comment]
@lelandrichardson following up on this - seems to be quite a bit of interest both for map region coverage as well as the ability to integrate the Google Places API

**Comment by lelandrichardson** [comment]
@EricPKerr it turns out I will most likely implement this. I'm not exactly sure how I will do it while maintaining MapKit support though. No timeline at the moment, but if anyone else has started work on this themselves, I'd love to collaborate.

**Comment by java99** [comment]
+1

**Comment by brgarciarivas** [comment]
+1 for Google Maps for iOS

**Comment by tinygipxy** [comment]
+1

**Comment by osungjin** [comment]
How is the issue going on?

**Comment by colus001** [comment]
+100

**Comment by spikebrehm** [comment]
Update: We're actively working on this at Airbnb.

**Comment by lelandrichardson** [comment]
I'm so excited to finally close this issue!

Google Maps support has been added https://github.com/airbnb/react-native-maps/pull/548

Though we are still not at feature parity, we are still actively working on it.

**Comment by nihp** [comment]
How can I add provider for mapkit
