### ISSUE TITLE
Error after bump version to v0.6.0 on Android 

### ISSUE THREAD

**Issue by weixingsun** [airbnb/react-native-maps#353]
It works perfectly on v0.4.2 for a long time
by a naive upgrade, I was lost in the config job. [1 day skipped here]

A dirty hack helped me fixed the following issue, but I am not very confident though:
- Where:
  Script '....../node_modules/react-native-maps/android/lib/gradle-maven-push.gradle' line: 48
- What went wrong:
  A problem occurred configuring project ':react-native-maps'.
  > No such property: GROUP for class: org.gradle.api.publication.maven.internal.deployer.DefaultGroovyMavenDeployer

FIX:
node_modules/react-native-maps/android/lib/build.gradle
//apply from: 'gradle-maven-push.gradle'

does this script do any serious jobs for this module? any impact related for removing this line from my module?

thx,

**Comment by stanlemon** [comment]
I am also seeing this issue after upgrading to 0.6.0 from 0.4.2. I have tried clearing node_modules, reinstalling and relinking and I am still hitting this issue.

**Comment by felipecsl** [comment]
Closed due to inactivity.
