### ISSUE TITLE
Native Component For AirMapMarker does not exist

### ISSUE THREAD

**Issue by arashbi** [airbnb/react-native-maps#398]
Created a new project, and installed react-native-maps. I copied one of the examples to the project. But I get a couple of warnings saying 
Native Component for 'AirMapMarker' does not exist.
Native Component for 'AirMapPolyline' does not exist.

etc...

**Comment by zelll** [comment]
Did you try rnpm link / react-native link ?
Go #371 when you get "file not found" errors.

**Comment by edward8628** [comment]
upgrade to 0.13.0 fixed my issue
