### ISSUE TITLE
Language compile errors in Java 7 -- <> diamond's not supported. Explicit type needed.

### ISSUE THREAD

**Issue by NomadGraphix** [airbnb/react-native-maps#447]
To support the latest Java release, the `Map<String, Float> data = new HashMap<>();` syntax no longer is valid. Replace these implicit types with explicit types to fix the compile errors. `Map<String, Float> data = new HashMap<String,Float>();`

I changed AirMapView, AirMapPolyline, AirMapPolygon, and SizeReportingShadowNode on my own version to fix the compile errors in Android Studio.

**Comment by felipecsl** [comment]
Not an issue, it's a configuration problem on your local environment.
