### ISSUE TITLE
Android crashs on start. No static method zzic

### ISSUE THREAD

**Issue by flexy1994** [airbnb/react-native-maps#452]
I've updated react-native `"react-native": "^0.29.2"` and also added the maps `react-native-maps:0.7.1`. Now the Android-App does not start anymore. 

"Unfortunately, MyApp has stopped."

pidcat:

![bildschirmfoto 2016-08-09 um 11 21 56](https://cloud.githubusercontent.com/assets/1196318/17512077/61677514-5e26-11e6-98fc-5396a6d323fe.png)

I have no clue what this stacktrace wants to tell me.

**Comment by dbanck** [comment]
I'm getting the same error.

It might be working with another play-services version, as suggested here: https://github.com/googlemaps/android-maps-utils/issues/258

**Comment by rstuven** [comment]
@dbanck That's it! I made sure all play-services-* in all packages were the same version and it worked.

**Comment by KGALLET** [comment]
Same error, changed my `app/build.gradle` to :
```
    compile 'com.google.android.gms:play-services-auth:9.4.0' // should be at least 9.0.0
    compile 'com.google.android.gms:play-services-maps:9.4.0'
```

fix the issue

**Comment by ddresch** [comment]
In my case it helped to set the version in my app/build.gradle like that, which forces to use this version.

```
compile ('com.google.android.gms:play-services-gcm:8.4.0') {  force = true;  }
```

Just in case you are not able or don't want to upgrade.

**Comment by Nodonisko** [comment]
I write whole article about this problem:
[https://medium.com/@suchydan/how-to-solve-google-play-services-version-collision-in-gradle-dependencies-ef086ae5c75f#.9l0u84y9t](https://medium.com/@suchydan/how-to-solve-google-play-services-version-collision-in-gradle-dependencies-ef086ae5c75f#.9l0u84y9t)

Hope I helped you :)
