### ISSUE TITLE
Is it possible to change  the position of legalLabelInsets on the bottom left corner of the map, and also changing the location of the button for centering the map to user current Location?

### ISSUE THREAD

**Issue by GuelorEmanuel** [airbnb/react-native-maps#470]

**Comment by RomuxX** [comment]
Hello, 
I'm trying to change legalLabelInsets on Android, but doesn't work.

**Comment by scarlac** [comment]
@RomuxX 
It isn't working because the `legalLabelInset` prop isn't hooked up to anything meaningful. It'll read your value but it won't attempt to move the legal label at all, regardless of platform.

I've got it working locally and will try to submit a push request in the coming days.
