### ISSUE TITLE
Polygon onPress event

### ISSUE THREAD

**Issue by uriklar** [airbnb/react-native-maps#488]
First of all, thanks for the awesome library!  

I couldn't find anything in the docs about it but I was wondering if there's a way to make a Polygon clickable?

Thanks,
Uri

**Comment by ararog** [comment]
I would like to use this feature too, I'm trying to use point-in-polygon after map press but its buggy, its always returning a wrong coordinates!

**Comment by ararog** [comment]
Nevermind, I found this: https://github.com/maxogden/geojson-js-utils

**Comment by uriklar** [comment]
@ararog Mind sharing how this library helped you? Thanks!

**Comment by ararog** [comment]
I added a onPress handler, and inside the event hander I placed this code:

`
        let result = gju.pointInPolygon(
          {'type': 'Point', 'coordinates': point},
          {'type': 'Polygon', 'coordinates': polygon}
        )
        if(result) {
          //inside polygon
        }
`

**Comment by uriklar** [comment]
Thanks! I posted this thread as an answer with some more details here:
[http://stackoverflow.com/questions/39117761/react-native-maps-polygon-onpress-event/39129674?noredirect=1#comment66082684_39129674](url)

**Comment by RasmusKvejborg** [comment]
Try set the tappable prop to true
