### ISSUE TITLE
Way to show user a message what they need to update Google Play Services

### ISSUE THREAD

**Issue by alexHlebnikov** [airbnb/react-native-maps#503]
I've got the problem. I'm using latest version of Google Play Services
```
    compile 'com.google.android.gms:play-services-base:9.4.0'
    compile 'com.google.android.gms:play-services-maps:9.4.0'
```

But there are some users who didn't update Google Play Services on they Android devices. And now my app crashes when they trying to open the map page. 

So is there any way to show system notification or modal to users with old Google Play Services to force to update it? Or is there a way to block the app until user updates Google Play Services?

**Comment by i8wu** [comment]
@alexHlebnikov Have you been able to find a good solution yet?

**Comment by jrichardlai** [comment]
You can use something like this: https://github.com/google/iosched/blob/master/android/src/main/java/com/google/samples/apps/iosched/util/PlayServicesUtils.java and you will call it like this in your `MainActivity.java` PlayServicesUtils.checkGooglePlaySevices(this);

**Comment by i8wu** [comment]
Works great, thanks @jrichardlai !

**Comment by ys-sherzad** [comment]
@jrichardlai I am looking for a similar solution, the link you provided no longer work, could you please update it! thank you.
