### ISSUE TITLE
[iOS] Cannot control render order of markers

### ISSUE THREAD

**Issue by carleryd** [airbnb/react-native-maps#518]
I am using Images inside of Markers, and I want the larger images to be displayed over smaller ones. So I initially sort my list of markers before rendering so that they are sorted by ascending order(I have printed to make sure they are ordered, and reversing the order does not work either).
This doesn't work, on initial render the markers furthest down are prioritized, however when I drag the map just slightly, they reorder correctly.
I tried adding zIndex in style, but this didn't help either.

Has anyone else tried to do the same? Seems like some default marker behavior controlling the initial render.

**Comment by eugenehp** [comment]
So potential if we could have `didAddAnnotationViews` added to `AirMap` which utilises `MKMapView` [interface](https://developer.apple.com/reference/mapkit/mkmapviewdelegate/1452311-mapview?language=objc). We could do something close to sorting using old methods like these:

```objective-c
- (void)mapView:(MKMapView *)mapView didAddAnnotationViews:(NSArray *)views {
   for (MKAnnotationView * annView in views) {
      TopBottomAnnotation * ann = (TopBottomAnnotation *) [annView annotation];
      if ([ann top]) {
         [[annView superview] bringSubviewToFront:annView];
      } else {
         [[annView superview] sendSubviewToBack:annView];
      }
   }

}
```

What do you guys think? @lelandrichardson @spikebrehm @felipecsl @thelordoftheboards

**Comment by spikebrehm** [comment]
@eugenehp that looks good! Can you create a PR?

**Comment by magrinj** [comment]
@eugenehp @spikebrehm any news on this ?

**Comment by thelordoftheboards** [comment]
@magrinj check out 0.11 zIndex. Works well.

**Comment by felipecsl** [comment]
Sounds like this can be closed?

**Comment by magrinj** [comment]
@thelordoftheboards @felipecsl I think this bug can be link at this one #751 no ?
