### ISSUE TITLE
cannot change user location icon

### ISSUE THREAD

**Issue by haibinyu** [airbnb/react-native-maps#540]
Hi, Is there a way to change the default icon of user location in the map?

**Comment by joncursi** [comment]
+1

It would be great if we could have access to the iOS Maps default user location marker, which handles coordinates, which direction you're facing, accuracy radius, etc:

![img_2963](https://cloud.githubusercontent.com/assets/4974609/18532707/de1d9268-7aab-11e6-9d7f-56b2259be067.PNG)

**Comment by joncursi** [comment]
Woops, this is already available with `showsUserLocation`. I had a typo in my code, I was using `showUserLocation` without the "s" and wondering why it wasn't working!

**Comment by joncursi** [comment]
@haibinyu if you want to customize the marker, you could try something like MapView.Circle:

```jsx
              <MapView.Circle
                center={{
                  latitude: userLocation.get('coords').get('latitude'),
                  longitude: userLocation.get('coords').get('longitude'),
                }}
                fillColor={COLOR.paperBlue100.color}
                radius={userLocation.get('coords').get('accuracy')}
                strokeColor={COLOR.paperBlue200.color}
                strokeWidth={2}
              />
```

or MapView.Marker with a custom image, and pass in the user's coordinates.

**Comment by haibinyu** [comment]
@joncursi  thanks for the workround.

**Comment by jojonarte** [comment]
@joncursi yo, I'd like to ask did the userlocation really show up just like that, With the direction arrow? Please let me know how did you do it. I can't seem to get it right, my userlocation only shows the circle without the arrow.

**Comment by joncursi** [comment]
@jojonarte I got the user location circle but no arrow. I think the arrow is not yet supported in RN core

**Comment by jojonarte** [comment]
@joncursi it would be cool man.

**Comment by CrisHemswerthThor** [comment]
I am also getting through it and it is really frustrating. In my case it is shown in IOS but not on android.
Is there any update on this issue?

**Comment by IkaroAlef** [comment]
> @haibinyu if you want to customize the marker, you could try something like MapView.Circle:
> 
> ```js-jsx
>               <MapView.Circle
>                 center={{
>                   latitude: userLocation.get('coords').get('latitude'),
>                   longitude: userLocation.get('coords').get('longitude'),
>                 }}
>                 fillColor={COLOR.paperBlue100.color}
>                 radius={userLocation.get('coords').get('accuracy')}
>                 strokeColor={COLOR.paperBlue200.color}
>                 strokeWidth={2}
>               />
> ```
> 
> or MapView.Marker with a custom image, and pass in the user's coordinates.

how do you keep watching for user location ? I tried Location.watchPositionAsync from Expo Location but it doesn't work as expected. Can you provide details on how do you map user location to the component state?

**Comment by admdni** [comment]
> @haibinyu if you want to customize the marker, you could try something like MapView.Circle:
> 
> ```js-jsx
>               <MapView.Circle
>                 center={{
>                   latitude: userLocation.get('coords').get('latitude'),
>                   longitude: userLocation.get('coords').get('longitude'),
>                 }}
>                 fillColor={COLOR.paperBlue100.color}
>                 radius={userLocation.get('coords').get('accuracy')}
>                 strokeColor={COLOR.paperBlue200.color}
>                 strokeWidth={2}
>               />
> ```
> 
> or MapView.Marker with a custom image, and pass in the user's coordinates.

not working for me :(
