### ISSUE TITLE
How To get User location? should i use geolocation?

### ISSUE THREAD

**Issue by shindol** [airbnb/react-native-maps#552]
i'm newbie on this JS react-native and i use ES6, but i'm poor on JS, i'm learn react native now .. anny suggest or script of project example how i can get the user location? or make my application default show user location when i oppened the application? its any suggest?

[![Question.png](https://s16.postimg.org/w50zff0np/Question.png)](https://postimg.org/image/slf1plxxt/)

**Comment by mvnpgh** [comment]
Itt was basic RN feature.go through  with this link `[.](https://facebook.github.io/react-native/docs/geolocation.html)

**Comment by mvnpgh** [comment]
https://facebook.github.io/react-native/docs/geolocation.html

**Comment by mauron85** [comment]
Check my [exampleApp](https://github.com/mauron85/react-native-background-geolocation-example), which uses react-native-maps and react-native-background-geolocation.
