### ISSUE TITLE
How to dynamically update marker locations?

### ISSUE THREAD

**Issue by Kaihuang724** [airbnb/react-native-maps#565]
Hey guys, I'm trying to implement a map that allows the user to search for locations within their map region, then have the map display those locations as markers based on the map's position

I'm using onRegionChange to get the map's center coordinates. When the user presses a button, a call is made to our API that returns an object with the list of valid locations (number of locations is variable). I need the map to update dynamically after the button is pressed to display markers for the new objects being returned.

Is there any example of how to achieve this? I was following the fitToSuppliedMarkers example, but they have all the marker coordinates hardcoded, as well as the number of markers.

Thanks for any help. Let me know if you guys need anything from me.

**Comment by marko89kv** [comment]
Check out DefaultMarkers.js in the examples, that should cover it. And here's a bit of code that I use:

Inside of `render()` I have this, before the `return()` : 

`var markers = this.state.markers || [];`

It takes care of the case that your state is initially empty. Then, you lay out the markers iteration:

```
{markers.map(marker => (
            <MapView.Marker
              key={marker.uniqueId}
              coordinate={{
                latitude: marker.latitude,
                longitude: marker.longitude
              }}
              title="This is a title"
              description="This is a description"
            >
            <MapView.Callout>
              <View>
                <Text>This is a plain view</Text>
              </View>
            </MapView.Callout>
            </MapView.Marker>
          ))}
```
And, as your `markers` state changes, your markers will render automatically on different positions.
Hope this clears it up a bit.

**Comment by Kaihuang724** [comment]
Thanks for your response! This worked perfectly for my project.

If anyone's interested, this is what the final looks like with the payload as the response given back from the API:

`updateMarkers(payload) {
        var markers = []
        let id = 0
        _.forOwn(payload, function(value, key) {
            markers.push({
                coordinate: value.coordinates,
                key: id++
            });
        })
        this.setState({markers}, ()=> {console.log(this.state.markers)})
    }`

And here's the markers iteration, although I did have to use a componentWillReceiveProps to get the map to re-render, not sure why.

`componentWillReceiveProps(nextProps) {
        this.setState({
            markers: nextProps.markers
        })
    }`

`<MapView
                    ref={ref => { this.map = ref; }}
                    style={styles.map}
                    showsUserLocation={true}
                    followsUserLocation={true}
                    onRegionChange={region => this.updateLocation(region)} >
                    {markers.map(marker => (
                    <MapView.Marker
                        key={marker.key}
                        coordinate={{
                            latitude: Number(marker.coordinate.lat),
                            longitude: Number(marker.coordinate.lon)
                        }}
                        title="This is a title"
                        description="This is a description"
                    >
                    <MapView.Callout>
                        <View>
                            <Text>This is a plain view</Text>
                            </View>
                    </MapView.Callout>
                    </MapView.Marker>`

**Comment by marko89kv** [comment]
A remark - you don't need componentWillReceiveProps to update the markers, I think that the problem is in your `updateMarkers` function, in this line:

`this.setState({markers}, ()=> {console.log(this.state.markers)})`

Just re-initiate the whole array:

`this.setState({markers: newArrayOfCoordinates})`

**Comment by Kaihuang724** [comment]
Got it Marko! Thanks again for your help.

**Comment by michaelstokes** [comment]
Sorry but I'd like to expand on this and ask a further question, with the several map markers you have here, lets say each has a custom child component i.e. MapMarker and MapMarker can have 2 different images based whether that it is the current selected MapMarker or not, now how would one do this please or can you redirect please? Absolutely frustrating, I've not figured it out yet. 

Passing it an active prop which will equal the current selecte map marker and then using componentWilLReceiveProps to get whether the current is selected or not, this works fine but the problem is that with even updating the state to be active or not, the image icon will not rerender nor change, why?

```
    componentWillReceiveProps(nextProps) {
        if (!this.state.initialized) {
            console.log('initialization');            
            this.setState({initialized: true});
        }
        else {
            // If the nextProps.selected prop exists which it will
            if (nextProps.selected) {
                // If the nextProps.selected props id equals the this event id then selected else non-selected.
                if (nextProps.selected.id === nextProps.event.id) {
                    console.log('SELECTED: ' + JSON.stringify(nextProps.selected));
                    // set staae to active
                    this.setState({
                        active: true
                    });
                    console.log(interestIconsSelected[nextProps.event.interest[0]]);
                } else {
                    // set state to not active
                    // console.log('NON-SELECTED: ' + JSON.stringify(nextProps.event));   
                    this.setState({
                        active: false
                    });                
                }
                this.forceUpdate();
            }

```

```
                                    <MapMarker
                                        event={e}
                                        size={this.state.markerSize}
                                        selected={this.state.selectedEvent}

```

etc

```
    renderIcon() {
            return (
                <Image
                    source={this.markerIcon(this.props.event.interest[0])}
                    style={Styles.MapMarker.image}
                />
  
        }
    }
```

Thanks very much!
