### ISSUE TITLE
JSON value of type NSMutableDictionary cannot be converted to CLLocationDegrees

### ISSUE THREAD

**Issue by alexHlebnikov** [airbnb/react-native-maps#568]
Hi, I've got this problem when trying to tap on marker. 
The problem reproduced *only on iOS* and only when *"Debugging JS Remotely" is off*.

I've got this code:
```
if (this.refs.map && nextProps.active) {
    const animatedRegion = new Animated.Region(nextProps.region);
    this.refs.map._component.animateToRegion(animatedRegion);
} else {
    this.setState({region: nextProps.region});
}
```

If I replace ` this.refs.map._component.animateToRegion(animatedRegion);` with `this.setState({region: nextProps.region});`, the problem is gone, but animated zooming to marker is also gone. 
So, maybe the problem is with AnimatedImplementation.js? But then how could it work on Android with the same code?

![screenshot 2016-09-09 12 46 48](https://cloud.githubusercontent.com/assets/1951398/18424718/5d2870b8-78dc-11e6-92b5-d1e533b6e5b6.png)

Checked on RN 0.33.0 - 0.34.0.RC.0, react-native-maps 0.8.2.

**Comment by jrichardlai** [comment]
I think what you want to do is to pass the region as the first param to `animateToRegion` but not as an `Animated.Region`, try just a region.

From what I'm seeing in the doc `animateToRegion(region, duration)` https://github.com/airbnb/react-native-maps/blob/3f9d9bf0fc183b430c2fd4c58d517823c5793a48/docs/mapview.md

**Comment by alexHlebnikov** [comment]
@jrichardlai Yep, you right! I'm just needed to pass `nextProps.region`! Thank you! 

P.S. But I'm still don't get why incorrect variant it works on Android.
