### ISSUE TITLE
compatibility with RN 0.32

### ISSUE THREAD

**Issue by adamjones353** [airbnb/react-native-maps#571]
I have search for this issues and founds some that are close but not the correct versions. 

I am using 
RN 0.32
React 15.3.1
React-native-maps 0.8.2

I have use rnpm to link the libraries but every time i do this I get this error. Also this is for Ios

![screen shot 2016-09-13 at 12 37 41](https://cloud.githubusercontent.com/assets/4711725/18472482/9f45e7d6-79af-11e6-9c02-76d273eb66c5.png)

Anyone else in the same boat

**Comment by JonasWho** [comment]
I am also have problems with RN 0.33 and react-native-maps 0.8.2, I can't compile my project.

Lots of compilation log messages about not finding Google Play Services (which are installed).

**Comment by chrisv95** [comment]
@JonasWho I am getting the same error

**Comment by chrisv95** [comment]
@JonasWho Ok, I figured out a way to make things work.
The error we're receiving may be explained by this quote:

> This problem usually comes from gradle dependency in new components, i can see you have installed react-native-maps

So, those are the steps that you could take in order to make things work:

- Open `./node_modules/react-native-maps/android/build.gradle` and, under 'dependencies', change 9.4.0 into +, so that the dependencies look like this:
```
compile "com.google.android.gms:play-services-base:+"
compile 'com.google.android.gms:play-services-maps:+'
```
- Save the build.gradle file
- Make sure that your React Packager (or the packaging software that you use) is closed
- Make sure that you have no files related to your React Native project opened in any text editor whatsoever
- Open a cmd prompt in your project folder and execute the following command: `cd android/ && ./gradlew clean && cd ../ && react-native run-android`

This cleans your Gradle dependencies, and then builds again the _app:_ and _react-native-maps:_ folders.
It worked for me!

**Comment by julienvincent** [comment]
@christianversloot Thanks! this worked for me.

**Comment by JonasWho** [comment]
@christianversloot thanks a lot, that worked :)

**Comment by sammosampson** [comment]
Guys I am getting a slightly differnt one. ANy ideas?

A problem occurred configuring project ':app'.
> A problem occurred configuring project ':react-native-maps'.
   > Failed to notify project evaluation listener.
      > failed to find Build Tools revision 23.0.3
      > failed to find Build Tools revision 23.0.3

**Comment by julienvincent** [comment]
You probably need to update your android sdk. run `$ android` and update the relevant SDK's

**Comment by sammosampson** [comment]
ah of course thanks

**Comment by adamjones353** [comment]
So after some more testing I have found how to resolve the issues. 
This is for IOS I have not tested on android 

before npm install close the simulator and the npm dependency terminal. Install and link the package, I did the manually because rnpm failed to do it right. After install and link relaunch simulator. This fixed the error for me.

**Comment by sammosampson** [comment]
Me again guys sorry. I upgraded the sdk tools. Now i get this:

:app:dexDebug
Unknown source file : UNEXPECTED TOP-LEVEL EXCEPTION:
Unknown source file : com.android.dex.DexException: Multiple dex files define Landroid/support/v7/appcompat/R$anim;
Unknown source file : 	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
Unknown source file : 	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
Unknown source file : 	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
Unknown source file : 	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
Unknown source file : 	at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
Unknown source file : 	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
Unknown source file : 	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
Unknown source file : 	at com.android.dx.command.dexer.Main.run(Main.java:277)
Unknown source file : 	at com.android.dx.command.dexer.Main.main(Main.java:245)
Unknown source file : 	at com.android.dx.command.Main.main(Main.java:106)

:app:dexDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:dexDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/bin/java'' finished with non-zero exit value 2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by julienvincent** [comment]
Did you try @christianversloot's answer?

**Comment by christianversloot** [comment]
@sammosampson @julienvincent  Indeed, my answer does help to remove the discrepancy between required files and present files used in dexdebug.

**Comment by sammosampson** [comment]
The answer about updating sdk? If so then I did update the build tools
already, is there anything specific/other than that I should update?
