### ISSUE TITLE
Unable to compile on rn0.33.0

### ISSUE THREAD

**Issue by julienvincent** [airbnb/react-native-maps#584]
After linking this package, I am getting the following error:
```
com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/bin/java'' finished with non-zero exit value 2
```

If I remove react-native-maps then I can compile correctly.

**Comment by christianversloot** [comment]
In another issue, you mentioned that a solution that I wrote worked for you. Given the fact that this solution was for 0.33 while it was written in a 0.32 related topic, here is a reference to the solution: [click](https://github.com/airbnb/react-native-maps/issues/571#issuecomment-247037837).

**Comment by julienvincent** [comment]
Yes, I opened this issue before finding your solution. I will close this now in favor of #571
