### ISSUE TITLE
Android: Map not rendering whole world

### ISSUE THREAD

**Issue by CoreyAR** [airbnb/react-native-maps#585]
The MapView is not loading the Western United States, Pacific Ocean and Asia. If I zoom in on the west coast, it will render but the MidWest and Asia don't render zoomed in or out. 

Originally, thought this was related to incorrect Lat, Lng Deltas but the problem occurs without a region set.

```
<MapView
     style={styles.map}
>
    <Marker
        coordinate={{latitude: 37.7588176, longitude: -122.42646}}
     />
 </MapView>
```

![screenshot_20160916-124907](https://cloud.githubusercontent.com/assets/7258308/18595888/499db976-7c0c-11e6-9f37-aadd770f788a.png)

**Comment by christianversloot** [comment]
What is your _styles.map_ stylesheet content?

**Comment by CoreyAR** [comment]
The component is also wrapped in a view element with `style={{flex:1}}`

```
var styles = StyleSheet.create({
map: {
    	flex: 1,
        bottom: 0
  }
})
```

**Comment by christianversloot** [comment]
What happens when you add `import { Dimensions } from 'react-native';` to your map, as well as `var {width,height} = Dimensions.get('window');`, and then, change your style info into:

`map: {
    width: width,
    height: height
}`

.... this works perfectly fine for me :-)

**Comment by CoreyAR** [comment]
Thanks, for the tip. I tried setting the dimensions of the map from the window width and height as you recommended  and the problem persists for me.

**Comment by ihor** [comment]
How did you solve this issue?

**Comment by rahulbhankar786** [comment]
still stuck with this problem. if someone has solution pls let me know....... this eating my performance

**Comment by prasanthvpwyanad** [comment]
Have you solved this issue?
