### ISSUE TITLE
Polylines app crash

### ISSUE THREAD

**Issue by cande1gut** [airbnb/react-native-maps#586]
I just tried the polylines example in my app project and every time I try to draw a polyline, after a certain amount of time, the app crashes.

One more thing is that the polyline itself is not working for me, if I try to draw a polyline with a coordinates array, it marks an error: [#529](https://github.com/airbnb/react-native-maps/issues/529)

**Comment by cande1gut** [comment]
I really don't know what was the problem, but when I reinstalled the component and recompiled the project, I tried it in a real device and it worked without crashing.

**Comment by Wasylmakarenko** [comment]
I have reinstalled the component and recompiled the project.
But I got the same issue.
