### ISSUE TITLE
App crashes when using Google Play Services 9.6

### ISSUE THREAD

**Issue by alexHlebnikov** [airbnb/react-native-maps#596]
There is a new version of GPS [was released](https://developers.google.com/android/guides/releases) on 21 of September. 

So, I'm updated the 'build.gradle' file with this 
```
compile "com.google.android.gms:play-services-base:9.6.0"
compile 'com.google.android.gms:play-services-maps:9.6.0'
```

But after my map is loads It looks like on screenshot. 

![screenshot_20160922-120026](https://cloud.githubusercontent.com/assets/1951398/18738269/7e8bf2f8-80c4-11e6-8bb0-dfe86ba2a8f3.png)

The button on top left corners means "Update". But after I touching map in any place, the app instantly crashes.

~~**Update 1**: the problem occurs only on Android 6.0+ devices. ~~
~~On Android 5.1 map works great.~~
~~Here is some lines from my config:~~
```
compileSdkVersion 24
buildToolsVersion "23.0.3"
minSdkVersion 19
targetSdkVersion 24
```
**Update 2**: seems like the problem occurs because of old version (9.4.52) of Google Play Services installed on my device. You need to update to version 9.6.83 and it will work correctly.

**Comment by alexHlebnikov** [comment]
I've managed how to resolve my issue. 
In two words, you need two separate Activity. The first one invoked after app launches and checks is Google Play Services installed or up to date (see [here] (https://github.com/googlesamples/google-services/blob/master/android/gcm/app/src/main/java/gcm/play/android/samples/com/gcmquickstart/MainActivity.java) for code). 
After that, if GPS are not up to date, you need to show EmptyActivity and the update dialog will be shown. 
After user update GPS the MainActivity must be shown.

**Comment by Clcll** [comment]
How did you solve it?

**Comment by alexHlebnikov** [comment]
Well, as for now I'm switched back to GPS 9.4.0. 
If you need 9.6.0 - I've write short explanation just over there.

**Comment by Nodonisko** [comment]
I write whole article about this problem:
[https://medium.com/@suchydan/how-to-solve-google-play-services-version-collision-in-gradle-dependencies-ef086ae5c75f#.9l0u84y9t](https://medium.com/@suchydan/how-to-solve-google-play-services-version-collision-in-gradle-dependencies-ef086ae5c75f#.9l0u84y9t)

Hope I helped you :)
