### ISSUE TITLE
`MapView` has no propType for native prop `AIRMap.showsMyLocationButton`

### ISSUE THREAD

**Issue by arhmnsh** [airbnb/react-native-maps#598]
Getting this error:
`MapView` has no propType for native prop `AIRMap.showsMyLocationButton` of native type `boolean`
<img width="276" alt="screen shot 2016-09-23 at 12 06 49 am" src="https://cloud.githubusercontent.com/assets/1363724/18766229/de5c7d44-8121-11e6-849e-443502be8b32.png">

I'm on:
"react-native": "^0.33.0",
"react-native-maps": "^0.8.2"

**Comment by nilsonivano** [comment]
Same error here

**Comment by nillo** [comment]
I was struggling with the same issue, so when digging into the code, i saw
that this pullrequest: 
`https://github.com/airbnb/react-native-maps/pull/382`

is in the source of 0.80, but its gone in 0.82, i think something went wrong. i was checking the commits , but i couldnt find a deletion of this code between 0.80 and 0.82,

So maybe somebody could elaborate on this. (why it is removed, while it still expected)

So i tried 2 options,
- add the changes from the pullrequest to react 0.82 myself, which works.
- downgrade to 0.80, and edit node_modules/react-native-maps/android/build.gradle 
and change:

```
dependencies {
  compile 'com.facebook.react:react-native:0.34.0' <--- to match ur version, 
  compile "com.google.android.gms:play-services-base:8.4.0"
  compile 'com.google.android.gms:play-services-maps:8.4.0'
}

```

This fixes the issue,  but im still curious why its not in 0.82

**Comment by lelandrichardson** [comment]
Fixed

**Comment by cinder92** [comment]
same issue here! i
