### ISSUE TITLE
Build fails when not using CocoaPods

### ISSUE THREAD

**Issue by sjmueller** [airbnb/react-native-maps#611]
I have a react-native project that only uses carthage, no cocoapods. When using the latest react-native-maps from master (manual setup), the build fails on `PhaseScriptExecution Check\ Pods\ Manifest.lock`:

![image](https://cloud.githubusercontent.com/assets/29085/18823074/431c998a-836b-11e6-8e15-b6332be545b1.png)

This is most likely due to the build scripts that were added in support of google maps:
https://github.com/airbnb/react-native-maps/commit/f78c0ee674a2a67bc72f843779cd3eb0f16e1675#diff-b5c34708840d3b818caefbc631f8e514R398

Is the plan going forward to only support projects that use cocoapods?

**Comment by simonmitchell** [comment]
Same issue here. We've never used CocoaPods due to issues we had with it, and never plan on doing so. Will you be supporting manual install?

**Comment by mjsisley** [comment]
I am attempting to run with cocoapods, and am also getting this error. I can't run the example project on iOS when following the directions.

**Comment by simonmitchell** [comment]
I managed to get it working with cocoapods in the end (manual was just not going to work at all) but had to make the change in my pull request here: https://github.com/airbnb/react-native-maps/pull/614

**Comment by gilbox** [comment]
My b. I'll look into it.

**Comment by gilbox** [comment]
https://github.com/airbnb/react-native-maps/pull/620

**Comment by mjsisley** [comment]
#620 solved this issue. Thanks @gilbox.

For me, using cocoapods 1.0.1, xcode 8.0, and the example (and instructions) it also took the following (as a record for anyone looking):

1. senpng's comment on https://github.com/facebook/react-native/issues/9014
2. http://stackoverflow.com/questions/26263637/apple-mach-o-linker-error-cocoapods

**Comment by spikebrehm** [comment]
Closed by #620
