### ISSUE TITLE
Support for custom map tiles

### ISSUE THREAD

**Issue by yairbr** [airbnb/react-native-maps#617]
Is there a support for custom map tiles or only earth map is available?

thanks

**Comment by alexHlebnikov** [comment]
The PR with custom tiles overlay is merged in master: https://github.com/airbnb/react-native-maps/pull/595

**Comment by spikebrehm** [comment]
Yes, this has been merged to master, and I'll be cutting a new release today.

**Comment by Stophface** [comment]
@spikebrehm not sure. I think the `Custom Map Tiles` is not working properly.

When I pinch, drag and zoom in/out, it displays the underlaying tiles (on Android Google Maps). Once the pinching, dragging, zooming is done, it only then loads the `Tiles` passed with `<MapView.UrlTile .../>`. It looks like basically it loads two maps. First the underlaying, and then the one passed through `<MapView.UrlTile .../>`.
Here a Video: [https://www.file-upload.net/download-12828114/maps_prob1.mov.html](https://www.file-upload.net/download-12828114/maps_prob1.mov.html) (19.41 MB, download link)
