### ISSUE TITLE
Concern about the semantic versioning 

### ISSUE THREAD

**Issue by charpeni** [airbnb/react-native-maps#619]
Recently Google Play Services dependency has been updated from `8.4.0` to `9.4.0`. #533

I'm concerned about the semantic versioning of this library, since this change has been versioning as a patch : `0.8.0` -> `0.8.1`.

My npm package (`"react-native-maps": "~0.8.0"`) will install `react-native-maps` `0.8.*`, so I expect that only bug fixes will be applied.

I know it's not a big deal for someone who only uses this library without others gms dependencies, but in my case we unfortunately rely on a library that doesn't support the latest version of gms. So begin the unexpected nightmare with transitive dependencies and gradle.

It could easily fixed with the exclude below, but my point was, should we published gms updates as minor rather than patch next time since it can cause some breaking changes with project? Any thoughts?

``` java
compile(project(':react-native-maps')) {
    exclude group: 'com.google.android.gms'
}
```

**Comment by felipecsl** [comment]
@charpeni those are good points and yes, we should be more careful about how transitive dependencies affect this librarie's own semver. I'll close this one, but we'll do our due diligence for future releases. Thanks!
