### ISSUE TITLE
Callouts on image markers working randomly

### ISSUE THREAD

**Issue by alfredoreduarte** [airbnb/react-native-maps#621]
I'm using custom image markers with default callouts, here's my code:

```
<MapView.Marker
	key={location.id}
	coordinate={{
		latitude: ParseDMS(location.latitude),
		longitude: ParseDMS(location.longitude),
	}}
	image={location.locationType == 'food' ? iconFood : iconHerbs}
	title={location.title}
	description={'Vestibulum id ligula porta felis euismod semper.'}
	onPress={() => console.log('lol press')}
	calloutVisible={true}
	>
</MapView.Marker>
```

Callouts only show up on press when there's one marker wrongly fixed to the top left corner, as mentioned in #499 

![screen shot 2016-09-27 at 6 00 31 pm](https://cloud.githubusercontent.com/assets/4633753/18893620/b5b05e24-84dc-11e6-859c-f4b24b94bd8e.png)

Whenever that bug stops showing up (which is random) the markers stop working.

Anybody having the same problem?

**Comment by nazywamsiepawel** [comment]
[https://github.com/airbnb/react-native-maps/issues/553](url)

**Comment by nazywamsiepawel** [comment]
#553
