### ISSUE TITLE
When running for IOS, support for Google maps is on its way?

### ISSUE THREAD

**Issue by mattiLeBlanc** [airbnb/react-native-maps#633]
I was going through the example and saw that for IOS the Apple maps are used. I personally don't like the look of that so I was wondering if I can also for it to run Google maps on IOS?
Is it using a webversion (I see urls to apple maps and google maps in the project) or is using a native component?

I have also been playing with Google SDK example:
https://github.com/Pod-Point-Open-Source/react-native-maps

Not sure what the benefits are of using the SDK over a webversion?

**Comment by jgkim** [comment]
[`Support Google Maps on iOS`](https://github.com/airbnb/react-native-maps/pull/548) has been merged.

**Comment by mattiLeBlanc** [comment]
Splenid. I will have a look.
This is not the sdk but a webversion, right?
Any performance issues over the sdk?

**Comment by jgkim** [comment]
@mattiLeBlanc It's based on the SDK.

**Comment by mattiLeBlanc** [comment]
Awesome!

**Comment by joewoodhouse** [comment]
Has anyone managed to install this properly? I'm trying to follow the install instructions but just keep hitting problems. All I get is "AirGoogleMaps dir must be added to your project". I've tried following the instructions here: https://github.com/airbnb/react-native-maps/blob/master/docs/installation.md (Option1). When it says "Drag the folder" I assume I must be doing that wrong. Am I supposed to be loading the .xcodeproj or .xcworkspace to drag the folders in to? Is it possible to do that on the command-line?

(Apologies, I'm from a cordova background where we don't touch stuff like this :) )

**Comment by ippa** [comment]
I second @joewoodhouse , I can't seem to quite get it right, more detailed instructions would be greatly appreciated.

**Comment by mattiLeBlanc** [comment]
@joewoodhouse maybe have a look at the SDK implementation of this Google maps plugin:
https://github.com/Pod-Point-Open-Source/react-native-maps

I got it to work and I have to do some stuff in Xcode with my project. Maybe you need to do the same for the AirBnB implementation

**Comment by gilbox** [comment]
@joewoodhouse 

> When it says "Drag the folder" I assume I must be doing that wrong. Am I supposed to be loading the .xcodeproj or .xcworkspace to drag the folders in to? Is it possible to do that on the command-line?

Drag the folder from a **finder** window, into your xCode project.

> Could someone just paste the actual Podfile required (rather than this https://github.com/airbnb/react-native-maps/blob/master/example/ios/Podfile which is a smorgasbord of bits of a Podfile, to me?)

If you are using Option1, you can ignore all of the commented code in the example `Podfile`.

**Comment by joewoodhouse** [comment]
@gilbox Yep that's what I've done, and I still get the same errors as above.

**Comment by gilbox** [comment]
@joewoodhouse what errors are you getting? I don't see any above.

**Comment by joewoodhouse** [comment]
"AirGoogleMaps dir must be added to your project"

![screen shot 2016-10-12 at 23 32 21](https://cloud.githubusercontent.com/assets/3168135/19330098/31caea62-90d4-11e6-8304-5e784d025589.png)

**Comment by gilbox** [comment]
hmm 2 thoughts

- This probably has nothing to do w/your Podfile since your app wouldn't even compile if you added the AirGoogleMaps dir without proper Podfile config
- In JS, You can inspect `NativeModules.UIManager` to see what is available. It should have `AIRGoogleMap` and `AIRMap` as properties.

**Comment by joewoodhouse** [comment]
I have AIRMap (and AIRMapMarker, AIRMapCircle etc) but no AIRGoogleMap

**Comment by gilbox** [comment]
you project looks like this?

![image](https://cloud.githubusercontent.com/assets/2136203/19330573/12f096e0-9094-11e6-9f89-cdd4547974ae.png)

**Comment by joewoodhouse** [comment]
![screen shot 2016-10-12 at 23 58 49](https://cloud.githubusercontent.com/assets/3168135/19330697/da5c3cfa-90d7-11e6-9da2-f9f283342afa.png)

**Comment by gilbox** [comment]
excuse my ignorance, but do you know why your folder icons look different? also, if you are installing React as a pod shouldnt it be in the `Pods/` dir (donno if that would make a difference though)

**Comment by joewoodhouse** [comment]
Not sure, I'm on XCode 8.0 if that makes any difference.

I've no idea if I'm installing React as a Pod or not to be honest, which probably isn't very helpful. Basically I've started a new project with `react-native init` then tweaked the index a bit to put a `<MapView provider="google"/>`, and now trying to install this module

**Comment by gilbox** [comment]
- Please remove `AirMaps.xcodeproj` from your project. 
- Are you opening an xcworkspace or an xcodeproj ?

**Comment by joewoodhouse** [comment]
I'm opening the .xcodeproj

**Comment by gilbox** [comment]
Please review the cocoapods docs. You can't use GoogleMaps without using CocoaPods in your project.

**Comment by joewoodhouse** [comment]
On looking I see I am using Pods. 

@ippa Did you get any further with this?

If someone could just write down some command-by-command instructions from `react-native init` to the point where the map runs on iOS using Google Maps, I think that would be really helpful.

**Comment by gilbox** [comment]
> If someone could just write down some command-by-command instructions from react-native init to the point where the map runs on iOS using Google Maps, I think that would be really helpful.

👍 👍 👍 👍  This would be an awesome contribution.

I suggest you become comfortable with `pod install` and understand the difference between xcodeproj and xcodeworkspace.

**Comment by Clcll** [comment]
@joewoodhouse Have you got the result ?

**Comment by joewoodhouse** [comment]
@Clcll Hi no sadly haven't made any progress with this myself. Was hoping one of the developers/contributors would be able to write up some steps.

**Comment by knkevinlai** [comment]
Same problem here, too.

1. I found that in MyProject.xcodeproj > Build Settings > Framework Search Paths:
both Debug and Release are having the paths of "${PODS_ROOT}/GoogleMaps/Subspecs/Base/Frameworks" and "${PODS_ROOT}/GoogleMaps/Subspecs/Maps/Frameworks"
But In the MyProject.xcworkspace (after pod install) under folder tree of Pods, there are no such paths but only "Pods/GoogleMaps/Base/Frameworks" and "Pods/GoogleMaps/Maps/Frameworks"

2. The path "problem" also exists in my MyProject.xcodeproj > Pods > Pods-MyProject.debug.xcconfig and MyProject.release.xcconfig

3. After correcting the paths, problem still exist.

I wonder if this is related to the issue.

Thanks.

**Comment by mersay** [comment]
@gilbox how do you inspect NativeModules.UIManager?

**Comment by Mjuk-Biltvatt** [comment]
@joewoodhouse Did you make any progress with this?

**Comment by AndersenTobias** [comment]
I'm also having issues with this.
