### ISSUE TITLE
Could not find com.google.android.gms:play-services-base:9.4.0.

### ISSUE THREAD

**Issue by srenault** [airbnb/react-native-maps#634]
I just upgraded react native to version `0.35.0-rc.0`.
I upgraded react-native-maps from `git://github.com/chrisknepper/react-native-maps.git#master`
to `git://github.com/airbnb/react-native-maps.git#master`
Now, I'm facing this error: 
Could not find com.google.android.gms:play-services-base:9.4.0.
https://gist.github.com/srenault/17f22b448d4bd880e839abe19b6ff5cf.
Of course, I've installed:
* Extras / Google Play services
* Extras / Google Repository
* Android 6.0 (API 23) / Google APIs Intel x86 Atom System Image Rev. 13

I check in my disk too:
<img width="700" alt="capture d ecran 2016-10-01 a 20 20 09" src="https://cloud.githubusercontent.com/assets/1011289/19016242/b3b58ce4-8814-11e6-9b17-c55bb8aa8d8f.png">

Can someone help me ?

**Comment by willeexl** [comment]
How did you resolve this issue? I'm running into the same problem.

**Comment by benderlidze** [comment]
Got the same error. Any luck?

**Comment by ischenkodv** [comment]
@benderlidze I also encountered this issue today and managed to fix it by upgrading Android SDK.

**Comment by stereodenis** [comment]
If you use Genymotion — this helps me [Genymotion 2.0 Emulators with Google Play support
](https://github.com/codepath/android_guides/wiki/Genymotion-2.0-Emulators-with-Google-Play-support)

**Comment by creativefull** [comment]
up
