### ISSUE TITLE
How to Keep com.google.android.geo.API_KEY out of Version Control History?

### ISSUE THREAD

**Issue by joncursi** [airbnb/react-native-maps#635]
Per the installation instructions, we must add

```
<meta-data
       android:name="com.google.android.geo.API_KEY"
       android:value="KEY_IN_HERE"/>
```

to `AndroidManifest.xml`. However, this file is under version control by default for React Native apps because it defines a lot of necessary configuration for the app to run.

Is there a way to store the private key in a separate file, that can be `.gitignore`d, and create a variable reference to it from `AndroidManifest.xml`?

Going one step further, is it possible to create a more advanced setup that will swap in a development API key when running the android app in debug mode, and a production API key when running the app in release mode? I'm thinking along the lines of a JavaScript switch statement based on environment flag.

Thanks!

**Comment by erickreutz** [comment]
Hey! Check this project out. https://github.com/luggit/react-native-config

**Comment by joncursi** [comment]
Just what I was looking for! Thanks!
