### ISSUE TITLE
Compilation - Java Finished with non-zero exit value 2

### ISSUE THREAD

**Issue by Sachavent** [airbnb/react-native-maps#642]
After the tutorial i have this screen when I execute "react-native run-android":
http://puu.sh/rwL0z/20c8d6138c.png

(Java finished with non-zero exit value after :app:dexDebug Failed)

(Maybe it's due to that I have "react-native-fbsdk" too ... )

I fellew all the tutorial, here I explain what I did : 
`npm install react-native-maps --save`

`$ react-native link`

add in build.gradle : ` compile project(':react-native-maps')`

add in android/settings.gradle : 
```
include ':react-native-maps'
project(':react-native-maps').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-maps/android')
```

add in android/Manifest.xml:
```
   <meta-data
     android:name="com.google.android.geo.API_KEY"
     android:value="{{Your Google maps API Key Here}}"/>
```
and:
```
   <meta-data
       android:name="com.google.android.maps.v2.API_KEY"
       android:value="{{@string/ANDROID_GOOGLE_MAPS_API_KEY}}"/>
```

**Comment by Sachavent** [comment]
I solved it by using gradlew (didn't work first time..)

**Comment by adnanmayo** [comment]
@Sachavent can you show me the gradle file i have the same issue.

**Comment by efkan** [comment]
@adnanmayo I guess Sachavent had used the command of `./gradlew clean`  which doesn't work for me.

**Comment by Sachavent** [comment]
I'm not sure but I think my problem was that I used "2 google API KEY".

I deleted this :    <meta-data
       android:name="com.google.android.maps.v2.API_KEY"
       android:value="{{@string/ANDROID_GOOGLE_MAPS_API_KEY}}"/>

Then I did a gradlew clean and it worked (if I remember well)
