### ISSUE TITLE
Error install on IOS

### ISSUE THREAD

**Issue by agumack** [airbnb/react-native-maps#656]
```
rnpm-link ERR! It seems something went wrong while linking. Error: ENOENT: no such file or directory, open '/Users/macpro/Desktop/mbizvietnam/mobile/mBizPlus/node_modules/react-native-maps/ios/AirGoogleMaps.xcodeproj/project.pbxproj' 
Please file an issue here: https://github.com/rnpm/rnpm/issues 

```

"react-native-maps": "0.10.0",

**Comment by olegdizus** [comment]
Have same issue.

```
rnpm-install ERR! It seems something went wrong while linking. Error: ENOENT: no such file or directory, open '/Users/olegdizus/vezde-app/node_modules/react-native-maps/ios/AirGoogleMaps.xcodeproj/project.pbxproj' 
Please file an issue here: https://github.com/facebook/react-native/issues 
```

```json
  "dependencies": {
    "react": "15.3.2",
    "react-native": "0.34.1",
    "react-native-maps": "^0.10.0"
  }
```

**Comment by ricardokdz** [comment]
I have same issue.

`"react-native-maps": "^0.10.0"`

**Comment by jjzazuet** [comment]
Same here :(.

**Comment by gavinlynch** [comment]
and same again

**Comment by Denys-Bushulyak** [comment]
Join too, have the same.

**Comment by spksoft** [comment]
Me too.

**Comment by gilbox** [comment]
Please paste the full output, including the command you are running.

**Comment by spksoft** [comment]
Full output :

`Sippakorns-MacBook-Air:AwesomeProject spksoft$ npm install --save react-native-maps
AwesomeProject@0.0.1 /Users/spksoft/Projects/React Map Test/AwesomeProject
└── react-native-maps@0.10.0 

Sippakorns-MacBook-Air:AwesomeProject spksoft$ react-native link
rnpm-install info Linking react-native-maps android dependency 
rnpm-install info Android module react-native-maps has been successfully linked 
rnpm-install info Linking react-native-maps ios dependency 
rnpm-install ERR! It seems something went wrong while linking. Error: ENOENT: no such file or directory, open '/Users/spksoft/Projects/React Map Test/AwesomeProject/node_modules/react-native-maps/ios/AirGoogleMaps.xcodeproj/project.pbxproj' 
Please file an issue here: https://github.com/facebook/react-native/issues 

ENOENT: no such file or directory, open '/Users/spksoft/Projects/React Map Test/AwesomeProject/node_modules/react-native-maps/ios/AirGoogleMaps.xcodeproj/project.pbxproj'

Sippakorns-MacBook-Air:AwesomeProject spksoft$ `

**Comment by gilbox** [comment]
Excuse my ignorance, but why are you using `react-native link`? We don't use it for the included example project, AirMapExplorer, nor do we use it at Airbnb.

**Comment by gilbox** [comment]
OK, I looked at this documentation for [rnpm](https://facebook.github.io/react-native/docs/linking-libraries-ios.html). Because of the way we support GoogleMaps, rnpm is not supported right now. Please follow the instructions for setting up your project, and have a look at the included example if you use Option 1.

**Comment by stephanemaillard** [comment]
I used ```react-native link``` because the installation guide suggest to use it https://github.com/airbnb/react-native-maps/blob/master/docs/installation.md

Also rnpm worked until the version 0.8.2 and this could be a problem because if ```react-native link```is used with another library the command will return an error.

**Comment by gilbox** [comment]
> I used ```react-native link``` because the installation guide suggest to use it 

So it does! We should look into that.

**Comment by gilbox** [comment]
I was looking at `ios/` dir in _master_ branch thinking it was the same as `v0.10.0`. However, it's not. Also, my bad for not pushing a tag with `v0.10.0`. When we make another release, `AirGoogleMaps.xcodeproj` will not exist and this bug will go away.

**Comment by joewoodhouse** [comment]
Any ideas when the next release might happen? Or the quickest workaround for now? I seem to have chosen a bad evening to try my google maps hello-world in react-native :) (I want to use google maps on iOS so can't go back too many versions).

**Comment by gilbox** [comment]
trying to get it in today
https://github.com/airbnb/react-native-maps/pull/673

**Comment by joewoodhouse** [comment]
Awesome thanks!

**Comment by gilbox** [comment]
just published `v0.10.1` ... hopefully it's fixed now. That said we still need to figure how we can properly support rnpm link. Currently things will be weird if you try to use `rnpm link` as well as use GoogleMaps.

**Comment by ricardokdz** [comment]
@gilbox 

v0.10.1 works for me on iOS.

`rnpm-install info iOS module react-native-facebook-login is already linked
rnpm-install info Linking react-native-maps ios dependency
rnpm-install info iOS module react-native-maps has been successfully linked`

thx!

**Comment by christopherdro** [comment]
@ricardokdz Thanks for your solution.

**Comment by gilbox** [comment]
Just to clarify my earlier comment, if you follow the instructions to setup react-native-maps with Google maps *and* use rnpm link, afaik you will end up with `AirMaps.xcodeproj` linked in your project *as well* as the `AirMaps/` directory in your project. IOW, it is included 2 times. I don't know if there are any drawbacks to this or not.

**Comment by kiranraj2k** [comment]
![screen shot 2016-12-23 at 6 45 53 pm](https://cloud.githubusercontent.com/assets/20181550/21454644/2312d0c6-c940-11e6-89a2-90796bdeefb4.png)

@gilbox I am not sure whether this is related to what you have specified in your comment.
