### ISSUE TITLE
Android Blank Map.

### ISSUE THREAD

**Issue by Nedvedyy** [airbnb/react-native-maps#661]
I follow the [guide](https://github.com/airbnb/react-native-maps/blob/master/docs/installation.md#Android)  to run on android device. Tried both the android key and web key listed in "Troubleshooting" without luck (except for the step 8 "When starting emulator, make sure you have enabled Wipe user data", as I am using the device.)

My remote console shows, 
```
"ExceptionsManager.js:82Warning: Native component for "AIRMapUrlTile" does not exist
ExceptionsManager.js:82Warning: Native component for "AIRMap" does not exist"

```
My codes are copied below.

```
    return (
    <View style ={styles.container}>
         <MapView
         initialRegion={{
         latitude: 37.78825,
         longitude: -122.4324,
         latitudeDelta: 0.0922,
         longitudeDelta: 0.0421,
         }}
         />
        <Text style={{color: 'green'}}>test text</Text>
    </View>

    );
```
Any suggestion how to troubleshoot the issue?

**Comment by gilbox** [comment]
option 3 is for iOS but you mention android so I'm a little confused.

**Comment by Nedvedyy** [comment]
Pls see the update. I m following Android setup guide

**Comment by Nedvedyy** [comment]
closed. MapView is there but invisible, as I forget to set its dimensions.

**Comment by xegulon** [comment]
Which dimensions are you talking about? I think I have the same problem.

**Comment by xegulon** [comment]
I found it. This example explains things well: https://docs.expo.dev/versions/latest/sdk/map-view/#usage

![image](https://user-images.githubusercontent.com/74178038/152121414-0d99a40a-9e3a-448e-ab78-d0277c2c4829.png)
