### ISSUE TITLE
Getting error/crash in Android - Could not find method com.google.android.gms.common.internal.zzab.zzb

### ISSUE THREAD

**Issue by nbastoWM** [airbnb/react-native-maps#669]
```
W/unknown:ViewManagerPropertyUpdater( 3515): Could not find generated setter for class com.airbnb.android.react.maps.SizeReportingShadowNode
I/dalvikvm( 3515): Could not find method com.google.android.gms.common.internal.zzab.zzb, referenced from method com.google.android.gms.maps.MapsInitializer.initialize
W/dalvikvm( 3515): VFY: unable to resolve static method 31567: Lcom/google/android/gms/common/internal/zzab;.zzb (Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
D/dalvikvm( 3515): VFY: replacing opcode 0x71 at 0x0006
D/AndroidRuntime( 3515): Shutting down VM
W/dalvikvm( 3515): threadid=1: thread exiting with uncaught exception (group=0xa4cbcb20)
E/AndroidRuntime( 3515): FATAL EXCEPTION: main
E/AndroidRuntime( 3515): Process: com.meu112, PID: 3515
E/AndroidRuntime( 3515): java.lang.NoSuchMethodError: com.google.android.gms.common.internal.zzab.zzb
E/AndroidRuntime( 3515): 	at com.google.android.gms.maps.MapsInitializer.initialize(Unknown Source)
E/AndroidRuntime( 3515): 	at com.airbnb.android.react.maps.AirMapManager.createViewInstance(AirMapManager.java:60)
E/AndroidRuntime( 3515): 	at com.airbnb.android.react.maps.AirMapManager.createViewInstance(AirMapManager.java:27)
E/AndroidRuntime( 3515): 	at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:44)
E/AndroidRuntime( 3515): 	at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:211)
E/AndroidRuntime( 3515): 	at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:148)
E/AndroidRuntime( 3515): 	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:890)
E/AndroidRuntime( 3515): 	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:863)
E/AndroidRuntime( 3515): 	at com.facebook.react.uimanager.GuardedChoreographerFrameCallback.doFrame(GuardedChoreographerFrameCallback.java:32)
E/AndroidRuntime( 3515): 	at com.facebook.react.uimanager.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:131)
E/AndroidRuntime( 3515): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:759)
E/AndroidRuntime( 3515): 	at android.view.Choreographer.doCallbacks(Choreographer.java:574)
E/AndroidRuntime( 3515): 	at android.view.Choreographer.doFrame(Choreographer.java:543)
E/AndroidRuntime( 3515): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
E/AndroidRuntime( 3515): 	at android.os.Handler.handleCallback(Handler.java:733)
E/AndroidRuntime( 3515): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime( 3515): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 3515): 	at android.app.ActivityThread.main(ActivityThread.java:5001)
E/AndroidRuntime( 3515): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 3515): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 3515): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
E/AndroidRuntime( 3515): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
E/AndroidRuntime( 3515): 	at dalvik.system.NativeStart.main(Native Method)
W/ActivityManager(  541):   Force finishing activity com.meu112/.MainActivity
D/MobileDataStateTracker(  541): default: setPolicyDataEnable(enabled=true)
W/ActivityManager(  541): Activity pause timeout for ActivityRecord{52d61494 u0 com.meu112/.MainActivity t15 f}
W/EGL_genymotion(  720): eglSurfaceAttrib not implemented
D/MobileDataStateTracker(  541): default: setPolicyDataEnable(enabled=true)
D/Genymotion(   76): Received Ping
D/MobileDataStateTracker(  541): default: setPolicyDataEnable(enabled=true)
D/ConnectivityService(  541): Sampling interval elapsed, updating statistics ..
D/ConnectivityService(  541): Done.
```

I saw a similar error in issue #164 and I'm using push-notifications also, but I checked and the dependencies in the current version are only for gcm:
```compile 'com.google.android.gms:play-services-gcm:+' ```

I'm using:
"react-native": "0.33.0",
"react-native-maps": "^0.8.2",
"react-native-push-notification": "^2.1.1",

**Comment by priezz** [comment]
I have started to suffer from crashes recently as well. Can't explain the reason, but adding the following lines to the `app/build.gradle` fixes the issue:
```
    compile "com.google.android.gms:play-services-base:+"
    compile 'com.google.android.gms:play-services-location:+'
    compile 'com.google.android.gms:play-services-maps:+'
```

**Comment by sixcycle-personal** [comment]
I confirm priezz's solution after wasting a whole day facing the same error. I'm using Android Studio 2.0 and the SDK manager doesn't allow me to download older versions of google play services which this library is using. Adding the ":+" instead of a fixed version number allows the project to use the newest version available.

**Comment by nbastoWM** [comment]
Great! It works for me too.
I tried several versions but never with the ':+'.
Thanks!

**Comment by beydogan** [comment]
@priezz thank you for reply!! I spent more than 3-4 hours on this issue, tried so many different solution never worked, your solution fixed it. Thanks!

**Comment by MatthiasDebaere** [comment]
Is this an official fix? If so, can this be committed to the module? because now, everytime we do npm install, the build.gradle file is overwritten and each time it has to be adjusted manually..

**Comment by priezz** [comment]
@MattiasDebaere, you should make this change in your
`android/app/build.gradle` file, not in the one in the
package.![](https://link.nylas.com/open/agwwlmp32ok2sb4y8ns0ugace/local-204854
b3-3058?r=cmVwbHkrMDA2NWVlZmQxZmM0ZDVjNDM5NmI1MGNiOGZjYTFjODRiYjRmYWQyM2Q0MDVm
NTIxOTJjZjAwMDAwMDAxMTQzMTY5ZmU5MmExNjljZTBhZDc0ZDIyQHJlcGx5LmdpdGh1Yi5jb20=)

  
On ноя 2 2016, at 11:46 утра, MatthiasDebaere <notifications@github.com>
wrote:  

> Is this an official fix? If so, can this be committed to the module? because
now, everytime we do npm install, the build.gradle file is overwritten and
each time it has to be adjusted manually..

>

> —  
You are receiving this because you were mentioned.  
Reply to this email directly, [view it on GitHub](https://github.com/airbnb
/react-native-maps/issues/669#issuecomment-257804908&r=cmVwbHkrMDA2NWVlZmQxZmM
0ZDVjNDM5NmI1MGNiOGZjYTFjODRiYjRmYWQyM2Q0MDVmNTIxOTJjZjAwMDAwMDAxMTQzMTY5ZmU5M
mExNjljZTBhZDc0ZDIyQHJlcGx5LmdpdGh1Yi5jb20=), or [mute the
thread](https://github.com/notifications/unsubscribe-
auth/AGXu_SJ65UDGkr2ju7dXXcN6sR_GBcz2ks5q6E3-gaJpZM4KR-pU&r=cmVwbHkrMDA2NWVlZm
QxZmM0ZDVjNDM5NmI1MGNiOGZjYTFjODRiYjRmYWQyM2Q0MDVmNTIxOTJjZjAwMDAwMDAxMTQzMTY5
ZmU5MmExNjljZTBhZDc0ZDIyQHJlcGx5LmdpdGh1Yi5jb20=).![](https://github.com/notif
ications/beacon/AGXu_birf468WLF1KYPaD7E3LL0Gh0Ucks5q6E3-gaJpZM4KR-pU.gif)

**Comment by MatthiasDebaere** [comment]
Ah yes, that's it, thank you :)

**Comment by cavilaho** [comment]
Using `react-native-fcm: ^2.3.2` when I apply this solution:
```
compile "com.google.android.gms:play-services-base:+"
compile 'com.google.android.gms:play-services-location:+'
compile 'com.google.android.gms:play-services-maps:+'
```

Throws me this error:
```
Found com.google.android.gms:play-services-base:+, but version 9.0.0 is needed for the google-services plugin.
Found com.google.android.gms:play-services-location:+, but version 9.0.0 is needed for the google-services plugin.
Found com.google.android.gms:play-services-maps:+, but version 9.0.0 is needed for the google-services plugin.
```

Cause the `react-native-fcm` library requires 
```
apply plugin: "com.android.application"
apply plugin: 'com.google.gms.google-services'
```

Any idea how to solve this?

**Comment by Nodonisko** [comment]
I write whole article about this problem:
[https://medium.com/@suchydan/how-to-solve-google-play-services-version-collision-in-gradle-dependencies-ef086ae5c75f#.9l0u84y9t](https://medium.com/@suchydan/how-to-solve-google-play-services-version-collision-in-gradle-dependencies-ef086ae5c75f#.9l0u84y9t)

Hope I helped you :)

**Comment by tywoodpav** [comment]
Mine was failing after the change to `+` from `10.2.4`. In `android/app/build.gradle`:

    compile "com.google.android.gms:play-services-base:10.2.4"
    compile "com.google.android.gms:play-services-location:10.2.4"
    compile "com.google.android.gms:play-services-maps:10.2.4"
    compile "com.google.firebase:firebase-core:11.0.1"

Changing instead to `11.0.1` solved the problem. **It has to match firebase.** 

    compile "com.google.android.gms:play-services-base:11.0.1"
    compile "com.google.android.gms:play-services-location:11.0.1"
    compile "com.google.android.gms:play-services-maps:11.0.1"
    compile "com.google.firebase:firebase-core:11.0.1"

Possibly changing firebase to `+` will solve it, but I dont want to wait for gradle sync lol

**Comment by codesinghanoop** [comment]
If anyone stuck in this, Below is the solution for it. 

I also faced the same issue when i upgraded android build tools for some other third party so, i resolved it by keeping the latest version of build tools equal to maps and base services. Below is what i'm referring to.

compile "com.google.android.gms:play-services-base:11.0.4" 
compile "com.google.android.gms:play-services-maps:11.0.4"

**Comment by kalexmills** [comment]
It's 2018 and this issue still affects developers. No root cause other than missing dependencies? Why do the missing deps not show up at compile time?
