### ISSUE TITLE
What changed in 10??

### ISSUE THREAD

**Issue by npomfret** [airbnb/react-native-maps#671]
Sorry, this isn't an issue, just a question (don't know where else to ask).

I've noticed there's been quite a big jump in version numbers recently.  I'm usually fairly up to date but I'm currently using 0.8.2 and I see that the latest is now at v10.x.  That's quite a big jump, I assume it brings some breaking changes.

What important stuff has changed since the last 0.8x release?  Particularly I'm interested in changes to setup / configuration.

**Comment by stephanemaillard** [comment]
Apparently two separate updates with breaking changes https://github.com/airbnb/react-native-maps/blob/master/CHANGELOG.md
A breaking change forces a version number to upgrade from x.y.z to x.(y+1).0
