### ISSUE TITLE
How to zoom to current location?

### ISSUE THREAD

**Issue by DylanRichardPearson** [airbnb/react-native-maps#674]
What is the best method to zoom into the device's current location on the map? Would it be to use fitToCoordinates and pass the current location coords into it?

**Comment by Clcll** [comment]
@DylanRichardPearson, 
You need playing with         
Example:
            let currentLocation = {
                latitude: lat,
                longitude: lng,
                latitudeDelta: 0.0041,
                longitudeDelta: 0.0021
            };

**Comment by richardhuang09** [comment]
Are you working with iOS or Android?  With iOS, you can simply add "followsUserLocation" to your MapView.

**Comment by eamonpenland** [comment]
what about android?

**Comment by christopherdro** [comment]
@Clcll Answer is correct.

If you have the proper latitude and longitude coordinates you can adjust the delta values for zooming.

This applies to both iOS and Android.

**Comment by richardhuang09** [comment]
Do you need to set the lat and lng variables with the geolocation API or do those default to the user location in this context?

**Comment by christopherdro** [comment]
You will have to set it using the geo location API.

**Comment by DylanRichardPearson** [comment]
Thanks!

**Comment by hanpanpan200** [comment]
Hi @christopherdro 

```
const DEFAULT_PADDING = { top: 40, right: 40, bottom: 40, left: 40 }

navigator.geolocation.getCurrentPosition(
      ({coords}) => {
        this.map.fitToCoordinates([coords], {
          edgePadding: DEFAULT_PADDING,
          animated: true,
       })
      },
      (error) => alert('Error: Are location services on?'),
      {enableHighAccuracy: true}
    )
```

But actually, now the map can't focus on my current location automatically because the zoom scale is wrong. Do you know what can I do to solve this problem?

**Comment by chrismcleod** [comment]
@hanpanpan200 animateToRegion can center on a coordinate and allows you to set deltas:

```javascript
    navigator.geolocation.getCurrentPosition(
      ({ coords }) => {
        if (this.map) {
          this.map.animateToRegion({
            latitude: coords.latitude,
            longitude: coords.longitude,
            latitudeDelta: 0.005,
            longitudeDelta: 0.005
          })
        }
      },
      (error) => alert('Error: Are location services on?'),
      { enableHighAccuracy: true }
    )
```
