### ISSUE TITLE
No Visible @interface for 'RCTImageLoader' in RN 35

### ISSUE THREAD

**Issue by tharrington** [airbnb/react-native-maps#679]
I just upgraded to react native 35 and v0.10.1 of react-native-maps. I am not getting this error when trying to build:

`/Users/user/Desktop/AwesomeProject/node_modules/react-native-maps/ios/AirMaps/AIRMapMarker.m:212:58: No visible @interface for 'RCTImageLoader' declares the selector 'loadImageWithURLRequest:size:scale:clipped:resizeMode:progressBlock:completionBlock:'`

**Comment by eugenehp** [comment]
@tharrington possible fix https://github.com/airbnb/react-native-maps/pull/680

**Comment by ippa** [comment]
#680 fixes this for me

**Comment by worldlyjohn** [comment]
@tharrington im getting same error, but without line numbers and complete error.  did you set some flags to show this?

**Comment by tharrington** [comment]
@worldlyjohn - No, the error in Xcode takes you directly to the relevant line. #680 fixes this problem. 
Thanks!

**Comment by alaingoldman** [comment]
This fixed it for me thanks!
