### ISSUE TITLE
Errors when using on Android

### ISSUE THREAD

**Issue by chadwilken** [airbnb/react-native-maps#681]
I have everything working perfectly on iOS with a fullscreen map view. On Android however I get various errors such as `animateToCoordinate` and `animateToRegion` says it's being called on a null object. Most recently I am getting:
![screenshot](https://dl.dropboxusercontent.com/u/13238118/Screenshot_2016-10-11-16-32-28.png)

We are on RN 0.32.1 with react-native-maps 0.8.2.  Any help would be appreciated.

**Comment by raubas** [comment]
I'm having similar issues, lots of:
 map.ad.R.d
and 
animateToRegion

[stack trace](https://gist.github.com/raubas/fb3961e1117f7ac3dea8b54ea9e5bbe2)

**Comment by Clcll** [comment]
@raubas , @chadwilken  Did you solve the issue ?

**Comment by chadwilken** [comment]
@Clcll you can close if you wish, I was able to get around this by setting the initialRegion to a non 0 coordinate and removing jumping to the users location after obtaining coordinates.
