### ISSUE TITLE
Animate marker blinks on react-native-maps@0.10.1

### ISSUE THREAD

**Issue by carleryd** [airbnb/react-native-maps#683]
I have a marker that animates between locations on the map, it works using the latest MapView.AnimatedRegion value as the coordinate of the marker. However, the marker is blinking when animating, and lags on both Android and iOS in debug mode. It works good enough on iOS production but is still very laggy on Android production build.

Has anyone experienced this? Here is a gist of my animating marker, which is wrapped inside of a parent MapView https://gist.github.com/carleryd/4923f57294b7d46acddc137f5ff1b47d

**Comment by keung725** [comment]
Same as me?

https://github.com/airbnb/react-native-maps/issues/678

**Comment by kkgelu** [comment]
Not sure if it's the same issue. I have a list of custom markers rendered on the map, when dragging(pressing and moving) on the map (not dragging or pressing the markers), the markers start blinking and jumping, looks like re-rendering. This happens after upgrading to 0.11.0, it was not happening on 0.8.x. Tested iOS.

**Comment by keung725** [comment]
Yes. I have also tried on 0.8.2. It works. I think we are getting the same bugs.

**Comment by kkgelu** [comment]
Should mention that it does not happen when the default pin is used.

**Comment by athaeryn** [comment]
I'm also seeing this with custom markers that render an `<Image/>`. Not using the AnimatedRegion.

**Comment by jatsrt** [comment]
0.11.0 on Android - GoogleMaps and iOS - Maps
Blinking when any change in map position, zoom, etc.  
Custom view marker using just View and Text
![blinking](https://cloud.githubusercontent.com/assets/635242/19489222/608d6c2c-9538-11e6-853e-6ab261e045dc.gif)

**Comment by kkgelu** [comment]
I figured something, it could be related to _onRegionChangeComplete_ or _onPress_.  I guess you _setState_ in these methods and consequently the re-rendering happens. I commented out the _onRegionChangeComplete_ and _onPress_, the blinking is gone. 

So as a workaround, I am checking if I actually need to _setState_ in _onRegionChangeComplete_ or _onPress_, it largely improved the situation now.

**Comment by carleryd** [comment]
I have been able to work around this problem by telling my custom marker to not re-render in shouldComponentUpdate. However, I now find myself needing to update something in the marker and my image inside of `MapView.Marker Image MapView.Marker` is constantly recreated every time a prop to it changes, which makes the marker blink...

**Comment by pauwlsky** [comment]
I am also having the same issue and another when using an image source. 

Not only do my markers blink, but updated marker descriptions no longer show when selecting the marker.

I thought this had to do with how my markers were updating on each _onRegionChangeComplete_ , since my app is using both redux state and making ajax calls to our locations api once each function fires. 

This problem doesn't happen as much when not using image for the pin, but still does occur sometimes.

My code is below: 

`class Map extends Component {

  render() {
    return (
      <View style={styles.container}>
        <SearchField navigator={this.props.navigator}/>
        <View style={styles.mapContainer}>
        <MapView
            ref={ref => { this.map = ref; }}
            style={styles.map}
            region={this.props.coords}
            onRegionChange={this.regionUpdate.bind(this)}
            onRegionChangeComplete={this.annotationUpdate.bind(this)}
        >
          {this.props.markers.map((marker, i)=> (
              <MapView.Marker
                  image={require('../img/marker_blue.png')}
                  key={i}
                  coordinate={marker.latlng}
                  title={marker.title}
                  description={marker.address_display + ' ' + marker.distance}
              />
          ))}
        </MapView>
      </View>
        {this.parkListRender()}
    </View>
    )
  }


//onPress={this.scrollToMarker.bind(this)}
//
// scrollToMarker(region) {
//     this.map.animateToCoordinate(region.nativeEvent.coordinate, 100);
//   }


  regionUpdate(region) {
    // console.log('updating region')
      this.props.dispatch({
        type: 'UPDATE_REGION',
        state: region
      });
  }

  annotationUpdate(region) {
    setTimeout(()=> {
      // console.log('updating annotations');
      var DIST = Math.ceil(this.props.coords.latitudeDelta * 69/2);
      var LAT = this.props.coords.latitude;
      var LNG = this.props.coords.longitude;
      // console.log('lat: ' + LAT, 'long: ' + LNG, 'dist: ' + DIST);
      updateParksAction(LAT , LNG, DIST).done((state) => {
        this.props.dispatch({type: 'UPDATE_ANNOTATIONS', state: state});
        console.log(this.props);
      });
    }, 2000)
  }`

**Comment by tlvenn** [comment]
I can confirm that this rather annoying bug is still present in 0.11.0 :(

@lelandrichardson @spikebrehm any idea on the root issue and where the regression might be located ? Thanks !

**Comment by dot3bumpmap** [comment]
I also see jumping\blinking every time state updates. Using vector icons as pins. Problem appeared after upgrading from 0.8.x version.  I was using shouldComponentUpdate to optimise rendering, but now it seems markers are re-created each time state changes so shouldComponentUpdate is not called.

**Comment by DennisMG** [comment]
try fix #716! it worked for me on iOS and Android!

**Comment by athaeryn** [comment]
#716 works for me on both platforms as well. 👍

**Comment by cbartondock** [comment]
Seeing this issue for a custom marker using an Image child in react-native-maps 0.15.1. Potential regression.

**Comment by cbartondock** [comment]
Nope. Nevermind. I was giving them key=Math.random() to lazily avoid the repeat keys issue. My own silly fault!
