### ISSUE TITLE
iOS Build Failed (RN0.35 + r-n-maps 0.10.1)

### ISSUE THREAD

**Issue by worldlyjohn** [airbnb/react-native-maps#685]
I've read #411 but this is happening with the latest builds.  Was working on RN-0.33 with react-native-maps-0.8.2.  I unlinked and relinked the maps package.

What else am I missing?  Incompatible versions?

```
dependencies:
    "react": "15.3.1",
    "react-native": "0.35.0",
    "react-native-maps": "^0.10.1",

```

```
The following build commands failed:
	CompileC /Users/john/Sites/travelco-mobile/ios/build/Build/Intermediates/AirMaps.build/Debug-iphonesimulator/AirMaps.build/Objects-normal/x86_64/AIRMapMarker.o AirMaps/AIRMapMarker.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler

```

**Comment by worldlyjohn** [comment]
found possible fix at #680 but not in a release yet

**Comment by eugenehp** [comment]
@worldlyjohn have you tried to clear your DerivedData?

**Comment by worldlyjohn** [comment]
well #680 fixed the issue.  i could clear out DerivedData, but not sure that would fix the issue of missing `partialLoadBlock:nil`

**Comment by Clcll** [comment]
Application is running but with this error, how can I fix it ? Thx


Check dependencies

** BUILD FAILED **


The following build commands failed:
	CompileC  .../App/ios/build/Build/Intermediates/AirMaps.build/Debug-iphonesimulator/AirMaps.build/Objects-normal/x86_64/AIRMapManager.o AirMaps/AIRMapManager.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
	CompileC .../App/ios/build/Build/Intermediates/AirMaps.build/Debug-iphonesimulator/AirMaps.build/Objects-normal/x86_64/AIRMapPolygonManager.o AirMaps/AIRMapPolygonManager.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
	CompileC .../App/ios/build/Build/Intermediates/AirMaps.build/Debug-iphonesimulator/AirMaps.build/Objects-normal/x86_64/AIRMapPolygon.o AirMaps/AIRMapPolygon.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler

**Comment by eugenehp** [comment]
@Clcll have you tried to remove DerivedData and then do a clean up build?

**Comment by christopherdro** [comment]
11.0 will be released shortly with the appropriate fix.

You can try pointing to master in the meantime.

**Comment by pt-mpb** [comment]
Hi, I'm using 0.11.0 and I'm still getting this issue. Wasn't 0.11.0 supposed to fix this?

**Comment by eugenehp** [comment]
@pt-mbp what kind of issue are you having? Have you tried to clean up your
NPM cache?

**Comment by pt-mpb** [comment]
@eugenehp already tried that. Didn't work.
My iOS project is not building. I'm getting a compile time error on .../node_modules/react-native-maps/ios/AirMaps/Callout/SMCalloutView.h Line 43
Cannot find protocol declaration from 'CAAnimationDelegate'

**Comment by willyyang** [comment]
why is this issue closed? Having same issue.

**Comment by ProteanDev** [comment]
@christopherdro and @worldlyjohn  Issue is back.
