### ISSUE TITLE
Can use Amap  Instead of GoogleMap on Android?

### ISSUE THREAD

**Issue by liudakehpu** [airbnb/react-native-maps#688]
I am very sorry that GoogleMap Service was prohibit  in our country.But I'm very interested in this rn-maps.Is there any other way to show the Map on Android? Thank you very much!

**Comment by alexHlebnikov** [comment]
Hi! You should try https://github.com/mapbox/react-native-mapbox-gl

**Comment by christopherdro** [comment]
Hi @liudakehpu!

Sorry to hear that. @alexHlebnikov suggestion is what I would try as well.

Best of luck!
