### ISSUE TITLE
How to switch to Google Maps on iOS?

### ISSUE THREAD

**Issue by kelset** [airbnb/react-native-maps#693]
In the documentation there is only the explanation on how to install the dependencies in order to make it works - more or less - but there is no clear way to understand how to actually force iOS to use google maps (or maybe I've simply completely missed it).

By going through the example [App.js](https://github.com/airbnb/react-native-maps/blob/master/example/App.js) code, it seems that it is related to two elements:

`import { PROVIDER_GOOGLE, PROVIDER_DEFAULT } from 'react-native-maps';`

And passing to a generic Component provider what imported:

`{Component && <Component provider={useGoogleMaps ? PROVIDER_GOOGLE : PROVIDER_DEFAULT} />}`

But this is quite abstract, I'm not sure I get the grasp of it. 
Does it mean that in a less complex example I'd simply write `<MapView provider={PROVIDER_GOOGLE} >` kind of thing? Or it is something more complex?

**Comment by gilbox** [comment]
via the `provider` prop:

```
provider={MapView.PROVIDER_GOOGLE}
```

**Comment by mersay** [comment]
I have dragged the AirGoogleMaps folder to my proj, but it is still consoling an error "AirGoogleMaps dir must be added to your xCode project to support GoogleMaps on iOS"? i have already installed GoogleMaps using pod install. any insights??

**Comment by kelset** [comment]
When you dragged the folder in your project, have you selected the correct targets?

Moreover, apart from doing what wrote in the Installation guide you have to add to the Framework Search Libraries for the project `$(inherited)` (in Build Setting).

**Comment by pascalc** [comment]
@kelset Could you provide more detailed instructions? I'm getting the same error as @mersay and I can't tell whether I've dragged the AirGoogleMaps and AirMaps to the correct place in XCode, and I can't find how to add Framework Search Libraries in Build Settings either. Thank you!

**Comment by kelset** [comment]
Hey @pascalc I won't have much time until Saturday to write a proper answer - so if you need a hand "urgently" pm [me](https://twitter.com/Kelset) on twitter.

**Comment by pascalc** [comment]
@kelset not urgent for me so no rush! I think more detailed instructions will help a lot of people so thanks for taking the time!

**Comment by pascalc** [comment]
@kelset @mersay Got it working by copying the setup of AirMaps and AirGoogleMaps in the [AirMapsExplorer](https://github.com/airbnb/react-native-maps/tree/master/example) example project:

1. *Don't* do `react-native link` (do `react-native unlink react-native-maps` if you already have)
2. Drop the AirMaps and AirGoogleMaps folders into the root of your project 
![image](https://cloud.githubusercontent.com/assets/193289/20193749/5936f40a-a787-11e6-9203-4d98841713b1.png)

3. Select "Create groups" instead of "Create folder references" while dropping them ![image](https://cloud.githubusercontent.com/assets/193289/20193589/92b480ae-a786-11e6-8b08-e64493ab6ff7.png)
4. Add your API key to AppDelegate.m as in [AirMapsExplorer](https://github.com/airbnb/react-native-maps/blob/master/example/ios/AirMapsExplorer/AppDelegate.m)
5. Don't forget this crazy style-hack 😉 
![image](https://cloud.githubusercontent.com/assets/193289/20193793/8579527e-a787-11e6-8e94-9b5d4295463e.png)

**Comment by gilbox** [comment]
You can use `StyleSheet.absoluteFill` instead of your "style-hack"

**Comment by nrathi** [comment]
Thank you @pascalc!! I've added some end-to-end instructions below. Hopefully they'll be of use to others! 

1) Install cocoapods: `sudo gem install cocoapods`
2) Copy and paste the [example Podfile](https://github.com/airbnb/react-native-maps/blob/master/example/ios/Podfile) to your `{YOUR_PROJECT}/ios` directory and change `AirMapsExplorer` to `{YOUR_PROJECT}` in the file.
3) Do not run `react-native-link`; If you do, simply run `react-native unlink react-native-maps` (you will never re-link).
4) Run `pod install` to generate the Podfile.lock file (this may take some time).
5) Open `{YOUR_PROJECT}/ios/{YOUR_PROJECT}.xcodeproj` in Xcode.
6) Copy and paste the AirMaps and AirGoogleMaps directories from `{YOUR_PROJECT}/node_modules/react-native-maps/ios/` as children of the root `{YOUR_PROJECT}` folder in Xcode; make sure to "Create groups" instead of "Create folder references".
7) Add the Google Maps import and your API key to AppDelegate.m as in [AirMapsExplorer](https://github.com/airbnb/react-native-maps/blob/master/example/ios/AirMapsExplorer/AppDelegate.m).
8) Include these two props in MapView:
```
<MapView
  provider={MapView.PROVIDER_GOOGLE}
  style={StyleSheet.absoluteFill}
  ...
```

**Comment by yianyang** [comment]
but why when i add the Google Maps import there has an error "GoogleMaps/GoogleMaps.h" file not found

**Comment by kelset** [comment]
I totally forgot about this post, sorry @pascalc.
That said, you and @nrathi did a really good job at writing down the proper steps to install GMaps.
For the sake of argument, if anyone would do a PR to the [installation instruction](https://github.com/airbnb/react-native-maps/blob/master/docs/installation.md) IMHO should take @nrathi  list and do a couple of modifications:

1. change step 6 to open` {YOUR_PROJECT}/ios/{YOUR_PROJECT}.xcworkspace` instead of `{YOUR_PROJECT}/ios/{YOUR_PROJECT}.xcodeproj` - it is best practise for when Pods are installed if I can recall correctly
2. substitute step 7 with steps 2 and 3 from @pascalc answer

With a catch (that may help @yianyang) : be **always** sure that you do `npm install` and `pod install` with XCode shut down. Basically, from my understanding by reading around, when you fire up XCode its schemebuilder tool runs but if you do one of the previous command after opening, something goes wrong and you get linking errors.
To fix them, do a `Clean` Build & `Clean Build folder` from XCode top bar menù - you can find them by clicking to `Product` and by pressing `alt` you get the clean folder one. After cleaning, close XCode and redo the `npm install` and `pod install` (optionally you can even remove `node_modules` and `Pods` folder to have a truly clean reinstall).

**Comment by mCzolko** [comment]
It would be great to change the installation notes because there are not so clear :) Thank you @pascalc and @kelset

**Comment by nrathi** [comment]
FYI, I updated my previous comment based on @kelset's feedback.

**Comment by gilbox** [comment]
We'd welcome a PR @mCzolko :-)

**Comment by piloulac** [comment]
I did all @nrathi say but i got this error when i try to build my app:

`'RCTImageLoader.h' file not found AIRGoogleMapMarker.m`

**Comment by vdesdoigts** [comment]
Hello, same error, miss something ?

**Comment by kelset** [comment]
Hey guys, quick question: which version of RN are you using? Because this that list was made while 0.38 was the main.

**Comment by vdesdoigts** [comment]
@kelset 
````
    "react": "^15.4.2",
    "react-native": "^0.39.2",
    "react-native-maps": "^0.12.2"
```

**Comment by nrathi** [comment]
Yeah, here's my `package.json`: 

```
    "react": "15.3.2",
    "react-native": "0.37.0",
    "react-native-maps": "0.12.2"
```

Here are apparently instructions for the RN 0.40, but I haven't tried myself: airbnb/react-native-maps/issues/943.

**Comment by piloulac** [comment]
Same thing:

```
"react": "15.4.1",
"react-native": "0.39.2",
"react-native-maps": "^0.12.4",
```

**Comment by nrathi** [comment]
Yeah, my `package.json` versions were the highest I was able to go. I would try downgrading and then following my instructions above if you're in a rush, or upgrading and following the link I just shared.

**Comment by anucreative** [comment]
@piloulac @vdesdoigts. I just had the same issue ('RCTImageLoader.h' file not found AIRGoogleMapMarker.m). This fixed it for me: https://github.com/airbnb/react-native-maps/issues/794#issuecomment-261751403

**Comment by belal-mazlom** [comment]
I get it work by following these steps:
`npm install https://github.com/airbnb/react-native-maps.git#v0.13.0 --save`

Don't link package using `react-native link`

`cd ios`

Add Podfile
[Podfile](https://github.com/airbnb/react-native-maps/blob/master/example/ios/Podfile)
Run this command
`pod install`

Open Xcode project
Drag and drop inside root of project
node_modules/react-native-maps/ios/AirGoogleMaps
node_modules/react-native-maps/ios/AirMaps

Inside AppDelegate.m add these:
`#import <GoogleMaps/GoogleMaps.h>`
Add under NSURL *jsCodeLocation;
`[GMSServices provideAPIKey:@"GoogleAPIKey"];`

**Comment by akaiz** [comment]
I have followed the steps above but I get this error library not found for -lPods-AppName

**Comment by belal-mazlom** [comment]
@akaiz 

You should open:
{YOUR_PROJECT}/ios/{YOUR_PROJECT}.xcworkspace in Xcode
instead of {YOUR_PROJECT}.xcodeproj

**Comment by KarlosQ** [comment]
If 'GoogleMaps/GoogleMaps.h file not found' persists delete tvOS and tvOSTest projects

**Comment by dorthwein** [comment]
@KarlosQ can you explain this a bit more and where to delete them?  Thanks

**Comment by trevans24** [comment]
When I followed the above instructions from @nrathi I get an error from the pod install:
Unable to find a target named `AirMapsExplorer`

here is the podfile that I have

```
# You Podfile should look similar to this file. React Native currently does not support use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

# Change 'AirMapsExplorer' to match the target in your Xcode project.
target 'AirMapsExplorer' do

  pod 'Yoga', :path => '../../node_modules/react-native/ReactCommon/yoga/Yoga.podspec'
  pod 'React', path: '../../node_modules/react-native', :subspecs => [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
    'BatchedBridge'
  ]

  pod 'GoogleMaps'  # <~~ remove this line if you do not want to support GoogleMaps on iOS
  pod 'react-native-maps', path: '../../'
  pod 'react-native-google-maps', path: '../../'  # <~~ if you need GoogleMaps support on iOS

end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "react-native-google-maps"
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
      end
    end
  end
end

```

I rebooted my device (2 times now) removed the pod folder and podfile, followed the instructions again and get the same error. I even tried doing clean build and clean folder still to no avail.

can someone please help me?

**Comment by trevans24** [comment]
there is some things missing from the steps above make sure you have run `npm install --save react-native-google-maps` then in the pod file you need it to be changed to look something like this:

```
# You Podfile should look similar to this file. React Native currently does not support use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

workspace 'AirMapsExplorer'

target ‘YOUR PROJECT NAME AS IT APPEARS IN XCODE’ do

  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga/Yoga.podspec'
  pod 'React', path: '../node_modules/react-native', :subspecs => [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
    'BatchedBridge'
  ]

  pod 'GoogleMaps'
  pod 'react-native-maps', path: '../node_modules/react-native-maps' #<- PATH to your node_modules/react-native-maps directory
  pod 'react-native-google-maps', path: '../node_modules/react-native-maps' #<- PATH to your node_modules/react-native-maps directory

end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "react-native-google-maps"
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
      end
    end
  end
end
```
note the project name in the target needs to be your project...then the paths to the other pods will need to be ../node_modules/... not ../../

hope this helps

**Comment by keithics** [comment]
@trevans24 i got apple mach linker error, i don't have any idea how to fix this. I tried cleaning derived data etc.. but still no avail.

**Comment by dhavaljardosh** [comment]
Can someone help me how to fix this error?
```
ld: 185 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by kelset** [comment]
@dhavaljardosh I think you should open XCode and check if you have duplicate imports for the lib

**Comment by akaiz** [comment]
I don't know if this may help but I did once have an issue like this but someone suggested that I should use the app_name.xcworkspace file instead of app_name.xcodeproj and it solved my problem.

**Comment by hoanghiepitvnn** [comment]
Thanks @pascalc, I work for me. I have error 

> ld: 185 duplicate symbols for architecture x86_64

 So I just do:

```
react-native unlink react-native-maps
react-native run-ios
```

And my Podfile:
  ```
    # Podfile content
    source 'https://github.com/CocoaPods/Specs.git'
    platform :ios, '8.0'

    target 'sbn_react_native' do
      pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
      pod 'React', path: '../node_modules/react-native', :subspecs => [
        'Core',
        'RCTActionSheet',
        'RCTAnimation',
        'RCTGeolocation',
        'RCTImage',
        'RCTLinkingIOS',
        'RCTNetwork',
        'RCTSettings',
        'RCTText',
        'RCTVibration',
        'RCTWebSocket',
        'BatchedBridge'
      ]
      pod 'GoogleMaps'
    end
  ```
Anh package.json

```
"react-native": "^0.47.1",
"react-native-maps": "^0.16.4",
```

**Comment by Tom29** [comment]
@hoanghiepitvnn got this error while using above pod

> [!] Unable to satisfy the following requirements:
> 
> - `React/BatchedBridge (from `../node_modules/react-native`)` required by `Podfile`
> 
> None of your spec sources contain a spec satisfying the dependency: `React/BatchedBridge (from `../node_modules/react-native`)`.
> 
> You have either:
>  * out-of-date source repos which you can update with `pod repo update`.
>  * mistyped the name or version.
>  * not added the source repo that hosts the Podspec to your Podfile.
> 
> Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

**Comment by cinder92** [comment]
im receiving `'GoogleMaps/GoogleMaps.h' file not found` on file `AIRGoogleMapUrlTitle.h`, how can i solve it?

**Comment by genkobar** [comment]
Hi all, 

I'm trying to enable Google Maps in my RN project, and I don't want to add CocoaPods.

My code is consistently failing the with the error "AirGoogleMaps dir must be added to your xCode project to support GoogleMaps on iOS.".

I'm on RN 0.57.4 and react-native-maps 0.22.0.

I've tried adding the AirGoogleMaps folder to the project - both via the Xcode project navigator and via "project->target->Build Phases->Compile Sources" but it still gives the error above.

Has anyone gotten this to work without CocoaPods?

**Comment by MarkCSmith** [comment]
We were able to avoid CocoaPods and get it to work by doing these extra things:
* Remove AirMaps.xcodeproj from our project.
* Follow nrathi's Steps 7 and 8 above: "Drop the AirMaps and AirGoogleMaps directories from {YOUR_PROJECT}/node_modules/react-native-maps/ios/ into your root directory"  At first, we did not choose "Create Groups".
* Add HAVE_GOOGLE_MAPS=1 to preprocessor macros within our project's Build Settings.

**Comment by genkobar** [comment]
I managed to get Google Maps working via manual install, and the key seems to have been that I added the google frameworks to the "Embedded Binaries" section of my Xcode target. It worked when I only added them to the project via the file explorer in Xcode, which I feel the Google Maps SDK documentation isn't clear on.

@markCSmith Thanks for the reply! I was writing this update when I saw your comment appear 😃

**Comment by janhesters** [comment]
@MarkCSmith @genkobar Could one of you please write a tutorial on how to do this? Or at could you please be so kind and share step by step what you did to get it working without CocoaPods? If you do, thank you very much 🙏

**Comment by mecoFarid** [comment]
Why this community is so eager to close the issue before it's solved. Just leave it open maybe someone looking through open issues will come up with something logical, applicable to the issue, react-native is already hell out of struggle. I may sound dumb, but really it may clearly help

**Comment by Abramovick** [comment]
@MarkCSmith @genkobar Pleeeeeeeeease write a tutorial.

**Comment by fahedmahidi** [comment]
Here I am 4 years later having the very same issue on an Expo semi managed workflow with the podfile not looking at all like the example given in the steps. So definitely we need this issue to stay open. And why not, give it a refresher or add the actual way to set the component on Expo.

**Comment by shaileed** [comment]
When i added both AIRGoogleMaps and AIRMaps i got error as "plicate symbols for architecture x86_64". so i just added AIRGoogleMaps and now my project build is successful. but where i have putted <MapView/> i got error as below. please help, i have been working on this issue for weeks now. 

![Simulator Screen Shot - iPhone 13 Pro Max - 2023-03-14 at 21 12 12](https://user-images.githubusercontent.com/114909614/225058830-d52da4ba-e6fe-4620-8d12-73dcbad3e8db.png)

**Comment by 4sagar** [comment]
I solved it by following the instructions at https://github.com/react-native-maps/react-native-maps/blob/master/docs/installation.md#ios

**Comment by rajeshbejugam** [comment]
I ran into this issue and following the instructions given above I landed at the following errors during build time.

❌  duplicate symbol '_OBJC_IVAR_$_AIRMapUrlTile._map' in
┌─ AIRMapUrlTile.o
└─ libreact-native-maps.a[24](AIRMapUrlTile.o)

❌  duplicate symbol '_OBJC_IVAR_$_AIRMapPolylineRenderer._snapshot' in
┌─ AIRMapPolylineRenderer.o
└─ libreact-native-maps.a[23](AIRMapPolylineRenderer.o)

❌  ld: 295 duplicate symbols

I finally was able to fix these by removing AirMaps folder from Xcode project root (just add AirGoogleMaps folder). Also, in my Podfile, I don't have the following lines as was suggested in earlier steps.

rn_maps_path = '../node_modules/react-native-maps'
pod 'react-native-google-maps', :path => rn_maps_path

**Comment by rajeshbejugam** [comment]
I did add HAVE_GOOGLE_MAPS=1 to the preprocessor macros as suggested in https://github.com/react-native-maps/react-native-maps/issues/2573.

**Comment by bharathwebdev** [comment]
follow this https://stackoverflow.com/a/78975487/19910754
