### ISSUE TITLE
Cannot compile:RCTImageLoader

### ISSUE THREAD

**Issue by arashbi** [airbnb/react-native-maps#697]
It seems to be an issue resolved, but I cannot get rid of it.
Just created a new project, added react-native-maps, and trying to compile in xcode gives me
: /tmp/test/node_modules/react-native-maps/ios/AirMaps/AIRMapMarker.m:212:58: No visible @interface for 'RCTImageLoader' declares the selector 'loadImageWithURLRequest:size:scale:clipped:resizeMode:progressBlock:completionBlock:'

The command line output is somehow different, although compilation fails nevertheless:
The following build commands failed:
	CompileC /tmp/test/ios/build/Build/Intermediates/AirMaps.build/Debug-iphonesimulator/AirMaps.build/Objects-normal/x86_64/AIRMapMarker.o AirMaps/AIRMapMarker.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Installing build/Build/Products/Debug-iphonesimulator/test.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/test.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

**Comment by christopherdro** [comment]
Are you running on React Native 0.35? The necessary update has been merged but not yet released.

Could you try updating your apps package.json source for react native maps to point to master?

**Comment by tapickell** [comment]
@christopherdro what PR / Closed Issue is resolving this in Master react-native?

**Comment by christopherdro** [comment]
Should be https://github.com/airbnb/react-native-maps/commit/99c3bdadbcec3cfccb58f87ecfaffc95deb03aa0

**Comment by arashbi** [comment]
I will try.

**Comment by christopherdro** [comment]
https://github.com/airbnb/react-native-maps/commit/12853f03686f7f8af11d853e629afcb8146e50c8

**Comment by arashbi** [comment]
Thanks!

**Comment by Peakdrum** [comment]
This actually solved my problem and I got the map running initially !

**Comment by rjain-pivotal** [comment]
I am getting the same error. I am on react-native 0.35
I am copying the ```node_modules/react-native-maps/ios/AirMaps/``` and ```node_modules/react-native-maps/ios/AirGoogleMaps/``` in my project folder (not dragging them in XCode)

$react-native run-ios

```
tutor/node_modules/react-native-maps/ios/AirMaps/AIRMapMarker.m:212:58: error: 
      no visible @interface for 'RCTImageLoader' declares the selector
      'loadImageWithURLRequest:size:scale:clipped:resizeMode:progressBlock:completionBlock:'
    _reloadImageCancellationBlock = [_bridge.imageLoader loadImageWithURLRequest:[RCTConvert NSURLRequest:_imageSrc]
                                     ~~~~~~~~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

Final error in the build process

```
=== BUILD TARGET RCTNetwork OF PROJECT RCTNetwork WITH CONFIGURATION Debug ===

Check dependencies

** BUILD FAILED **


The following build commands failed:
	CompileC /Users/rjain/code/react-native-samples/tutor/ios/build/Build/Intermediates/AirMaps.build/Debug-iphonesimulator/AirMaps.build/Objects-normal/x86_64/AIRMapMarker.o AirMaps/AIRMapMarker.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Installing build/Build/Products/Debug-iphonesimulator/tutor.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/tutor.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist
```

**Comment by rjain15** [comment]
I am getting the same error. I am on react-native 0.35
I am copying the ```node_modules/react-native-maps/ios/AirMaps/``` and ```node_modules/react-native-maps/ios/AirGoogleMaps/``` in my project folder (not dragging them in XCode)

$react-native run-ios

```
tutor/node_modules/react-native-maps/ios/AirMaps/AIRMapMarker.m:212:58: error: 
      no visible @interface for 'RCTImageLoader' declares the selector
      'loadImageWithURLRequest:size:scale:clipped:resizeMode:progressBlock:completionBlock:'
    _reloadImageCancellationBlock = [_bridge.imageLoader loadImageWithURLRequest:[RCTConvert NSURLRequest:_imageSrc]
                                     ~~~~~~~~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

Final error in the build process

```
=== BUILD TARGET RCTNetwork OF PROJECT RCTNetwork WITH CONFIGURATION Debug ===

Check dependencies

** BUILD FAILED **


The following build commands failed:
	CompileC /Users/rjain/code/react-native-samples/tutor/ios/build/Build/Intermediates/AirMaps.build/Debug-iphonesimulator/AirMaps.build/Objects-normal/x86_64/AIRMapMarker.o AirMaps/AIRMapMarker.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Installing build/Build/Products/Debug-iphonesimulator/tutor.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/tutor.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist
```

**Comment by rjain15** [comment]
changing the package.json to use react-native-maps 0.11.0 fixed this issue.

**Comment by kingydw** [comment]
I'm getting the same error on react-native 0.35 and use the react-native-maps 0.11.0 in package.json can work for me. THX

**Comment by zolar** [comment]
I am having the same issue with the same combination. react-native 0.35 & react-native-maps 0.11.0.
