### ISSUE TITLE
Zoom level

### ISSUE THREAD

**Issue by thundenilla** [airbnb/react-native-maps#705]
Can i set the zoom level for the map once its open? when i work on android native, used to set the zoom level, but now i cant find a method for zoom level.

**Comment by jojonarte** [comment]
I'd also like to ask this :D

**Comment by jeveloper** [comment]
Hey folks

There is no ZOOm level here

Its called lat delta and long delta 
e.g. 0.03 is about a few city blocks 
Most of the north america/canada would be visible at 
latitude_delta value 60

this works on both platforms very well

**Comment by jojonarte** [comment]
What is the equivalent delta to a mile or a km scale? @jeveloper

**Comment by jeveloper** [comment]
Here is my contribution , there isn't one, you have to think of width and height of a display and that is your ratio

let { width, height } = Dimensions.get('window')
const ASPECT_RATIO = width / height
const LATITUDE_DELTA = 60 //Very high zoom level
const LONGITUDE_DELTA = LATITUDE_DELTA * ASPECT_RATIO

as you can imagine you can figure out distance between locations and apply math to figure out approximate delta to show them all :) its a challenging with many points however 

the above code is more than enough to do what you're trying to do.

**Comment by jojonarte** [comment]
@jeveloper  Can we somehow convert a scale of mile/meter into LATDELTA AND LONGDELTA?

**Comment by jeveloper** [comment]
Quick update for you

add an event handler 
onRegionChangeComplete

onRegionChangeComplete = (region) => {
    console.log(" region", region)
  }

As your user will zoom in out, you'll get updated delta values :)

Object {longitudeDelta: 0.04250270688370961, latitude: 37.79227293625211, longitude: -122.4211020066645, latitudeDelta: 0.03358723958820065}

The rest is up to you

Please close the ticket, the issue is resolved :)

**Comment by ElMaghri** [comment]
Hi guys @jeveloper  you're right i try it it's and it's work very very good in simulator IOS (iPhone SE) but when i try in my real device Android the maps dont be zoomed when is loaded

**Comment by marano** [comment]
I've found this function to be useful:
```
let zoom = Math.round(Math.log(360 / region.longitudeDelta) / Math.LN2)
```
source https://stackoverflow.com/questions/46568465/convert-a-region-latitudedelta-longitudedelta-into-an-approximate-zoomlevel

**Comment by ShaikhKabeer** [comment]
Hi @jeveloper , my MapView is not zooming out . Also I want to display map in such a way that it should cover all the cordinates. Kindly check the code here



import React from 'react';
import { StyleSheet,Text,View }  from 'react-native';
import MapView from 'react-native-maps';

export default class ReactMap extends React.Component {
    constructor(props){
        super(props);
        this.state={
            markers:[{
                title:'Coordinate 1',
                coordinates:{
                    latitude: 18.5204,
                    longitude: 73.8567,
                    longitudeDelta:50,
                    latitudeDelta:50,
                },
            },
            {
                title:'Coordinate 2',
                coordinates:{
                    latitude: 25.2744,
                    longitude: 133.7751,
                    longitudeDelta:50,
                    latitudeDelta:50,
                },
            },
            {
                title:'Coordinate 3',
                coordinates:{
                    latitude: 37.0902,
                    longitude: 72.8777,
                    longitudeDelta:50,
                    latitudeDelta:50,
                },
            },
            {
                title:'Coordinate 4',
                coordinates:{
                    latitude: 46.2276,
                    longitude: 2.2137,
                    longitudeDelta:50,
                    latitudeDelta:50,
                },
            }]
        }
    }

    getInitialState(){
        return{
            region:new MapView.AnimatedRegion({
                latitude: 37.0902,
                longitude: 72.8777,
                longitudeDelta:0.1,
                latitudeDelta:0.1
            }),
        };
    }

    render() {
 
        return (
           
                    <MapView style={styles.map}
                    region={this.state.region}
                    onRegionChangeComplete={(region) => {
                        console.log(" region", region) 
                  }}>
                     
                    {this.state.markers.map(marker =>   (
                        <MapView.Marker key={marker.title}
                        coordinate={marker.coordinates}
                        title={marker.title}
                        >
                        <View style={styles.radius}>
                        <View style={styles.markerStyle}/>
                        </View>
                       </MapView.Marker>
                    ))}

                    </MapView> 
        
        );
    }
 
}

const styles=StyleSheet.create({
    container:{
        position:'absolute',
        top:0,
        bottom:0,
        left:0,
        right:0,
        justifyContent:'flex-end',
        alignItems:'center' 
    },
    map:{
        position:'absolute',
        top:0,
        bottom:0,
        left:0,
        right:0,
    },
    radius:{
        height:15,
        width:15,
        backgroundColor:'#81BD26',
        overflow:'hidden',
        borderRadius:50/2,
        borderWidth:1,
        alignItems:'center',
        justifyContent:'center'
    },
    markerStyle:{
        height:14,
        width:14,
        backgroundColor:'#81BD26',
        alignItems:'center',
        justifyContent:'center'
    }
});

**Comment by Moumene** [comment]
Thank you @marano 👍 
```
const distanceDelta = Math.exp(Math.log(360) - (zoom * Math.LN2));
```
You can use this to get the `delta` from `zoom` 

https://stackoverflow.com/questions/46568465/convert-a-region-latitudedelta-longitudedelta-into-an-approximate-zoomlevel/#comment90207683_46570766

**Comment by l-Marty-l** [comment]
Thank you everyone, zoom level 11 is great to display an entire city.

**Comment by LuizFBrisighello** [comment]
> I've found this function to be useful:
> 
> ```
> let zoom = Math.round(Math.log(360 / region.longitudeDelta) / Math.LN2)
> ```
> 
> source https://stackoverflow.com/questions/46568465/convert-a-region-latitudedelta-longitudedelta-into-an-approximate-zoomlevel

I'm not able to set the zoom value on a state, the map keeps going back to the original value.

       const [zoom, setZoom] = useState(15)

      <MapView
        onMapReady={_onMapReady}
        latitude={position.latitude}
        longitude={position.longitude}
        onRegionChangeComplete={region => {
          setZoom(Math.round(Math.log(360 / region.longitudeDelta) / Math.LN2))
        }}
      >

**Comment by andrewtelkamp** [comment]
Is this all of your code? You need to either specify `initialCamera`, `camera`, `initialRegion` or `region` depending on your use case.

**Comment by LuizFBrisighello** [comment]
@andrewtelkamp Oh sorry about that, this snippet of code isnt the best way to show my code, that's the proper code :

    const [zoom, setZoom] = useState(15)

    <MapView
      ref={map => { this.mapRef = map }}
      onMapReady={props.onMapReady}
      region={{
        latitude: props.latitude,
        longitude: props.longitude,
        latitudeDelta: 0.01,
        longitudeDelta: 0.01
      }}
      loadingEnabled={false}
      showsUserLocation={true}
      showsMyLocationButton={true}
      showsBuildings={false}
      minZoomLevel={13}
      maxZoomLevel={17}
      onRegionChangeComplete={region => {
        setZoom(Math.round(Math.log(360 / region.longitudeDelta) / Math.LN2))
      }}
    >

But I found the issue here #1995 
And it seems there is no solution for these too.. I'm cracking my head for almost over a week now about this.
I need to store latitudeDelta (zoom) on a state so I can render the markers based on the zoom level. But when I execute the code above and I try to move the map, it keeps jumping to the previous position.

**Comment by LuizFBrisighello** [comment]
@andrewtelkamp I looked deeply into #1995 and solved by not controlling the region with `region` and so with `initialRegion`.

**Comment by andrewtelkamp** [comment]
Yeah, you have to use one or the other. If you want to explicitly control the region use `region` (I rarely find a need for this). Otherwise use `initialRegion` and use the `animateToRegion` method if you need to programmatically change your region. Similar use case for `camera` and `initialCamera` if you were go that route.

**Comment by EgorKazachenko** [comment]
Hope that it will be useful for someone.

This way we can work with `region` property  based on real zoom-level (0..20)

```
type Region {
  latitude: Number,
  longitude: Number,
  latitudeDelta: Number,
  longitudeDelta: Number,
}
```

```
static getRegionWithDeltaByAccuracy = ({ latitude, longitude, accuracy }) => { 
        const latitudeDelta = accuracy / ONE_LATITUDE_DEGREE_IN_METERS;
        const longitudeDelta = accuracy / (ONE_LATITUDE_DEGREE_IN_METERS * Math.cos(latitude * (Math.PI / 180)));
 
        return result = {
            latitude: latitude,
            longitude: longitude,
            latitudeDelta,
            longitudeDelta,
        }
    }

    static getZoomByRegion = ({ longitudeDelta }) => Math.round(Math.log(360 / longitudeDelta) / Math.LN2);

    static getRegionDeltasFromZoom = (zoom, latitude) => {
        const longitudeDelta = Math.exp(Math.log(360) - (zoom * Math.LN2));
        const accuracy = longitudeDelta * (ONE_LATITUDE_DEGREE_IN_METERS * Math.cos(latitude * (Math.PI / 180)));
        const latitudeDelta = accuracy / ONE_LATITUDE_DEGREE_IN_METERS;
        return {
            longitudeDelta,
            latitudeDelta,
        };
    }
```

Example of usage
```
const location = yield call(locationService.getCurrentLocation);
        const regionDeltas = locationService.getRegionDeltasFromZoom(ZOOM_LEVEL_WHEN_GRANTED, location.coords.latitude);
        const region = {
            ...location.coords,
            ...regionDeltas,
        };

        yield all([
            put(setCurrentLocation(location)),
            put(setRegion(region)),
        ]);
```

**Comment by NavpreetXccelerata** [comment]
> Hi @jeveloper , my MapView is not zooming out . Also I want to display map in such a way that it should cover all the cordinates. Kindly check the code here
> 
> import React from 'react';
> import { StyleSheet,Text,View } from 'react-native';
> import MapView from 'react-native-maps';
> 
> export default class ReactMap extends React.Component {
> constructor(props){
> super(props);
> this.state={
> markers:[{
> title:'Coordinate 1',
> coordinates:{
> latitude: 18.5204,
> longitude: 73.8567,
> longitudeDelta:50,
> latitudeDelta:50,
> },
> },
> {
> title:'Coordinate 2',
> coordinates:{
> latitude: 25.2744,
> longitude: 133.7751,
> longitudeDelta:50,
> latitudeDelta:50,
> },
> },
> {
> title:'Coordinate 3',
> coordinates:{
> latitude: 37.0902,
> longitude: 72.8777,
> longitudeDelta:50,
> latitudeDelta:50,
> },
> },
> {
> title:'Coordinate 4',
> coordinates:{
> latitude: 46.2276,
> longitude: 2.2137,
> longitudeDelta:50,
> latitudeDelta:50,
> },
> }]
> }
> }
> 
> ```
> getInitialState(){
>     return{
>         region:new MapView.AnimatedRegion({
>             latitude: 37.0902,
>             longitude: 72.8777,
>             longitudeDelta:0.1,
>             latitudeDelta:0.1
>         }),
>     };
> }
> 
> render() {
> 
>     return (
>        
>                 <MapView style={styles.map}
>                 region={this.state.region}
>                 onRegionChangeComplete={(region) => {
>                     console.log(" region", region) 
>               }}>
>                  
>                 {this.state.markers.map(marker =>   (
>                     <MapView.Marker key={marker.title}
>                     coordinate={marker.coordinates}
>                     title={marker.title}
>                     >
>                     <View style={styles.radius}>
>                     <View style={styles.markerStyle}/>
>                     </View>
>                    </MapView.Marker>
>                 ))}
> 
>                 </MapView> 
>     
>     );
> }
> ```
> 
> }
> 
> const styles=StyleSheet.create({
> container:{
> position:'absolute',
> top:0,
> bottom:0,
> left:0,
> right:0,
> justifyContent:'flex-end',
> alignItems:'center'
> },
> map:{
> position:'absolute',
> top:0,
> bottom:0,
> left:0,
> right:0,
> },
> radius:{
> height:15,
> width:15,
> backgroundColor:'#81BD26',
> overflow:'hidden',
> borderRadius:50/2,
> borderWidth:1,
> alignItems:'center',
> justifyContent:'center'
> },
> markerStyle:{
> height:14,
> width:14,
> backgroundColor:'#81BD26',
> alignItems:'center',
> justifyContent:'center'
> }
> });


hi developer...
have you solved this issue m getting the same issue

**Comment by ZeeshanAhmadKhalil** [comment]
> Hey folks
> 
> There is no ZOOm level here
> 
> Its called lat delta and long delta
> e.g. 0.03 is about a few city blocks
> Most of the north america/canada would be visible at
> latitude_delta value 60
> 
> this works on both platforms very well

But  I am getting blur map if I zoom in
