### ISSUE TITLE
Having contents over the map,

### ISSUE THREAD

**Issue by jojonarte** [airbnb/react-native-maps#711]
I would like to have the mapview to be on the background of a list of locations/point of interest. I'd like to have the MapView on a separate component so I could easily manage each pointers and other functions and stuffs.

So case 1 If I'd lay out the Mapview like this it would display just like how I would like it to display but I would get some weird issues on the pointer when clicking them.

```
<View>
<MapView>
<ListView />
</MapView>
</View>
```

Case 2:

If I put the Mapview in another custom react component and import it back to the main view
```
<View>
<CustomView>
<ListView />
</CustomView>
</View>
```

This case would just load in such a way the only the map shows covering everything. 

How could I get around it so I could have the Map on a separate component with specific functions, then allow it to wrap components just like it would normally on case 1.

**Comment by Clcll** [comment]
@jojonarte 

Styles for  MapView    

map: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0
    },

If you what have something over the map, just put it under MapView 

Like

<View>
 <MapView />
<ListView/>
</View>

**Comment by jojonarte** [comment]
I've tried that and it wouldn't work with Markers and listview wrapped inside mapview

**Comment by Clcll** [comment]
@jojonarte Don't wrap it. Put map as single tag

**Comment by jeveloper** [comment]
Hey there 

Please don't add children inside mapview.

Instead add a view below it and use style with relative position and offset to however above the map , for example:

position: 'absolute', bottom: (height / 4.5)

i use height variable from Dimensions 

There you go, problem solved

**Comment by jojonarte** [comment]
Hey @jeveloper  thanks for that man, got it to work now :D closing this.

**Comment by jeveloper** [comment]
I'm glad i was of help.  Feel free to "follow"

**Comment by NafisaShriwardhankar** [comment]
worked for me too thanks man @jeveloper

**Comment by jeveloper** [comment]
@NafisaShriwardhankar  I'm glad it helps :)
