### ISSUE TITLE
PitchAngle

### ISSUE THREAD

**Issue by jojonarte** [airbnb/react-native-maps#715]
I've tried setting PitchEnabled to true it works with dragging.

How could I change the map/control the camera programatically such that if I could manipulate it since I'm having my component change the map angle when tilting the device.

**Comment by tedjames** [comment]
Hey @jojonarte, any luck figuring this one out?

**Comment by jojonarte** [comment]
@tedjames  I still have no luck I opened a specific issue for this here. :( Still hoping for an update with it as I've been trying to do the integration my self to no success. #765

**Comment by kzka90** [comment]
Any luck on this? @jojonarte @tedjames

**Comment by sandinosaso** [comment]
Maybe this can help with what you are trying to achieve: https://github.com/airbnb/react-native-maps/pull/1544
