### ISSUE TITLE
Crash app after useGoogleMaps for IOS v0.11.0

### ISSUE THREAD

**Issue by 2ducanhpham** [airbnb/react-native-maps#719]
my screen shot 
I install by 'Pod install'.
Provider={PROVIDER_GOOGLE}

<img width="1387" alt="screen shot 2016-10-22 at 10 40 33 pm" src="https://cloud.githubusercontent.com/assets/14899775/19620491/a52ba074-98a8-11e6-9fde-0318f9ca9cbe.png">

but use provider={PROVIDER_DEFAULT} ok.

Please help me!

**Comment by btoueg** [comment]
Have you tried running the example app on iOS with your own Google API key?

**Comment by olegdizus** [comment]
@2ducanhpham, try to add
```
#import <GoogleMaps/GoogleMaps.h>
```
and
```
[GMSServices provideAPIKey:@"YOUR_GOOGLE_MAPS_IOS_API_KEY"];
```
to AppDelegate.m

For example
```
/**
 * Copyright (c) 2015-present, Facebook, Inc.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree. An additional grant
 * of patent rights can be found in the PATENTS file in the same directory.
 */

#import "AppDelegate.h"

#import "RCTBundleURLProvider.h"
#import "RCTRootView.h"
#import <GoogleMaps/GoogleMaps.h> /* <=== there */

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  NSURL *jsCodeLocation;
	[GMSServices provideAPIKey:@"YOUR_GOOGLE_MAPS_IOS_API_KEY"]; /* <=== and there */

  jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index.ios" fallbackResource:nil];

  RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                      moduleName:@"vezdeapp"
                                               initialProperties:nil
                                                   launchOptions:launchOptions];
  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  return YES;
}

@end
```

Of course, with your api keys.
I not sure that is right way, but in my case this has helped.

**Comment by 2ducanhpham** [comment]
thanks @btoueg , @olegdizus  . it working.

**Comment by warmwater** [comment]
Hi 

I have tried the solution, but it shows:
'GoogleMaps/GoogleMaps.h' file not found in AIRGoogleMap.h

any idea?

**Comment by 2ducanhpham** [comment]
@warmwater maybe you missing drag this folder into your project:
node_modules/react-native-maps/ios/AirGoogleMaps/

**Comment by warmwater** [comment]
hi @2ducanhpham 

I think I did, I drag them into Xcode and pod install googlemaps, and I can see googlemaps.h in header folder

<img width="280" alt="screen shot 2016-11-09 at 8 41 12 am" src="https://cloud.githubusercontent.com/assets/19963/20123110/cffe5d0c-a657-11e6-92af-b343a1280152.png">

**Comment by warmwater** [comment]
ah just found out it happens to test target...i ll just ignore it

thanks for help

**Comment by matikups** [comment]
Fixed for me too @olegdeezus 
Thanks!
