### ISSUE TITLE
[RNMaps 0.11] iOS GGMaps - showsUserLocation supported?

### ISSUE THREAD

**Issue by julien-rodrigues** [airbnb/react-native-maps#720]
Hi!

I would like to know if this is supported right now.

I set the option "showsUserLocation" on the MapView component but it doesn't seems to work.

Thx

**Comment by jojonarte** [comment]
Hey did you fix this? WHat did you do? I can't make mine work.

**Comment by julien-rodrigues** [comment]
I added the functionality to the package :) 

https://github.com/airbnb/react-native-maps/pull/721

I think it is now on version 0.10.4: https://github.com/airbnb/react-native-maps/blob/master/CHANGELOG.md#0104-october-31-2016

The only thing to do is to keep the property on your tag. Just like on Android
