### ISSUE TITLE
Google Map on ios renders blank,

### ISSUE THREAD

**Issue by jojonarte** [airbnb/react-native-maps#723]
Here's a screenshot of how it looks like.
http://screencast.com/t/Ai03DPwdmE

I've tried setting everything as it is required on the installation requirements.

**Comment by btoueg** [comment]
Have you tried running the example app on iOS with your own Google API key?

**Comment by manelpb** [comment]
@jojonarte I just found how to solve this issue, you need to enable Google Maps SDK for iOS, see here: 

http://stackoverflow.com/questions/14007075/google-maps-not-working-on-iphone-simulator

**Comment by jojonarte** [comment]
The apikey was the issue.

**Comment by truongluong1314520** [comment]
@manelpb , you save my life even there is almost 2 years from now. Thank you
