### ISSUE TITLE
Markers with custom images are rendered with the wrong size in production

### ISSUE THREAD

**Issue by Exilz** [airbnb/react-native-maps#725]
When I render markers with custom images, I noticed that when `__DEV__` is `false`, the image rendered has the same height and width as the file itself.
When it's `true`, it's displayed with the proper height and width that I provide.

This happens on both iOS and Android.

Here's a sample of my code :

```
            return (
                <MapView.Marker
                  key={`marker-${index}`}
                  coordinate={{ latitude: Number(latitude), longitude: Number(longitude) }}
                  onPress={options.onPress ? () => options.onPress(marker) : false}
                  image={icons[marker.type] || icons.default}
                  style={styles.marker}
                  identifier={marker._id}
                />
            );
```

```
export default StyleSheet.create({
    marker: {
        width: 60,
        height: 75
    }
});
```

And screenshots :

![](http://i.imgur.com/1YVLdt8.jpg)
![](http://i.imgur.com/3i8tiPN.jpg)

**Comment by robmoorman** [comment]
Are you sure you have supplied the correct @2x @3x image sizes?

**Comment by invig** [comment]
I can confirm this issue exists, in dev it uses the correct image sizes but in prod it gets the scaling wrong, it also ignores any height and width styles you add to the markers.

**Comment by Exilz** [comment]
@robmoorman no I didn't, I'll try it out and let you know if that fixes it. But according to @invig, it shouldn't, since he's experiencing the exact same thing.

**Comment by seanislegend** [comment]
I also noticed this, but thanks to @robmoorman I realised I didn't specify @2x in my filename. D'oh. Thanks!

**Comment by Exilz** [comment]
@seanislegend So that fixed it for you then ?

**Comment by Exilz** [comment]
@robmoorman It looks like adding 2x, 3x, 4x images fixed it for us. Still weird that it didn't happen in dev mode, though.
Thanks anyway.

**Comment by mgtitimoli** [comment]
Hi everyone, I'm experiencing the same, could anyone explain more in depth what you mean with

> adding 2x, 3x, 4x to the images

What I don't understand is, let's imagine I have an image of a certain WxH, do I have to provide 3 versions of it with that scaling sizes (2x, 3x, 4x) applied and append the corresponding label to each of them, like this?

Thanks!

**Comment by robmoorman** [comment]
Correctly @mgtitimoli please read [React Native's docs](https://facebook.github.io/react-native/docs/images.html) for more information

**Comment by seanislegend** [comment]
And also Apple's docs https://developer.apple.com/library/content/documentation/2DDrawing/Conceptual/DrawingPrintingiOS/SupportingHiResScreensInViews/SupportingHiResScreensInViews.html

**Comment by danielbh** [comment]
Is anyone else having trouble making the 2x, 3x, 4x work for iOS?

**Comment by morrislaptop** [comment]
I still think this is an issue as the behaviour in dev is different to the behaviour in release...

**Comment by coreyphillips** [comment]
@danielbh I would suggest something similar to the following if adding 2x, 3x etc., doesn't work for you:
```
<MapView.Marker
	coordinate={{ latitude, longitude }}
>
	<Image
		source={mySource}
		style={{ height: 22, width: 22, zIndex: 0 }}
	/>
</MapView.Marker>
```

**Comment by Kosai106** [comment]
I've also found that providing width and height props to the `MapView.Marker` itself sometimes can help with sizing issues.

**Comment by LorandP** [comment]
@coreyphillips Putting an image inside MapView.Marker works fine but it's not showing anything on an android emulator with a 26 version apk.

**Comment by coreyphillips** [comment]
@LorandP I haven't been able to test on an emulator with v26, but I wonder if bumping up or playing around with the zIndex of the Marker would help it become visible.

**Comment by douglasjunior** [comment]
> ```
> <MapView.Marker
>	coordinate={{ latitude, longitude }}
> >
>	<Image
>		source={mySource}
>		style={{ height: 22, width: 22 }}
>	/>
> </MapView.Marker>
> ```

Not working for Android.

**Comment by tatsna** [comment]
Thx you . @douglasjunior
