### ISSUE TITLE
Duplicate symbols for armv7

### ISSUE THREAD

**Issue by jojonarte** [airbnb/react-native-maps#727]
I'm getting 
"ld: 930 duplicate symbols for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)"

when trying to run on a real iPhone4s, how could I fix this?

```
export IPHONEOS_DEPLOYMENT_TARGET=8.0
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
  ld: 930 duplicate symbols for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by jojonarte** [comment]
resolved.

**Comment by lappalj4** [comment]
@jojonarte could you please add a comment describing the steps you took to resolve the issue, so that other people can benefit from this ticket as well?
