### ISSUE TITLE
Map swallows scroll events on Android, even if scroll is disabled

### ISSUE THREAD

**Issue by sibnerian** [airbnb/react-native-maps#730]
If there is a `MapView` inside of a `ScrollView`, then any scroll event that starts on the map will be ignored by the `ScrollView`. They should only be swallowed like this if the map scroll is enabled.

I think this is related to #343, which fixed the issue of `ScrollView` taking priority of scroll events by using `requestDisallowInterceptTouchEvent`.

**Comment by Thomas101** [comment]
I've just moved from using the 11.0 release to master and it seems to fixed there. Hopefully they'll push a release out shortly :)

**Comment by gilbox** [comment]
please let us know if `v0.12.0` fixes it

**Comment by Thomas101** [comment]
@gilbox fixed it for us. Thank you!

**Comment by sibnerian** [comment]
Yup! Thanks @gilbox 😄
