### ISSUE TITLE
How to enable Night/Dark mode?

### ISSUE THREAD

**Issue by toaa-media** [airbnb/react-native-maps#754]
I am facing a problem. That is the map need to be in a Night mode but I don't know how to implement it using this library.
Could anyone tell me does library support Night mode and if yes then how to implement it?
Many thanks for everyone.

**Comment by Roconda** [comment]
You could use dark tiles and switch between them with custom tiles, see https://github.com/airbnb/react-native-maps/blob/master/example/examples/CustomTiles.js

**Comment by toaa-media** [comment]
Wow that is so cool. I will check it out now.
Thank you so much.

**Comment by RWOverdijk** [comment]
That's cool indeed... Now making my own maps, which is what I _actually_ wanted. Thanks @Roconda

**Comment by jojonarte** [comment]
#745

**Comment by toaa-media** [comment]
I found out the answer as mentioned above. I will close this issue now.

**Comment by simardeepgithub-1997** [comment]
how to make a map color black.

**Comment by ajaykumar97** [comment]
You can make use of [google style generator](https://mapstyle.withgoogle.com/)  for this. After creating the custom style, download the JSON file and then pass it to the ``MapView`` component via prop called ``customMapStyle`` like:

```
mapStyle = [ ... ]

<MapView
      region={this.state.region}
      onRegionChange={this.onRegionChange}
      customMapStyle={mapStyle}
 />
```

**Comment by xhirazi** [comment]
@ajaykumar97  thanks buddy.

**Comment by malikhamza0546** [comment]
Its giving me blank screen just along with location marker on Google Maps, anyone will u please help

**Comment by NawazKhanMd** [comment]
@simardeepgithub-1997 Have you found the solution ?
