### ISSUE TITLE
Marker onPress triggers Map onPress

### ISSUE THREAD

**Issue by stereodenis** [airbnb/react-native-maps#758]
Maybe I don't know how, but when I press on Marker — I get Map onPress too

**Comment by nharsch** [comment]
I'm having the same issue with onCalloutPress and Map onPress. 

With a marker callout open:
- If I short tap the marker, both onCalloutPress and Map onPress are called
  - in my case, this will promptly open and then close a details modal
- If I long tap, only onCalloutPress is called

**Comment by gilbox** [comment]
Currently we are working around this bug:

```
const stopPropagation = thunk => e => {
  e.stopPropagation();
  thunk();
};
//....
onPress={stopPropagation(handleMarkerPress)}
```

**Comment by thundenilla** [comment]
@stereodenis is it fix?

**Comment by stereodenis** [comment]
@thundenilla yep!

**Comment by KarlosQ** [comment]
How to fix this?

**Comment by scotthollandjr** [comment]
@stereodenis Is there a link to how this issue was resolved? I'm having the same problem.

**Comment by avdept** [comment]
@gilbox Could you provide short example please. Thanks.

**Comment by duhaime** [comment]
@avdept @scotthollandjr @KarlosQ , I believe the suggestion above is to do something like this:

```
{this.state.markers.map((marker, i) => (
  <MapView.Marker
    key={i}
    coordinate={marker.coordinate}
    onPress={(e) => {e.stopPropagation(); this.onMarkerPress(i)}}
  />
))}
```

That is to say, prevent the propagation of the event then call the event you wish to trigger...

**Comment by lelandrichardson** [comment]
Closed as duplicate of #1132

**Comment by saadmutahar** [comment]
@lelandrichardson @duhaime  The same error is occurred in latest version of maps. 
When I press the marker, it triggers the onPress of parent Maps also. 

    "react-native": "0.59.8",
    "react-native-maps": "0.25.0",

Thanks

**Comment by saadmutahar** [comment]
It's fixed the issue for me, As I forgot to add the stopPropagation event on marker click. 

Thanks.
