### ISSUE TITLE
Example Animated with MapViews broken

### ISSUE THREAD

**Issue by RWOverdijk** [airbnb/react-native-maps#763]
Animated with MapViews as provided in the examples directory isn't working.

![](https://dl.dropboxusercontent.com/spa/5fx2el5lql1lidy/c_p70l-q.png)

**Comment by kevando** [comment]
Hey @RWOverdijk I got the same error and changing these 2 lines fixed it for me.

https://github.com/airbnb/react-native-maps/compare/master...kevando:patch-2

Not sure if this has been discussed or I'm working with an outdated version, but hope this gets you through the day. Kev
