### ISSUE TITLE
MapStyleOptions

### ISSUE THREAD

**Issue by kordeviant** [airbnb/react-native-maps#781]
hi , there. as of [september_21_2016](https://developers.google.com/maps/documentation/android-api/releases#september_21_2016) google has made it possible to give styling to mobile maps. please make this possible !!

**Comment by kordeviant** [comment]
can anybody help?

**Comment by ali-alamine** [comment]
I'll be doing this (I need it for a project). But I'm not sure about the naming since I don't want to confuse it with the react 'style' option. Any suggestions?? I'm thinking about about tilesStyle.

**Comment by gilbox** [comment]
This might be related

**Comment by ali-alamine** [comment]
Yes it does solve this.

**Comment by gilbox** [comment]
@ali-alamine if you'd like to assist by breaking up that code into smaller PRs, it would be very helpful!

**Comment by ali-alamine** [comment]
@gilbox I already am, just need some time cz I have to finish a few things first. By monday it will be done.
