### ISSUE TITLE
[Android] Markers flicker on State Change

### ISSUE THREAD

**Issue by ChrisCates** [airbnb/react-native-maps#782]
Not sure how to resolve this. I am updating state every second and there are multiple pins... What's the best approach to managing pins with custom images?

**Comment by akshay2604** [comment]
I think with the latest version they have fixed this issue. Try upgrading to latest version

**Comment by stephanemaillard** [comment]
#728 should have fixed this but it's still in master and has not been released yet

**Comment by ChrisCates** [comment]
@stephanemaillard 

How do I build the latest version into production? Do I just clone it and do `npm link`?

**Comment by stephanemaillard** [comment]
You can specify it in your `package.json` like this :
`"react-native-maps": "/airbnb/react-native-maps#master"`

Or you could patch your current version by modifing some files in node modules in the same way than this pull request : https://github.com/airbnb/react-native-maps/pull/728/commits

**Comment by lelandrichardson** [comment]
I believe this is fixed now. Please reopen if not.

**Comment by nwaughachukwuma** [comment]
Hi @lelandrichardson I know this issue has been closed for 2 years now, but am getting same issue. Map flickers when dragging the marker or when trying to move around the map. Please what could be responsible for this? Find below a code sample from my project.

```
<View style={styles.container}>
	<MapView

		ref={map => this.map = map}    
		region={this.state.region}
		provider={PROVIDER_GOOGLE}
		onRegionChange={this.onRegionChange}
		showsMyLocationButton={true}
		zoomEnabled={true}
		customMapStyle={mapStyle}
		showsUserLocation={false}
		style={[styles.map, { flex: 1 }]}>
		<Marker.Animated
			ref={marker => { this.marker = marker }}
			draggable
			coordinate={this.state.coordinate}
			image={Images.marker}
			title={"My location"}
			description={"I am here?"}>

		</Marker.Animated>                                
	</MapView>
</View>

```
