### ISSUE TITLE
./gradlew clean build results in compile errors

### ISSUE THREAD

**Issue by npomfret** [airbnb/react-native-maps#784]
When I run:

`
cd android
./gradlew clean build
`

I get lots of compile errors:

`android/src/main/java/com/airbnb/android/react/maps/AirMapCallout.java:5: error: package com.facebook.react.views.view does not exist
import com.facebook.react.views.view.ReactViewGroup;`

How do you build this project?

**Comment by felipecsl** [comment]
You probably have the wrong version of react native. Run `./gradlew dependencies` and make sure you have at least 0.34
