### ISSUE TITLE
iOS: mapType has no effect when provider is Google.

### ISSUE THREAD

**Issue by adammacdonald** [airbnb/react-native-maps#792]
This works fine under Apple Maps, however if I change the `provider='google'` the map renders in standard view no matter what the value of `mapType`

```
<MapView style={styles.map} 
    mapType='satellite'
    initialRegion={{
        latitude: {this.state.region.lat},
        longitude: {this.state.region.lon},
        latitudeDelta: 0.008,
        longitudeDelta: 0.008
     }}
/>
```

Relevant version information:
node: 7.1
react-native-cli: 1.2.0
react-native: 0.37.0
react-native-maps: 0.11.0

**Comment by unboundfire** [comment]
Google maps doesn't support satellite on iOS only hybrid, street, terrain, and none.

**Comment by adammacdonald** [comment]
@unboundfire:  The Google Maps for iOS SDK absolutely supports [Satellite as a MapType](https://developers.google.com/maps/documentation/ios-sdk/map#map_types)

Please correct me if I'm wrong but isn't master at 0.11.0?

**Comment by unboundfire** [comment]
@adammacdonald Yup I meant we need to just add the enum value to this file.
https://github.com/airbnb/react-native-maps/blob/master/ios/AirGoogleMaps/RCTConvert%2BGMSMapViewType.m

This is 0.11.0
https://github.com/airbnb/react-native-maps/tree/v0.11.0

Published about 4 weeks ago
https://www.npmjs.com/package/react-native-maps

Some of the google maps ios features(Shapes, Map types, Custom Tiles) have been merged in the past few weeks, so they are only in master currently to my understanding.

**Comment by adammacdonald** [comment]
After installing the package directly from github - can confirm its working.
