### ISSUE TITLE
 EACCES: permission denied on yarn install

### ISSUE THREAD

**Issue by matart15** [airbnb/react-native-maps#799]
`yarn install` gives me this error

```
  Error: EACCES: permission denied, open '/Users/username/workplace/react_native/project/node_modules/react-native-maps/android/build/intermediates/exploded-aar/com.google.android.gms/play-services-basement/9.4.0/AndroidManifest.xml'
```

I tried chmod 777 the file. but error is same even there is 777 permission

**Comment by misteral** [comment]
Get the same issue.

**Comment by matart15** [comment]
https://github.com/yarnpkg/yarn/issues/1806#issuecomment-260375161

**Comment by kfiroo** [comment]
I strongly suggest against running `sudo yarn`.
Try running
```bash
cd ./android
./gradlew clean
cd ..
yarn
```

**Comment by henrikra** [comment]
Is there any fix for this? I am getting this very often.

One way to solve is to reinstall node_modules with `rm -rf node_modules && yarn`

**Comment by kfiroo** [comment]
@henrikra simply cleaning the android build solved it for me and its a lot quicker
