### ISSUE TITLE
Center and Zoom in/out custom button

### ISSUE THREAD

**Issue by thundenilla** [airbnb/react-native-maps#803]
Is there anyway to make a custom button for zoom in/out and center for the map. Somehow the zoom in/out is not showing and the center button is fix and cant move it location.

**Comment by voidale** [comment]
I'm also interested if we can attach a custom buttom the zoom in zoom out?

**Comment by symmetriccurve** [comment]
You can simply increase(ZoomOut)/decrease(ZoomIn) the delta value on the current region with combination of animateToRegion  to achieve this.

**Comment by gilbox** [comment]
if @symmetriccurve is unsatisfactory, feel free to re-open this issue
