### ISSUE TITLE
incompatibility with react-native-fcm 

### ISSUE THREAD

**Issue by cavilaho** [airbnb/react-native-maps#804]
Related to issue #669, integrating with react-native-fcm throw a serie of errors of compatibility between libraries.

My approach to this is: 
on `android/app/build.gradle` from `myProject`
```
dependencies {
    ...
    compile project(':react-native-fcm')
    compile project(':react-native-maps')
    ...
}
...

apply plugin: 'com.google.gms.google-services'
```

on `android/build.gradle`  from `myProject`
```
dependencies {
    classpath 'com.android.tools.build:gradle:1.3.1'
    classpath 'com.google.gms:google-services:3.0.0'
    ...
}
```

This works fine if the `android/app/build.gradle` from `react-native-maps` project looks like:
```
dependencies {
    compile 'com.facebook.react:react-native:+'
    compile "com.google.android.gms:play-services-base:+"
    compile 'com.google.android.gms:play-services-maps:+'
}
```

What do you think about this? Someone have any other solution? Anyone has had this problem too?

Thanks.

**Comment by lrivera** [comment]
hey hello am having exactly the same issue, 
but for my your solution doesn't work,

this si my android/app/build.gradle

....
dependencies {
    compile project(':react-native-maps')
    compile project(':react-native-fcm')
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:+"  // From node_modules

    compile "com.google.android.gms:play-services-base:9.6.1"
    compile "com.google.android.gms:play-services-maps:9.6.1"
}
...
apply plugin: "com.google.gms.google-services"


this is my android/build.gradle

...
    dependencies {
        classpath 'com.android.tools.build:gradle:1.3.1'
        classpath 'com.google.gms:google-services:3.0.0
    }

some help ?

**Comment by cavilaho** [comment]
Try removing this from your `android/app/build.gradle`

```
compile "com.google.android.gms:play-services-base:9.6.1"
compile "com.google.android.gms:play-services-maps:9.6.1"
```

**Comment by lrivera** [comment]
no that doesn't work either,
am  following this post
[https://github.com/evollu/react-native-fcm/issues/118](url)

i think the problem is the maps plugin i change the build.gradle file of the plugin from:
```
compile "com.google.android.gms:play-services-base:9.4.0"
compile 'com.google.android.gms:play-services-maps:9.4.0'
```
to
```
compile "com.google.android.gms:play-services-base:9+"
compile 'com.google.android.gms:play-services-maps:9+'
```

because i prefer change the maps library to "+" than change all the new libraries for the exact version of this plugin

maybe someone can update this repo with my idea, :)

what you think ?

**Comment by cavilaho** [comment]
I think the PR #805 fix this issue. I'll try and comment.

**Comment by felipecsl** [comment]
Is this fixed by #805?

**Comment by cavilaho** [comment]
Yes, it's working for me with the #805 fix (at least in debug mode).

**Comment by Marco62** [comment]
sorry I have the some problem, but I'm not using react-native-maps.
My android/app/build.gradle is:
    _dependencies {
            compile project(':react-native-device-info')
            compile project(':react-native-fabric-digits')
            compile project(':react-native-dcm')
            compile fileTree(dir: "libs", include: ["*.jar"])
            compile "com.android.support:appcompat-v7:23.0.1"
            compile "com.facebook.react:react-native:+"  // From node_modules
            compile project(':react-native-contacts')
            compile project(':react-native-device-info')
           compile('com.digits.sdk.android:digits:1.9.2@aar') {
                transitive = true;
           }
          compile project(':react-native-fabric-digits')
}_

The android build.gradle is:
   _dependencies {
        classpath 'com.android.tools.build:grade:2.2.1'
        classpath 'com.google.gms:google-services:3.0.0'
  }_

Have you any suggestion please ?
Thank you

**Comment by Nodonisko** [comment]
I write whole article about this problem:
[https://medium.com/@suchydan/how-to-solve-google-play-services-version-collision-in-gradle-dependencies-ef086ae5c75f#.9l0u84y9t](https://medium.com/@suchydan/how-to-solve-google-play-services-version-collision-in-gradle-dependencies-ef086ae5c75f#.9l0u84y9t)

Hope I helped you :)

**Comment by JayKurniawan** [comment]
@Nodonisko I've red your article... where should I run `gradelw clean` ? is it on the `android` dir ?

**Comment by JayKurniawan** [comment]
can someone tell me what should I change to my `build.gradle` ? I stuck here for 2 days :(

````javascript
dependencies {    
    implementation(project(':react-native-maps')){
        exclude group: 'com.google.android.gms', module: 'play-services-base'
        exclude group: 'com.google.android.gms', module: 'play-services-maps'
    }
    implementation 'com.google.android.gms:play-services-base:15.0.0'
    implementation 'com.google.android.gms:play-services-maps:15.0.0'
    implementation project(':react-native-splash-screen')
    implementation project(':react-native-vector-icons')
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.android.support:appcompat-v7:23.0.1"
    implementation "com.facebook.react:react-native:+"  // From node_modules
    implementation project(':react-native-fcm')
    implementation 'com.google.firebase:firebase-core:15.0.0'   
}
````
