### ISSUE TITLE
Apple Mach-O Linker Error

### ISSUE THREAD

**Issue by ruci06** [airbnb/react-native-maps#813]
Hi I'm newbie to develop a app using xcode.

I tried to launch ios app with google map on simulator and got this error.

no such file or directory: '/Users/ruci.k/Library/Developer/Xcode/DerivedData/snappinPhotographer-ciezjvwndpeipgglzatkopsrsmnz/Build/Products/Debug-iphonesimulator/libReact.a'

There was a React dir in Debug-iphonesimulator dir, and libReact.a was in it.
'libReact.a' file is seem to generated by some kind of xcode project build setting automatically,
But I can't find which setting decides the path of 'React' library file.

Is there any information about it?

I did just follow instruction guide
`npm install react-native-maps --save`
` rnpm link`
 `vim podfile`
 `pod install`
 `pod update`

**Comment by symmetriccurve** [comment]
This might help: https://github.com/decosoftware/deco-ide/issues/84

**Comment by ruci06** [comment]
@symmetriccurve Thanks, but that option already checked :'-(

**Comment by DennisSnijder** [comment]
Did you try linking it by hand instead of Podfiles or rnpm link?
I did it by hand myself and it worked for me.

**Comment by ruci06** [comment]
Thanks for your reply.
I tried to link it by hand, and it worked 😄

**Comment by chourobin** [comment]
https://github.com/ivpusic/react-native-image-crop-picker/issues/21#issuecomment-239710351

**Comment by rajeshkos** [comment]
Hi ,

I am facing same issue why archiving the build.

The app is running fine in iphone 7 simulator. But when i am archiving the app i am getting linker error.

Please help me.

**Comment by asimolmez** [comment]
I deleted a folder of a test project in` Project Navigator` and `Targets`. It solved my problem.

**Comment by ifalldev** [comment]
@asimolmez, I deleted test project folder in `Project Navigator` but i did not find the `Targets` area, and the error still occurring.

I not even understand what you do mean with `Targets`.

Could you be more didactic, please?

Thanks!

**Comment by NawazKhanMd** [comment]
@rajeshkos hi, am facing  same issue have you found a way to workout the issue >??

**Comment by zyskowsk** [comment]
I ran into a similar problem and clearing my DerivedData and re-building fixed this issue for me.

you can do this by running `Command + option + shift + k` in xcode and rebuilding

**Comment by rynatk** [comment]
@zyskowsk thank you so much

**Comment by pavermakov** [comment]
@zyskowsk God bless you!

**Comment by mjstelly** [comment]
@zyskowsk Am I supposed to get a dialog when running your solution? I get no notice whether the cache cleared or not. 🤷‍♂️

**Comment by zyskowsk** [comment]
@mjstelly 
> @zyskowsk Am I supposed to get a dialog when running your solution? I get no notice whether the cache cleared or not. 🤷‍♂️

This changed in XCode10, there is no longer a dialog. It seems that now the only notice is a flask of `cleaning` and `clean finished` in the build bar

**Comment by rabiaasif** [comment]
have you tried adding javascriptcore.framework under linked libraries? That worked for me

**Comment by StarkAndy** [comment]
> decosoftware/deco-ide#84

Hi thanks it really helped me apart from that please make sure try to check the workspace setting if  it has following setting :

 Build System:
     -Legacy Build System

1.Build Architecture Yes

2.Workspace Setting:
   Build System:
    Legacy Build System

 Per-User Workspace
  DerivedData:
    Workspace relative location
  Build System 
    Use User Setting

**Comment by fabriziobertoglio1987** [comment]
https://stackoverflow.com/questions/5329001/apple-mach-o-linker-error-when-compiling-for-device
