### ISSUE TITLE
Can't run react-native run-android after installing

### ISSUE THREAD

**Issue by renanpvaz** [airbnb/react-native-maps#815]
After following the steps targeting Android, running `react-native run-android` gives me the following output: 

:react-native-maps:processReleaseResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-maps:processReleaseResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Android\sdk\build-tools\23.0.3\aapt.exe'' finished with non-zero exit value 1

**Comment by davidfekke** [comment]
Did you ever get passed this issue? I am getting the same error with Genymotion.

**Comment by renanpvaz** [comment]
I had no opportunity to test it again, but i think it might be related to the API key

**Comment by ianaz** [comment]
Same issue
