### ISSUE TITLE
incompatibility with react-native-fcm "no static method zzz"

### ISSUE THREAD

**Issue by Marco62** [airbnb/react-native-maps#819]
related to issue #804  I have the same problem, but I'm not using react-native-maps.

My **android/app/build.gradle** is:

_dependencies {
compile project(':react-native-device-info')
compile project(':react-native-fabric-digits')
compile project(':react-native-dcm')
compile fileTree(dir: "libs", include: ["*.jar"])
compile "com.android.support:appcompat-v7:23.0.1"
compile "com.facebook.react:react-native:+" // From node_modules
compile project(':react-native-contacts')
compile project(':react-native-device-info')
compile('com.digits.sdk.android:digits:1.9.2@aar') {
transitive = true;
}_
_compile project(':react-native-fabric-digits')_
}

The **android build.gradle** is:

_dependencies {
classpath 'com.android.tools.build:grade:2.2.1'
classpath 'com.google.gms:google-services:3.0.0'
}_

Have you any suggestion please ?
Thank you

**Comment by lrivera** [comment]
the problem is because two or ore of your libraries have different versions of the same binary, like in problem #804  fcm was calling the newest version of google play services and react-native-map not,
you need to look into your android/build.gradle libraries in node_modules folder to see what is the problem, only look into the react native libs, 

let me know if i can help with something else
greetings

**Comment by Marco62** [comment]
I inspect all my react-native-*/android/build.gradle and the only reference to play-services founded was:
node_modules/react-native-device-info/android/build.gradle:    compile 'com.google.android.gms:play-services-gcm:+'

**Comment by Marco62** [comment]
Ok I modify the node_modules/react-native-device-info/android/build.gradle like you _suggest:dependencies {
    compile 'com.facebook.react:react-native:+'
    //compile 'com.google.android.gms:play-services-gam:+'
    **compile 'com.google.android.gms:play-services-gcm:9.8.0'**
}_

and now it works fine.
Thanks to all

**Comment by Nodonisko** [comment]
I write whole article about this problem:
[https://medium.com/@suchydan/how-to-solve-google-play-services-version-collision-in-gradle-dependencies-ef086ae5c75f#.9l0u84y9t](https://medium.com/@suchydan/how-to-solve-google-play-services-version-collision-in-gradle-dependencies-ef086ae5c75f#.9l0u84y9t)

Hope I helped you :)
