### ISSUE TITLE
Center text on top of a custom marker 

### ISSUE THREAD

**Issue by danielbh** [airbnb/react-native-maps#832]
![screen shot 2016-11-26 at 7 58 48 pm](https://cloud.githubusercontent.com/assets/6653234/20642588/25cd315e-b413-11e6-8dae-6201d187e603.png)

How can I center the text on top of this marker such that it works for any screen size on both ios and android? In the screenshot above the text appears to the top left of the marker. It's a 1.

 Code included below. Thanks for any guidance!

```javascript
<MapView.Marker
  style ={{zIndex: this.state.selectedMarker === marker ? 1 : 0}}
  key={marker.id}
  image={
     require('../../assets/marker-with-label/marker-with-label.png')
  }
  coordinate={marker.coordinate}
>
  <Text>1</Text>
</MapView.Marker>
```

**Comment by gilbox** [comment]
Next the `Text` node inside of a `View` with fixed size and read about using flexbox to center it.

**Comment by danielbh** [comment]
What do you mean fixed size?

**Comment by danielbh** [comment]
I tried with flexbox already with no effect. Using the following style on the Marker view. 

style={{
                  flex: 1,
                  justifyContent: 'center',
                  alignItems: 'center'
                }}

**Comment by danielbh** [comment]
I suppose the only way I think I can do it is to make the height and width change based on the size of the marker (I'm using @x2 @x3 @x4 method for multiple screen sizes). I wish their was an easier way.

**Comment by danielbh** [comment]
If I do what you recommend with the fixed size then this is what I get on iphone 5 and nexus 5 respectively.

![screen shot 2016-11-26 at 10 09 20 pm](https://cloud.githubusercontent.com/assets/6653234/20643897/18187a0c-b425-11e6-8be2-aa5dc806ce11.png)
![screen shot 2016-11-26 at 10 09 27 pm](https://cloud.githubusercontent.com/assets/6653234/20643899/19e127e4-b425-11e6-884f-92ca5dc7c8ac.png)

**Comment by gilbox** [comment]
you can try applying border to the text to debug it. getting text to align perfectly across platforms is tricky b/c of differences with implementation of font rendering. It also seems like you might be using different fonts on each platform.

**Comment by danielbh** [comment]
I see. Your assumption is that it was a platform issue. Mine was that it was a screen size issue. You appear to be correct. So I'll just position it based on platform conditional. Thanks!

**Comment by danielbh** [comment]
Darn. I was wrong. It's a screen size issue. The issue persists based on screen size, not platform.

For instance on an iphone5 and a htc 420 desire they have the same behavior when attempting to center text. I think though this is not an issue with this library. However it is related as this seems like a common use case. What do you think?

Do you have anymore ideas on how to proceed given this information? 

Thanks again for any additional help you could offer.

**Comment by M3po** [comment]
@danielbh Did you find a solution? If so can you share it? I also found my self in this position

**Comment by manithin** [comment]
Here is a fix

https://stackoverflow.com/questions/40822129/airbnb-react-native-maps-custom-marker-with-centered-text-on-top

**Comment by yonureker** [comment]
What if the marker also has a Callout? Adding <View><Text></Text><View> above Callout component doesn't work for me.
