### ISSUE TITLE
Current location marker looks strange in Google Maps on iOS.

### ISSUE THREAD

**Issue by nrathi** [airbnb/react-native-maps#841]
I'm using `"react-native-maps": "github:airbnb/react-native-maps#fd2219fe101940bf999969e6601127a35f30cc1a"` in my package.json.

![simulator screen shot nov 29 2016 1 44 21 pm](https://cloud.githubusercontent.com/assets/3291034/20723801/f3d63a32-b639-11e6-8d88-6c34768e1265.png)

**Comment by gilbox** [comment]
you might want to search for similar issues. iirc, someone reported it only happens in the simulator. btw, at airbnb we are currently using a MapView.Marker to create our own location marker b/c of the inflexibility of the built-in implementation.

**Comment by nrathi** [comment]
It worked on my device! Thanks.

**Comment by AndrewHenderson** [comment]
How does one use the Google version of the map on iOS? Mine defaults to iOS's Apple Map.
