### ISSUE TITLE
Error using newLatLngBounds, int,int,int): map size cant be 0 

### ISSUE THREAD

**Issue by MaxToyberman** [airbnb/react-native-maps#842]
this is my render function : 
```
  return (
    <MapView
      style={styles.map}
      region={this.props.lastLocation.LatLng}
    >
    <MapView.Marker
      coordinate={{latitude: 37.78825, longitude: -122.4324,}}
      title= 'test'
      description = 'test'
    />
    </MapView>
  );
```
without the marker everything works fine but when i add the marker i get an error : 
"Error using newLatLngBounds, int,int,int): map size cant be 0.

looks like it tries to add the marker before the map is loaded .

Any suggestions ?

**Comment by sandman45** [comment]
I am seeing this as well running in Android.. works fine on iOS

**Comment by Gvade** [comment]
In my case specifying the height of map + flex:1 solved the problem.

**Comment by sandman45** [comment]
@Gvade same that solved it for me .. just forgot to post that here

**Comment by MaxToyberman** [comment]
I have solved this by using : 
var width = Dimensions.get('window').width; //full width
var height = Dimensions.get('window').height; //full height

and flex: 1

**Comment by mattijsf** [comment]
Still having the same problem on Android. Specifying hardcoded width / height / flex didn't work.
The react view is loaded inside fragment. Not sure if that matters.

**Comment by warka0** [comment]
Yep, still have the same issue!

**Comment by henrikra** [comment]
We got one yesterday on Samsung SM-G925F with trace:
```
java.lang.IllegalStateException Error using newLatLngBounds(LatLngBounds, int, int, int): Map size can't be 0. 
    :com.google.android.gms.DynamiteModulesB:14 com.google.maps.api.android.lib6.common.l.a
    :com.google.android.gms.DynamiteModulesB:175 com.google.maps.api.android.lib6.gmm6.api.a.a
    :com.google.android.gms.DynamiteModulesB:3 com.google.maps.api.android.lib6.impl.z.a
    :com.google.android.gms.DynamiteModulesB:42 com.google.maps.api.android.lib6.gmm6.api.a.a
    :com.google.android.gms.DynamiteModulesB:338 com.google.maps.api.android.lib6.impl.az.a
    :com.google.android.gms.DynamiteModulesB:35 com.google.android.gms.maps.internal.j.onTransact
    Binder.java:507 android.os.Binder.transact
    Unknown:-1 com.google.android.gms.maps.internal.IGoogleMapDelegate$zza$zza.moveCamera
    Unknown:-1 com.google.android.gms.maps.GoogleMap.moveCamera
    AirMapView.java:543 com.airbnb.android.react.maps.AirMapView.updateExtraData
    AirMapManager.java:291 com.airbnb.android.react.maps.AirMapManager.updateExtraData
    AirMapManager.java:29 com.airbnb.android.react.maps.AirMapManager.updateExtraData
    NativeViewHierarchyManager.java:136 com.facebook.react.uimanager.NativeViewHierarchyManager.updateViewExtraData
    UIViewOperationQueue.java:217 com.facebook.react.uimanager.UIViewOperationQueue$UpdateViewExtraData.execute
    UIViewOperationQueue.java:787 com.facebook.react.uimanager.UIViewOperationQueue$2.run
    UIViewOperationQueue.java:843 com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches
    UIViewOperationQueue.java:48 com.facebook.react.uimanager.UIViewOperationQueue.access$1600
    UIViewOperationQueue.java:889 com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded
    GuardedFrameCallback.java:31 com.facebook.react.uimanager.GuardedFrameCallback.doFrame
    ReactChoreographer.java:129 com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame
    ChoreographerCompat.java:107 com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame
    Choreographer.java:925 android.view.Choreographer$CallbackRecord.run
    Choreographer.java:702 android.view.Choreographer.doCallbacks
    Choreographer.java:635 android.view.Choreographer.doFrame
    Choreographer.java:913 android.view.Choreographer$FrameDisplayEventReceiver.run
    Handler.java:751 android.os.Handler.handleCallback
    Handler.java:95 android.os.Handler.dispatchMessage
    Looper.java:154 android.os.Looper.loop
    ActivityThread.java:6682 android.app.ActivityThread.main
    Method.java:-2 java.lang.reflect.Method.invoke
    ZygoteInit.java:1520 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run
    ZygoteInit.java:1410 com.android.internal.os.ZygoteInit.main
```

**Comment by nonameolsson** [comment]
I'm also having this issue. I have got it to work with: 
```javascript
import { Dimensions, StyleSheet } from 'react-native'

const width = Dimensions.get('window').width
const height = Dimensions.get('window').height

export default StyleSheet.create({
  map: {
    flex: 1,
    width
    eight
  }
})
```

But I need it to bee 100% of parent height, not the window height.

**Comment by pitakill** [comment]
@nonameolsson I made this:

`
const {height, width} = Dimensions.get('window');
`

for a concise way and ES6 nice looking.

Thanks for your comment, it helped me.

**Comment by siloebb** [comment]
I had same problem but, using `{height, width, flex:1}` don't work.
I fix it don't using a loading view.
E.g:

```
render(){
if( !location ){
<View>
  <Loading ... />
</View>
}else{
<View>
  <MapView ... />
</View>
}
}

```
this give me bug, so I excluded the loading.
in the end...

```
render(){
 <View>
    <MapView .../>
 </View>
}
```

**Comment by gardner** [comment]
Same issue here. Specifying the height and width does not resolve the issue. There are 3 parent <View> components.

It works fine when the <MapView> is the top level component.

```json
  "dependencies": {
    "expo": "^19.0.1",
    "react": "^16.0.0-alpha.12",
    "react-native": "^0.46.4",
    "react-navigation": "^1.0.0-beta.11",

```

**Comment by sytolk** [comment]
@gardner updating to react-native 0.46.4 and react 16.0.0-alpha.12 don't change anything for me. I have fixed this by removing flex:1 from map style and specifying width and height:

```
const { width, height } = Dimensions.get('window');
const halfHeight = height / 2;
const themeStyles = themes.createStyleSheet({
    map: {
        width,
        height: halfHeight
    },
});
```

**Comment by samthui** [comment]
Hi, I have same after upgrade to RN 0.43.3.

Previously I used RN 0.42.3 & react-native-maps 0.13.1. My map is included in a View with flex=1.
Before upgrading to RN 0.43.3, this code worked fine:
```
<MapView
        provider={provider}
        ref="map"
         rotateEnabled={false}
         maxZoomLevel={18}
        style={{ flex: 1, width: "100%" }}
         initialRegion={this.state._region}
         onRegionChange={region => this.onRegionChange(region)}
/>
```

But after upgrading, same error occurs, only changing `style={{ flex: 1, width: "100%" }}` to `style={{ width: some-hard-code-value, height: "100%" }}`, but that's not what I want, same reason with @nonameolsson

**Comment by kozillla** [comment]
I'm experiencing the same error with RN 0.48,

**Comment by nonameolsson** [comment]
Has someone been able to make the app work with percentages? I have a wrapper, with `flex: 1`, and I want the map to be `100%` of that height.

**Comment by 7laria** [comment]
same issue.

**Comment by mnsrv** [comment]
I have this issue on Android too.

I fixed this by adding absolute style:
```
map: {
  ...Platform.select({
    ios: {
      flex: 1
    },
    android: {
      position: 'absolute',
      top: 50,
      width: SCREEN_WIDTH,
      height: SCREEN_HEIGHT - 100
    }
  })
}
```

**Comment by sytolk** [comment]
@mnsrv are you sure that you have the last v.0.18.2 of the react-native-maps library? fix for this issue is allready merged https://github.com/airbnb/react-native-maps/pull/1521 and after that I don't have this issue again.

**Comment by mnsrv** [comment]
@sytolk, Thank you, now it's working without absolute style.
At the moment I had written comment to this issue latest version was v0.18.1. now it works

**Comment by MacKentoch** [comment]
having this issues when I use `fitToCoordinates` despite I ensure reference to map exists.
I have v0.19.0

**Comment by MacKentoch** [comment]
Alright I resolved my issue on android, that was more related to `fitToCoordinates`.

This is due to some kind asynchronism between react and native layout.

**My solution: wait for layout (if you just iOS you don't care) before calling `fitToCoordinates`:**

```javascript
<MapView
          style={styles.map}
          ref={this.setMapReference}
          onLayout={this.onMapReady}
          initialRegion={{
            latitude: LATITUDE,
            longitude: LONGITUDE,
            latitudeDelta: LATITUDE_DELTA,
            longitudeDelta: LONGITUDE_DELTA,
          }}
        >
          {markers.map((marker, i) => (
            <MapView.Marker key={i} coordinate={marker} />
          ))}
        </MapView>
```

AND ensure (as said above to tell android precise style for `map`
```javascript
map: {
      ...Platform.select({
        ios: { ...StyleSheet.absoluteFillObject },
        android: {
          flex: 1,
          // ...StyleSheet.absoluteFillObject,
          height: deviceHeight,
          width: deviceWidth,
        },
      }),
    },
```

**Comment by reyalpsirc** [comment]
In my case I was having the error due to the call to `animateToRegion` before the map was ready. Using @MacKentoch solution worked for me by using a flag on the state of my component that is set to true on the `onLayout` event.

**Comment by LuckySambial** [comment]
@MacKentoch I have same issue as you were facing but your solution is not working for me. In IOS it's working fine but not at all in android.
Can you please help me to sort it out ?

**Comment by sarmad1995** [comment]
TO whom ever its not working, the solutions provided. They can also try one more thing,
Mine MapView is nested, its a children component and down to 4-5 components....
My flex 1 + static heights were not working,
so i provided flex 1 to parent and window height and width to map and it solved the problem..here is my sameple code...
```
renderContent = () => {
    if (this.state.loading) {
      return <Loading />;
    }
    return (
      <View style={{ flex: 1 }}>
          <GooglePlaces
            onSelect={this.onPlacesSelect}
          />         
         <MapView
          provider='google'
          onLayout={this.onMapLayout}
          ref={ref => { this.map = ref; }}
          initialRegion={this.state.region}
          region={this.state.region}
          style={styles.map}
          onRegionChangeComplete={this.onRegionChange}
         > 
         { this.state.isMapReady &&
            this.renderMarker()
          }
         </MapView>
        <Button    
            icon={{ name: 'done' }}
            backgroundColor='#415041'
            buttonStyle={{ alignSelf: 'center', borderRadius: 6, width: 150, position: 'absolute', bottom: 50 }}
            title='Done'
            onPress={this.onDone}
        />
      </View>
    );
  }
```

and about styling

```
render() {
    return (
      <View style={{ flex: 1 }}>
        {this.renderContent()}
      </View>

    );
  }
}

const styles = StyleSheet.create({
  map: {
    height: height,
    width: width,
    position: 'relative'
  },
});
```
my imports: 
```
const { width, height } = Dimensions.get('window');
const ASPECT_RATIO = width / height;
const LATITUDE_DELTA = 0.0922;
const LONGITUDE_DELTA = LATITUDE_DELTA * ASPECT_RATIO;
```

**Comment by SKempin** [comment]
Obtaining the width and height dimensions and adding these to the map `styles` solved this issue for me.

Import at top of file:
`const { width, height } = Dimensions.get("window");`

In styles:
```
  map: {
    height: height,
    width: width
  },
```


I also wrapped my markers in an `isMapReady` boolean to ensure they weren't rendered until the `mapview` was ready.

```
<MapView
ref={map => (this.map = map)}
initialRegion={this.state.region}
style={styles.map}
onMapReady={() => this.onMapReady()}
>
```

Function:
```
 onMapReady = () => {
   this.setState({ isMapReady: true });
   console.log("map is ready!!");
 };
```

Markers:
```
{this.state.isMapReady &&
            this.state.data.map((marker, index) => {
              return (
                <MapView.Marker
                  key={marker.title}
                  etc...
```

**Comment by blarzHernandez** [comment]
I just only set the `flex:1` to the parent and it worked well.

**Comment by brccabral** [comment]
```
    @Override
    public void onMapReady(GoogleMap googleMap) {
        mMap = googleMap;
        //***
        //***
        mMap.setOnMapLoadedCallback(new GoogleMap.OnMapLoadedCallback() {
            @Override
            public void onMapLoaded() {
                mMap.moveCamera(CameraUpdateFactory.newLatLngBounds(builder.build(), padding));
            }
        });
    }
```

**Comment by crobinson42** [comment]
This was happening due to a call to `mapRef.current.animateToRegion({ ...DEFAULT_REGION }, 1000)` before the <MapView /> had mounted and loaded. The solution is to add `onMapReady={ () => setMapReady(true) }` as a prop and wait for the local state like this: `if (mapReady) mapRef.current.animateToRegion({ ...DEFAULT_REGION }, 1000)`
