### ISSUE TITLE
Problem with android build after package installation

### ISSUE THREAD

**Issue by leoCamilo** [airbnb/react-native-maps#845]
First of all, sorry about my English, I'm new in react-native development, so, I tried to install react-native-maps to test maps performance and do a comparative with Xamarin, I created a test project and did the steps bellow:

1° - npm install react-native-maps --save
2° - react-native link

until now ok, but when I try to build the project I get this error

```
:app:dexDebug
Unknown source file : UNEXPECTED TOP-LEVEL EXCEPTION:
Unknown source file : com.android.dex.DexException: Multiple dex files define Landroid/support/v7/appcompat/R$anim;
Unknown source file :   at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
Unknown source file :   at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
Unknown source file :   at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
Unknown source file :   at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
Unknown source file :   at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
Unknown source file :   at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
Unknown source file :   at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
Unknown source file :   at com.android.dx.command.dexer.Main.run(Main.java:277)
Unknown source file :   at com.android.dx.command.dexer.Main.main(Main.java:245)
Unknown source file :   at com.android.dx.command.Main.main(Main.java:106)

:app:dexDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:dexDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk1.8.0_111\bin\java.exe' ' finished with non-zero exit value 2
```

**Comment by stephanemaillard** [comment]
Did you install any other react-native libraries? react-native-fcm can triggered this kind of errors when installed with react-native-maps

**Comment by leoCamilo** [comment]
no, only react-native-maps, the purpose was test the package.

**Comment by davidfekke** [comment]
I am getting this error too.

**Comment by gilbox** [comment]
https://github.com/airbnb/react-native-maps/blob/81865819309b6644c13e4c52aa1cadbeab4aa73c/docs/installation.md#android

**Comment by leoCamilo** [comment]
`react-native link` do this steps automatically @gilbox, but I tried to do this by my self too, none of both worked

**Comment by mhoffman** [comment]
Have you tried `cd android/ && ./gradlew clean && cd .. && react-native run-android` ?

[source](http://stackoverflow.com/a/39704876/691407)

**Comment by leoCamilo** [comment]
It works! \o/ thanks @mhoffman and everyone, I'm using Windows, so there is no need './' before `gradlew clean`, try this solution @davidfekke.
