### ISSUE TITLE
Dependency problem

### ISSUE THREAD

**Issue by Gentlee** [airbnb/react-native-maps#850]
You need to set
```
compile "com.google.android.gms:play-services-base:9.8.0"
compile "com.google.android.gms:play-services-maps:9.8.0"
```
to 
```
compile "com.google.android.gms:play-services-base:9.+"
compile "com.google.android.gms:play-services-maps:9.+"
```
not to receive `DexException: Multiple dex files define Lcom/google/android/gms/common/api/zza;` if other package also use them.

**Comment by vjeranc** [comment]
you might have needed a ./gradlew clean and the problem solves itself.
