### ISSUE TITLE
0.11 not up to date with 0.10.4?

### ISSUE THREAD

**Issue by julien-rodrigues** [airbnb/react-native-maps#851]
I think there is a problem with either the changelog or the `0.11` version.

https://github.com/airbnb/react-native-maps/blob/master/CHANGELOG.md

I'm not too sure but it seems the `0.11` has been released before the `0.10.4`.

And last changes on the `0.11` tag seem to be older than the one on `0.10.4`: 

0.11: https://github.com/airbnb/react-native-maps/commits/v0.11.0
0.10.4: https://github.com/airbnb/react-native-maps/commits/v0.10.4

**Comment by gilbox** [comment]
The CHANGELOG has been updated to mention this.
