### ISSUE TITLE
Don't working followsUserLocation on google map

### ISSUE THREAD

**Issue by Wasylmakarenko** [airbnb/react-native-maps#852]
When I set followsUserLocation = {true}, Map isn't moving to follow user location.

![glass_and_iphone_6_ _ios_10_1__14b72_](https://cloud.githubusercontent.com/assets/22398446/20821754/04be2aaa-b7fa-11e6-9400-b5bc525084d1.png)

![bookingmapboxapi0_js_ __volumes_osx-tool_work_react_krom_krom](https://cloud.githubusercontent.com/assets/22398446/20821766/23dc9e58-b7fa-11e6-8ff4-9e44b41817ff.png)

Please Help me

**Comment by Wasylmakarenko** [comment]
I have solved.

**Comment by ronnierios** [comment]
@Wasylmakarenko How did you resolve it?

**Comment by texas697** [comment]
@Wasylmakarenko  what was solution

**Comment by Wasylmakarenko** [comment]
I have got current location to geolocation and Location change every time, I have changed region of mapview.
        var region={
           latitude: global.latitude,
           longitude: global.longitude,
           latitudeDelta: 0.015499,
           longitudeDelta: T,
         }
        this._map.animateToRegion(region, 1500)
