### ISSUE TITLE
CustomMapStyle not working on android 

### ISSUE THREAD

**Issue by gerardus1995** [airbnb/react-native-maps#853]
CustomMapStyle not working on android for me. Here is my mapview:
          <MapView
            showsUserLocation={true}
            style={STYLES.map}
            region={this.state.initialRegion}
            onRegionChange={this.props.changeInitialRegion}
            customMapStyle={mapStyle}
          >
            {this.state.coordinates.map((data) => {return <MapView.Marker coordinate={{latitude: data.lat, longitude: data.long}} image={require('../img/pointer.png')} onPress={()=>this.openModal(data)}/> })}
          </MapView>

For some reason it doesn't change the appearence of the map. mapStyle is a json object from google site.

**Comment by Grundmanis** [comment]
+1

**Comment by Grundmanis** [comment]
I've just updated "react-native-maps": to "^0.12.0" in package.json and it worked, i have react-native 0.38.0

**Comment by gilbox** [comment]
thanks for reporting!
