### ISSUE TITLE
markers jumping when used react native Image component

### ISSUE THREAD

**Issue by ochanje210** [airbnb/react-native-maps#858]
when I render the marker images like below, it seems unstable or jumping on the map.
```jsx
<MapView.Marker>
       <Image source={your_custom_image}/>
</MapView.Marker>
```
however, it looks fine when you directly put your custom marker image to the prop like below:
```jsx
<MapView.Marker
       image={your_custom_image}
/>
```
The thing is that when you do the second option, it is unable to give styles on the image such as width or height.

**Comment by stinju** [comment]
FWIW, pulling master seems to resolve the issue for me - perhaps it has been addressed: 

```    
"react-native-maps": "https://github.com/airbnb/react-native-maps#master",
```

**Comment by nharsch** [comment]
Looks like it could be related to this: https://github.com/airbnb/react-native-maps/pull/728

**Comment by gilbox** [comment]
let us know if `v0.12.1` fixes it

**Comment by stinju** [comment]
Yes, `v0.12.1` resolves the issue for me.  Thanks!

**Comment by artemautomatic** [comment]
didn't fix in the current version
