### ISSUE TITLE
Update dynamically coordinates of Polyline

### ISSUE THREAD

**Issue by ianaz** [airbnb/react-native-maps#863]
react-native-maps v0.11.0
react-native 0.37.0

Is it possible to change the coordinates property of MapView.Polyline?
Whenever I try to add data dynamically to my MapView.Polyline.coordinates proprety I get a "Attempted to assign a readonly property"

Is there a workaround for this or is it thought to be static?

This is pretty much what I'm doing (this.state.position is updated by react with setState({positions: [...]})
```
<MapView
  style={styles.map}
  region={{
     latitude: lastPosition.latitude,
     longitude: lastPosition.longitude,
     latitudeDelta: 0.3,
     longitudeDelta: 0.2
  }}>
       <MapView.Polyline coordinates={this.state.positions} />
</MapView>
```

**Comment by ianaz** [comment]
Was a very weird error on my side, sorry

**Comment by Larney11** [comment]
@ianaz Having the same problem when I try push an object of coordinates into the "this.state.positions". 
Any Ideas of what could be wrong?

**Comment by ianaz** [comment]
@Larney11 could you post your piece of code? I don't really remember what it was in mine, but maybe if i see yours I could remember :)

**Comment by Larney11** [comment]
@ianaz 
No bother, I solved it.
When updateing the state I changed this line:
`        routeCoordinates: this.state.routeCoordinates.concat(currentCoordinate),
`
to
`
        routeCoordinates: this.state.routeCoordinates.concat([currentCoordinate]),
`

I just put the new coordinates inside an array [].

**Comment by Imran-cse** [comment]
Facing the same issue
