### ISSUE TITLE
unable to resolve module react/lib/reactUpdates

### ISSUE THREAD

**Issue by qweqweq** [airbnb/react-native-maps#864]
i git clone the code from react-native-maps do as the guidance.
but i got a error as follows:
![image](https://cloud.githubusercontent.com/assets/10056390/20958195/4e3a1452-bc8f-11e6-9875-fd61e4c9fe71.png)

then i check the react and i found the error. miss version 15.3.1
![image](https://cloud.githubusercontent.com/assets/10056390/20958410/73deb2c0-bc90-11e6-8fbd-faf8b15a45b6.png)

in the package.json i found the "react":"^15.3.1" ,i delete the '^' and it works.
![image](https://cloud.githubusercontent.com/assets/10056390/20958336/1c0ffd42-bc90-11e6-8d7a-284fc5e71dd8.png)

**Comment by arthurnn** [comment]
had the same issue, and removing the `^` fixed it.
Should I send a PR with that change?

**Comment by qweqweq** [comment]
i think it's not a bug. however, if  you want to do this ,just do it .

**Comment by soulrelay** [comment]
done
