### ISSUE TITLE
Error installing react-native-maps

### ISSUE THREAD

**Issue by Marcelrama** [airbnb/react-native-maps#883]
Hello guys, I'm having problems installing react-native-maps clone the repository to experience the operation but nothing that I get install in Ios emulator or android, then I wonder is it compatible with the latest version of react-native? Or some missing dependency.

![I leave the image attached.](https://cloud.githubusercontent.com/assets/22013703/21101888/c5bbd4a0-c051-11e6-83a0-aa01bcf94f4c.png)

**Comment by Marcelrama** [comment]
i solve whit npm install react@15.3.2.

**Comment by maotora** [comment]
This should be published more, I mean i got the same kinda error message and same solutions suggested, but mined wasn't even particular about a certain lib.

It kepts saying `node_modules/../Renders` forgot the path it gave me but something like that.
I came to understand it was some broken `react` dependency,  upgraded to`react@15.3.2` and solved it.

Funny that it's not being talked about / published much.

**Comment by Marcelrama** [comment]
@maotora Hi I read about the error is due to an update of react@15.3.2 the paths where those folders were located were moved to another folder which when trying to locate them does not get, then when installing the dependency react@15.3.2. Is assigned the path in which the folder is located, now what I do not know how much affects the react-native
