### ISSUE TITLE
lite Mode works on iOS

### ISSUE THREAD

**Issue by ochanje210** [airbnb/react-native-maps#886]
I've been using lite Mode on iOS without an issue while README tells it only supports Android.
should it be changed that it supports both platforms? or is there anything I misunderstood?

**Comment by gilbox** [comment]
on iOS it's just falling back to the non-lite mode

**Comment by ochanje210** [comment]
oh ok thank you!

**Comment by fukemy** [comment]
any solution for IOS with FlatList of MapView? Thanks
