### ISSUE TITLE
onCalloutPress & onPress not working [0.12.2]

### ISSUE THREAD

**Issue by magrinj** [airbnb/react-native-maps#898]
I everyone, since I update to 0.12.2 the `onCalloutPress` function and `onPress` are never called, did someone got the same issue ? :)

**Comment by alborozd** [comment]
I have the same issue only in ios. Sometimes It calls, but It calls only when I tap somewhere under the marker.  It's problem for me too. How can we fix this?

**Comment by magrinj** [comment]
@alborozd I didn't find any solutions for the moment.... Still got no answer on this repository....

**Comment by RajkumarPunchh** [comment]
@alborozd, @magrinj 
Let me know if this [fix](https://github.com/airbnb/react-native-maps/pull/954) works for you.

**Comment by magrinj** [comment]
@RajkumarPunchh Your fix seems to work! Thanks a lot!! :)

**Comment by yonahforst** [comment]
Yes! +1 to get this merged

**Comment by spikebrehm** [comment]
Fixed by #954
