### ISSUE TITLE
unfortunately project has stopped

### ISSUE THREAD

**Issue by rushabhrakholiya** [airbnb/react-native-maps#903]
i have recently add this package with fresh installation of react native but its throw an error "Unfortunately  ReactProject has stopped." how could i resolved it..
I'm unable to launch application else don't know how to resolve 
your kind help will helpfull for me..

**Comment by akshay2604** [comment]
try https://github.com/airbnb/react-native-maps/pull/877 [url]

**Comment by felipecsl** [comment]
Please provide more details about the problem in order to help us diagnose.
