### ISSUE TITLE
Build Error 

### ISSUE THREAD

**Issue by Mackenzie-Mance** [airbnb/react-native-maps#918]
//...
import com.BV.LinearGradient.LinearGradientPackage; // <--- This!
//...
@Override
protected List<ReactPackage> getPackages() {
 return Arrays.<ReactPackage>asList(
   new MainReactPackage(),
   new LinearGradientPackage() // <---- and This!
 );
}

Tried implementing this in both MainActivity.java and MainApplication.java with no luck shaking the build error. Everything else is installed correctly. Someone help a mann.

**Comment by christopherdro** [comment]
@Mackenzie-Mance  How does `LinearGradientPackage` relate to this library?
