### ISSUE TITLE
Initial region automatically gets changed

### ISSUE THREAD

**Issue by stief510** [airbnb/react-native-maps#919]
I set my initial region to my current position and then have a small delta to both long and lat. However, onRegionChange gets called immediately and sets the delta to values much larger and so the map zooms out.

**Comment by symmetriccurve** [comment]
Do you mind sharing some code snippets of the issue?

**Comment by stief510** [comment]
import {
  styledClass,
  styledWithClasses,
  Flexed,
  FlexedClass,
  ContainerWrapper,
  Row,
  Column,
  AlignCenteredClass,
  JustifyCenteredClass,
  JustifySpaceBetweenClass,
  TransparentBackground,
  PrimaryText,
  SecondaryText
} from '../../components/common_styled_components';

const { width, height } = Dimensions.get('window');
const LATITUDE_DELTA = 0.3;

const ViewButtonTop = styledWithClasses(View, TransparentBackground, Column)`
  marginVertical: 5;
`;
const ViewButtonBottom = styledWithClasses(View, Row)`
  position: absolute;
  bottom: 30;
  width: ${width};
  alignSelf: center;
  left: 0;
  right: 0;
`;

export const ButtonCommonClass = styledClass`
  backgroundColor: 'rgba(255,255,255,0.7)';
  paddingVertical: 12;
`;

const ModalButton = styledWithClasses(TouchableHighlight, AlignCenteredClass, ButtonCommonClass)`
  paddingHorizontal: 18;
  marginVertical: 5;
  borderRadius: 10;
`;

const MapButton = styledWithClasses(TouchableOpacity, AlignCenteredClass, ButtonCommonClass)`
  paddingHorizontal: 12;
  marginHorizontal: 10;
  borderRadius: 20;
  marginTop: 12;
`;

const TextBlack = styled.Text`
 color: black;
`;
const TextRed = styled.Text`
 color: red;
`;

const CalloutText = styledWithClasses(PrimaryText)`
  fontSize: ${scalingFactor.lvl_12};
`;

const AddressText = styledWithClasses(PrimaryText)`
  fontSize: ${scalingFactor.lvl_13};
`;

const DistanceText = styledWithClasses(SecondaryText)`
  fontSize: ${scalingFactor.lvl_15};
`;

const MapContainer =styledWithClasses(MapView)`
 width: ${width};
 height: ${props => _.get(props,'height', height - NAV_BAR_HEIGHT)};
 ${StyleSheet.absoluteFillObject}
`;

const ViewMapContainer = styledWithClasses(View, FlexedClass, AlignCenteredClass, JustifySpaceBetweenClass)``;

@observer
class StoreLocatorDialog extends Component {
  static trackingID = 'StoreLocatorDialog';
  @observable searchBarHeight = 0;
  @observable query = '';
  @observable region = undefined;
  @observable coordinate = undefined;
  @observable keyboardVisible = false;
  @observable curPositionCoordinate = undefined;


  setInitial = () => {
    transaction( () => {
      this.region = {
        latitude: this.props.storeLocator.lat,
        longitude: this.props.storeLocator.lng,
        latitudeDelta: LATITUDE_DELTA,
        longitudeDelta: LATITUDE_DELTA * this.aspect_ratio,
      };
      this.coordinate = {
        latitude: this.props.storeLocator.lat,
        longitude: this.props.storeLocator.lng
      };
      this.curPositionCoordinate = this.coordinate;
    } );
  };

  constructor(props: Object, context) {
    super(props, context);
    this.setInitial();
  }

  @computed get aspect_ratio() {
    let h = height - NAV_BAR_HEIGHT - this.searchBarHeight;
    return width / h;
  }

  onRegionChange = (region) => {
    console.log(region);
    this.region = {
      latitude: region.latitude,
      longitude: region.longitude,
      latitudeDelta: LATITUDE_DELTA,
      longitudeDelta: LATITUDE_DELTA * this.aspect_ratio
    };
  };
  changeQuery = (q) => {
    this.query = q;
  };

  clearQuery = () => {
    this.query = "";
  };

  onDoSearch = () => {
    processPositionByAddress(this.query)
      .then((array) => {
        if (_.isArray(array)) {
          if (array.length == 1) {
            let h = _.head(array);
            this.region = {
              latitude: h.position.lat,
              longitude: h.position.lng,
              latitudeDelta: LATITUDE_DELTA,
              longitudeDelta: LATITUDE_DELTA * this.aspect_ratio,
            };
            this.coordinate = {
              latitude: h.position.lat,
              longitude: h.position.lng
            };
          }
        }
      });
  };

  resetMap = () => {
    this.selectedStore = undefined;
    this.setInitial();
    this.changeQuery('');
  };

  zoomIn = () => {
    let latitudeDelta = this.region.latitudeDelta / 2;
    let longitudeDelta = latitudeDelta * this.aspect_ratio;
    if (latitudeDelta > 0.002 ) {
      this.region = {
        latitude: this.region.latitude,
        longitude: this.region.longitude,
        latitudeDelta,
        longitudeDelta,
      };
    }
  };

  zoomOut = () => {
    let latitudeDelta = this.region.latitudeDelta * 2;
    let longitudeDelta = latitudeDelta * this.aspect_ratio;
    if (latitudeDelta < 120 ) {
      this.region = {
        latitude: this.region.latitude,
        longitude: this.region.longitude,
        latitudeDelta,
        longitudeDelta,
      };
    }
  };

  render(): ReactElement {
    let searchBar =
      <SearchBar
        clearSearchText={this.clearQuery}
        searchText={this.query}
        onChangeSearchText={this.changeQuery}
        placeholder={_t('Search by Zip, City or State')}
        onSubmitEditing={this.onDoSearch}
      />;

    let mapView =
      <ViewMapContainer>
        <MapView
          ref={ref => { this.map = ref; }}
          onRegionChange={this.onRegionChange}
          region={this.region}
          style={[{
             width: width,
             height: height - NAV_BAR_HEIGHT - this.searchBarHeight,
             },
             ...StyleSheet.absoluteFillObject
          ]}
        >
          <MapView.Marker.Animated coordinate={this.coordinate} pinColor={linkColor} title={this.query == "" ? _t("Current Location") : this.query}/>
        </MapView>
        <ViewButtonBottom>
          <MapButton onPress={this.zoomOut}>
            <View>
              <TextBlack>{_t("zoom -")}</TextBlack>
            </View>
          </MapButton>
          <MapButton onPress={this.zoomIn}>
            <View>
              <TextBlack>{_t("zoom +")}</TextBlack>
            </View>
          </MapButton>
          <MapButton onPress={this.resetMap}>
            <View>
              <Icon name={"my-location"} size={scalingFactor.lvl_10} color="black"/>
            </View>
          </MapButton>
        </ViewButtonBottom>
      </ViewMapContainer>;

    return (
      <ContainerWrapper>
        <Flexed>
          <NavBarWrapper
            leftPress={this.onBack}
            leftText={<MaterialIcon name="arrow-back" size={iconSize}/>}
            title={_t("Locator")}
          />
          {searchBar}
          {
            (Platform.OS == 'android')?
              <KeyboardAvoiding
                onKeyboardVisible={this.updateKeyboardState}
              >
                {mapView}
              </KeyboardAvoiding>
              :
              <Flexed>
                {mapView}
              </Flexed>
          }
        </Flexed>
      </ContainerWrapper>
    );
  }
}

StoreLocatorDialog.defaultProps = {
};

StoreLocatorDialog.propTypes = {
  navigator: PropTypes.object.isRequired,
  user: PropTypes.object,
  storeLocator: PropTypes.object.isRequired
};

export default StoreLocatorDialog;
```

**Comment by stief510** [comment]
I attached a big chunk of our code, while removing some styling pieces and other bits that are not relevant

**Comment by M3po** [comment]
see [https://github.com/airbnb/react-native-maps/issues/846](url). I think you have the same issue as akshay2604 and me.

**Comment by zevmo** [comment]
And the same for #949

**Comment by stief510** [comment]
The solution of changing it to `onRegionChangeComplete` works

**Comment by j-planet** [comment]
It's broken again.

**Comment by henrydeclety** [comment]
I get the same problem with onRegionChangeComplete

**Comment by acoulon99** [comment]
I came across the same problem. I'm using `react-redux`. It's not my favorite solution, but after incorporating a 1 second delay between the map loading and when state is updated.

```
  constructor(props) {
    super(props);
    this.state = {
      openedAt: Moment(),
    };
  }

...

  updateRegion = (region) => {
    const { updateMapRegion } = this.props;
    if(Moment().subtract(1, 'seconds').isAfter(this.state.openedAt)){
      updateMapRegion(region);
    }
  }

...

export default connect(
  state => ({
    data: state.data,
    loading: state.loading,
    region: state.mapRegion,
  }),
  dispatch => ({
    refresh: (region) => {
      dispatch({
        type: 'GET_DATA',
        region,
      });
    },
    updateMapRegion: (region) => {
      dispatch({
        type: 'UPDATE_MAP_REGION',
        region,
      });
    },
  }),
)(GalleryMap);
```
