### ISSUE TITLE
Could not find com.google.android.gms:play-services-base:9.8.0

### ISSUE THREAD

**Issue by nairicode** [airbnb/react-native-maps#932]
![image](https://cloud.githubusercontent.com/assets/15065065/21644217/d9f0e58a-d2a5-11e6-9a11-b8458711fc2b.png)

![image](https://cloud.githubusercontent.com/assets/15065065/21644231/f268ddca-d2a5-11e6-9dd6-9055a1c916f2.png)

**Comment by skoob13** [comment]
Have you installed Google Repository from Android SDK manager?

**Comment by nairicode** [comment]
how i can install it?

**Comment by nairicode** [comment]
i will install, and try again.

**Comment by nairicode** [comment]
![image](https://cloud.githubusercontent.com/assets/15065065/21649124/008429dc-d2ba-11e6-8fdd-cb9fce28190f.png)
