### ISSUE TITLE
iOS Marker Performance is really slow on device

### ISSUE THREAD

**Issue by gonzalezchris** [airbnb/react-native-maps#935]
When I run the app within the simulator, it runs really well and there are no issues. However, when I build and run on an iOS device, when a marker is tapped it takes about 3 seconds for the application to register the action. I only have 6 custom markers on the map. The rest of the application runs smoothly, the delay only occurs whenever I tap a marker. I checked the performance monitor on Xcode, and it appears that whenever I tap a marker on the device, it uses 100% of the cpu. 🤔  Has any one had any issues with using custom markers on a physical device? If so how did you fix the issue?

**Comment by gilbox** [comment]
for reference, are you using mapkit?

**Comment by gonzalezchris** [comment]
@gilbox thanks for checking in, it appears the issue was with how I set up my redux store, not with React-Native Maps itself

**Comment by truongluong1314520** [comment]
Hi @gonzalezchris , can you tell me how you fixed your redux store? I have the same problem as you but still not know the way out. Please let me know how you can solve it, thank you in advance!
