### ISSUE TITLE
map is empty Android, in debug mode working but in release mode not

### ISSUE THREAD

**Issue by nairicode** [airbnb/react-native-maps#946]
![image](https://cloud.githubusercontent.com/assets/15065065/21777078/c8adfece-d6b6-11e6-8755-f01c9b401fa1.png)

**Comment by kanekotic** [comment]
@nairicode what was it?

**Comment by nairicode** [comment]
need add SHA-1 key in google account,

**Comment by isaaclem** [comment]
@nairihar  Mind to elaborate some details as I'm facing this issue now
