### ISSUE TITLE
0.12.3 has breaking change, described in changelog as BC for 0.13.0

### ISSUE THREAD

**Issue by merapi** [airbnb/react-native-maps#957]
installed react-native-maps 0.12.2, package.json shows ^0.12.2, next time you install it - it will be 0.12.3 with breaking change

should we do 0.12.4 with revert?

0.12.2
 ![0.12.2](https://www.dropbox.com/s/edosascbs9i8vkh/Screenshot%202017-01-12%2019.16.33.png?dl=0&raw=1)

0.12.3
 ![0.12.3](https://www.dropbox.com/s/cp98ohzo26r1puv/Screenshot%202017-01-12%2019.18.29.png?dl=0&raw=1)

changelog
 ![changelog](https://www.dropbox.com/s/vkid25e90cv00tj/Screenshot%202017-01-12%2019.24.20.png?dl=0&raw=1)

**Comment by spikebrehm** [comment]
Oh no, my bad!  Good catch, I'll publish 0.12.4 with a revert.

:man_facepalming:
