### ISSUE TITLE
Novice problem.

### ISSUE THREAD

**Issue by AndriesLSteenkamp** [airbnb/react-native-maps#960]
Hi. 

I recently stumbled upon React Native and was trying to to make a simple app that will show your location on a map. I then came across this article, so I tried to use it as an example. I get up to the point where you make a fixed point on the map, but from there on I am unable to do anything or get any of the code beyond that point to work. 

Am I missing something or do I somehow need to download the example files and then edit them? 

Any advice would be greatly appreciated.

**Comment by edencakir** [comment]
Check the example folder?

**Comment by AndriesLSteenkamp** [comment]
I tried to make my own one, but then I only get the map to show in the emulator with fixed coordinates. I then tried to download the example file and run it in an emulator, but ran into compilation errors and was not able to get it running.

**Comment by edencakir** [comment]
What do you want to accomplish? Moving around? Circles on map? Custom markers?

**Comment by AndriesLSteenkamp** [comment]
I want to be able to zoom in on my current location when I open the app with some form of indication of my location on the map. This is the basic feature that I wish to accomplish.

**Comment by edencakir** [comment]
Compare your MapView with mine below.

```
       <MapView
          loadingEnabled
          loadingIndicatorColor="#666666"
          loadingBackgroundColor="#eeeeee"
          style={{height: 160, marginTop: 8}}
          region={{
            latitude: 37.78825,
            longitude: -122.4324,
            latitudeDelta: 0.001*this.state.radius + 0.002,
            longitudeDelta: 0.001*this.state.radius + 0.002,
          }} >
          <MapView.Marker
            title="This is a title"
            description="This is a description"
            coordinate={{
              latitude: 37.78825,
              longitude: -122.4324,
              latitudeDelta: 0.0922,
            }}
          />
        </MapView>
```

Make sure you have these true, or not defined at all:
```
            pitchEnabled={false}
            scrollEnabled={false}
```

**Comment by AndriesLSteenkamp** [comment]
Thank you, I will give this a try and report back.

**Comment by AndriesLSteenkamp** [comment]
Do I need to have the example files in the location where I am working on the app, or can that code be used without the files.

**Comment by edencakir** [comment]
No, you don't need the files. Just follow the installation instructions and you should be fine. It's about using the **MapView** component of this repo, which can be easily imported after a NPM install (and of course some bridging stuff between JS and Native).

**Comment by AndriesLSteenkamp** [comment]
Thank you, I will try this when I am near my workstation again.

**Comment by AndriesLSteenkamp** [comment]
I had to restart the project as I ran into some problems with the old file. I am once again able to show a normal mapview with fixed coordinates, but the problem I am facing now is that when I try to use this in the code, I get the error that says, null is not an object.  I have attached my working code so far. I think that I may be trying to use the example incorrectly.


[Code.txt](https://github.com/airbnb/react-native-maps/files/707520/Code.txt)

**Comment by AndriesLSteenkamp** [comment]
I messed around with the code a bit, but I get the error: "Error while updating property 'region' of a view managed by: AIRMap. I looked at the issues board and tried some of those solutions, but then I get errors with missing symbols.

**Comment by saberking** [comment]
@AndriesLSteenkamp Your attached code looks fine, I guess the problem is somewhere else in your code. Please could you attach the broken code, then people can try to figure out what is wrong. Hope you get it working!

**Comment by vinagrito** [comment]
@christopherdro I think this one can be closed
