### ISSUE TITLE
Map calls `onRegionChange` on init with wrong region after it's correctly set

### ISSUE THREAD

**Issue by lucasbento** [airbnb/react-native-maps#964]
So, I have a map as follows:
```jsx
// render
<MapView
  region={this.state.region}
  onRegionChange={this.handleRegionChange}
  style={styles.map}
  showsUserLocation={false}
  showsTraffic={true}
  showsIndoors={false}
  rotateEnabled={false}
>
  {this.renderMapMarker()}
</MapView>
```

```jsx
// renderMapMarker
<MapView.Marker.Animated
  coordinate={this.state.userLocation}
  title="I'm here"
>
  <View style={styles.marker} />
</MapView.Marker.Animated>
```

On `componentDidMount()` I get user's location, set it on `this.state.userLocation` and change `this.state.region` to match the location coordinates. After initializing, the component keeps calling `onRegionChange` until it stops with the value:

```js
{
  latitude: -14.36687999999999,
  latitudeDelta: 48.71334786739263,
  longitude: -54.49218800000002,
  longitudeDelta: 40.60546966557548,
}
```

**BUT** the map renders fine and the region seems to be ok, however, if I need to go to another screen OR render another `<View />` instead of the map on that same screen, it tries to retrieve `this.state.region` again **which is wrong** and just keep on it.

These are the logs that I put on `onRegionChange` to see what was happening (I only set `this.state.userLocation` ONCE):

![image](https://cloud.githubusercontent.com/assets/6207220/21963381/d246169c-db20-11e6-9dc4-f26f998486a9.png)

**Edit**: if I render map without setting any location, only with `this.state.region` with random coordinates, it still calls `onRegionChange` with those same values mentioned above.

**react-native**: `0.39.2`
**react-native-maps**: `0.12.2`
**OS**: `iOS`

**Comment by lucasbento** [comment]
Seems to be the same problem of #919 and #846, solved it by switching `onRegionChanged` to `onRegionChangeComplete`, really weird thing.

I'll close this since it appears to be fixed.

**Comment by max-mykhailenko** [comment]
I have wrong region (big deltas) for both handlers on map init, but correct map visible part.

**Comment by j-planet** [comment]
same experience as max-mykhailenko: "I have wrong region (big deltas) for both handlers on map init, but correct map visible part." Please reopen.

**Comment by iwarshak** [comment]
I am experiencing this same behavior. The delta is very large (~60), but when I manually pan the map, even just a little, the delta goes back to the correct value (~0.4 in this case).

**Comment by ryanfabela** [comment]
onRegionChange is called 4 times, once with the initialRegion, then two more with the a different region then before but equal to each other, then one last one in kansas. MapView displays correctly.
