### ISSUE TITLE
gaode map is work well,but google map can't

### ISSUE THREAD

**Issue by qq326646683** [airbnb/react-native-maps#972]
![wechatimg23](https://cloud.githubusercontent.com/assets/15717688/22031806/ccb798a6-dd1c-11e6-9986-a45ac3648761.jpeg)

**Comment by qq326646683** [comment]
I deal with it after asking to start api server of googlemap and set up api key.

**Comment by felipecsl** [comment]
This lacks information needed in order to help us diagnose and reproduce the issue.
Please describe your problem clearly and provide as much information as possible.
Thanks!
