### ISSUE TITLE
google map in IOS can't render polyline

### ISSUE THREAD

**Issue by AnupatRuangsuwan** [airbnb/react-native-maps#974]
Android 
![2560-01-18 13_35_52](https://cloud.githubusercontent.com/assets/20763521/22053554/fe88b830-dd83-11e6-910e-7472b05bbe2c.gif)

IOS
![2560-01-18 13_38_46](https://cloud.githubusercontent.com/assets/20763521/22053559/08b19a8e-dd84-11e6-85d6-35b69816c466.gif)

I'm use
react-native: 0.38
react-native: 0.12.4

thank you.

**Comment by patiphannn** [comment]
+1

**Comment by VinZenTz1989** [comment]
I got the same problem too. I couldn't render the line on map
