### ISSUE TITLE
How to update React-Native-Maps version?

### ISSUE THREAD

**Issue by Drikoso** [airbnb/react-native-maps#981]
I know this will sound like a really newbie question, but I can't find a way to update my react-native-maps package. I've run npm update and npm update react-native-maps, but the version is still shown in the packages.json as 0.12.4.  I'm using react native 0.40 and just installed maps with npm install --save react-native-maps.

Please help, without this update I keep getting the AIRMapMarker, AIRMapCallout errors

**Comment by shadowcz007** [comment]
#import <React/xxx>

**Comment by kurniad001** [comment]
solution from #789 

from your app folder on terminal:
- [ ] **cd node_modules**
- [ ] **/bin/rm -rf react-native-maps** (delete your current react-native-maps)
- [ ] **git clone https://github.com/airbnb/react-native-maps** (clone it directly from github)
- [ ] **cd react-native-maps**
- [ ] **npm install** 
- [ ] **/bin/rm -rf .git***
- [ ]  **cd ..**

hope this helps.

**Comment by Drikoso** [comment]
thank you very much :D

**Comment by ChenLi0830** [comment]
Another way to do this is utilizing the github tarball link directly. 
Namely, run the following command
`npm install https://github.com/airbnb/react-native-maps/tarball/master --save`
