### ISSUE TITLE
<MapView. Polygon /> onPress event not working in iOS Google map [0.12.2].

### ISSUE THREAD

**Issue by inv-jithin** [airbnb/react-native-maps#982]
<MapView.Polygon /> onPress event not triggered in iOS Google map. The same code working in iOS default and Android google map. 

Is onPress event support not available in iOS google map?

**Comment by geriux** [comment]
Hi!

I'm having the same issue, it works well on Android but not on iOS (Google Maps)

**Comment by lelandrichardson** [comment]
Now fixed.

**Comment by weisssean** [comment]
I got stuck on this for a while, onPress was working on Android and iOS but not with **GoogleMaps on iOS**. Found out I needed the **tappable={true}** attribute. now my question is, why do you need such an attribute? Isn't it obvious that I want it to be tappable if I have an onPress event?
Can you not just check whether onPress does not equal null?

**Comment by antonioreyna** [comment]
i have the same problem
