### ISSUE TITLE
Lots of small polylines slow, a few big polylines fast

### ISSUE THREAD

**Issue by butchmarshall** [airbnb/react-native-maps#988]
I can render 15 polylines each with 8,000 points and the map is very responsive.

Rendering 8000 polylines with 2 points each is very, very slow.

I don't encounter this issue with web maps - is this a known limitation with mobile?

**Comment by kengiro** [comment]
hello , has you got some light from this matter, i have the same problem with poligons

**Comment by butchmarshall** [comment]
No insight.  My solution was to merge all the polylines into a single polyline.

I was lucky because my polylines all touch or intersect in some way.

It's way faster (doesn't crash, map is responsive) even though the total number of points goes up by a factor of 10x (due to all the double-backs along the same points my algorithm has to take).

**Comment by rajeshkos** [comment]
@butchmarshall  are you able to draw polyline on android app ??

I am facing an issue : https://github.com/airbnb/react-native-maps/issues/1095

**Comment by butchmarshall** [comment]
I've switched over to [react-native-mabpox-gl](https://github.com/mapbox/react-native-mapbox-gl).

The v6 branch using MapboxGL.ShapeSource / MapboxGL.LineLayer components handles 100,000+ points no problem (because I believe it converts it into a graphic, maybe?).
