### ISSUE TITLE
updating urlTemplate for MapView.URLTile on iOS doesn't update the map

### ISSUE THREAD

**Issue by jschloer** [airbnb/react-native-maps#991]
When updating the urlTemplate prop only, the MapView doesn't update. If I remove the child urlTile component and re-add with the new url, it displays fine. 

It appears the cause is that the _map variable is never set on the AIRMapURLTile class, so when the update is called, the _map is always nil and the update call in AIRMapURLTile bails out [here](https://github.com/airbnb/react-native-maps/blob/master/ios/AirMaps/AIRMapUrlTile.m#L36).

I was able to fix by setting the map value in AIRMap.m insertReactSubview similar to what's being done for AIRMapPolyline and AIRMapPolygon, [here](https://github.com/airbnb/react-native-maps/blob/master/ios/AirMaps/AIRMap.m#L99).

I'll be submitting a small PR for this in just a moment. Let me know if there are other implications of this that I am missing.

**Comment by spikebrehm** [comment]
Fixed by #992
