### ISSUE TITLE
Multiple Markers Image errors

### ISSUE THREAD

**Issue by MarcwL22** [airbnb/react-native-maps#997]
Hello guys, i'm new at react-native. I choose a friend's project to study and i'm stuck in styling different markers, let me show to you.
I want to define 1 marker to 1 sport icon, and I have 4 different registered sports in the database.
Here I defined the image locations

> var futIcon = require('../images/soccer.png');
> var baskIcon = require('../images/basketball_ball.png');
> var volleyIcon = require('../images/volleyball.png');
> var tenisIcon = require('../images/tebletennis.png');

Here i do de if/else marker images

> _iconUrl = (marker) => {
>       if(marker.sport.id == 1 ){
>         return futIcon;
>       }
>       if(marker.sport.id == 2 ){
>         return tenisIcon;
>       }
>       if(marker.sport.id == 3 ){
>         return volleyIcon;
>       }
>       if(marker.sport.id == 4 ){
>         return baskIcon;
>       }
>       // else {
>       // return defaultIcon;
>       // }
>     }

and in the MapView.Markers I do this

> <MapView
>                     ref={ref => { this.map = ref; }}
>                     showsUserLocation={true}
>                     image={()=>this._iconUrl()}
>                     style={[styles.container, styles.map]}
>                     initialRegion={this.state.region}>

I'm getting 'undefined is not an object(evaluating 'marker.sport').
What i'm doing wrong?

**Comment by spikebrehm** [comment]
You're calling `this._iconUrl()` without any arguments.  Thus, the `marker` argument is undefined.

**Comment by MarcwL22** [comment]
Works! Thanks!
