### ISSUE TITLE
Use openstreetmap with react-native-maps

### ISSUE THREAD

**Issue by nschurmann** [airbnb/react-native-maps#999]
Hello!, i'm curious to know if we can use openstreetmaps with this component instead of google or apple's maps. Anything about this?

**Comment by spikebrehm** [comment]
We'd like to add MapBox support, which would open the door to OpenStreetMaps.

Feel free to submit a PR :)

**Comment by roots-ai** [comment]
Is this possible now?

**Comment by andela-cofor** [comment]
?

**Comment by sseyha** [comment]
is it Possible to use OSM yet?
Please...

**Comment by seco35** [comment]
Yes it is, but for some reason you still need a google api key. Without it, nothing renders. For me it looks like, as if it would get google maps tiles and re-render it with osm tiles (weird). You can see the google tiles for a fraction of a second, eventually it looks like re-rendering with osm tiles. I will check my connection with a sniffer, whether I'm getting tiles from google or osm and tell you more.

**Comment by rickyviz** [comment]
we can use openstreet maps ? and this lib not request to google maps API ?
